### ISSUE TITLE
MultiGrid does not update right grid when fixed column size changes

### ISSUE THREAD

**Issue by MarcelSchmitt** [bvaughn/react-virtualized#1004]
I have a MultiGrid where the column widths can be changed by the user. When that happens on a fixed column the column itself is updated but the right grid is not updated to use the free space.

Here is an example:
https://codesandbox.io/s/jllvqo5n0w

**Comment by bvaughn** [comment]
Looks like a bug!

A PR with a failing unit test and a fix would be welcome!

**Comment by MarcelSchmitt** [comment]
I created PR #1007 
Had no idea for a failing test after the fix but the new test failed without the fix :).

**Comment by nicoladefranceschi** [comment]
Hi, I'm experiencing a similar bug. to reproduce, I changed the MultiGrid example setting               columnWidth={({index}) => 100 + index * 20}

then, in the example page, if i change the fixedColumnCount number, you see that the column in the right grids maintain the old widths. If you then scroll horizontally, the widths gets updated to the right values, but you see the cells overlapping while this happens

**Comment by nicoladefranceschi** [comment]
The solution is probably to reset the cache of the columns' widths in the right grids when the number of fixed columns changes.. what do you think?

**Comment by runfaj** [comment]
In case anyone still runs into this, here's how I fixed it. I have a grid where updating works fine for most updates, but the column resizing has issues. I had two issues:
1. The columns wouldn't resize unless I manually refreshed the grid
2. The row heights wouldn't resize after a column resize unless I manually refreshed the grid, then did a force update and refresh again in a new thread.

This is extremely hacky, but is literally the only thing that worked for me:

```
// while dragging column
... logic to update column widths
this.recalculate();

// on stop drag
... save the updated column widths
this.recalculate(true);

// this.recalculate
recalculate(skipWidths = false) {
  if (!skipWidths) {
    this.recalculateColumnWidths(); // When skipped, the column widths come from the results of the dragging
  }
  this.recalculateRowHeights();

  this.refreshView(skipWidths);
}

// this.refreshView
refreshView(timeout = false) {
  const refresh = (doForce = true) => {
    if (this.gridRef) {
      if (doForce) {
        this.gridRef.forceUpdate();
      }
      this.gridRef.recomputeGridSize();
    }
  };

  refresh(false);

  if (timeout) {
    setTimeout(refresh);
  }
}
```

**Comment by remizovMaxim** [comment]
i have same problem. Trying "This is extremely hacky"
