### ISSUE TITLE
NPM install fails due to incompatible dependency

### ISSUE THREAD

**Issue by amiramix** [bvaughn/react-virtualized#1005]
Is puppeteer required to run react-virtualized? Can it be an optional dependency?

Currently npm install fails on FreeBSD 11.1:

g@ultrabook:~/work/react-virtualized % npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> husky@0.14.3 install /usr/home/g/work/react-virtualized/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
done

> puppeteer@1.0.0 install /usr/home/g/work/react-virtualized/node_modules/puppeteer
> node install.js

assert.js:41
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Unsupported platform: 
    at Console.assert (console.js:188:23)
    at Downloader.revisionInfo (/usr/home/g/work/react-virtualized/node_modules/puppeteer/lib/Downloader.js:169:13)
    at Object.<anonymous> (/usr/home/g/work/react-virtualized/node_modules/puppeteer/install.js:35:33)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
npm WARN eslint-config-fbjs@2.0.1 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react-dom@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/g/.npm/_logs/2018-02-06T21_54_48_877Z-debug.log

**Comment by TrySound** [comment]
@amiramix puppeteer is used for e2e testing. Nope, it can't be optional dependency, caz it's part of development process. If you want to contibute you can always remove a few lines from package.json without commiting this change.

**Comment by amiramix** [comment]
If this is part of the development process then why does it run with 'npm install'? The problem is that 'npm install' script uses a bunch of dependencies that aren't compatible with some systems. Once these are removed the project can be compiled and works fine, so they are not essential.

**Comment by TrySound** [comment]
@amiramix Do you see puppeteer in regular dependencies https://github.com/bvaughn/react-virtualized/blob/master/package.json#L156-L166 ? Nope, it's DEV dependency, part of DEV process.

**Comment by amiramix** [comment]
Yeah, I should have raised this with puppeteer, not your project. Sorry for troubling you with my question.
