### ISSUE TITLE
Replace deprecated / async-unsafe lifecycles

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#1008]
Replace `componentWillMount`, `componentWillReceiveProps`, and `componentWillUpdate` with async-safe lifecycles in advance of React 16.4 deprecation warnings. Use [react-lifecycles-compat](https://github.com/reactjs/react-lifecycles-compat) to ensure backwards compatibility.

Relates to reactjs/rfcs/pull/6

In-progress documentation available at reactjs/reactjs.org/pull/587 and reactjs/reactjs.org/pull/596

RFC at https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md

**Comment by bvaughn** [comment]
FYI @TrySound, I'm picking this up for the weekend. Do you have any major structural changes in progress? And if not, could you hold off until I'm done with this upgrade?

**Comment by TrySound** [comment]
Awesome. No, I don't have. Only rollup,  but I'm sure it's not related.

**Comment by bvaughn** [comment]
Sweet! Thanks for confirming. 👍
