### ISSUE TITLE
Allow onScrollToChange() in ArrowKeyStepper to override scrollTo parameters

### ISSUE THREAD

**Issue by MarkBarbieri** [bvaughn/react-virtualized#1010]
Hi Brian, thanks for your ongoing support (and the community's :wink:)) on this project.  

I'm using arrowkeystepper with multigrid to create a TV guide.  Layout is similar to a gantt chart.  

I want to use ArrowKeyStepper's onScrollToChange() function to override the scrollTo parameters to facilitate moving between programs (which span multiple grid cells), but onScrollToChange() is not able to modify the scrollTo parameters.

What I'm suggesting is changing this:
```
  _updateScrollState({scrollToColumn, scrollToRow}: ScrollIndices) {
    const {isControlled, onScrollToChange} = this.props;

    if (typeof onScrollToChange === 'function') {
      onScrollToChange({scrollToColumn, scrollToRow});
    }

    if (!isControlled) {
      this.setState({scrollToColumn, scrollToRow});
    }
  }
```

to this
```
  _updateScrollState({scrollToColumn, scrollToRow}: ScrollIndices) {
    const {isControlled, onScrollToChange} = this.props;

    var scrollIndices = {
        scrollToColumn: scrollToColumn,
        scrollToRow: scrollToRow
    };

    if (typeof onScrollToChange === 'function') {
      onScrollToChange(scrollIndices);
    }

    if (!isControlled) {
      this.setState(scrollIndices);
    }
  }
```

Happy to raise a PR if this change appears reasonable.

I considered using isControlled and setScrollIndexes() but then I'll have extra work to replicate componentWillReceiveProps() which no longer fires with isControlled set.  This change feels logical and adds flexibility to the method.

As a background, I'm creating the guide as a grid of 1-minute intervals.  A 30 minute program is rendered with its first cell having the syle.width increased to 30 x cell width for the first minute of the program, all other overlapping cells have their width set to 0.  Programs are rendered using a button.  I maintain a 2D array for each cell that tracks the coordinates of the first cell for the overlapping program, and the first cell of the next program.  In this way I can jump from program to program by overriding scrollToColumn in onScrollToChange()  (with the proposed change of course)

I can do this in cellRenderer but multiple keypresses can be missed as rendering is async. 

Thanks for considering.

**Comment by bvaughn** [comment]
I'm not a fan of that proposal (passing a mutable object to a callback and then using it after the fact). I don't think it fits with the way that any of the other named parameter methods RV uses work.

I should also add that I think the current `isControlled` prop is awkwardly named and could be improved in the next version of RV. That being said...

> I want to use ArrowKeyStepper's onScrollToChange() function to override the scrollTo parameters to facilitate moving between programs

If you want to do this, just store the parameters passed to `onScrollToChange` in your parent component's state and pass them back to `ArrowKeyStepper` as props. Override the state/prop values when/if you want.

> I considered using isControlled and setScrollIndexes() but then I'll have extra work to replicate componentWillReceiveProps() which no longer fires with isControlled set.

I don't understand what you mean by this. 😄

`ArrowKeyStepper` will tell you the suggested values (via `onScrollToChange`). All you have to do is set them, or not. Should be as simple as this, I think:
```js
class ArrowKeyWrapper extends React.Component {
  state = {
    scrollToColumn: 0,
    scrollToRow: 0,
  };

  render() {
    return (
      <ArrowKeyStepper
        {...this.props}
        {...this.state}
        onScrollToChange={this.onScrollToChange}
      />
    );
  }

  onScrollToChange = ({ scrollToColumn, scrollToRow }) => {
    // Maybe you override the scroll-to indices here based on some custom logic 

    if (
      scrollToColumn !== this.state.scrollToColumn ||
      scrollToRow !== this.state.scrollToRow
    ) {
      this.setState({ scrollToColumn, scrollToRow });
    }
  };
}
```

Let me know if I've misunderstood anything. 😄

**Comment by MarkBarbieri** [comment]
Hi Brian, I understand your concern on modifying the object in that way.

What you proposed was where I was initially headed, but I had some issues with updating the props.  At least this confirmed I was on the right track.

I've gone back to that and have worked around my issue for now.

The complication (besides my very limited react experience) is that this component is being added to an existing javascript project (no jsx) and there is no parent react component/state to store the parameters.  The ArrowKeyStepperWrapper is what I was missing to manage the prop updating of the children.  A bit more work, but the right solution.

Thanks again for your time and feedback.

**Comment by bvaughn** [comment]
No worries 😄 

I'm sure you're aware of this, but you can replace the JSX bit in my example above with regular JavaScript:
```js
React.createElement(
  ArrowKeyStepper,
  Object.assign(
    {},
    this.props,
    this.state,
    {onScrollToChange: this.onScrollToChange}
  )
);
```

**Comment by MarkBarbieri** [comment]
Perfect, thanks
