### ISSUE TITLE
Variable Row Heights

### ISSUE THREAD

**Issue by davidychow87** [bvaughn/react-virtualized#1014]
I would like to make a Table with different rowHeights depending if the row was clicked. 

I have passed the following function to the rowHeight props in Table. Note that this.state.selectedIndex is the index of the row that was clicked.
```javascript
 rowHeightSetter = ({index}) => {
    if (index === this.state.selectedIndex) {
      return 150;
    }
    return 30;
  };
```

However, it seems that the absolute positioning of the rows makes it so that the expanded row overlaps other rows. Does anyone have an idea on how to fix this? Thanks!

**Comment by minicopper** [comment]
i also occur the same question? no method
