### ISSUE TITLE
Dropdown DateTimePicker on header not show: z-index issue

### ISSUE THREAD

**Issue by davidychow87** [bvaughn/react-virtualized#1017]
I added a DateTimePicker (from react-widgets) onto a column header, however when it drops down, the date selection widget doesn't get shown:
<img width="261" alt="screen shot 2018-02-19 at 12 11 01 pm" src="https://user-images.githubusercontent.com/22185727/36395544-801ff868-156e-11e8-87c3-53529b65c1c2.png">

Below is the basically the code I've used (minus some other logic and styling). I added the DateTimePicker in the headerRenderer of the Column component:

```javascript
<Column 
   .....props
   headerRenderer={this.headerRenderer}
/>

//headerRenderer function
headerRenderer = ({dataKey, label}) => {
    return (
        <div>
            {this.Label(label)}
            <div>
                 <DateTimePicker ...props />
            </div>
        </div>
    );
}
```

I've tried changing the z-index for the div wrapping DateTimePicker and also the headerStyle on the Table component, but the dropdown calender is still hidden. Is there any way to make it show over the rows?

**Comment by mpmeyer** [comment]
@davidychow87 were you able to resolve this?   How?   Thx.

**Comment by joshlongerbeam** [comment]
@mpmeyer I just hit this issue today.

The problem is the header row element has `style="...overflow: hidden;..."`

I fixed it by adding the following to my css
```css
.ReactVirtualized__Table__headerRow {
  overflow: visible !important;
}
```

The `!important` is necessary to override the element style.

**Comment by MihirModi1421** [comment]
has anyone resolved this issue 
in some answers i got told me to use "react portal" to reslove this issue 
but i do not know how
