### ISSUE TITLE
Unable to drag horizontal scrollbar

### ISSUE THREAD

**Issue by difelice** [bvaughn/react-virtualized#1018]
It is possible to drag the vertical scrollbar but not the horizontal one. (on Mac)

~On Windows systems horizontal scrolling might be tricky so having a way of dragging the scrollbar is helpful.~
Update: Looks like on Windows scrollbars are always visible.

Sandbox: https://codesandbox.io/s/8z7j1wjok2

**Comment by bvaughn** [comment]
I don't believe this has anything to do with `react-virtualized`. I can reproduce the behavior you're describing with the following HTML:
```html
<div style="height: 200px;width: 300px;overflow: auto;">
  <div style="width: 7500px;height: 2000px;" />
</div>
```

> Looks like on Windows scrollbars are always visible.

You're describing the default OS browser style. On Macs, scrollbars are hidden by default, but you can also make them always visible in settings (General > Show scrollbars > Always) if you prefer.

**Comment by difelice** [comment]
@bvaughn you're right. 

Yes, scrollbars are hidden by default, although looks like the behavior on Chrome (Mac) is very inconsistent; I did a quick "test" by shrinking the browser and the `body` horizontal scrollbar works fine (can be dragged), but not the one in a overflow-hidden `div` 🤦🏼‍♂️.  Safari and Firefox work just [fine](https://codepen.io/difelice/pen/wyYQYW). 

Definitely not related to `react-virtualized`.

Thank you so much for your time.

**Comment by bvaughn** [comment]
No problem :)
