### ISSUE TITLE
CellMeasurer propTypes shouldn't expect instance of CellMeasurerCache

### ISSUE THREAD

**Issue by kof** [bvaughn/react-virtualized#1026]
Currently CellMeasurer explicitly checks the type of cache prop to be CellMeasurerCache. If it is expected that user is able to implement his own Cache class, then one shouldn't validate that way, instead it should be checking for specific methods to be implemented.

**Comment by kof** [comment]
I worked this around temporarily by extending CellMeasurerCache but seems unnecessarily.

**Comment by diogofcunha** [comment]
We should create an interface with the public api and type check based on that, nice catch. 
Will do that tomorrow
