### ISSUE TITLE
Flickering on mouse wheel scroll on webkit browsers

### ISSUE THREAD

**Issue by sanex3339** [bvaughn/react-virtualized#1029]
Hi. I was using `react-virtualized` during few days and i noticed very bad behaviour during mouse wheel scroll on webkit browsers (chrome, safari)

All table content are flickering when i scrolled table with mouse wheel. But with sidebar everything is OK.

https://bvaughn.github.io/react-virtualized/#/components/Masonry
This bug can be reproduced here. Just scroll page with wheel and blocks will flicker.

This bug didn't appear on Firefox.

How to fix this flickering?

**Comment by vkhv** [comment]
same for me)

**Comment by erzhtor** [comment]
I also ran into this problem. Very frustrating bug...

**Comment by bajcmartinez** [comment]
same here... drives me nuts in my app

**Comment by xuhuanghuang** [comment]
需要在每一行div中应用{style}

**Comment by mandrewpowers** [comment]
@xuhuanghuang every returned `div` in my renderRow function has the style applied. I also still have this exact issue.

**Comment by noah79** [comment]
Any traction at all on this issue?  Any workarounds?  This doesn't happen when grabbing the thumb and dragging, only with mousewheel...

**Comment by noah79** [comment]
I also see this behavior in react-window.

**Comment by xxRockOnxx** [comment]
i dont think this is specifically an issue for `react-virtualized`. even on a simple "stickying" an element by setting the style to `position: fixed; top: 0` when the edge touches the viewport, this wheel event issue exists.

Im using Chrome 81 (Linux) and this still happens.

**Comment by JasonXiaoSpace** [comment]
> 需要在每一行div中应用{style}

 but not fixed
