### ISSUE TITLE
FlexTable: horizontal scroll appears when width set to viewport width

### ISSUE THREAD

**Issue by Guria** [bvaughn/react-virtualized#103]
`padding-right: 17px;` rule on header causes appear of window horizontal scroll.

**Comment by bvaughn** [comment]
Hi @Guria,

Thanks for taking the time to report an issue. Please link to a demonstration react.run (or similar) example though. If this is not possible, please include relevant information like screenshots, code, etc.

**Comment by Guria** [comment]
@bvaughn is there existing examples how to load react-virtualized in react.run?

**Comment by Guria** [comment]
Figured out a reason. It was because I have no `* { box-sizing: border-box }` rule.
I would recommend to make grids work without assuming this rule exist and add it where appropriate.

**Comment by bvaughn** [comment]
Ah. I think I could resolve that by moving the box-sizing style up 1 level in the Grid CSS. Let me check.

**Comment by bvaughn** [comment]
Actually ... even by removing the `box-sizing: border-box` style from my demo application CSS and turning scrollbars to always-on for OSX, I don't see a horizontal scroll bar for `FlexTable`

**Comment by bvaughn** [comment]
I'm going to close this as won't-fix. I think it's reasonable to require `box-sizing: border-box` be set in order to avoid more complicated layout code.

If you can point me to a react.run example (or a Plunker, or JSfiddle - or even something static that you're hosing on S3, whatever's easier) where I can see what's happening for you then I'd be happy to either update the documentation to make it more clear what's needed in that case, or to suggest a fix. But as it stands now things seem to work as-expected on my side.

**Comment by Guria** [comment]
Okay. Not a big problem, since I can apply this rule in my own stylesheets. But definetely it must be documented

**Comment by bvaughn** [comment]
Well the thing is, it's not necessary with normal usage of react-virtualized. (As the demo shows.) That's why I suggested maybe I could see an example of how you're using the library (what you're doing that's different) so I could maybe better understand how to document edge-cases.

**Comment by Guria** [comment]
I will just continue to use lib. If I found that it worth to be reopened I'll provide more details once I figure them out.

**Comment by bvaughn** [comment]
Sounds good. Thanks :)

**Comment by MikeMcElroy** [comment]
Just banged my head against the wall just to find out that the header row needs `box-sizing: border-box` set, or the padding of size `scrollBarWidth` isn't taken into account.  I'd love to make a react.run or plunk of this behavior, but I have no idea how to make it work with any of those services -- if you have an example I could fork from one of those, @bvaughn, that'd be awesome.

**Comment by bvaughn** [comment]
@MikeMcElroy Easiest way to create a sharable Plunker is probably to just fork one of my playground files: https://github.com/bvaughn/react-virtualized/tree/master/playground

**Comment by cyberxndr** [comment]
There is a related issue. Header overflow appears in cases when FlexTable rendered inside a parent with width < 100%. 

Please, check the following files to get the details (run them from the playground directory).
https://gist.github.com/cyberxndr/d01226de6f9ea15fe64de81c8b425a24
https://gist.github.com/cyberxndr/e662e00a9d6c49a18641a8ce8e3528e6

`* { box-sizing: border-box }` solves the problem.

**Comment by bvaughn** [comment]
Hey @cyberxndr Been sick and a little swamped at the moment. What free time I do have has been focused on the v7 update. Please file a new issue for this.

As a side note, it would be nice if your files were runnable directly from rawgit (eg [here](https://rawgit.com/cyberxndr/d01226de6f9ea15fe64de81c8b425a24/raw/6bf567e1903e15eec065944dbff0fe52b221f4de/example.html) as that would save me a tiny bit of trouble replicating your issue.
