### ISSUE TITLE
Is there a simple to implement pull-refresh in react-virtualized?

### ISSUE THREAD

**Issue by shikelong** [bvaughn/react-virtualized#1030]
Regards.

**Comment by TrySound** [comment]
@shikelong It's not clear what are you asking. Can you describe more?

**Comment by leuction** [comment]
@TrySound I think what he is asking is when we scroll to the top of the list, we can fetch more data and concat to the top of the list. I am asking for the same solution.

**Comment by TrySound** [comment]
Do you guys wanna set scrollTop to 0 when your data is refetched?

**Comment by shikelong** [comment]
@TrySound 
Not set scrollTop to 0. just like this:
[pull-refresh demo](https://apeatling.com/demos/web-ptr/)
Is there a way to implement it with react-virtualized? Regards.

**Comment by TrySound** [comment]
@shikelong How is that related to react virtualized? This feature can be implemented in userland.

**Comment by shikelong** [comment]
Thank you. :)  you are right.
