### ISSUE TITLE
AutoSizer doesn't update the height when removed a grid

### ISSUE THREAD

**Issue by SuhanKoh** [bvaughn/react-virtualized#1032]
The dom I have built looks like this
```
<AutoSizer>
  <List
     rowHeight = {function}>

  </List>
</AutoSizer>
```

In the list row rendered, I have a special row on row index 0, which will be skipped if certain conditions are met, but when this happen, row 1 and onward does not update the style.top which will leave an empty section.
Is there a way to force re-calculate the height?

**Comment by bvaughn** [comment]
Hi @SuhanKoh 👋

This section of the docs is what you're looking ofr:
* https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#recomputerowheights-index-number

The short answer is that you should attach a `ref` to `List` so you can call `recomputeRowHeights()` when the first row has been dismissed.
