### ISSUE TITLE
npm install and yarn install both crash with 404 errors

### ISSUE THREAD

**Issue by jtiscione** [bvaughn/react-virtualized#1033]
I'm trying to check out the repository to see how the demos work (because they certainly don't work for me) but the package.json is corrupt. The yarn.lock file is no help.

Steps to reproduce (yarn):
```
git clone https://github.com/bvaughn/react-virtualized
cd react-virtualized
yarn install
```

Result:

```
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.0.0-beta.31.tgz: Request failed \"404 Not Found\"".
```

Steps to reproduce (npm):
```
git clone https://github.com/bvaughn/react-virtualized
cd react-virtualized
npm install
```

Result:
```
npm ERR! code E404
npm ERR! 404 Not Found: @babel/traverse@^7.0.0-beta.40
```
Is there a tag or branch that uses stable packages?

**Comment by bvaughn** [comment]
This looks like a transient Yarn issue. It happens with Yarn from time to time. Nothing specific to react-virtualized

https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.0.0-beta.31.tgz is working fine now.
