### ISSUE TITLE
MultiGrid Rowrenderer

### ISSUE THREAD

**Issue by TriStarGod** [bvaughn/react-virtualized#1042]
# Requesting a Feature?
Rowrenderer for MultiGrid
Provide as much information as possible about your requested feature. Here are a few questions you may consider answering:
* What's your use case? (Tell me about your application and what problem you're trying to solve.)
Would like to add drag components to rendered row.
* What interface do you have in mind? (What new properties or methods do you think might be helpful?)
rowrenderer
* Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)
react-virtualized list component

**Comment by bvaughn** [comment]
I don't think it makes sense to slice grids into rows. Why not columns? Either is reasonable, and since there are multiple reasonable options- I think it's best to leave it as-is.

If you want to group cells within _your_ grid into rows, you can probably do this by providing your own `cellRangeRenderer`, but it isn't something I think belongs in grid by default.

Thanks!

**Comment by TriStarGod** [comment]
Hi @bvaughn ,
Thanks for the response. I wanted to apply 'react-sortable-hoc' to the MultiGrid and it needs to depend on the row. I'm adjusting the MutiGrid script for my purposes however I am facing some issues with the sorting feature. Anytime I drag a row from its original location, its not transitioning correctly and keeps moving to the extremes (topmost or bottom most). I created an example using Grid to portray the issue: https://codesandbox.io/s/5kl4z8olrn

**Comment by TriStarGod** [comment]
Follow up stack exchange question: https://stackoverflow.com/q/49262110/1370984

**Comment by TriStarGod** [comment]
In https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/defaultCellRangeRenderer.js
```
else {
          style = {
            height: rowDatum.size,
            left: columnDatum.offset + horizontalOffsetAdjustment,
            position: 'absolute',
            top: rowDatum.offset + verticalOffsetAdjustment,
            width: columnDatum.size,
          };

          styleCache[key] = style;
        }
```

`styleCache[key] = style;` should be outside the `else`, right?
