### ISSUE TITLE
MultiGrid: extra row/column to fit scrollbar must be added if the opposite scrollbar exists

### ISSUE THREAD

**Issue by jeron-diovis** [bvaughn/react-virtualized#1049]
Check out this fiddle, please: https://codesandbox.io/s/0om24qx99w

Under option `happy-path` is a reduced copy of your [official MultiGrid demo](https://bvaughn.github.io/react-virtualized/#/components/MultiGrid). 
In this example both total rows height and total columns width exceeds height/width of grid, so both scrollbars are visible and extra row/column is added to align content:

<img width="433" alt="screenshot 2018-03-15 14 10 01" src="https://user-images.githubusercontent.com/2756868/37462572-277a6572-285b-11e8-9e23-085a1b44daf1.png">

---

Under option `width` there is a case when total columns width is equal to grid width, and total rows height exceeds grid height. 
In this case Grid thinks that horizontal scrollbar should not be displayed (accordingly to [[1]](https://github.com/bvaughn/react-virtualized/blob/6faafb5c4398e502c568db73fc430e56e8434e81/source/Grid/Grid.js#L877-L880), [[2]](https://github.com/bvaughn/react-virtualized/blob/6faafb5c4398e502c568db73fc430e56e8434e81/source/Grid/Grid.js#L1222-L1225)), and so extra column is not added ([[3]](https://github.com/bvaughn/react-virtualized/blob/6faafb5c4398e502c568db73fc430e56e8434e81/source/MultiGrid/MultiGrid.js#L579-L590), [[4]](https://github.com/bvaughn/react-virtualized/blob/6faafb5c4398e502c568db73fc430e56e8434e81/source/MultiGrid/MultiGrid.js#L723)).

But vertical scroll exists, **and it takes some space inside grid**. So in fact grid width becomes a bit less than total columns width, and horizontal scroll still appears – while being not compensated by extra column:

<img width="573" alt="screenshot 2018-03-15 14 10 11" src="https://user-images.githubusercontent.com/2756868/37462573-2796db6c-285b-11e8-9743-a62c06c37fe1.png">

---

All the same is vice versa for `height` option:

<img width="441" alt="screenshot 2018-03-15 14 10 22" src="https://user-images.githubusercontent.com/2756868/37462574-27b386c2-285b-11e8-8f66-5eca8e328a86.png">

---

I managed to patch this problem in my project, but via very bad hack with updating state of a child by it's parent, intruding in child's internal logic.  

It looks like Grid logic should be updated, so if one scrollbar is present, second one must be considered present too.

**Comment by mikkelwf** [comment]
Same issue here.. :/

**Comment by casvil** [comment]
@bvaughn 

1 fixed row with visible scrollbar. is it possible to fix?
thx

![Screenshot 2019-07-31 at 09 28 14](https://user-images.githubusercontent.com/1532640/62192286-9989c800-b375-11e9-9435-13db802806e5.png)

**Comment by akhilaudable** [comment]
Any improvements on this issue?

**Comment by jesus4497** [comment]
For anyone facing this issue, a potential solution would be to calculate the scrollbar size with the prop `onScrollbarPresenceChange`, for instance: 
```js
onScrollbarPresenceChange={({vertical, size}) => {
                if (vertical) {
                  setScrollBarWidth(size);
                } else {
                  setScrollBarWidth(0);
                }
              }}
```  

And finally in the `columnWidth` prop, subtract this value to the columns width! Hope it helps
