### ISSUE TITLE
Cannot import components with aliases

### ISSUE THREAD

**Issue by chrisbrainerd** [bvaughn/react-virtualized#1057]
Hi, I'm already using semantic-ui-react in a file which has a component `Table`, so I attempted to `import { Table as vTable };`, which doesn't fail per se, but the second you put a column under it it throws `instance.render is not a function`.  If you import Table without an alias then alias Column as something else, it also breaks though with a different error. 

Here's a codesandbox project to demonstrate a minimal case: https://codesandbox.io/s/oqm3r05xqy

It starts with the working example rendering, but comment out the render call on line 43 and uncomment the one on 44 and you'll see the error. 

edit: should also note fwiw the example is the exact one from https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md other than the import switch.

**Comment by aem** [comment]
This is a function of how JSX works, actually. Anything that starts with a lowercase letter is interpreted as an HTML element, not a React component: https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized

Changing your example to `import { Table as RVTable } from 'react-virtualized';` works just fine
