### ISSUE TITLE
Doesn't re-render a row with isVisible until you stop scrolling

### ISSUE THREAD

**Issue by nickretallack** [bvaughn/react-virtualized#1059]
I used the isVisible flag in my List's rowRenderer.  Unfortunately, rows are not re-rendered with this flag until scrolling comes to a dead stop.  As a result, if you are smoothly scrolling without letting your fingers leave the trackpad, isVisible will never be true.  You could pass by a lot of content that never gets re-rendered with isVisible.  That means you can't rely on isVisible to re-render things as they enter view, and you also can't rely on it to track impressions on content since its behavior really depends on how smoothly you scrolled.

**Comment by ricopella** [comment]
Running into an issue was well that may or may not be related. In my case, I'm using List as a dropdown, and when the user mouses' out of the dropdown, it hides. The issue I'm running into, is if they mouse out while the list is still scrolling, and then re-open the list, it's blank. However, if they scroll down or up, the list re-appears in the correct index location it left off. 

![rv](https://user-images.githubusercontent.com/19675778/40246872-41d147a0-5a7f-11e8-87b1-3ff4a7acd5df.gif)

**Comment by matiastucci** [comment]
@nickretallack I'm having the same problem. Did you find a solution?

**Comment by nickretallack** [comment]
@matiastucci no.  I stopped using this library.
