### ISSUE TITLE
FlexColumn: add minWidth maxWidth props

### ISSUE THREAD

**Issue by Guria** [bvaughn/react-virtualized#106]
Is it able to add support off `minWidth` and `maxWidth` props for `FlexColumn`?

**Comment by bvaughn** [comment]
Hm. It's possible to add this, although I'm not sure how I feel about it. You _have_ to specify a `width`. If you chose to specify a `maxWidth` you'd have to also make sure `flexGrow` was greater than 0 or it would have no affect.

I've pushed PR #111 which adds this feature but I'm going to leave it sit for a while so I can think over it. I'm also temporarily more focused on trying to verify a fix for #2.

**Comment by bvaughn** [comment]
Look for this to go out momentarily with the 5.2.0 release.
