### ISSUE TITLE
Add links on README.md to current Roadmap

### ISSUE THREAD

**Issue by thadguidry** [bvaughn/react-virtualized#1062]
I noticed that there are no Milestones or Projects here in Github being utilized.
Our project was looking for the current Roadmap and only saw past Roadmaps under the Wiki.

It would be useful for other projects (like OpenRefine) looking to utilize react-virtualized to have a sense of where future development is going, at least with basic Milestones or some Roadmap or Project plan captured somewhere, if not in Github itself.

**Comment by bvaughn** [comment]
Issue #658 is about all I have for roadmap. Planning roadmaps is a lot of work and I'm not really able to keep up with questions and issues as it is lately.

If you'd like to help, I'd love for you to join the [Slack channel](https://react-virtualized.now.sh/), message me to add you to the maintainers group, and then help coordinate things. 😄

Realistically though, I don't have the time to create a roadmap.

**Comment by thadguidry** [comment]
@bvaughn thanks, that issue is enough info for now.
