### ISSUE TITLE
Flicker on an ios device with fixed position element while scrolling on Grid

### ISSUE THREAD

**Issue by john-aldridge** [bvaughn/react-virtualized#1065]
While using a very minimalistic example, I am able to see flickering on a fixed positioned element that is outside of the Grid while scrolling the Grid on an ios device.

Here is a live example of the issue:  https://codesandbox.io/s/qlp434xk04

Here is a video of the issue. https://youtu.be/KVfjI-Yk4F8

Is there anything that can be done to fix or mitigate this issue.  Thanks for the help!

**Comment by GulinSS** [comment]
We are dealing with something very similar to video even w/o `fixed` css rule... 🤔

**Comment by gdvsbp** [comment]
I've encountered this as well on the first day of putting this code out onto production. I see it hasn't gotten much traction here as an issue, but to anybody who has some inkling of an idea: any leads? It's pretty mysterious to me.

**Comment by Jarred-Sumner** [comment]
fwiw i fixed this by using `WindowScroller`. I think UIScrollView has trouble handling multiple vertically scrolling containers simultaneously, which is what's happening when you have a body that could theoretically scroll and another container which could theoretically scroll
