### ISSUE TITLE
Add Right to Left support to Masonry

### ISSUE THREAD

**Issue by bardiarastin** [bvaughn/react-virtualized#1070]
Hello,
i'm using this project for one of my projects which is in Farsi and RTL so i need masonry in right to left direction.

i've read a little bit of Masonry source code and figured out it's using position absolute + some top and left values to adjust elements, i was able to achieve this by switching left to right in 
https://github.com/bvaughn/react-virtualized/blob/af90cfec8b2b131896fd979795c5d8c54480ff27/source/Masonry/Masonry.js#L396

screenshot:
![image](https://user-images.githubusercontent.com/20615964/38451935-9b370934-3a4e-11e8-948f-385aab8eca73.png)

i'm not sure that this is a silly solution or it's okay, then if it is or you have better solution, i can make a PR for this for an additional prop called isRtl ❤️

**Comment by bvaughn** [comment]
> i can make a PR for this for an additional prop called isRtl

Property naming wise, I would suggest `direction` (defaults to "vertical" but can also be "horizontal").

You'd be welcome to submit a PR, including docs and tests. Depending on how much complexity it adds, I'll consider adding it to the library. 😄

**Comment by bardiarastin** [comment]
I agree with you about naming, just wanted to demonstrate the main idea.
if we only call it direction the use might misunderstand which direction do we mean (direction in the row or column).
what if we call it rowDirection instead which defaults to ```ltr``` and can be ```rtl``` too.
```
<Masonry rowDirection="rtl" />
```
