### ISSUE TITLE
Not rendering first row sometimes when scrollToPosition is used

### ISSUE THREAD

**Issue by cjhowedev** [bvaughn/react-virtualized#1074]
Hi! 👋

[Let's start with the reproduction of the issue](https://codesandbox.io/s/74no81k16). I expect the first row to be rendered (would be "0-0"), but it's not being rendered at all. 

This happens if I scroll to a position in the list, but that position can't actually be scrolled to. For example, if the entire list fits on the screen, then scrolling to `2 * rowHeight` will cause `react-virtualized` not to render the first row. This happens regardless of the `overscanRowCount`, so I'm not sure what's special about this number. But I have no way to know whether or not all the items will display without scrolling in the list unless I have its height. I think that `react-virtualized` should detect whether it's actually necessary to scroll before considering the value I give to `scrollToPosition`.

**Comment by cjhowe7** [comment]
More information. The following component wraps VirtualizedList with a workaround that prevents this issue.

```js
class BetterVirtualizedList extends Component {
  scrollToRow(row) {
    this.rowToScroll = row;
  }

  componentDidUpdate() {
    if (
      this.props.height > 0 &&
      this.rowToScroll != null &&
      this.props.height < this.props.rowCount * this.props.rowHeight
    ) {
      this.list.scrollToRow(this.rowToScroll);
      this.rowToScroll = null;
    }
  }

  render() {
    return (
      <VirtualizedList {...this.props} ref={value => (this.list = value)} />
    );
  }
}
```

**Comment by avin** [comment]
confirmed, there may be a problem like this when you try to `scrollToRow` to not existing row index

**Comment by cjhowe7** [comment]
Any updates on this?

**Comment by step-off** [comment]
Have the same issue.
