### ISSUE TITLE
InfiniteLoader spams loadMoreRows on scroll with slow API / small minimumBatchSize

### ISSUE THREAD

**Issue by luke-gumbley** [bvaughn/react-virtualized#1083]
Similar to #345, ran into it because of an unrelated bug in my code leading to slow API responses. See the impact of this issue in [this CodePen](https://codepen.io/luke-gumbley/pen/mxopjR?editors=1010).

Looking at the memoization code, I'd like to suggest adding a preference in [scanForUnloadedRanges](https://github.com/bvaughn/react-virtualized/blob/5fa323680c17023f06c35dfd1f928a42f3894031/source/InfiniteLoader/InfiniteLoader.js#L173) to load multiples of minimumBatchSize where possible. This would reduce the volume of duplicated calls.

I understand that I should be storing loaded rows in the state of my component (per the [documentation](https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md#tracking-loaded-and-loading-rows)), and I'll absolutely do that. I also know this tweaks the meaning of minimumBatchSize... and if you're storing loaded rows in the consuming component, as you should, this issue has no impact. However it was a very small change so I haven't lost much time if you don't like it :)

**Comment by akraines** [comment]
See this pen: https://codepen.io/akraines/pen/vjyKXy
The check isRowLoaded is what is used to decide whether the rows have been or are being loaded.
```
const isRowLoaded = ({index}) => {
  return !!items[index];
};
```
To use it all you need to do is set the rows to 'loading' state be fore calling the promise in loadMoreRows.
Then make your render routine deal with "loading" rows.

**Comment by luke-gumbley** [comment]
Hi @akraines ! I'm aware that the consuming component should store the loading state of a row, I've actually already modified my usage to do this.

The reason for this issue and PR is that once you maintain a loading state yourself, the memoization serves no purpose. In that case it would be better not to have it at all, because then you wouldn't need to call resetLoadMoreRowsCache on resetting the content of the child.

So if the memoization is there, it seems legitimate to make it a bit more efficient by regularising the indices that are memoized.
