### ISSUE TITLE
List inside an AutoSizer - scrolling locks up on iOS 11 with Safari

### ISSUE THREAD

**Issue by spjharper** [bvaughn/react-virtualized#1087]
I've seen some issues here about flickering when scrolling under iOS, but our app is having a very strange problem with scroll gestures being ignored.

The scenario that will make it happen is if we render the beginning of the list so that index 0 is at the top. Then swipe down on the list as if you wanted to see items that precede item 0, then swipe the other direction to scroll items into view with a higher index. Usually when we try the second swipe to show more items further down the list after first swiping in the wrong direction, the swipe has no effect - it will not scroll. 
Continued swipes have no effect, but if you pause for about 5 seconds then you can again swipe up and have the scrolling work.

I've tried checking for an index < 0 in the rowRenderer and also tried returning a lightweight element if rowRenderer is called with isScrolling true. Neither has had any effect on the scroll lock up.

This is happening with react-virtualized 9.18.5 with react 16.2.0 under Safari with iOS 11.0.3.

Wondering if anyone else has seen this and if there is a workaround.

**Comment by solkaz** [comment]
I am noticing the same issue, although in my case I am using a `Grid` instead of a `List` component. When comparing tablet devices, I was able to get a similar issue on a Surface Pro using Edge, but that almost never occurred. I believe there is an issue with the rubber-band scrolling effect from iOS, but I'm not certain as to the underlying issue.

Versions:
- react: 16.2.0
- react-virtualized: 9.19.0
- iOS version: 11.2.5

**Comment by pedro-mass** [comment]
Did anyone ever figure this out?

**Comment by ADagen** [comment]
Catch the same with react-virtualized@9.21.0, react@16.6 under Safari (WKWebView) on iOS 12.

**Comment by dep** [comment]
@jassmith 
> The only hack I've ever found to semi reliably fix this is to ensure the scrollable region is always at 1 or maxScroll - 1. This way it wont chain to the document scroller.

Can you elaborate on this solution a bit?
