### ISSUE TITLE
Wrong rows position on List

### ISSUE THREAD

**Issue by sebastiencs** [bvaughn/react-virtualized#1091]
Hi, thank you for this great library !

I've started to use it today to display +2 millions items in a List.
I noticed that when I'm using the scroll button on my mouse, everything works fine.
But if I'm moving in the list with the scrollbar, the rows won't show up:

![list](https://user-images.githubusercontent.com/5273820/39339600-fba45eea-49c9-11e8-829c-f127f0f813a3.gif)

In the gif, the chrome devtool is indicating that rows are renderer below the viewport (I'm new to web development so it might be a wrong diagnostic)

I'm using the following code:
```javascript
      // Buggy code
      <AutoSizer>
        <InfiniteLoader ... >
          <List
            rowHeight={a_function} // The function's body is just a `return 20;`
            ...
            />
        </InfiniteLoader>
      </AutoSizer>
```

If i'm setting the `rowHeight` props directly to a number, the rows are correctly rendered

```javascript
      // It works
      <AutoSizer>
        <InfiniteLoader ... >
          <List
            rowHeight={20}
            ...
            />
        </InfiniteLoader>
      </AutoSizer>
```

Let me know what informations can I give you.. Thanks

**Comment by wuweiweiwu** [comment]
Hi,

Can you put this reproduction in a codesandbox? thus maintainers can poke around.

Thanks!
