### ISSUE TITLE
CSS Styling is missing

### ISSUE THREAD

**Issue by entrptaher** [bvaughn/react-virtualized#1095]
I searched stackoverflow and found a [similar problem](https://stackoverflow.com/q/48077765/6161265) back in january and till now no good viable answer. I am not sure if it's an issue or a bug.

Problem:
- First one is the normal rendering. It contains all styles and such with proper styling. 
- Second one is the one where I tried to use Link, AutoScroll, Table, Column and whatnot element got the same screwed result. It simply loses the styles, also there is a problem with `key` property. 
- I used the dummy plukr provided with the issue template and it screwed up as soon as I provided a nested element. 
- Passing style can be done, that works neatly but passing anything with a className simply stops working. 

I did not find any proper docs regarding this, I am not sure if I missed something really simple. What can be the issue and how can this be solved? 

Here is the plukr link: https://plnkr.co/edit/fOa2pPGBit92W5eOmxF1?p=preview

**Comment by wuweiweiwu** [comment]
@entrptaher The issue is on this line

```
      rowRenderer={({ index, isScrolling, key, style }) => (
```

you need to apply the `style` to each of your rows. That styling is used to absolute position elements. within the virtualized List

Hope that helps!

**Comment by entrptaher** [comment]
@wuweiweiwu that means default style is obviously getting removed? Like I must provide my custom style and className is not supposed to work as I stated in the first post?

**Comment by TrySound** [comment]
@entrptaher `className` will work. style you may customize with `Object.assign` or spread operator

**Comment by entrptaher** [comment]
To make it work, I need to add `ui relaxed divided list` class to the `List` element. But if I add these to the `List className`, it doesn't get passed by. 

Maybe I am missing some really simple obvious.

**Comment by entrptaher** [comment]
Adding to above reply. I think we should have something like `innerScrollerClassName` or something on the Grid. I made some local changes to that(!) and sementic-ui worked perfectly.

But this is likely to break the scrolling functionality. If any of you have any alternative solution, please guide me.

**Comment by wuweiweiwu** [comment]
`className` for `Grid` is applied to the *root* element as specified in the doc. 

https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L1034

If you would like to submit a PR feel free!
