### ISSUE TITLE
CellMeasurer for List with equal dynamic height rows

### ISSUE THREAD

**Issue by zhulduz** [bvaughn/react-virtualized#1099]
I apologize in advance if the question already exists, but I have not found.

I use `CellMeasurer` for `List` with dynamic heights, and all rows have the **identical** heights.
`CellMeasure` calculates the height for each row, what is unnecessary for my case.

Is there any possible solution to make `CellMeasurer` calculate only one time to speed up performance?
Or maybe is there another solution for my case?

Thanks in advance.

**Comment by alecmerdler** [comment]
Found this: https://github.com/bvaughn/react-virtualized/issues/794

Use `CellMeasurerCache` with `keyMapper:() => 1`.

**Comment by wuweiweiwu** [comment]
thats awesome! thanks for finding that @alecmerdler

**Comment by zhulduz** [comment]
Sorry for later response. @alecmerdler thanks, it works now.
