### ISSUE TITLE
AutoSizer and offset* property

### ISSUE THREAD

**Issue by arshtepe** [bvaughn/react-virtualized#1100]
AutoSizer is used for size calculation offsetWidth and offsetHeight 
https://github.com/bvaughn/react-virtualized/blob/master/source/AutoSizer/AutoSizer.js#L165
but offset* property round value. When we have width like 303.1px, it rounds to 302px.
In this example content override right border https://codesandbox.io/s/qlwo8q5py9 .
If use getBoundingClientRect it solves this problem

**Comment by wuweiweiwu** [comment]
@arshtepe that would return the same values unless some transforms were applied [mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements) 

It also seemed to display properly for me on chrome. 
<img width="220" alt="screen shot 2018-06-08 at 2 44 14 am" src="https://user-images.githubusercontent.com/35270620/41151539-e7717850-6ac5-11e8-8af3-c6dbcb3b5479.png">
