### ISSUE TITLE
How to get `totalRows` as a props in cellRenderer function

### ISSUE THREAD

**Issue by ankit-chaurasia** [bvaughn/react-virtualized#1102]
I am trying to get following things in cellRenderer function:

1. Total rows count
2. Current number of rows(rows that are currently present in the table ), so that I can get the rowIndex for the newly added row in the table

Any suggestions will be helpful

**Comment by wuweiweiwu** [comment]
hi @ac13793 I don't fully understand your question.

usually in your component you specify a `rowCount` prop to rv components to tell it how many components it will have. and `cellRenderer` is automatically called with those indices to render the corresponding rows. 

I would encourage you to checkout out some of the [demos](https://github.com/bvaughn/react-virtualized#examples) on codesandbox. 

hope that helps!
