### ISSUE TITLE
polyfill - Breaking changes 

### ISSUE THREAD

**Issue by nir-welldone** [bvaughn/react-virtualized#1113]
hey,
I've got some unexpected error on 
> "version": "9.19.0"

![image](https://user-images.githubusercontent.com/32127792/40164765-192bf30c-59c3-11e8-9251-78d8c57927bc.png)

After some search I found this issue:
https://github.com/reactjs/react-lifecycles-compat/issues/8

When I changed in the node_moudles this line
`import polyfill from 'react-lifecycles-compat';`
to
`import {polyfill} from 'react-lifecycles-compat';`
it worked!

Can you please fix it?

**Comment by nir-welldone** [comment]
the problem was in a different package that used react-virtualized.
Sorry..

**Comment by joevbruno** [comment]
@nir-welldone how did you fix this. I'm running into the same thing

**Comment by wuweiweiwu** [comment]
version 9.19.1 should fix that.
