### ISSUE TITLE
Grid: rendering using react-test-renderer breaks in 9.19.0

### ISSUE THREAD

**Issue by wuweiweiwu** [bvaughn/react-virtualized#1117]
```js
import renderer from 'react-test-renderer';

const tree = renderer
      .create(<Grid ... />)
      .toJSON();
```

Error message: 
```js
      Error: Uncaught [TypeError: Cannot read property 'scrollLeft' of null]
```

Possibly not working because react-test-renderer doesn't support the polyfilled lifecycle functions?

**Comment by wuweiweiwu** [comment]
https://github.com/facebook/react/issues/7740 react-test-renderer. Doesn't support refs. Need to pass in `createNodeMock` option

**Comment by nihgwu** [comment]
@wuweiweiwu but how can I pass `createNodeMock` to `Grid`? I created a `Table` component on `Grid`, and testing the `Table` component

**Comment by nihgwu** [comment]
can we check before accessing the ref here? https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L627

**Comment by wuweiweiwu** [comment]
`createNodeMock` is an option in `react-test-renderer` 
https://reactjs.org/docs/test-renderer.html#ideas

**Comment by wuweiweiwu** [comment]
If you want to contribute a PR that'll be awesome!!

**Comment by nihgwu** [comment]
@wuweiweiwu seems `createNodeMock` is applied to all the nested components when creating, but that's still odd to me that I have to add that option manually in every test case, I'm testing my own `Table` component, and don't use refs in `cDM`, `Grid` should be transparent for me
