### ISSUE TITLE
Grid fixed rows/columns

### ISSUE THREAD

**Issue by benitogf** [bvaughn/react-virtualized#1122]
* What's your use case?
  using ArrowKeyStepper, AutoSizer and Grid to make a fullscreen spreadsheet

* What interface do you have in mind?
   same as in multigrid feature but w/o separating the fixed rows/columns to a different grid, and a boolean flag instead of a count

* Can you point to similar functionality with any existing libraries or components?
   this feature is available on the multigrid component

~Having the fixed row and column on a separated grid break some ArrowKeyStepper interactions,~  could be nice to have, thanks for this great project 👍

**Comment by benitogf** [comment]
the only limitation of using multigrid instead of grid to enable fixed rows/columns is as discussed on #1108 that data changes or resize events will not propagate, perhaps this feature will not be required if the propagation of events is fixed on multigrid

Or maybe we just need more documentation on how to call the public methods of multigrid https://github.com/bvaughn/react-virtualized/blob/master/docs/MultiGrid.md#forceupdategrids
https://github.com/bvaughn/react-virtualized/blob/master/docs/MultiGrid.md#recomputegridsize
https://github.com/bvaughn/react-virtualized/blob/master/docs/MultiGrid.md#measureallcells
in a way that would make the behavior event wise of multigrid the same as grid

**Comment by benitogf** [comment]
Made this replication of the issue: https://codesandbox.io/s/wq01850r7k using Grid it will resize (on window resize) but not with MultiGrid, however the rowCount change is not propagated to neither.

**Comment by benitogf** [comment]
I was able to solve above use case with [this change](https://github.com/benitogf/react-virtualized/commit/c6f0ba974b7e67a1febfd870fe27ed65a9df6c86#diff-99802fabd7c473f2716ef2f26b6ca690R552), sure that there is be a better way though

**Comment by wuweiweiwu** [comment]
hm interesting. regularly I would suggest using `Grid.forceUpdateGrids` but it seems that height and width changes still trigger rerenders, but just doesn't resize the columns. I'll take a look this weekend. 

Thanks!
