### ISSUE TITLE
Add support for Justified-Layout

### ISSUE THREAD

**Issue by xVanTuring** [bvaughn/react-virtualized#1125]
# Support for Justified Layout
Justified-Layout is one of the most-used layout, like the Masonry-Layout.
I viewed the doc, and didn't see any implementation about Justified-Layout.
So, hope it's a good feature to add!

## references
[flickr/justified-layout](https://github.com/flickr/justified-layout)

**Comment by wuweiweiwu** [comment]
cc/ @bvaughn @TrySound 

Do you guys think we should continue adding features v9? or only continue in maintenance mode?
