### ISSUE TITLE
new sideEffects specification removes css files

### ISSUE THREAD

**Issue by sfmcintyre** [bvaughn/react-virtualized#1135]
**Issue (with react-virtualized v9.19.1):** when importing react-virtualized css styles via
```
import 'react-virtualized/styles.css'
```
in a React component, these stylesheets are removed when using the following webpack (v4.11.1) configuration
```
module: {
	rules: [{
		test: /\.css$/,
		loader: 'style-loader!css-loader'
	]},
}
```
(This issue isn't present in react-virtualized v9.18.5 w React + React-dom v16.2.0, but arises in v9.19.0 & v9.19.1. Testing on Chrome v66.0.3359.181, MacOS 10.12.6)

**Potential solution:**
The v9.19.0 `package.json` specification which sets `"sideEffects": false` (shown here https://github.com/bvaughn/react-virtualized/compare/9.18.5...master) causes webpack's css loader to drop react-virtualized css files, since they're not explicitly used in our React jsx. If the above css importing paradigm is still supposed to ensure styles just work via import, it may be useful to change the documentation to discuss side effect management, or remove the `"sideEffects": false` specification.

Note, a quick fix by changing our webpack configuration to
```
module: {
	rules: [{
		test: /\.css$/,
		loader: 'style-loader!css-loader',
		sideEffects: true
	]},
}
```
ensures that react-virtualized's css files _are_ kept when imported in a React component, but this also prohibits webpack from tree shaking to remove any unused css files, which isn't ideal.

**Comment by wuweiweiwu** [comment]
hi @sfmcintyre I'm not super familiar with how side effects work with webpack. But thanks for bringing this to my attention. I will be investigating more thoroughly

**Comment by swarthy** [comment]
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
should package.json contain something like
```
sideEffects: ["*.css"]
```
?

**Comment by wuweiweiwu** [comment]
Makes sense.
