### ISSUE TITLE
Using CellMeasurer with scrollToIndex in a list bounces back to scrollToIndex if row is not in CellMeasurerCache

### ISSUE THREAD

**Issue by EmilyHwang** [bvaughn/react-virtualized#1148]
I'm using CellMeasurer with scrollToIndex set to that last item in the list. I found that with even with  the fix in #[998](https://github.com/bvaughn/react-virtualized/issues/998), if the user uses the mouse to manually drag the scrollbar all the way to the top then tries to scroll down normally, the list jumps back down to the last item. 

After some investigation, it seems that the list jumps to the scrollToIndex value if the row is not in the CellMeasurerCache

**Comment by wuweiweiwu** [comment]
hi @EmilyHwang that MR was reverted. I'll have to go back and and fix the tests. and push another change out.

**Comment by EmilyHwang** [comment]
@wuweiweiwu Even with that change (I manually made that fix locally), scrolling does not work properly

**Comment by wuweiweiwu** [comment]
@EmilyHwang Thanks for verifying. Ill take a look soon

**Comment by wuweiweiwu** [comment]
@EmilyHwang can you post a simple repro in a codesandbox? that'll be much appreciated
