### ISSUE TITLE
Feature request: initialNumToRender prop or similar

### ISSUE THREAD

**Issue by chitezh** [bvaughn/react-virtualized#1150]
How many items to render in the initial batch. This should be enough to fill the screen but not much more. Note these items will never be unmounted as part of the windowed rendering in order to improve perceived performance of scroll-to-top actions.

The most important use case of this for me is being able to prevent `windowing` in the first index

See react-native FlatList for more
https://facebook.github.io/react-native/docs/flatlist.html#initialnumtorender

**Comment by chitezh** [comment]
@wuweiweiwu how difficult will be to implement this? I'm happy to take this on if I can some pointers. Thanks

**Comment by wuweiweiwu** [comment]
@chitezh, i took a look at flat list. It seems that its purpose is to have permanently rendered items on top of the list to improve performance. I wouldn't be opposed to this however, one thing that would be difficult to handle is cache invalidation. When will you know that those cells changed and will have to rerender them?

I would take a look at the [cellRenderer](https://github.com/bvaughn/react-virtualized/blob/438b5672e5364cffa91f21656ee2f04003794ca1/source/Grid/defaultCellRangeRenderer.js) to understand how we cache cells to improve performance. 

Hope that helps!

**Comment by chitezh** [comment]
Thanks @wuweiweiwu, that helps. We are able to work around this by saving the state of the row I'm interested in and restoring it on remount. It would be great to have a solution that prevents the rows from being unmounted in the first place.
