### ISSUE TITLE
Presence of require() in es modules

### ISSUE THREAD

**Issue by magnetnation** [bvaughn/react-virtualized#1157]
I am trying to bundle es versions of several react-virtualized components using rollup module bundler.
I have noticed that many of them include code that uses `require()`.

For example in `react-virtualized/dist/es/Masonry/createCellPositioner.js`:
```
var babelPluginFlowReactPropTypes_proptype_Positioner = require('./Masonry').babelPluginFlowReactPropTypes_proptype_Positioner || require('prop-types').any;

var babelPluginFlowReactPropTypes_proptype_CellMeasurerCache = require('./Masonry').babelPluginFlowReactPropTypes_proptype_CellMeasurerCache || require('prop-types').any;

export default function createCellPositioner(_ref) {

```
This messes up rollup as it is unable to analyze it further and leaves `require` calls as is. 
It looks like they should be replaced with `import`?

So far the only way to use it with rollup is to manually replace lines that starts with 'babelPluginFlowReactPropTypes_'. But this is ugly and I would rather not do it.

Is there anything obvious I am missing here?

Thanks.

**Comment by TrySound** [comment]
Take a look at latest version.
https://unpkg.com/react-virtualized@9.20.0/dist/es/Masonry/createCellPositioner.js

**Comment by magnetnation** [comment]
Thanks, I was using 9.18 and latest does not suffer from this problem. Instead I got tons of warnings about circular dependencies like the one below:

```
Circular dependency: node_modules/react-virtualized/dist/es/WindowScroller/WindowScroller.js -> node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js -> node_modules/react-virtualized/dist/es/WindowScroller/WindowScroller.js
Non-existent export 'bpfrpt_proptype_WindowScroller' is imported from node_modules/react-virtualized/dist/es/WindowScroller/WindowScroller.js
```
As I see it is due to the following code in the end of onScroll.js:

`
import { bpfrpt_proptype_WindowScroller } from '../WindowScroller.js';
`
I saw this [(commit)](https://github.com/bvaughn/react-virtualized/commit/6faafb5c4398e502c568db73fc430e56e8434e81) that was meant to deal with the problem. But it does not seem to help?

**Comment by wuweiweiwu** [comment]
I think we can possibly just export the `Props` and `State` props from that file and use the `Component<Props,State>` type to avoid this

**Comment by AdamLantz** [comment]
Experiencing the same problem as @magnetnation. It doesn't harm our build at all, but it is certainly annoying.
