### ISSUE TITLE
Table error in console and does not render entire contents when scrollElement is specified for WindowScroller

### ISSUE THREAD

**Issue by sudall** [bvaughn/react-virtualized#1158]
Repro: https://codesandbox.io/s/r7l0mrkp4p

Console error:
```
proxyConsole.js:72 Warning: Failed prop type: The prop `height` is marked as required in `Table`, but its value is `undefined`.
    in Table (created by AutoSizer)
    in AutoSizer (created by WindowScroller)
    in WindowScroller (created by Example)
    in Example
```

After debugging, this appears to be due to the use of the spread operator on a non-iterable object which is coming from calling getBoundingClientRect() in getDimensions() dimensions.js. Because the instance is not iterable, the properties do not get copied and therefore 'height' ends up undefined in state in WindowScroller. You can see the spread operator here:

https://github.com/bvaughn/react-virtualized/blob/8738097a6ead422f74590d6a631bd5fd83ebc831/source/WindowScroller/WindowScroller.js#L92-L97

**Comment by wuweiweiwu** [comment]
https://github.com/bvaughn/react-virtualized/issues/1127
