### ISSUE TITLE
Setting scrollTop/scrollLeft on a Collection does not scroll in 9.19.0 or later.

### ISSUE THREAD

**Issue by dawnmist** [bvaughn/react-virtualized#1159]
Example:  https://codesandbox.io/s/9j5v53ryq4?module=%2FExample.js

React-virtualized versions 9.19.0 and later (9.19.1, 9.20.0) do not apply the scrollTop/scrollLeft values from ScrollSync to a Collection component properly. The end result is that the items to be drawn _are_ updated to match what should be in the view window, but the _view window_ is not scrolled to show those items. So what is visible is an unmoving Collection that slowly has the upper rows go invisible until there are no more rows being drawn in the view window instead of the Collection's view window scrolling to match.

Reverting to react-virtualized 9.18.5, the above example works as expected. The lower Collection does scroll in response to changes to the scrollTop value. You can test this by changing the dependency version for react-virtualized in the above sandbox without making any other changes.

**Comment by thecere** [comment]
Any news on this? I have also pinned 9.18.5 now after chasing a initialization problem of a Collection + scrollTop/scrollLeft values.

**Comment by thecere** [comment]
Thnx, dawnmist. Let's hope your fixes will be integrated soon.

**Comment by geej** [comment]
Is this update dead? Also running into this issue.

**Comment by dawnmist** [comment]
No idea. I've had absolutely no feedback other than the initial "bug" label on the issue and nothing at all on the pull request I submitted 10 months ago that fixes it (and explains what broke it). At this point, I'd suggest using a package called `[patch-package](https://github.com/ds300/patch-package)` to apply the patch to later versions of react-virtualized any time that node_modules gets updated/installed/removed.

**Comment by kelly-tock** [comment]
please please patch this!!!

**Comment by sengmitnick** [comment]
please please patch this!!!

**Comment by jaltmanQ** [comment]
Just ran into this, and it cost me quite a bit of time before I found that it was a bug.  Downgrading to 9.18.5 resolved it for me.  Putting in a vote to patch please.

**Comment by dawnmist** [comment]
@wuweiweiwu Is there any chance that someone could look into this. It's been 2 years since the report, it's had a pull request fixing the bug for more than 18 months, and the only feedback ever received from the react-virtualized team has been to set the status to "bug" a few hours after it was first reported.
