### ISSUE TITLE
Always on scrollbar causing offset issues with ColumnSizer and ScrollSync

### ISSUE THREAD

**Issue by ryanseddon** [bvaughn/react-virtualized#116]
I created two gifs to show what's happening on your demo pages, these seem like a similar issue to #81 in that they both need to take into account if a scrollbar is present and make adjustments based on that. 

I don't have capacity to dig into this and do a PR until later in the week so if you're busy I'll take a look when I can.

`<ColumnSizer />`:

![scrollbar-sizer](https://cloud.githubusercontent.com/assets/143402/13206245/33863d36-d94e-11e5-9ec2-b59a773a3f1a.gif)

`<ScrollSync />`:

![scrollsync-offset](https://cloud.githubusercontent.com/assets/143402/13206249/44bba7c6-d94e-11e5-9829-b2eb52a38712.gif)

**Comment by ryanseddon** [comment]
These gifs were recorded in Chrome 48.0.2564.109, I don't see the column sizer issue in Firefox but I see the scrollsync across the board.

**Comment by bvaughn** [comment]
Thanks for the detailed report @ryanseddon. This seems related to another issue I've filed but haven't had the time to address yet, #101.

**Comment by bvaughn** [comment]
My wedding was this weekend and I have family visiting so I probably won't get to this for another few days. If you beat me to it, more power to you. Else I'll take a look when I can. :)

**Comment by ryanseddon** [comment]
Oh! Congrats! Step away from the computer and go enjoy your wedding festivities.

**Comment by bvaughn** [comment]
Thanks thanks. ;) Was just taking a brief rest and catching my breath. Cheers!

**Comment by Guria** [comment]
Just for reference screenshot of ColumnSizer demo from windows:
![](http://i.imgur.com/lHINPVV.png)

Don't sure if it supposed to look like that.

**Comment by bvaughn** [comment]
If scrollbars are turned to always-on, then... yeah it would have to look like that.

**Comment by Guria** [comment]
@bvaughn scrollbar always on is default behaviour for all browser under windows and linux. There is no easy way to get mac os like behaviour.

**Comment by bvaughn** [comment]
I don't think that changes my response. I'm still not sure (in the above screenshot) what you would expect to see differently, given always-on scrollbars (regardless of whether the scrollbars are on because of the operating system, or the fact that the user is using a mouse instead of trackpad, or something else).

**Comment by Guria** [comment]
@bvaughn my expectation that with setting like on next screenshot is enough room to scrollbars not appear at all. But they always appears except on mobile or mac os:
![](http://i.imgur.com/VHg2LQD.png)

**Comment by bvaughn** [comment]
Ah, I see you only have 5 columns in your screenshot. You had 10 above with a min width of 75 and so... scrollbars were there, necessarily.

Yes, your most recent screenshot is essentially this defect and #101.

**Comment by bvaughn** [comment]
Just touching base again about this issue, @ryanseddon. Finally got some time to sit down and look at it but not having any great ideas so far. I did notice that if I toggle the `overflow: auto` property off and then back on again, it hides the scrollbars. Otherwise changes to width/height don't seem to.

**Comment by bvaughn** [comment]
**Update**: I've found a fix but it feels a little hacky.

```diff
diff --git a/source/Grid/Grid.js b/source/Grid/Grid.js
index 8268171..5f71ab4 100644
--- a/source/Grid/Grid.js
+++ b/source/Grid/Grid.js
@@ -452,6 +452,18 @@ export default class Grid extends Component {
       }
     }
 
+    const columnsWidth = this._getTotalColumnsWidth()
+    const columnsHeight = this._getTotalRowsHeight()
+
+    const style = {
+      height: height,
+      width: width
+    }
+
+    if (columnsWidth <= width && columnsHeight <= height) {
+      style.overflow = 'hidden'
+    }
+
     return (
       <div
         ref='scrollingContainer'
@@ -459,19 +471,16 @@ export default class Grid extends Component {
         onKeyDown={this._onKeyPress}
         onScroll={this._onScroll}
         tabIndex={0}
-        style={{
-          height: height,
-          width: width
-        }}
+        style={style}
       >
         {childrenToDisplay.length > 0 &&
           <div
             className='Grid__innerScrollContainer'
             style={{
-              width: this._getTotalColumnsWidth(),
-              height: this._getTotalRowsHeight(),
-              maxWidth: this._getTotalColumnsWidth(),
-              maxHeight: this._getTotalRowsHeight(),
+              width: columnsWidth,
+              height: columnsHeight,
+              maxWidth: columnsWidth,
+              maxHeight: columnsHeight,
               pointerEvents: isScrolling ? 'none' : 'auto'
             }}
           >
```

**Comment by bvaughn** [comment]
Okay. After a bit more thought and testing, I feel ... reasonably okay with the above change. It's the only way (that I can think of at least) to fix that particular problem.

The other issue (the scroll-synced `Grid`s not respecting each other's scrollbars) seems more complex. Let's break that off into its own issue for simplicity.

**Comment by bvaughn** [comment]
Release 5.3.1 just went out with the first half of this fix.

**Comment by ryanseddon** [comment]
Interesting I was playing around with this and noticed that same thing with toggling overflow.

I attempted a fix with the same solution you did for FlexTable.

```diff
diff --git a/source/Grid/Grid.js b/source/Grid/Grid.js
index 9b249dc..8a7458e 100644
--- a/source/Grid/Grid.js
+++ b/source/Grid/Grid.js
@@ -11,6 +11,7 @@ import {
 import cn from 'classnames'
 import raf from 'raf'
 import React, { Component, PropTypes } from 'react'
+import { findDOMNode } from 'react-dom'
 import shouldPureComponentUpdate from 'react-pure-render/function'
 
 /**
@@ -141,7 +142,8 @@ export default class Grid extends Component {
       computeGridMetadataOnNextUpdate: false,
       isScrolling: false,
       scrollLeft: 0,
-      scrollTop: 0
+      scrollTop: 0,
+      scrollbarWidth: 0
     }
 
     // Invokes onSectionRendered callback only when start/stop row or column indices change
@@ -223,6 +225,8 @@ export default class Grid extends Component {
 
     // Update onRowsRendered callback
     this._invokeOnGridRenderedHelper()
+
+    this._setScrollbarWidth()
   }
 
   componentDidUpdate (prevProps, prevState) {
@@ -283,6 +287,8 @@ export default class Grid extends Component {
 
     // Update onRowsRendered callback if start/stop indices have changed
     this._invokeOnGridRenderedHelper()
+
+    this._setScrollbarWidth()
   }
 
   componentWillMount () {
@@ -373,7 +379,8 @@ export default class Grid extends Component {
     const {
       isScrolling,
       scrollLeft,
-      scrollTop
+      scrollTop,
+      scrollbarWidth
     } = this.state
 
     let childrenToDisplay = []
@@ -522,10 +529,11 @@ export default class Grid extends Component {
 
   _getColumnWidth (index) {
     const { columnWidth } = this.props
+    const { scrollbarWidth } = this.state
 
     return columnWidth instanceof Function
-      ? columnWidth(index)
-      : columnWidth
+      ? columnWidth(index) - scrollbarWidth
+      : columnWidth - scrollbarWidth
   }
 
   _getRowHeight (index) {
@@ -542,7 +550,7 @@ export default class Grid extends Component {
     }
 
     const datum = this._columnMetadata[this._columnMetadata.length - 1]
-    return datum.offset + datum.size
+    return (datum.offset + datum.size) - this.state.scrollbarWidth
   }
 
   _getTotalRowsHeight () {
@@ -660,6 +668,15 @@ export default class Grid extends Component {
     }
   }
 
+  _setScrollbarWidth () {
+    const Grid = findDOMNode(this.refs.scrollingContainer)
+    const clientWidth = Grid.clientWidth || 0
+    const offsetWidth = Grid.offsetWidth || 0
+    const scrollbarWidth = offsetWidth - clientWidth
+
+    this.setState({ scrollbarWidth })
+  }
+
   /* ---------------------------- Event handlers ---------------------------- */
 
   _onKeyPress (event) {
```

**Comment by bvaughn** [comment]
Let me know if 5.3.1 doesn't fix things for you @ryanseddon (at least the first half of the issue you reported). We can talk about the remaining issue on #131 :)
