### ISSUE TITLE
MultiGrid header misaligned horizontally and vertically at max scroll for grid

### ISSUE THREAD

**Issue by EdBoucher** [bvaughn/react-virtualized#1162]
### What is the current behavior?

When using the MultiGrid with AutoSizer and a grid that scrolls, when scrolling to the end of the grid the columns and rows in the header grids become misaligned. Looking at the code, an extra `div` element should be appended to the header to account for the space for the vertical scrollbars; this is missing.  The `onScrollbarPresenceChange` handler also isn't invoked on the initial render when this fails, but on the computers where it doesn't it always is.

![screen shot 2018-07-06 at 14 17 57](https://user-images.githubusercontent.com/1915158/42381201-4874e10a-8128-11e8-9635-a94a902f90c4.png)

![screen shot 2018-07-06 at 14 24 36](https://user-images.githubusercontent.com/1915158/42381241-652c8730-8128-11e8-9ded-b9df05b33971.png)

It doesn't appear to be an issue with custom scrollbars; the same issue occurs even when using normal ones. Annoyingly this is only on some of our systems, not all of them- but they're all using the same version of Chrome.

See https://codesandbox.io/s/8yvw057ov0 for an example. This is using the AutoSizer, but the problem persists even without it.

### What is the expected behavior?

Scrolling to the end of the grid should see the headers aligned with the grid. A padding div should be created and appended to account for the scrollbars. The `onScrollBarPresenceChange` handler should be called.
 
### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? 
|                   |          |
|-------------------|----------|
| Browser           |    Chrome 67.0.3396.99     |
| OS                |    MacOS High Sierra  10.13.5    |
| React             |    16.4.1      |
| React DOM         |   16.4.1       |
| react-virtualized |      9.20.0    |

**Comment by casvil** [comment]
did you manage to fix it @EdBoucher ?

**Comment by EdBoucher** [comment]
I think we worked around it. Unfortunately I no longer work at the company that was having this problem, so they’ve probably replaced it with something else entirely

**Comment by chebb44** [comment]
Anybody find working fix for that issue?

**Comment by louisgenie** [comment]
Anybody found a fix?
