### ISSUE TITLE
Allow rowStyle on tables to override default styles?

### ISSUE THREAD

**Issue by emroussel** [bvaughn/react-virtualized#1171]
I have a table where I would like to have some content overflow from a row. However, passing a `rowStyle` object with `overflow: 'visible'` can't do it, because the `Table` component merges the `rowStyle` object with some other styles (including `overflow: 'hidden'`) [here](https://github.com/bvaughn/react-virtualized/blob/de107e81f6d412d3561b169f7fdbfdbe25dd7b00/source/Table/Table.js#L395).

We use css in js everywhere in the project, so using a className to override this would be a little inconsistent and confusing.

So I was wondering what the reasoning behind forcing default some styles is?

I would suggest changing this
```
style: {
    ...rowStyleObject,
    height: headerHeight,
    overflow: 'hidden',
    paddingRight: scrollbarWidth,
    width: width,
}
```

To this
```
style: {
    height: headerHeight,
    overflow: 'hidden',
    paddingRight: scrollbarWidth,
    width: width,
    ...rowStyleObject,
}
```

To give users the option to override the styles if they want, while still keeping the defaults if they don't override them.

If you guys agree to this change, I'm more than happy to submit a PR for it!

**Comment by emroussel** [comment]
@wuweiweiwu having `overflow: visible` seemed to work for me, the layout looked the same, and the height was properly set.

Either way, I feel like it would make sense to allow users to override these default styles when passing in a style object since they can do the same with a class.

What do you think?

**Comment by wuweiweiwu** [comment]
@emroussel I think thats valid. Feel free to open a PR! it'll be much appreciated!
