### ISSUE TITLE
Not completely resetting styles after measuring

### ISSUE THREAD

**Issue by keann** [bvaughn/react-virtualized#1174]
Hi!

Let's say I use a CellMeasurer inside a Table, so there's no `style` attribute set directly for cells (elements returned by `cellRenderer`). But their `height` is styled via some separate css file (e.g. `height: 100%` to occupy the entire height of `ReactVirtualized__Table__rowColumn`).

In this case an empty string is stored in `styleHeight` [here](https://github.com/bvaughn/react-virtualized/blob/0e7680bdd04a1c4442363eb61fdb786308cde8e1/source/CellMeasurer/CellMeasurer.js#L88) and the resetting statement is not executed. Thus `height: 'auto'` remains inside `style` attribute. The same apparently is applicable to `width`.

Of course there's a not so hard workaround: we can define cell's `height` explicitly in an attribute. But is there a reason why an `auto` value shouldn't be reset without any check of `styleHeight`?

**Comment by EricTheRed-VT** [comment]
My solution in https://github.com/bvaughn/react-virtualized/issues/1294 is (I think) the same work-around.
