### ISSUE TITLE
"[object Object]" appearing in tooltip when hovering column header

### ISSUE THREAD

**Issue by Baloche** [bvaughn/react-virtualized#1176]
Hello, I think I'm facing an issue : when I put a React element in the `label` prop of a column, the tooltip "[object Object]" appears when I the cursor is hovering the column header :

```jsx
<Table /* ... props */>
    <Column
      label={<LocalizedText id="WEB_LAST_MEASUREMENT" />}
      /* ... other props */
    />
</Table>
```

After inspecting the node, I can see that the `span` element in the header has its prop `title` containing the react element I declared as the label :
```js
{
  children: {…},
  className: "ReactVirtualized__Table__headerTruncatedText",
  title: {,
    $$typeof: Symbol(react.element),
    _owner: FiberNode{…},
    _store: {…},
    key: null,
    props: {…},
    ref: null,
    type: LocalizedText()
  }
}
```

I think I can fix that by giving the Column a custom `headerRenderer` prop, but I don't think that's the expected behaviour. Or am I doing something wrong ?

**Comment by ingvardm** [comment]
having the same issue

**Comment by BykovDenis** [comment]
You can try like this
ReactDOMServer.renderToString(<LocalizedText id="WEB_LAST_MEASUREMENT" />)
