### ISSUE TITLE
Library packaging / distribution

### ISSUE THREAD

**Issue by troch** [bvaughn/react-virtualized#118]
Hi,

Thanks for your work on this. Using the library, I notice a few things which can be improved the way it is packaged / distributed to users. From you config in package.json (`main` pointing to the standalone one, and `jsnext:main` pointing to the commonjs files), one distribution seems to be missing:
- `main` should point to commonjs files (currently in `es` folder)
- `jsnext:main` should point to files compiled with preset `es2015-rollup`: basically like commonjs except import / export statements are not transpiled.

If you agree with the points listed above, I can help and open a PR.

**Comment by bvaughn** [comment]
> `main` should point to commonjs files (currently in es folder)

I'm not sure I understand this point. `main` points to the UMD package and `jsnext:main` points to the es6 modules.

> `jsnext:main` should point to files compiled with preset `es2015-rollup`

If you have a proposal for a better way to bundle the `jsnext:main` target- I'd love to see it. :)

**Comment by troch** [comment]
For `main`: usually with npm you would point it to commonjs modules, not necessarily an UMD package.

I guess you have configured `jsnext:main` to support the use of rollup. The files you have placed in directory `es` are commonjs modules, not ES6 modules: they use `require` rather than import / export statements. For best supporting rollup (or similar tool wanting to tree-shake), you need to use the babel preset called "es2015-rollup": it is exactly like "es2015" except it does not contain the transformer for import / export statements.

**Comment by bvaughn** [comment]
react-virtualized has always targeted UMD (since it's just as easy to support both commonjs and AMD).

Thank you for the tip about using `es2015-rollup` though. I was unaware of that. (The `jsnext:main` target is pretty new and I don't know how many people are using it yet.)

**Comment by bvaughn** [comment]
@troch Double check me on PR #119 if you're willing to take a look.

**Comment by troch** [comment]
> react-virtualized has always targeted UMD (since it's just as easy to support both commonjs and AMD).

Even if `main` still point to the UMD build, would it be possible to get a commonjs build available for cherry-picking?

**Comment by bvaughn** [comment]
What would be the benefit of a commonjs-only build?

**Comment by troch** [comment]
Cherry-picking. In my case, this is my second biggest react dependency (excluding React itself), and I only use part of the library. You don't necessarily need to explicitly support and document cherry-picking, but having the opportunity to do it would be great (and I accept the risks of doing so, you don't have to bump a major all the time you rename a file).

**Comment by bvaughn** [comment]
I see. I'm a little reluctant to add _another_ build target to react-virtualized, especially when it's kind of a superset of what's currently being built.

**Comment by troch** [comment]
Another way would be to replace UMD by commonjs inside `dist`.

**Comment by bvaughn** [comment]
Right. Which I considered doing as part of the v5 update but I know at least some people (Mozilla) are using the global build and I don't know who else might be using AMD.

**Comment by bvaughn** [comment]
By the way I didn't close this ticket to indicate an end of discussion. (We can keep talking here.) It was auto-closed when I merged the PR.

**Comment by bvaughn** [comment]
By the way, @troch, I think I misunderstood what you were suggesting with regard to the commonjs build. I've posted PR #129 which I _think_ does the rest of what you suggested.
