### ISSUE TITLE
Virtualized List - Block scroll

### ISSUE THREAD

**Issue by CentroneF** [bvaughn/react-virtualized#1180]
Is there a way to block the scroll?
I have problems in Safari even if I block the scroll via CSS in Safari/IOS Hybrid app. 

I would be nice to have a prop to block the scroll action.

Thank you for help

**Comment by ajdaniel** [comment]
We do this with CSS in our project. We achieve it by applying a class to the `<List>` component, and in that class set the property 'overflow: hidden !important;' to lock it in place and prevent scrolling.

**Comment by halftonepixel** [comment]
> We do this with CSS in our project. We achieve it by applying a class to the `<List>` component, and in that class set the property 'overflow: hidden !important;' to lock it in place and prevent scrolling.

How does the List scroll then?

**Comment by halftonepixel** [comment]
I am using react-virtualized's Tree in a re-sizable drawer with position fixed; the issue I'm facing is that when I try to scroll the Tree beyond scroll limits, it starts scrolling the body. Does anyone have a clean solution for this? Thanks!
