### ISSUE TITLE
Long cells disappear too early

### ISSUE THREAD

**Issue by TiiRiiX** [bvaughn/react-virtualized#1181]
I use very long tables. And now I noticed an unpleasant bug. I used `MultiGrid` and too long cells disappear from the screen before they go beyond its border. I was trying to set up using `overscanColumnCount` and `overscanRowCount` but it didn't work.

![gif](https://user-images.githubusercontent.com/10673591/43266509-05c1a374-9105-11e8-8af7-847e5534ecd5.gif)

React-virtualized verison: `9.20.1`

**Comment by bradwoods** [comment]
I'm getting the same bug. As soon a column is off the screen, the cell is removed from the DOM, irrelevant of what overscanColumnCount is set to.

**Comment by conorgould** [comment]
Thanks @bradwoods - setting those defaults solved the issue for me
