### ISSUE TITLE
WindowScroller has strange behavior in IE11

### ISSUE THREAD

**Issue by nhatdq1810** [bvaughn/react-virtualized#1182]
Hi guys, I have an issue for WindowScroller in only **IE11**, I have used WindowScroller with AutoSizer, Table and CellMeasurer.
When I scroll, the browser will scroll more a little bit before it stops.

Here is the demo for it : [demo](https://stackblitz.com/edit/react-phg5wq)

|                   |          |
|-------------------|----------|
| Browser           | IE11        |
| React             | 16.1.1         |
| React DOM         | 16.1.1         |
| react-virtualized | 9.20.1         |

**Comment by gabrieluy** [comment]
same problem here
