### ISSUE TITLE
hideTopRightGridScrollbar & hideBottomLeftGridScrollbar are not working in multigrid

### ISSUE THREAD

**Issue by Rohanhacker** [bvaughn/react-virtualized#1184]
Reporting a Bug?

simple repro.: https://bvaughn.github.io/react-virtualized/#/components/MultiGrid

### What is the current behavior?
Top right & bottom left scrollbars are not hidden

### What is the expected behavior?
Top right & bottom left scrollbars should be hidden

### Which versions of react-virtualized, and which browser / OS are affected by this issue?
version: 9.20.1
firefox, chorme

**Comment by albburtsev** [comment]
Both props don't work on my Mac in Chrome when I use trackpad without external mouse.

**Comment by aschonfeld** [comment]
I was actually able to get the scrollbar to stop displaying by setting the height property of styleTopLeftGrid & styleTopRightGrid to 15px more than what I set my rowHeight to.

**Comment by ddrozdov** [comment]
This worked for me:
```
.gridBottomLeft, .gridTopRight {
  &::-webkit-scrollbar {
    -webkit-appearance: none;
    width: 0;
    height: 0;
  }
}
```
having
```
<MultiGrid
  classNameTopRightGrid="gridTopRight"
  classNameBottomLeftGrid="gridBottomLeft"
  ...
/>
```

**Comment by sgilligan** [comment]
a small adjustment for Firefox/IE

```
.gridBottomLeft, .gridTopRight {
    -ms-overflow-style: none;  /* Internet Explorer 10+ */
    scrollbar-width: none;         /* Firefox */
    &::-webkit-scrollbar {          /* Webkit */
          -webkit-appearance: none;
          width: 0;
          height: 0;
     }
}
```
