### ISSUE TITLE
headerRenderer is required, when should be optional

### ISSUE THREAD

**Issue by chrisands** [bvaughn/react-virtualized#1193]
headerRenderer is required prop, when docs says it's optional. Here's link:
https://github.com/bvaughn/react-virtualized/blob/master/source/Table/Column.js#L60

**Comment by tjands** [comment]
As far as I can see this is still the case?

**Comment by chrisands** [comment]
Yes, it wasn't fixed. Documentation contradicts realization.

**Comment by chrisands** [comment]
Hey. Issue is still wasn't fixed.
