### ISSUE TITLE
where is this piece of code?

### ISSUE THREAD

**Issue by DemGiran** [bvaughn/react-virtualized#1194]
Where is the piece of code that makes this alternating color?

https://bvaughn.github.io/react-virtualized/#/components/ScrollSync

**Comment by rloqvist** [comment]
It is in this renderer;

```javascript
_renderLeftSideCell({columnIndex, key, rowIndex, style}) {
    const rowClass =
      rowIndex % 2 === 0
        ? columnIndex % 2 === 0 ? styles.evenRow : styles.oddRow
        : columnIndex % 2 !== 0 ? styles.evenRow : styles.oddRow;
    const classNames = cn(rowClass, styles.cell);

    return (
      <div className={classNames} key={key} style={style}>
        {`R${rowIndex}, C${columnIndex}`}
      </div>
    );
  }
```

[ScrollSync.example.js](https://github.com/bvaughn/react-virtualized/blob/master/source/ScrollSync/ScrollSync.example.js#L236)


Mixed with this css;

```css
.evenRow {
}
.oddRow {
  background-color: rgba(0, 0, 0, .1);
}
```

[ScrollSync.example.css](https://github.com/bvaughn/react-virtualized/blob/master/source/ScrollSync/ScrollSync.example.css#L27)
