### ISSUE TITLE
MultiGrid misalignment when used with ColumnSizer

### ISSUE THREAD

**Issue by laurence-hudson-mindfoundry** [bvaughn/react-virtualized#1195]
I believe I've found a bug in MultiGrid which appears when it is used with ColumnSizer.

Specifically, when the column width is bigger than its minimum value the header can become misaligned with the data.

![Example](https://i.imgur.com/WV0cVtF.png)

Interestingly this doesn't happen on first render, and only occurs after you start to scroll vertically. Once you start to scroll vertically a horizontal scroll bar will (incorrectly) appear, which if used breaks the alignment of the fixed header

There is an example of this behaviour here: https://next.plnkr.co/edit/v2N7VVkjOnJava3o?preview

It looks like this used to be [an issue](https://github.com/bvaughn/react-virtualized/issues/535) for MultiGrid, even when used without ColumnSize, but got fixed, without accounting for ColumnSizer.

|                   |          |
|-------------------|----------|
| Browser           |   chrome & edge (for sure, maybe others too)    |
| OS                |   win7 (for sure, maybe others too)  |
| React             |    15 & 16 (for sure, maybe others too)       |
| React DOM         |     15 & 16 (for sure, maybe others too)       |
| react-virtualized |   9.20.1  (for sure, maybe others too)      |

**Comment by zag2art** [comment]
The bug is still there. "version": "9.21.0"
