### ISSUE TITLE
e.target.className.indexOf is not a function

### ISSUE THREAD

**Issue by dmydry** [bvaughn/react-virtualized#1203]
Unfortunately I can't make a working repro. This is a main reason of this issue.

In our production code we often get client errors with the next traceback: 
`TypeError: e.target.className.indexOf is not a function`.

Apparently this is the next code: https://github.com/bvaughn/react-virtualized/blob/master/source/vendor/detectElementResize.js#L73

Browser occurrences are quite different (last chrome is in top). Hence it's not a browser issue.

We use WindowScroller, AutoSizer and List components with quite standart props and behaviour.
```
        <WindowScroller>
          {({ height, isScrolling, scrollTop }) => (
            <AutoSizer disableHeight>
              {({ width }) => (
                <List
                  isScrolling={isScrolling}
                  overscanRowCount={3}
                  scrollTop={scrollTop}
                  autoHeight
                  height={height}
                  rowCount={listCount}
                  rowHeight={rowHeight}
                  rowRenderer={this.rowRenderer}
                  width={width}
                />
              )}
            </AutoSizer>
          )}
        </WindowScroller>
```

Could anyone give me a tip, what is a possible reason of this issue?

|                   |          |
|-------------------|----------|
| React             |     16.4.1     |
| React DOM         |    16.4.1      |
| react-virtualized |     9.20.1     |

**Comment by wuweiweiwu** [comment]
I'm guessing that className is returning a `null` or `undefined`. 

A fix would be to check that `e.target` and `e.target.className` exists

**Comment by dmydry** [comment]
@wuweiweiwu thats right and I guess I will do a fork after a while. I just prefer to use the original package source if possible.
Just asked if anyone got the same issue. And if so, maybe we just should add an extra checks for a `e.target.className` and `typeof e.target.className.indexOf === 'function'`. This should broke nothing but fix the issue.

**Comment by wuweiweiwu** [comment]
@dmydry would you be interested in submitting a pull request for this?

**Comment by dmydry** [comment]
@wuweiweiwu done ;)

I didn't find any tests for the `detectElementResize` listeners. 
Will be happy to dive deeper into the project and cover if possible.

**Comment by wuweiweiwu** [comment]
@dmydry Awesome! thanks for contributing!
