### ISSUE TITLE
Horizontal List

### ISSUE THREAD

**Issue by acollazomayer** [bvaughn/react-virtualized#1209]
Is it posible to have an horizontal list

**Comment by TrySound** [comment]
https://react-window.now.sh/#/examples/list/fixed-size

**Comment by acollazomayer** [comment]
@TrySound thanks! but that library does not support smooth scroll to index.

**Comment by keyban** [comment]
any update on this?

**Comment by goldylucks** [comment]
Would love an out of the box solution. I'm going to try the `Grid` component

**Comment by goldylucks** [comment]
So I'm happy to say this works!

Simply use `Grid` with one row :)

[![Edit react-virtualized-row](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-agnesi-icvhv?fontsize=14)
