### ISSUE TITLE
Flicker screen

### ISSUE THREAD

**Issue by JayenLee** [bvaughn/react-virtualized#1214]
I use this as the chat room message list, and when I slide down with this, the line with the text message will flash, but when I remove the onLoad ={measure} above the picture element, it won't, but there's a new problem, and that's some. The height of the message can not be calculated successfully, and there will be two message overlaps.

**Comment by xuhuanghuang** [comment]
我也遇到同样的问题，滚动的时候列表会闪，求解

**Comment by JasonXiaoSpace** [comment]
> 我也遇到同样的问题，滚动的时候列表会闪，求解

me too.  and i had added style on rowRenderer

**Comment by Jayanzhou** [comment]
@xuhuanghuang @JasonXiaoSpace @JayenLee The solution, please see #1327
