### ISSUE TITLE
Big list won't get rendered on scroll with WindowScroller, AutoSizer and List

### ISSUE THREAD

**Issue by DennisBecker** [bvaughn/react-virtualized#1216]
I think have found a bug or the documentation is incomplete.

I have a large list of 300+ items. The design decision is that it is visible on the whole page and for performance reasons I have searched for a react component which is capable of the needs. I have reafctored my code and added WindowScroller and AutoSizer with the List component of react-virtualized. Everything looks good, but when I scroll down, I won't see all list entries.

In fact, if the window is bigger, I can see more list entries. I have build a small example where the behaviour is visible at https://codesandbox.io/s/64lzm266n

I thought at first, this is a mistake by myself but so far no one answered my question at stackoverflow (https://stackoverflow.com/questions/52367022/react-virtualized-combined-with-windowscroller-and-autosizer-on-large-list-does) so my guess is that this is a bug.

I have tried the example on codesandbox.io on my Mac OS 10.13 laptop with Google Chrome 69 and Firefox 62.

**Comment by anagorsky** [comment]
You forgot to set style for each row element and synchronize scrollTop property between WindowScroller and List components. So the complete example you can find [here](https://codesandbox.io/s/7yzzw92xw1)

I also agree that at the first look at readme file the documentation is not clearly represent complete examples...

**Comment by DennisBecker** [comment]
Thank you for the help, I will fix this in my code.

**Comment by ruslanzharkov** [comment]
Thanks a lot, fixed my issue as well!
