### ISSUE TITLE
Can we pin rows in a multigrid

### ISSUE THREAD

**Issue by nat009** [bvaughn/react-virtualized#1217]
Hi,

I use the multigrid component. Was wondering if there is a way to pin the grid rows on clicking on the row. I know there is a fixed row option already available, but I'm looking for pinning any row that I click on

**Comment by ohmyguigs** [comment]
If you move the clicked row to the top and increase the fixedRows number you can do it.
My doubt is how to track a rowClick. I could only do this passing onClick to every cell.
