### ISSUE TITLE
Cannot read property 'offset' of undefined

### ISSUE THREAD

**Issue by sanalpanicker-zz** [bvaughn/react-virtualized#1219]
### What is the current behavior?

Attached is a screencast. this has been previously reported, but closed without a fix.

Using List & Autosizer only, why does it throw and error in Grid?

### What is the expected behavior?
Should not throw an error and I should be able to scroll smoothly
### Which versions of React and react-virtualized, and which browser / OS are affected by this issue?
9.20.1
Chrome - latest - macOS

[https://screencast.com/t/Lu7PiRwtCN](url)

**Comment by Pong420** [comment]
I have the same error. In my case,
I keep update the value `columnCount`  and `columnWidth` when resize.
I found  that the error occur when `Grid` change from scrollable to cannot scroll

**Comment by Pong420** [comment]
My issue solved by adding `Math.ceil` for calculating the number of rows
```diff
  <Grid
    columnCount={columnCount}
    columnWidth={columnWidth + spacer}
-   rowCount={list.length / columnCount}
+   rowCount={Math.ceil(list.length / columnCount)}
    ...
  />
```
