### ISSUE TITLE
When you try to click, but scroll a little by mistake, your click doesn't register

### ISSUE THREAD

**Issue by infu** [bvaughn/react-virtualized#1222]
I am experiencing weird behaviour with my mac mouse, because its too easy to scroll by mistake few pixels while trying to click. 

It can be observed here in the demo too:
https://bvaughn.github.io/react-virtualized/#/components/ArrowKeyStepper

I guess when you scroll by mistake even 3 pixels, things rerender and your mouse isn't over anything until it moves again.

**Comment by dudenamedjune** [comment]
I believe this is inherent browser behavior. If you click the link you posted and drag it 3px "accidentally scroll' it won't register your click 

If this is a QA raised issue RIP
