### ISSUE TITLE
Help on AutoSizer Table fixed Header Body Full Height

### ISSUE THREAD

**Issue by axelhuizinga** [bvaughn/react-virtualized#1225]
Hi - any example of a Table with fixed Header and scrollable Table Body expanding to the
Full Height of the parent container will be appreciated.
--- Sorry I missed to apply the Table height in the children function of AutoSizer - works as expected :)

**Comment by EmanuelaGr** [comment]
Hi I have the same issue but I put height in children function of AutoSizer, can you please tell me how is working on your side?
