### ISSUE TITLE
React virtualized Masonry rendering aggregated data

### ISSUE THREAD

**Issue by MatteoGioioso** [bvaughn/react-virtualized#1229]
### Do you want to request a *feature* or report a *bug*?

Requesting a feature?

React virtualized Masonry rendering aggregated data

* What's your use case?
I have a list of images or data, rendered with React-virtualized Masonry
I would like to group the images or data per year or property (Like in the screenshot).

![image](https://user-images.githubusercontent.com/43592430/46452405-d02e9a80-c7c5-11e8-9228-1d383ff1d5f2.png)

* What interface do you have in mind?

Something that allow to access row or group of rows, to put a divider of a title between group of rows
```
function groupRenderer ({ index, key, parent, style }) {
   
    return (
      <Group
       row={4}
      >
     <h1>title ...1967</h1>
     </Group>
    )
  }

<Masonry
        groupRenderer={groupRenderer}
    />
```

**Comment by MatteoGioioso** [comment]
For now I have solved the issue by making each year a list item. 
But sometimes one year can contain many pictures. So is there a way to virtualize those pictures inside each year?

**Comment by devinmorgan** [comment]
I could really benefit from this feature as well. I have a giant list of ordered groups of images that I need to display to users so such a feature would be of great use.
