### ISSUE TITLE
Implementing row level DnD on table

### ISSUE THREAD

**Issue by serle** [bvaughn/react-virtualized#1232]
Does anyone have an efficient example of row level Drag and Drop on the table component. I'm finding that once I add the overhead on involved in Dnd the scroll performance degrades to such and extent that the table becomes unusable. Are there any plans to bake DnD into the table and solve these issues in a comprehensive way?

**Comment by augbog** [comment]
Just curious, what's the use case you're trying to tackle? Personally don't think it makes sense to bake in dnd logic into this library. Lots of dnd libraries i.e. react-dnd let you export draggable and droppable HOCs which you can simply render in `react-virtualized` and that way you keep the logic separate.
