### ISSUE TITLE
Horizontal scrolling doesn't work in ReactVirtualized List

### ISSUE THREAD

**Issue by bdubrovsky** [bvaughn/react-virtualized#1248]
Hi, 

We're implementing a tree using ReactVirtualized List.  With each level of indent in the tree, the length of each line in the list gets longer, ultimately requiring a horizontal scroll.

We made the horizontal scrolling work by adding highly specific CSS rules which force overflow: auto on the outer div (classNames= "ReactVirtualized__Grid ReactVirtualized__List"), and by forcing overflow: visible on the inner div (classNames="ReactVirtualized__Grid__innerScrollContainer")

1) Are there any mine fields here we're not seeing?
2) Please feel free to use this approach in any new feature you might add.

Thanks,

Ben Dubrovsky

**Comment by asakalou-exadel** [comment]
Looking forward for this feature. 
Need to have horizontal scrolling for zoom in/out content inside the list.

**Comment by rmariuzzo** [comment]
We are also needing this in a internal tool. How can I help?

**Comment by Andry361** [comment]
as a workaround i redefine styles
`
.ReactVirtualized__Grid__innerScrollContainer {
  overflow: initial !important;
}
`

**Comment by mir3z** [comment]
> as a workaround i redefine styles
> `.ReactVirtualized__Grid__innerScrollContainer { overflow: initial !important; }`

Great, but `overflow: initial` does not work in IE11

**Comment by ChristophVitz-Actano** [comment]
Is there any new development on this issue so far?
