### ISSUE TITLE
Scroll bar is too small

### ISSUE THREAD

**Issue by enesyteam** [bvaughn/react-virtualized#1249]
Hi,
I'm using your library and every thing seem to be good, but the scroll bar in Infinitive loader is too small. How can I increase the height of scrool bar?
Using Inspect in chrome, the element `ReactVirtualized__Grid__innerScrollContainer` has style:
`width: auto;
    height: 79920px;
    max-width: 365px;
    max-height: 79920px;
    overflow: hidden;
    position: relative;`

I think 79920px is very large so the scroll bar is small. but at the begining page load, there are only 30 items fetched from API, so why 79920px?
![xd](https://user-images.githubusercontent.com/16075067/47218016-94eeb700-d3d4-11e8-9ab0-6578d256eb78.JPG)

**Comment by enesyteam** [comment]
Is this project under maintained or downed?

**Comment by expertup** [comment]
> Hi,
> I'm using your library and every thing seem to be good, but the scroll bar in Infinitive loader is too small. How can I increase the height of scrool bar?
> Using Inspect in chrome, the element `ReactVirtualized__Grid__innerScrollContainer` has style:
> `width: auto; height: 79920px; max-width: 365px; max-height: 79920px; overflow: hidden; position: relative;`
> 
> I think 79920px is very large so the scroll bar is small. but at the begining page load, there are only 30 items fetched from API, so why 79920px?
> ![xd](https://user-images.githubusercontent.com/16075067/47218016-94eeb700-d3d4-11e8-9ab0-6578d256eb78.JPG)

I think that this is problem from React Semantic UI, not from React-virtualized.
