### ISSUE TITLE
how to use 2 dataKey in one Column?

### ISSUE THREAD

**Issue by StarNeit** [bvaughn/react-virtualized#1259]
Hello, guys.

I want to use more than 2 dataKey in one Column of Table.

Is there any solution for that?

**Comment by JoeSzymkowicz** [comment]
What was the solution to this? I 'm trying to pull multiple values from an object to be used into a single column.

**Comment by fortunee** [comment]
Hello @StarNeit were you able to figure this out? If yes, could you please share how? I'd really appreciate it. Thanks

**Comment by mbudk** [comment]
Just use
```
dataKey=''
cellDataGetter={({dataKey, rowData}) => rowData}
```
