### ISSUE TITLE
List doesn't update display or row heights when data updated.

### ISSUE THREAD

**Issue by sAnti09** [bvaughn/react-virtualized#1262]
**Setup**
I have this `List` that uses `CellMeasurer` to compute row heights dynamically.
```
<WindowScroller ref={ref => (this.windowScroller = ref)}>
  {({ height, isScrolling, onChildScroll, scrollTop }) => (
    <AutoSizer disableHeight={true}>
      {({ width }) => (
        <div>
          <List
            autoHeight={true}
            height={height}
            isScrolling={isScrolling}
            onScroll={onChildScroll}
            scrollTop={scrollTop}
            rowCount={contacts.length}
            rowHeight={this._cache.rowHeight}
            rowRenderer={this._rowRenderer}
            width={width}
            deferredMeasurementCache={this._cache}
            overscanRowCount={0}
          />
        </div>
      )}
    </AutoSizer>
  )}
</WindowScroller>
```

**Problem**
The list doesn't update either display or row heights when data has changed. For the list to change, I have to scroll the window manually. I've tried to clear the cache, updatePosition and forceRender but still has no effect.

**Temporary Solution**
Since scrolling to update isn't acceptable, I created a hack in the `componentDidUpdate` to be able to update the list when data changes.
```
/**
   * Since virtual list doesn't update till it scrolls, programmatically scroll window to
   * trigger update.
   */
  public componentDidUpdate(prevProps: Props) {
    const becameVisible = this.props.isVisible && !prevProps.isVisible;
    const contactChanged = this.props.contacts !== prevProps.contacts;

    if (this.windowScroller && (becameVisible || contactChanged)) {
      this._cache.clearAll();
      this.windowScroller!.updatePosition();

      window.scrollTo(window.scrollX, window.scrollY + 5);
      window.scrollTo(window.scrollX, window.scrollY - 5);
    }
  }
```

**Comment by znarkd** [comment]
I have the same problem using ReactVirtualized.Grid.  I've found that even when using unique keys, the grid display won't update unless the number of rows is different.  Example code at https://codesandbox.io/s/3qlqz9o8nq

**Comment by vjdv** [comment]
I tried ref.forceUpdate() but it only works first time:

`this.setState({selectedIndex:index}, ()=>list.forceUpdate())`

`function({ index, key, style }) {
  const selected = index===this.state.selectedIndex;
  return (
    <div
      className={cx("sitcontrol_list_item", selected && "sitcontrol_selected")}
      data-index={index}
      key={key}
      style={style}>{this.props.data[index]}</div>
  );
}`

**Comment by superman66** [comment]
You can add ref
```
       <List
           ref={this.bindListRef}
            autoHeight={true}
            height={height}
            isScrolling={isScrolling}
            onScroll={onChildScroll}
            scrollTop={scrollTop}
            rowCount={contacts.length}
            rowHeight={this._cache.rowHeight}
            rowRenderer={this._rowRenderer}
            width={width}
            deferredMeasurementCache={this._cache}
            overscanRowCount={0}
          />
```
the `bindListRef` function
```
  bindListRef = ref => {
    this.list = ref;
  };
```

At last, call `forceUpdateGrid` in `ComponentDidUpdate`
```
  componentDidUpdate() {
    if (this.list) {
      this.list.forceUpdateGrid();
    }
  }
```

**Comment by yuri2peter** [comment]
@superman66 It works! Thank you for solving my problem.

**Comment by goldylucks** [comment]
for me this didn't work, so I dynamically set an "artificial" key on the `List`, and I bump it by 1 to programmatically force a rerender

**Comment by y2x33** [comment]
Simular problem here, and when my data updated, row height which should also change doesn't update.
Solve this by 
```
componentDidUpdate() {
    if (this.list) {
      this._cache.clearAll(); // re-calculate cache & rowHeight
      this.list.forceUpdateGrid(); 
    }
  }
```

**Comment by ajay-kounta** [comment]
It's related to an issue with `onRowsRendered` if you pass in a no op, the grid values are updated. Without needing to call `cache.ClearAll()` or `ref.current.forceUpdateGrid()`

**Comment by As1aNH4wK** [comment]
It’s something related to the onRowsRendered prop, I noticed that if you pass in a no op function (or if you’re not using the onRowsRendered as a class method), the grid updates without the need to call cache.clearAll() or ref.current.forceUpdateGrid()

**Comment by armavion** [comment]
> **Setup**
> I have this `List` that uses `CellMeasurer` to compute row heights dynamically.
> 
> ```
> <WindowScroller ref={ref => (this.windowScroller = ref)}>
>   {({ height, isScrolling, onChildScroll, scrollTop }) => (
>     <AutoSizer disableHeight={true}>
>       {({ width }) => (
>         <div>
>           <List
>             autoHeight={true}
>             height={height}
>             isScrolling={isScrolling}
>             onScroll={onChildScroll}
>             scrollTop={scrollTop}
>             rowCount={contacts.length}
>             rowHeight={this._cache.rowHeight}
>             rowRenderer={this._rowRenderer}
>             width={width}
>             deferredMeasurementCache={this._cache}
>             overscanRowCount={0}
>           />
>         </div>
>       )}
>     </AutoSizer>
>   )}
> </WindowScroller>
> ```
> 
> **Problem**
> The list doesn't update either display or row heights when data has changed. For the list to change, I have to scroll the window manually. I've tried to clear the cache, updatePosition and forceRender but still has no effect.
> 
> **Temporary Solution**
> Since scrolling to update isn't acceptable, I created a hack in the `componentDidUpdate` to be able to update the list when data changes.
> 
> ```
> /**
>    * Since virtual list doesn't update till it scrolls, programmatically scroll window to
>    * trigger update.
>    */
>   public componentDidUpdate(prevProps: Props) {
>     const becameVisible = this.props.isVisible && !prevProps.isVisible;
>     const contactChanged = this.props.contacts !== prevProps.contacts;
> 
>     if (this.windowScroller && (becameVisible || contactChanged)) {
>       this._cache.clearAll();
>       this.windowScroller!.updatePosition();
> 
>       window.scrollTo(window.scrollX, window.scrollY + 5);
>       window.scrollTo(window.scrollX, window.scrollY - 5);
>     }
>   }
> ```

The 5px window scroll helped me a lot! Thanks :smile:

**Comment by mrfambo** [comment]
I am facing the same issue. Seems like a very tricky thing for react-virtualized to handle.

**Comment by luanraithz** [comment]
Calling the method `recomputeRowHeights` did the trick for me. The function that was used to calculate height had some state dependencies that was not being applied after an update to the state.
