### ISSUE TITLE
Resize events when shrinking don't fire when the root div has dir="rtl" set

### ISSUE THREAD

**Issue by MarkFalconbridge** [bvaughn/react-virtualized#1271]
This can be seen by adding the attribute dir="rtl" to the root div element in the example - https://bvaughn.github.io/react-virtualized/#/components/List

When you make the window smaller the elements in the list get pushed off the screen.

This is related to https://github.com/sdecima/javascript-detect-element-resize/issues/57.

**Comment by TremayneChrist** [comment]
Could update the library to use https://github.com/juggle/resize-observer 🙂

**Comment by arthurpankiewicz** [comment]
bump
