### ISSUE TITLE
Something is wrong with the table

### ISSUE THREAD

**Issue by vaheqelyan** [bvaughn/react-virtualized#1273]
[https://bvaughn.github.io/react-virtualized/#/components/Table](https://bvaughn.github.io/react-virtualized/#/components/Table)
![](https://res.cloudinary.com/dmtrk3yns/image/upload/q_auto/v1542613353/ezgif-6-38f74c2b6582_fbb6zo.gif)

**Comment by damiangreen** [comment]
That runs fine on my machine

**Comment by davalapar** [comment]
@vaheqelyan what's wrong with it?
