### ISSUE TITLE
Why don't this support custom scrollbars?

### ISSUE THREAD

**Issue by enesyteam** [bvaughn/react-virtualized#1275]
Just one word: Why?

I see many people ask about integrate react-virtualized with a custom scrollbars, but absolutely there is no solution work. So why are you don't support custom scrollbars in your library?

Thanks you!

**Comment by SleepingWhale** [comment]
@enesyteam 
It is probably outdated. Anyway I faced the same problem and here is the solution that worked for me.
```
import { Scrollbars } from 'react-custom-scrollbars';

<Scrollbars ref={this.scrollRef}>
    <WindowScroller scrollElement={this.scrollRef.current.view}>
```

**Comment by casvil** [comment]
is this possible using MultiGrid?
