### ISSUE TITLE
InfiniteLoader has incoherent architecture for tracking loaded versus loading rows

### ISSUE THREAD

**Issue by jedwards1211** [bvaughn/react-virtualized#1278]
I'm beginning to suspect that multiple people's different ideas about how to make `InfiniteLoader` work got accidentally mixed together in the course of merging PRs...

These quotes from the docs directly contradict each other:

> InfiniteLoader is not a stateful component, meaning that it does not keep track of which rows it has requested to be loaded.

> InfiniteLoader memoizes calls to loadMoreRows in order to avoid multiple calls with the same parameters while a user is scrolling.

This memoizer does literally "keep track of which rows InfiniteLoader has requested to be loaded".

A comment from a code example says
> An entry (either LOADING or LOADED) can be treated as loaded as far as InfiniteLoader is concerned

I don't get this memoization.  If `isRowLoaded` should return true for both loading and loaded state, then InfiniteLoader *should not need a cache/memoizer at all and can rely entirely on `isRowLoaded`* to prevent redundant calls to `loadMoreRows`.

If `isRowLoaded` should *not* return true for rows that are loading, then a separate `isRowLoading` function should be required, or whatever API is necessary so that `InfiniteLoader` can be truly stateless and rely on the user's code to keep track of loading/loaded state.

**Comment by pdkovacs** [comment]
What I am experiencing now is that `rowGetter` will be called for a row-index before is `isRowLoaded` and the thing will fail on the empty object (or `undefined` &ndash; I tried both) `rowGetter` returns. This thing should be either prepared to `rowGetter` returning nothing or probe each index with `isRowLoaded` before calling rowGetter. `InfiniteLoader` apparently follows some (ineffective) heuristics based on other parameters to decide when to call `isRowLoaded`.
