### ISSUE TITLE
How to close the blue lines

### ISSUE THREAD

**Issue by lixiaozhangme** [bvaughn/react-virtualized#1282]
![image](https://user-images.githubusercontent.com/19645470/49720258-49e97580-fc9a-11e8-954b-97cb36c17a94.png)
![image](https://user-images.githubusercontent.com/19645470/49720461-c5e3bd80-fc9a-11e8-9488-aa773f6aeb71.png)

This blue line will appear when I click on any element in WindowScroller

**Comment by le0zh** [comment]
```
.ReactVirtualized__List:focus{
  outline: none;
}
```

**Comment by lixiaozhangme** [comment]
thanks
