### ISSUE TITLE
AutoSizer is not properly calculating width

### ISSUE THREAD

**Issue by mar753** [bvaughn/react-virtualized#1287]
I have an issue with AutoSizer component used inside semantic-ui-react's Grid column. As I have investigated AutoSizer incorrectly calculates width, to be precise, when Grid column width is equal to not integer value e.g.: 1281.5px, the width of a List component that I am using inside is rounded to 1282px, what causes vertical scrollbar to appear sometimes (depending on height). I think this issue may be related to: https://github.com/bvaughn/react-virtualized/issues/1213

I have fixed it temporary by passing 'width-1' instead of 'width' to the List, but now the vertical scrollbar is not always at the right edge and sometimes there is a 1px space between the scrollbar and the edge:
```
<AutoSizer>
    {({ width, height }) => (
        <List
            width={width-1}
            [...]
```

react-virtualized@9.21.0

**Comment by bdubrovsky** [comment]
We have the same problem - where a div on screen is, say, 250.59px.  The gets rendered in 250px, but AutoSizer returns a size of 251px.  So, as a symptom, we lose a pixel of content.

We looked into the AutoSizer code and found that to figure out the dimensions of the parent container, the code uses element.offsetWidth and element.offsetHeight.  According to documentation, (e.g. https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth) these functions "round the value to an integer".  So, 250.59 gets rounded to 251 -- creating the problem.

We patched AutoSizer to truncate the fractional width and height by using Math.trunc(element.getBoundingClientRect().width or .height) This seems to work.  

Please let me know if there are any unforeseen issues here that we're not considering.

Thanks,

Ben

**Comment by eek** [comment]
Same issue is happening if you're using React Virtualized with Material-UI, and a MUI Popover is triggered (which removes the scrollbar), because of the rounding issue, the whole virtualized list changes (with the addition of subtraction of 1px from the width)

Until this is fixed, my simple work-around is to save the previous width and if the diff between the new width and old width is less than 5px, to use the old width.

**Comment by pavelspichonak** [comment]
I also have the same issue. And I'm also using material-ui library. Could you please fix this issue like @bdubrovsky said?

**Comment by BBaskovec** [comment]
Hi,

I had to create my own component as a workaround for this issue.
Here is the code i'm using:

```js
import React, { useEffect, useRef, useState } from "react";

const defaultOnResize = () => {};

export default ({
  className,
  defaultHeight = 0,
  defaultWidth = 0,
  disableHeight = false,
  disableWidth = false,
  children,
  style = {},
  onResize = defaultOnResize
}) => {
  const [dimensions, setDimensions] = useState({
    height: defaultHeight,
    width: defaultWidth
  });
  const ref = useRef();

  const resize = () => {
    if (ref.current.parentElement) {
      const height =
        ref.current.parentElement.getBoundingClientRect().height || 0;
      const width =
        ref.current.parentElement.getBoundingClientRect().width || 0;

      const style = window.getComputedStyle(ref.current.parentElement) || {};
      const paddingLeft = parseInt(style.paddingLeft, 10) || 0;
      const paddingRight = parseInt(style.paddingRight, 10) || 0;
      const paddingTop = parseInt(style.paddingTop, 10) || 0;
      const paddingBottom = parseInt(style.paddingBottom, 10) || 0;

      const newHeight = height - paddingTop - paddingBottom;
      const newWidth = width - paddingLeft - paddingRight;

      if (
        (!disableHeight && dimensions.height !== newHeight) ||
        (!disableWidth && dimensions.width !== newWidth)
      ) {
        setDimensions({
          height: height - paddingTop - paddingBottom,
          width: width - paddingLeft - paddingRight
        });

        onResize({ height, width });
      }
    }
  };

  useEffect(() => {
    window.addEventListener("resize", resize);
    resize();
    // cleanup this component
    return () => {
      window.removeEventListener("resize", resize);
    };
  }, [ref, resize]);
  const outerStyle = { overflow: "visible" };

  if (!disableHeight) {
    outerStyle.height = 0;
  }

  if (!disableWidth) {
    outerStyle.width = 0;
  }

  return (
    <div
      className={className}
      ref={ref}
      style={{
        ...outerStyle,
        ...style
      }}
    >
      {children({ ...dimensions })}
    </div>
  );
};
```
