### ISSUE TITLE
Make scrollbarWidth as passable prop to <Table />

### ISSUE THREAD

**Issue by sankalplakhina** [bvaughn/react-virtualized#1290]
Hi,

I am facing a *performance issue* when using `react-virtualised`'s `<Table />` component. Basically I am pushing new rows every few seconds to this component coming over a websocket connection. I am seeing a layout thrashing/forced reflow due to how `<Table />` calculates `scrollbarWidth` everytime new rows are passed to it.

I see a *"Forced reflow is a likely performance bottleneck."* in my performance console because `<Table />` calls the `_setScrollbarWidth` function on every `componenetDidUpdate`. This function recalculate scrollbar width using grid's `clientWidth` and `offsetWidth` causing a layout thrash.

Seeing this problem, I have following solution in mind - Pass `scrollbarWidth` as prop and stop calculating it every time on `didUpdate`.

Can anyone else suggest a better solution to handle this scenario? If not, what is the best way to get this change into this repo?

|                   |          |
|-------------------|----------|
| Browser           | Chrome         |
| OS                | Linux          |
| React             |   16.6.3       |
| React DOM         |  16.6.3        |
| react-virtualized |    9.21.0      |

**Comment by sankalplakhina** [comment]
Another solution I can think of to minimize the reflow is, if we can use the `rowCount` and `height` property together to figure out if it needs to calculate `scrollbarWidth` and cause the reflow only once.

**Comment by jincan39** [comment]
any update? @sankalplakhina

**Comment by IanVS** [comment]
I'm seeing about 300ms of self-time in `scrollbarWidth` during initialization in my own app, with the accompanying warning in Chrome mentioned by the OP.  I'm not sure whether passing a prop is the right solution, but it would be great if this time could be minimized.
