### ISSUE TITLE
Memory keeps increasing when react >= V16.6.1

### ISSUE THREAD

**Issue by olivermsw** [bvaughn/react-virtualized#1292]
Grid Component uses react >=V16.6.1 to increase memory as it scrolls
### What is the current behavior?

Memory keeps increasing

### What is the expected behavior?
memory automatic collection
### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |      Chrome v71    |
| OS                |    OSX 10.14.2      |
| React             |    16.6.1      |
| React DOM         |     16.6.1     |
| react-virtualized |     9.21.0     |

**Comment by MIKL99999** [comment]
Hi, can you provide some code examples on Codesandbox, CodePen or somewhere else?

**Comment by olivermsw** [comment]
update react-redux to 6.0.0 can fix it
