### ISSUE TITLE
Implementing sticky row button

### ISSUE THREAD

**Issue by Kosat** [bvaughn/react-virtualized#1293]
Hello,

QUESTION:
I need to implement sticky buttons on the right side of the row in `Grid` component as depicted on the sketch below.

![image](https://user-images.githubusercontent.com/153023/50355707-e4c23980-054f-11e9-9cc3-01ba354c01c0.png)

I looked into the example [here](https://bvaughn.github.io/react-virtualized/#/components/ScrollSync) and implemented the sticky buttons as a separate `Grid` control synchronized with the main `Grid` (containing rows) using `ScrollSync` component. 
The problem with this approach is that it takes a significant time to synchronize this two grids. Thus, when user scrolls vertically with mouse wheel the synchronization delays become very visible and annoying. 

Kindly, is there a better way of implementing such sticky buttons in *react-virtualized* `Grid`?

Thank you.

**Comment by Aarbel** [comment]
@Kosat have you found a way ?

**Comment by Kadrian** [comment]
I'm also trying but I can't get it to work: https://codesandbox.io/s/sticky-tester-qhwld

**Comment by Kadrian** [comment]
Ok, now I could, by removing the `overflow: hidden` in the Grid's inner scroll container.  Does anyone know what this `overflow: hidden` is used for?

**Comment by rscotten** [comment]
@Kadrian I'm also wondering what `overflow:hidden` is used for.  Disabling it in Chrome Dev Tools doesn't seem to affect the layout, and it allows my dropdown menu on each grid item at the bottom of the grid to overflow the inner scroll container.

@bvaughn can you help us understand the purpose of `overflow: hidden` on both `ReactVirtualized__Grid` and `ReactVirtualized__Grid__innerScrollContainer`?  I want to disable it, so I can have my dropdown menus on the last row of grid items overflow the outer containers.
