### ISSUE TITLE
onColumnClick should also pass rowData because there is no way of accessing it

### ISSUE THREAD

**Issue by vertazzar** [bvaughn/react-virtualized#1295]
https://github.com/bvaughn/react-virtualized/blob/5cf418c2462f083696b9ca26b51e57cd2475f0e3/source/Table/Table.js#L466

**Comment by eubrunomiguel** [comment]
Same, columnData seems to be undefined

**Comment by B3Kay** [comment]
I've got the same.
`onColumnClick={(prop)` => console.log(prop)}`
returns
`{
   columnData: undefined
   dataKey: "name"
   event: Class {dispatchConfig: null, _targetInst: null, _dispatchListeners: null, _dispatchInstances: null, …}}
 `

**Comment by rizwanahmed19** [comment]
I've got the same problem. Any solutions?

**Comment by jozefhm** [comment]
This problem still occour, any updates ?

**Comment by gemme** [comment]
I just faced same situation, to get row index selection on this event, any updates?

**Comment by vladislavkovaliov** [comment]
It looks that `columnData` isn't passed into `cellRenderer` too.
```
{
cellData: undefined, 
columnData: undefined, 
columnIndex: 6, 
dataKey: "", 
isScrolling: false,
rowData: {plantId: "id", imageTags: "tags", areaTags: "Perfect", data: "2019.07.05", time: "11:59 pm", …}
rowIndex: 1,
}
```

The only way that i could find is `plantId` could be passed into `data-attribute` for a while.

**Comment by hari96k** [comment]
Same issue, columnData is undefined when passed to headerRenderer. Plunkr to replicate (logging columnData):
https://next.plnkr.co/edit/PNPLhghK3QzMq8Hj

**Comment by davidlygagnon** [comment]
I'm running into this exact situation today. Seems too obvious to have been forgotten :(

**Comment by vsile** [comment]
The same issue. columnData is undefined
```
onColumnClick={(e) => console.log(e)}
```
```
{
   columnData: undefined,
   dataKey: "name",
   event: {..},
 }
```

**Comment by vertazzar** [comment]
Considering the fact there's bunch of vars around this block of code:

```
      var cellData = cellDataGetter({ columnData: columnData, dataKey: dataKey, rowData: rowData });
      var renderedCell = cellRenderer({
        cellData: cellData,
        columnData: columnData,
        columnIndex: columnIndex,
        dataKey: dataKey,
        isScrolling: isScrolling,
        parent: parent,
        rowData: rowData,
        rowIndex: rowIndex
      });

      var onClick = function onClick(event) {
        onColumnClick && onColumnClick({ columnData: columnData, dataKey: dataKey, event: event, rowData: rowData });
      };

      var style = this._cachedColumnStyles[columnIndex];
```
Take your pick, I've passed rowData: rowData and that's that. Note that I had to edit node_modules/react-virtualized/dist/es/Table/Table.js because, I really have no time to deal with making a pull request and all that.
