### ISSUE TITLE
Support column resizer in MultiGrid

### ISSUE THREAD

**Issue by dixyxavier** [bvaughn/react-virtualized#1302]
### Could you help me to implement column resizer in MultiGrid?

My use case is as shown below:

* I have a table with a million cells. The header row position should be fixed on vertical scroll. The table should render only the cells which are in viewport, so I selected MultiGrid.
* The react draggable demo which you provide [here](https://github.com/bvaughn/react-virtualized/issues/883) supports in Table, Column
* I need same column resizer in MultiGrid

**Comment by pavankumar-n** [comment]
Checkout below link for Column resizer in multigrid:
[https://codesandbox.io/s/multigrid-column-resizer-ccnxn](url)

**Comment by pavankumar-n** [comment]
[column-resizer-multigird](https://codesandbox.io/s/multigrid-column-resizer-ccnxn)

**Comment by pavankumar-n** [comment]
Checkout below link for Column resizer in MultiGrid:
[column-resizer-multigird](https://codesandbox.io/s/multigrid-column-resizer-ccnxn)
