### ISSUE TITLE
Something is wrong in IE9 and IE10

### ISSUE THREAD

**Issue by gyh9457** [bvaughn/react-virtualized#1305]
### What is the current behavior?
I get an error message when i use it in IE9 and IE10

![image](https://user-images.githubusercontent.com/13557235/51021461-8cb1ac80-15bc-11e9-9ebd-654823cf9168.png)

Demo

![image](https://user-images.githubusercontent.com/13557235/51021563-e1552780-15bc-11e9-800e-691e14690372.png)

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |     IE9 & IE10     |
| OS                |     WIN7     |
| React             |     16.7.0     |
| React DOM         |    16.7.0      |
| react-virtualized |    9.21.0      |

**Comment by gyh9457** [comment]
I want to debug locally, and then I get an error message when npm run build

![image](https://user-images.githubusercontent.com/13557235/51022853-583fef80-15c0-11e9-81bb-7e594bd5facf.png)

**Comment by illuminist** [comment]
https://github.com/bvaughn/react-virtualized/issues/1127
