### ISSUE TITLE
Circular Dependency

### ISSUE THREAD

**Issue by FabianSellmann** [bvaughn/react-virtualized#1308]
### What is the current behavior?

When compiling my project the following circular dependency has been detected by the Webpack [CircularDependencyPlugin](https://github.com/aackerman/circular-dependency-plugin) :  
```
node_modules/react-virtualized/dist/es/Grid/types.js -> node_modules/react-virtualized/dist/es/Grid/utils/ScalingCellSizeAndPositionManager.js -> node_modules/react-virtualized/dist/es/Grid/utils/CellSizeAndPositionManager.js -> node_modules/react-virtualized/dist/es/Grid/types.js
```
Sadly react-virtualized@9.21.0 is unusable if we throw an error during compile on detecting a circular dependency. 

I only imported AutoSizer and List directly from their respective dist folders.

### What is the expected behavior?
No circular dependency should be detected.

**Comment by velusgautam** [comment]
Released a circular dependency fix here. 

https://www.npmjs.com/package/@velusgautam/react-virtualized

Also raised a PR
https://github.com/bvaughn/react-virtualized/pull/1609

**Comment by melloware** [comment]
@velusgautam I can't find your fork or your fixed version on NPM?

**Comment by velusgautam** [comment]
Sorry, I have deleted the npm package and repository since I thought nobody is using it.
