### ISSUE TITLE
https://react-virtualized.now.sh  security alert from norton when opening website?

### ISSUE THREAD

**Issue by benchpresser** [bvaughn/react-virtualized#1309]
when opening this website ending with .now.sh (or react-window) norton prevents the site from being opened because of:

Threat Name: Web Attack: Fake TechSupport Website
Location: https:// mxcdn1 . now . sh

Threat Name: Web Attack: Fake TechSupport Website
Location: https:// mxcdn2 . now . sh

Threat Name: Web Attack: Fake TechSupport Website
Location: https:// npcdn1 . now . sh

Threat Name: Web Attack: Fake TechSupport Website
Location: https:// sxcdn02 . now . sh

Threat Name: Web Attack: Fake TechSupport Website
Location: https:// sxcdn3 . now . sh

Threat Name: Web Attack: Fake TechSupport Website
Location: https:// sxcdn4 . now. sh

Threat Name: Web Attack: Fake TechSupport Website
Location: https:// sxcdn6 . now . sh

Location: https:// 67346756743854bghjghg44242323442-ophzpectrw . now . sh

Is that a false alarm by norton?

**Comment by AndyCJ** [comment]
No, that's a fake TechSupport Website.
