### ISSUE TITLE
Scroll jumps in List with CellMeasurerCache

### ISSUE THREAD

**Issue by dariuszpaluch** [bvaughn/react-virtualized#1315]
### Do you want to request a *feature* or report a *bug*?
- BUG

[Example in codepen](https://codepen.io/dariuszpaluch/pen/QYdadM?editors=0110)

### What is the current behavior?
 - When I try to remove two rows and add one new row instead, the scroll jumps to the bottom of the list. This bug seems to appear only when the operation is performed at the bottom of the list.
![bug-example](https://user-images.githubusercontent.com/15227876/52050415-c426cf80-2550-11e9-9dcc-2359b79c0857.gif)

### What is the expected behavior?
 - Scroll stays in the current position after operation.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue?
|                   |          |
|-------------------|----------|
| react-virtualized |9.21.0|
| React                  |16.2.0|
| React DOM         |6.2.0|
| Browser           |Chrome, Firefox, Edge |
| OS                |Windows 10 |

**Comment by i-kushlianski** [comment]
+1 having the same issue

**Comment by dariuszpaluch** [comment]
I analize problem in source code and I think it's problem with method `Grid/utils/CellSizeAndPositionManager.getTotalSize()`  executed by `Grid/utils/updateScrollIndexHelper`

## Describe example
In example I removed rows with index 94 and 95, and add new Row instead (index = 94) without size in cache.

## Path of algorithm after this operation
#### 1) consequences of the add new row
- CellMeasurer analize rows, and found new row(94) and run method Grid.invalidateCellSizeAfterRender({columnIndex = 0, rowIndex = 94))
- Then execute `Grid.recomputeGridSize` and set `this._lastMeasuredIndex = index - 1 (93)` in `CellSizeAndPositionManager`

#### 2) consequences of the remove two rorws
```
// 85 line in Grid/utils/updateScrollIndexHlper.js

else if (
    !hasScrollToIndex &&
    cellCount > 0 &&
    (size < previousSize || cellCount < previousCellsCount)
  ) {

    // We need to ensure that the current scroll offset is still within the collection's range.
    // To do this, we don't need to measure everything; CellMeasurer would perform poorly.
    // Just check to make sure we're still okay.
    // Only adjust the scroll position if we've scrolled below the last set of rows.
    if (scrollOffset > cellSizeAndPositionManager.getTotalSize() - size) {
      updateScrollIndexCallback(cellCount - 1);
    }
  }
```
- Condition of `if` is true, because `cellCount < previousCellsCount (99 < 100)`. 
- Then method `Grid/utils/CellSizeAndPositionManager.getTotalSize()`  inside this block of code return wrong value. Then fulfilling the below condition and reset vertical scrollOffset:
```
//line 94 in /Grid/utils/updateScrollIndexHelper.js

 if (scrollOffset > cellSizeAndPositionManager.getTotalSize() - size) {
      updateScrollIndexCallback(cellCount - 1);
    }
```

`cellSizeAndPositionManager.getTotalSize` return wrong value because get only topOffset from 93 row(`this._lastMeasuredIndex = 93` - consequences of add new row)  and estimate others rows size.

**Comment by binglinglanyun** [comment]
Also have the same problem, do you have any workaround?

**Comment by Chyeegin** [comment]
+1 too..having same issue

**Comment by dariuszpaluch** [comment]
It looks like the problem no longer occurs in version `9.21.1`
