### ISSUE TITLE
[Suggestion] ability to set the Column's width prop to "auto" or "content"

### ISSUE THREAD

**Issue by warpdesign** [bvaughn/react-virtualized#1316]
I am using the Table component with two columns. Right now the `width` prop of the Column component appears to be mapped to the css `flex-basis` property so it basically sets the initial width of the column which can change depending on the `flexGrow` and `flexShrink`.

I wish I could use `auto` or `content` for the `width` prop of the Column component and not only number values since these are valid values for the `flex-basis` property.

In my case, I want the left column to grow as much as possible without overlapping the right column which default size I cannot guess since it depends on localized text.

Setting the `flex-basis` property to `auto` gives me the exact behavior I want but since the `width`'s prop must be a number there's no way I can set it without this ugly css:

```css
.myColumn{
   flex-basis: auto !important;
}
```

Suggestion: accept 'auto' and 'content' as well as numbers for the Column's `width` prop.

Example:

```tsx
<Table>
....
    <Column
    dataKey="name"
    label="Name"
    cellRenderer={this.nameRenderer}
    width="auto"
    flexGrow={1}
    />
...
</Table>
```

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |  Chrome 72        |
| OS                |        macOS mojave  |
| React             |       16.5.2   |
| React DOM         |   16.5.2       |
| react-virtualized |      9.21.0    |

**Comment by mdere-unbound** [comment]
@warpdesign - were you able to find a workaround? I kinda don't think width and height should be required? I think it should just default to a 100% width and height? then if the width/height of any prop is provided it should override...

**Comment by warpdesign** [comment]
@warpdesign I ended up using the ugly CSS hack I suggested:
 - I set a random `width` to the column
 - I override it using `flex-basis: auto !important`

**Comment by OnkelTem** [comment]
Having this `width` required is a pain. 

*First*, it works without this attribute just fine. Yeah, it complains in console that `width` is required, but doesn't create `flex` style property on the element, which is good, because in this case, it's gonna be: `0 1 auto`.

*Second*, why should we think about width all the time after all? It's a table, it grows usually whatever it wants, and that's exactly what we expect from it most of time.

So my propositions:

1) remove isRequired from props
2) allow user to provide the full range of `flex-basis` values

**Comment by OnkelTem** [comment]
/summon @bvaughn 

Brian, would you have a look at this? Thanks.

**Comment by OnkelTem** [comment]
Check out the PR please.

**Comment by EliRobinson** [comment]
It's 2021, is this something that will be added? This would be very nice to have.

**Comment by crow7m** [comment]
Hi All, thanks for your effort, will this be added  ? thank you

**Comment by lowzijian** [comment]
+1

**Comment by RichardHpa** [comment]
+1

**Comment by Liel208** [comment]
+1

**Comment by nolan-symphony** [comment]
+1
