### ISSUE TITLE
Scroll click on the list causes it to close in IE11 and Edge

### ISSUE THREAD

**Issue by Lekha30** [bvaughn/react-virtualized#1323]
I am using Material UI, react-select to render a virtualized list. When I click on the vertical scroll of the list. the list gets closed off in Edge and IE11. It works fine in other browsers. The click on the scroll just acts like a click away listener. The mouse scroll works although the key strokes are doesn't shift the view of the list.

Can someone throw some light on this please?

|                   |          |
|-------------------|----------|
| Browser           |   IE, Edge       |
| OS                |     Windows 10     |
| React             |    16.4.0      |
| React DOM         |    16.0.9      |
| react-virtualized |    9.21.0      |

**Comment by MinhNguyen41092** [comment]
@Lekha30 have you found the fix for this issue?

**Comment by Lekha30** [comment]
Unfortunately, no

**Comment by MinhNguyen41092** [comment]
@Lekha30 did you use react-virtualized List as custom MenuList for react-select? If yes you can try this:

```
import { components } from 'react-select'
const { MenuList } = components

const CustomMenuList = (props) => (
  <MenuList {...props} getStyles={() => {}>
     <List />
  </MenuList>
)
```
Then update react-select to the newest version and you are all set.

**Comment by Lekha30** [comment]
Hi Minh,
I tried the same way as you have done above. It is not working either. My react-select's version is 2.1.0

**Comment by MinhNguyen41092** [comment]
Hi @Lekha30 
Pls update to the newer version, your version is too old. You can read the change log of react-select to see the fix. Also remember to pass an empty function to `getStyles` prop to override styles of MenuList.

**Comment by Lekha30** [comment]
Great, upgrading react-select fixed the issue.  Also that passing an empty function to `getStyles` didn't work for me, so I passed in custom styles for the `menuList` to override its styles

**Comment by Lekha30** [comment]
But the above workaround isn't working for smaller lists with about 2 options. Is there any workaround for this?

**Comment by MinhNguyen41092** [comment]
Just use react-select instead?

**Comment by michalica** [comment]
I have the same problem on IE 11, when user want to drag vertical scroll bar, it closes dropwdown with options.
