### ISSUE TITLE
Wrap of long string to a new line in the table (with an example)

### ISSUE THREAD

**Issue by ghost** [bvaughn/react-virtualized#1326]
I have a table with two columns. How to wrap the text to a new line and change the height of the row?
I attach an example: https://codepen.io/azodklas/pen/yZjejj
I want the message column not to cut the text, but to transfer to a new line
**If not difficult, correct my example so that it works as it should.**

|-------------------|----------|
| Any browser          |          |
| Win and Mac         |          |
| React                      |16.7.0|
| React DOM            |16.7.0|
| react-virtualized     |9.10.1|

**Comment by azotklas** [comment]
I updated codepen example... [DEMO](https://codepen.io/azotklas/pen/QYBYVQ)
I added "CellMeasurerCache" and "CellMeasurer" in my "Table" component, but long text wrapping doesn't work for me!!
Help me please!! What am I doing wrong? 
I have reviewed many examples, I do the same, but it does not work. long text is still not wrap to the new line!

**Comment by azotklas** [comment]
[Working example](https://codepen.io/azotklas/pen/QYBYVQ)

**Comment by pabrahamusa** [comment]
Thanks @azotklas it helped me to fix similar issue, Appreciate you posted your solution.
