### ISSUE TITLE
dataKey should allow for nested properties...

### ISSUE THREAD

**Issue by ghost** [bvaughn/react-virtualized#1329]
We have a scenario where our row data is an object with nested properties, like so:

```
{
  "name": 'bob',
  "metaData": {
     "foo": 'x',
     "bar": {
        // ... more data ...
      },
     "baz": {
       "blah": false
     }
  }
}
```

In my table I want to display columns of information for all the data in my object, not just the top-level... also, because dataKey is used to uniquely identify a column to an object property, and because it does not allow nesting, I have to flatten my object and assign a different dataKey for every column...

It would be helpful if instead, I could provide a nested dataKey value and have `react-virtualized` parse my object accordingly...

**Example:**
```
<Column dataKey='name' ... />
<Column dataKey='metaData.foo' ... />
<Column dataKey='metaData.bar' ... />
<Column dataKey='metaData.baz.blah' ... />
```

**Comment by AlexAichinger** [comment]
Just started implementing the table in our application and also ran into this. What is the best way to access the nested value? Flatten the object and then display in the table?

**Comment by jbarker4682** [comment]
@AlexAichinger What we ended up doing is passing in a dataKey that does not map to anything specific, but is unique, and then using a switch statement in our renderer that used to dataKey to determine which rowData value to use...  its not great, but it works...

**Comment by GuySerfaty** [comment]
Another option can be:
`<Column
                  label="Eye color"
                  dataKey="someid"
                  cellDataGetter={({rowData}) => rowData.nested.eyeColor}
/>`

**Comment by FedeBev** [comment]
Definitely, that would be awesome!

**Comment by nous-** [comment]
> Another option can be:
> `<Column label="Eye color" dataKey="someid" cellDataGetter={({rowData})=>rowData.nested.eyeColor} />`

I thought this was a recommendation for a future API, but this is live in master.
