### ISSUE TITLE
ArrowKeyStepper: expose onKeyDown as a property

### ISSUE THREAD

**Issue by macobo** [bvaughn/react-virtualized#1332]
Hello. We're looking to use ArrowKeyStepper in an interactive product choosing modal and want to experiment with different navigation methods, in particular:

- Navigation with different keys (ws, tab)
- Capturing user choice with enter key

ArrowKeyStepper is really close code-wise to solve this usecase, but isn't flexible enough. 

## Proposal

Introduce new prop `onKeyDown`. For example:

```typescript
onKeyDown?: (
  event: KeyboardEvent,
  setScrollState: (row: number, column: number) => void
)
```

Existing onKeyDown implementation would become the default, but users could swap out the implementation wholly.

`setScrollState` function could be used by users inside the function to force navigation. Alternatively, to use this new prop you would need to use a controlled component.

**Comment by roboslone** [comment]
+1, this breaks global keydown listeners.
