### ISSUE TITLE
Ability to show noContentRenderer result in only one grid

### ISSUE THREAD

**Issue by vcardins** [bvaughn/react-virtualized#1335]
Currently, if I have `fixedColumnCount` and `noContentRenderer` set, it displays the no content text in both panels, but that doesn't look good.
![image](https://user-images.githubusercontent.com/2383329/53267950-9806f600-3699-11e9-9a15-f7ae1c8bd7fe.png)
Would be possible to either have to props, e.g: `noContentRightGridRenderer` and `noContentLeftGridRenderer` or anything to avoid this behaviour?

**Comment by akhilaudable** [comment]
+ 1

**Comment by ayushagg31** [comment]
@vcardins did you found any workaround for this issue?

**Comment by redwind** [comment]
> @vcardins did you found any workaround for this issue?

i think maybe we can use css classNameTopLeftGrid, classNameTopRightGrid to hidden empty view.
