### ISSUE TITLE
Weird horizontal scrolling issue on iOS

### ISSUE THREAD

**Issue by leif-erikson** [bvaughn/react-virtualized#1339]
Hi,

I am using the List component to render a list where certain elements of the list are horizontally scrollable ( Eg. -- [Google search results on mobile](https://i.imgur.com/giABoxB.png)). 

Here's a sample of what I am trying to achieve -- https://codesandbox.io/s/wo7vv1877k?fontsize=14

This seems to work perfectly fine on various Android devices that I've tested, but on iOS Safari I've noticed a weird issue where if I flick to scroll vertically and then try to scrolling horizontally on the nested group, that doesn't seem to work at all (the input on the nested group div is ignored completely).

I am not sure if this is an issue since this usecase isn't really mentioned anywhere in the docs. But still I posted here for help as this issue is kinda of a blocker on what I am working on. 

EDIT: Also, I've tried the same sample without using react-virtualized and that seems to work fine on iOS devices. 

Regards,  
Leif

**Comment by rajtrivedi88** [comment]
I am having exactly the same requirement and facing exactly the same issue on iOS 12.2

**Comment by satyajit-shetye** [comment]
@leif-erikson Similar Requirement, same issue.

**Comment by kole** [comment]
Any updates on this? I am seeing the same thing on v9.21.1

**Comment by ahmetaydogduoglu** [comment]
I have same issue. Does anyone have an idea @bvaughn

**Comment by Petar-Pankov** [comment]
Any update?
