### ISSUE TITLE
Whole list re-rendering when one item changes

### ISSUE THREAD

**Issue by jamesalester** [bvaughn/react-virtualized#1341]
I'm using the InfiniteLoader to render potentially long lists of items. When an item is selected it loads up a new list next to it but keeps the original list in place with updated styling on the selected item. But it seems like this is causing the whole list to re-render: 

![mar-04-2019 15-31-09](https://user-images.githubusercontent.com/19751644/53743709-5ba27980-3e93-11e9-886a-6887e983a6da.gif)

Is this to do with the way rowRenderer is called?

This might be linked to issue #1028 where it looks like a property was added to prevent Grids from being re-rendered but it may not have been added to Lists.

**Comment by jlil** [comment]
@jamesalester do you have a codesandbox for this? 
Try either passing `isScrollingOptOut` as a prop to `<List>` (beware of other side effects it could have) or try returning `false` in the `componentShouldUpdate` of your list item component.

**Comment by YaroslavAntipov357** [comment]
It will be great to have this feature added to the `List` component, as well.
