### ISSUE TITLE
scrollbarWidth Bug

### ISSUE THREAD

**Issue by joshjung** [bvaughn/react-virtualized#1342]
I cannot for the life of me see any good reason for the `scrollbarWidth` calculation. I'm trying to style the header of my grid, and the extra 15px is completely destroying my ability to do so:

<img width="616" alt="screen shot 2019-03-05 at 09 06 22" src="https://user-images.githubusercontent.com/913181/53790014-22671980-3f26-11e9-8ceb-ef7cd185e913.png">

All I want is a top border on my grid header, but the extra 15px forces the header to lie outside of the rest of my content. I want it completely removed. Is there any way to do this?

**Comment by daiict218** [comment]
Facing the same issue
