### ISSUE TITLE
custom layers in scrollable area

### ISSUE THREAD

**Issue by Guria** [bvaughn/react-virtualized#135]
Custom layers in inner scrollable area would be useful to place some non-virtualized content. Eg.:
* links between items across lines
* "row" / "column" borders (1 row table for rendering columns and 1 column table to render row borders)

![](http://i.imgur.com/IVvfj2n.png)

Example markup based on kendo gantt:
```html
<!-- 'Grid__innerScrollContainer' content goes here -->
<div class="k-gantt-tables">
    <table class="k-gantt-rows" style="width: 1400px;">
        <colgroup>
            <col>
        </colgroup>
        <tbody>
            <tr class="k-alt">
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr class="k-alt">
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr class="k-alt">
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr class="k-alt">
                <td>&nbsp;</td>
            </tr>
        </tbody>
    </table>
    <table class="k-gantt-columns" style="width: 1400px; height: 770px;">
        <colgroup><col><col><col><col><col></colgroup>
        <tbody>
            <tr>
                <td>&nbsp;</td>
                <td class="k-nonwork-hour">&nbsp;</td>
                <td class="k-nonwork-hour">&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </tbody>
    </table>
</div>
<div class="k-gantt-dependencies" style="width: 1400px;">
    <div class="k-line k-line-h" data-uid="374423c0-1b1a-45d2-b14a-fa3426815c1b" style="left: 1299px; top: 191px; width: 10px;"></div>
    <div class="k-line k-line-v" data-uid="374423c0-1b1a-45d2-b14a-fa3426815c1b" style="left: 1307px; top: 191px; height: 17px;"></div>
    <div class="k-line k-line-h" data-uid="374423c0-1b1a-45d2-b14a-fa3426815c1b" style="left: 1089px; top: 208px; width: 220px;"></div>
    <div class="k-line k-line-v" data-uid="374423c0-1b1a-45d2-b14a-fa3426815c1b" style="left: 1089px; top: 208px; height: 333px;"></div>
    <div class="k-line k-line-h" data-uid="374423c0-1b1a-45d2-b14a-fa3426815c1b" style="left: 1089px; top: 541px; width: 9px;"><span class="k-arrow-e"></span>
    </div>
</div>
<!-- {childrenToDisplay} -->
```

**Comment by Guria** [comment]
Can try to self assign on it, but will need your approve and API suggestions.

**Comment by bvaughn** [comment]
Honestly not sure how this would work without significantly complicating the rendering logic.

**Comment by bvaughn** [comment]
Let this issue sit for a bit and sink in and basically it's not something that I know how to approach in a generic way.

I think you could use the [`onScroll` callback](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md) in a similar way as [`ScrollSync`](https://github.com/bvaughn/react-virtualized/blob/master/source/ScrollSync/ScrollSync.js) to implement this type of functionality if you wanted. You'd essentially just need to position another `<div>` (or custom component) on top of the `Grid` and then put whatever you want inside of it- keeping it "synced" with the visible cells using the callback.

If you'd like to tackle implementing it I'd be happy to review a PR. If it seems generic enough we could bundle it with react-virtualized. If it seems too use-case specific we could include it in the recipes/examples section. :)

I don't plan to work on this myself though so I'm going to close the issue for now. (I don't like leaving issues open that I don't plan to act on.) We can continue to discuss this feature here, or through PRs, though.

**Comment by Guria** [comment]
@bvaughn it looks as easy as just:
```
diff --git a/source/Grid/Grid.js b/source/Grid/Grid.js
index 2ba198b..1ffe02b 100644
--- a/source/Grid/Grid.js
+++ b/source/Grid/Grid.js
@@ -487,6 +487,7 @@ export default class Grid extends Component {
               pointerEvents: isScrolling ? 'none' : 'auto'
             }}
           >
+            {this.props.children}
             {childrenToDisplay}
           </div>
         }
```
Works as I expect:
```js
<Grid ...props>
  <div style={{ height: '100%' }}>
    any background content
  </div>
</Grid>
```

**Comment by Guria** [comment]
`VirtualScroll` and `FlexTable` hocs could also pass their (non `FlexColumn`) children to `Grid` as well.

**Comment by bvaughn** [comment]
That definitely seems like an over-simplification.

* How do you plan to sync your `childrenToDisplay` (horizontally and vertically) to ensure that they line up with the rendered cells underneath of them?
* How do you plan on informing the `childrenToDisplay` of which cells are being displayed (and where) so you can align your overlay?
* Presumably your grid contains many many cells (or you wouldn't need to virtualize them). How do you plan on windowing the content in `childrenToDisplay` so avoid rendering all of it (and defeating the purpose of using the `Grid` in the first place)?

**Comment by Guria** [comment]
@bvaughn it is not over-simpification it is really only thing I need:

```js
<ScrollSync ...ssProps>
  {({ onScroll, scrollLeft, scrollTop }) => (
     <TimelineHeaderGrid scrollLeft={scrollLeft} ...timelineProps />
     <div className='LeftColumn'>
       <VirtualScroll
         onScroll={onScroll}
         scrollTop={scrollTop}
         width={1024}
         height={200}
         rowsCount={10}
         rowHeight={20}
         rowRenderer={
           index => <GanttTask ...getGanttTaskProps(index) /> // task positioned in a row
         }
         {...props}
       >
        <RowsBackground
         width={1024}
         height={200}
         rowsCount={10}
         rowHeight={20}
        />
        <ColsBackground ...colsBackgrounProps />
        <Dependencies ...depsProps />
       </VirtualScroll>
     </div>
  )}
</ScrollSync>
```
I have all what I need to manually position dependencies on background layer: rowsCount, rowHeight, and tasks positioned horizontally.

**Comment by Guria** [comment]
I don't need to virtualize every cells because background comes only with `n + m` elements, not `n * m`

**Comment by bvaughn** [comment]
If you don't need to virtualize cells, and none of the questions I asked above are problems for you, then why does this need to be inside of the `VirtualScroll` at all?

```js
<ScrollSync>
  {({ onScroll, scrollLeft, scrollTop }) => (
    <TimelineHeaderGrid scrollLeft={scrollLeft} ...timelineProps />
    <div className='LeftColumn'>
      <VirtualScroll
        onScroll={onScroll}
        scrollTop={scrollTop}
        width={1024}
        height={200}
        rowsCount={10}
        rowHeight={20}
        rowRenderer={
          index => <GanttTask ...getGanttTaskProps(index) /> // task positioned in a row
        }
        {...props}
      />
      <div className='AbsolutelyPositionedOnTop'>
        <RowsBackground
          width={1024}
          height={200}
          rowsCount={10}
          rowHeight={20}
        />
        <ColsBackground ...colsBackgrounProps />
        <Dependencies ...depsProps />
      </div>
    </div>
  )}
</ScrollSync>
```

**Comment by Guria** [comment]
Because it would require to hook it on ScrollSync too. Which seems complete overkill, because it can be scrolled natively within container.

**Comment by Guria** [comment]
I can try to prepare a pr with demo

**Comment by bvaughn** [comment]
I don't think it's overkill, considering this seems to be a special use-case.

**Comment by Guria** [comment]
@bvaughn just try any `ScrollSync` on mobile or Internet Explorer. You'll see that it is not so smooth. I try to avoid using `ScrollSync` on mobile views and decrease using it at all on desktop ones too. Just can't find any reason to use it, because placing layer to existing scroll container doesn't requires to redraw layer on scroll, but ScrollSync does.
I have created a little demo: [Source](https://github.com/Guria/react-virtualized/tree/layers-demo) [Deployed](https://guria.github.io/react-virtualized/) (see `ScrollSync demo`)

**Comment by bvaughn** [comment]
The scroll-sync demo you linked to looks fine to me, even for IE10 in my crappy little Virtual Box VM (which is the only way I have to test IE) and in the iOS simulator.

Anyway, I don't think this example test-case you've created is very representative in terms of windowing performance because you're only drawing a few small lines to connect certain cells. How is it going to perform when you're connecting thousands of cells? (It won't, I don't think, without windowing.) Which makes me think that you'd do better stacking 2 windows components on top of each other (like 2 `Grid`s).

**Comment by Guria** [comment]
It works acceptable in ie10+, but lag is pretty notable by eye. It always happens in IE. I don't know any existing solution to make good controlled scroll behaviour.

But even without taking IE in account can't get why I have to create one scrollable area over another with the same container and inner scrollable area sizes and keep them in sync.

I know how important and hard to keep library's public API narrow and focused, but can't see why you against of this change. Do you see any drawbacks?

**Comment by bvaughn** [comment]
I already pointed out a few issues I saw with this feature request. I'll try to word them differently.

* How do you convey position of grid-cells (or table rows) to your custom layer to ensure that things line up?
* How do you inform your custom layer of which cells are currently being displayed so you can implement windowing? (And if you don't plan on implementing windowing in the custom layer, why use a react-virtualized component at all?)

**Comment by somebody32** [comment]
I’m also will be glad about the opportunity to pass children to `Grid`.
Looks like everyone who is doing Gantt charts will find this issue eventually, so I will try to answer the questions and describe the use case:

Here is the code:
```javascript
<AutoSizer>
  {({ height, width }) => (
    <Grid     
      rowsCount={1}
      width={width}
      height={height}
      columnWidth={col_width}
      columnsCount={columns_count}
      rowHeight={height}
      renderCell={this.renderGridCol}
    >
      <Grid
        className={styles.rowsContainer}
        rowsCount={rows.length}
        width={columns_count * col_width}
        height={height}
        overscanRowsCount={15}
        columnWidth={columns_count * col_width}
        columnsCount={1}
        rowHeight={unit_height}
        renderCell={this.renderRow} />
    </Grid>
  )}
</AutoSizer>

```

As you can see here are 2 Grids: the parent one is rendering background cols, so it is just one row and n-cols.
The child Grid is rendering task rows: so just one col and m-task rows.
Child grid styles are pretty simple too:

```css
.rowsContainer {
  position: absolute;
  top: 0;
}

```

With that composition there is no need to do scroll syncing, browser is doing that for us.
And as soon as we have 2 distinct windowing: horizontal and vertical, no need to pass anything from the parent grid, scroll doing everything for us here too.

Hope that makes sense!

**Comment by bvaughn** [comment]
Hey @somebody32,

Your example code is functionally no different than stacking 2 `Grid`s (position one so that it covers the other). Without `ScrollSync` (or a similar technique) only the top `Grid` will be scrollable by the user. (The browser will not sync them for you. Scroll events don't pass through the z-index like that.)

What you are asking for is already possible as I mentioned above with the `ScrollSync`. Your code would just need to change slightly:

```js
<ScrollSync>
  {({ onScroll, scrollLeft, scrollTop }) => (
    <AutoSizer disableHeight>
      {({ width }) => (
        [
          <Grid
            k='backgroundGrid'
            scrollLeft={scrollLeft}
            scrollTop={scrollTop}
            {...backgroundGridProps}
          />,
          <Grid
            k='foregroundGrid'
            onScroll={onScroll}
            {...foregroundGridProps}
          />
        ]
      )}
    </AutoSizer>
  )}
</ScrollSync>
```

**Comment by somebody32** [comment]
@bvaughn,

It is working already (I've cloned the repo and added `{props.children}` into Grid's render).

Here is an example:
![react-virtual](https://cloud.githubusercontent.com/assets/25742/13532509/2640c8d0-e22c-11e5-9c0a-4720b9c4ff03.gif)

These color bars are the rows from the second grid, the background is generated by the parent one.

I've tried stacking 2 grids too + scroll sync, but that was showing some delay and as a result, the table had kind of parallax effect :) You can see an example in the GIF of that if you take a look at the Gantt Grid header (it is yet another `Grid` which is `ScrollSync`'ed with the two others from the previous example), its today mark flows away from the grid's one. I know that I need to optimize header rerenders, but if it is possible to avoid usage of ScrollSync I think it is good to do so.

**Comment by bvaughn** [comment]
Hm. Share your code with me? (Link me to your fork?)

If you stack 2 scrollable containers, only the top one will get scroll events, so I don't understand how the lowest-z-index `Grid` is getting scrolled.

In Aleksey's previous examples, the additional children were just absolutely positioned within the `scrollContainer` and so they scrolled naturally with the rest of the content, but that tosses out the benefits of windowing.

**Comment by somebody32** [comment]
@bvaughn it is totally identical to Aleksey's except `{this.props.children}` are rendered after the `{childrenToDisplay}`.

Sorry, forgot to tell that color rows are horizontally positioned with `translatex`, but windowing is still working because I'm interested in vertical windowing for them, not the horizontal one.

Will be glad to share more code/examples.  maybe just resulting html will work?

**Comment by bvaughn** [comment]
Ah, then the code sample you pasted above (a `Grid` within a `Grid`) would not work. Scrolling doesn't automatically get synced that way. I'm a bit confused. I'm going to need to see a complete coding example. (Something I can check out and run, or a demo with source I can view.)

**Comment by somebody32** [comment]
@bvaughn I will try to prepare repo today

**Comment by bvaughn** [comment]
Take your time. This is not a job/project I'm paid for so I can't really work on it during the day. I'll check back this evening.

**Comment by somebody32** [comment]
I've created the [demo](http://somebody32.github.io/react-virtualized/), click on `Grid`  to see it live.

The code is [here](https://github.com/somebody32/react-virtualized/commit/feb1fafb87193af1785177a0328c86a6f99e8051)

**Comment by bvaughn** [comment]
Ah. I see what you're doing. It seems pretty limited though. The inner `Grid` isn't being virtualized along the x-axis (there's no horizontal windowing) because its width is 2600 pixels. The outer `Grid` is only scrollable horizontally. So this only works if each `Grid` only needs to scroll along one axis.

**Comment by bvaughn** [comment]
One approach you could consider trying if the `Grid`s seemed out of sync with the `ScrollSync` approach I recommended would be to sync _both_ `Grid`s based on an invisible scrollable div. In other words something like this:

```js
      <div className={styles.wrapper}>
        <ScrollSync>
          {({ onScroll, scrollLeft, scrollTop }) => (
            <AutoSizer>
              {({ height, width }) => (
                <div className={styles.wrapper}>
                  <Grid
                    className={styles.gridStyle}
                    {...bottomGridProps}
                    scrollLeft={scrollLeft}
                    scrollTop={scrollTop}
                  />
                  <Grid
                    className={styles.gridStyle}
                    {...bottomGridProps}
                    scrollLeft={scrollLeft}
                    scrollTop={scrollTop}
                  />
                  <div
                    onScroll={
                      (event) => onScroll({ scrollLeft: event.target.scrollLeft, scrollTop: event.target.scrollTop })
                    }
                    style={{
                      width,
                      height,
                      overflow: 'auto',
                      position: 'absolute',
                      zIndex: 1
                    }}
                  >
                    <div
                      style={{
                        width: grid_width,
                        height: grid_height
                      }}
                    />
                  </div>
                </div>
              )}
            </AutoSizer>
          )}
        </ScrollSync>
      </div>
```

And in the above example, the `gridStyle` class could disable default scrolling:
```css
.gridStyle {
  overflow: hidden !important;
  position: absolute !important;
  top: 0;
  left: 0;
}
```

**Comment by somebody32** [comment]
This is a great idea! Tried that and scroll sync seems way better now (no lags for header and grids). The only problem that this approach has is: this new div steals all pointer events from the grids. Looks like there is no way to do scrolling and also do hovers/interaction with grids' content

**Comment by bvaughn** [comment]
Hm. Tried swapping the `<div>` with the `onScroll` handler to the bottom? Seems like that should still work though I admit I haven't tried it.

**Comment by somebody32** [comment]
Yep, I've tried moving it to the different places, but the problem seems the same: it needs to get pointer events to be scrollable, but then grid's children will receive nothing

**Comment by bvaughn** [comment]
Hm. Your previous demo [above](https://github.com/bvaughn/react-virtualized/issues/135#issuecomment-192339653) suggests that scroll events can go through one item to another if the top item has it's `overflow: hidden`. That's why I thought it might work if the `onScroll` div was in the back.

**Comment by somebody32** [comment]
I think it only works when you're trying to scroll children because an event is bubbling up to the parent, but here we have everything all in one layer. Looks like it is not possible to solve without placing one grid into another

**Comment by bvaughn** [comment]
Ah, I see. I guess you _could_ put the `Grid`s inside of the `onScroll` div then. But you'd have to move them as the user scrolled which would probably end up being too much of a hack. Rats.

**Comment by somebody32** [comment]
So maybe then you can accept PR for rendering `children` inside the `Grid`? This will allow avoiding `onScroll` div and relay on the browser native one

**Comment by somebody32** [comment]
I've just published a new example (http://somebody32.github.io/react-virtualized/, click on `Grid`, here is the [code](https://github.com/somebody32/react-virtualized/commit/57dd9ddd02dbdc96ace30ac58146dc01e1864e81)).

It uses one scrollable div as the parent of both `Grid`'s and then positions grids depending on the current scroll value.

What do you think?

**Comment by bvaughn** [comment]
That actually looks pretty reasonable to me. Although I think you could further simplify by...
```js
<div className={styles.wrapper}>
  <ScrollSync>
    {({ onScroll, scrollLeft, scrollTop }) => (
      <AutoSizer>
        {({ height, width }) => (
          <div
            ref={(node) => this.wrapper = node}
            style={{height, width}}
            className={styles.grid_wrapper}
            onScroll={onScroll}
          >
            <div
              style={{height: grid_height, width: grid_width}}
              className={styles.scroller}
              >
              <div
                style={{
                  left: scrollLeft,
                  top: scrollTop
                }}
                className={styles.innerWrapper}
              >
                <Grid
                  className={styles.gridStyle}
                  rowsCount={1}
                  width={width}
                  height={height}
                  columnWidth={COL_WIDTH}
                  columnsCount={COLS}
                  rowHeight={height}
                  renderCell={this.renderCol}
                  scrollLeft={scrollLeft}
                  scrollTop={scrollTop}/>
                <Grid
                  className={styles.gridStyle}
                  rowsCount={rows.length}
                  width={width}
                  height={height}
                  columnWidth={grid_width}
                  columnsCount={1}
                  rowHeight={ROW_HEIGHT}
                  renderCell={this.renderRow}
                  scrollLeft={scrollLeft}
                  scrollTop={scrollTop}/>
              </div>
            </div>
          </div>
        )}
      </AutoSizer>
    )}
  </ScrollSync>
</div>
```

PS. You can deep-link by the way, by adding `?component=Grid` (eg. http://somebody32.github.io/react-virtualized/?component=Grid)

**Comment by somebody32** [comment]
Yep, thanks, obviously I don't need `this.position` at all, because there are already `scrollLeft, scrollTop` available.

But you need an extra check for `if (this.wrapper !== event.target) return;` inside the top div's `onScroll` because Grids are producing scroll events too and they are bubbling. If you omit this check, then `top` could be reset to `0` for a short period of time and everything jumps and seems broken.

Anyway, looks like everything is working great now, thanks a lot for your help and for your hard work on this library! If you're interested and you think this can be useful for users, I can prepare a PR with this example

**Comment by bvaughn** [comment]
Makes sense.

Yeah, this would probably make a good example to add to the [`playground` folder](https://github.com/bvaughn/react-virtualized/tree/master/playground). If you'd be willing to put together a PR, that would be great. :)

**Comment by bvaughn** [comment]
Hey @Guria  and @somebody32. I wanted to let you know about the recent release [6.1.0](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#610) as it has a feature I think you would both find useful.

You can provide a custom render function to create `Gris` children. Among other things, this should allow you to do your layering within a single `Grid` instance.

**Comment by somebody32** [comment]
@bvaughn thank you for notifying about that! Our Gantt product is in the final stages before the release now, but I will try to refactor our current 2 grid implementation into one in the first iterations after it asap. 

And as a sidenote: thanks a lot for your hard work on this lib, it is really amazing!

**Comment by Guria** [comment]
@somebody32 does your gantt completely internal? is there a plans to make it public?

**Comment by somebody32** [comment]
@Guria in terms of code or product? if the last one, then it will be released as part of redbooth.com soon

**Comment by Guria** [comment]
@somebody32 in terms of code but only gantt part as component

**Comment by somebody32** [comment]
@Guria I think after the 6.1 release of react-virtualized and new `CollectionView` that is coming it is really easy to make it yourself (and I will try to make a PR with an example as I said earlier). I don't think that extracting something more will be useful for the wide audience because it is really coupled to our product.

**Comment by mariobrubio** [comment]
Hi! I know this issue is kind of old, but I'm currently trying to refactor a Gantt component that I developed using react virtualized. My major problem is that I can't set relations between nodes (visually) because the data is not rendered at all time as it should be with this library, but... How can I draw relations between two or more nodes using for example ScrollSync? @bvaughn
