### ISSUE TITLE
Strict mode compatibility

### ISSUE THREAD

**Issue by NeoLegends** [bvaughn/react-virtualized#1353]
RV makes use of `findDOMNode` in `WindowScroller` and that's deprecated in recent versions of react. You might want to switch this to using refs instead. :)

**Comment by jacklee814** [comment]
1

**Comment by jacklee814** [comment]
Test

**Comment by Ericnr** [comment]
@bvaughn can this be addressed? Concurrent mode is coming and it'd be nice if the library worked  smoothly with it.

**Comment by jktravis** [comment]
It also seems to be used in `CellMeasurer`

**Comment by Hypnosphi** [comment]
In `WindowScroller`, it can be avoided by using [`registerChild` render prop](https://github.com/bvaughn/react-virtualized/blob/master/docs/WindowScroller.md#render-props)

I'm going to open a PR adding the same pattern for `CellMeasurer`

**Comment by Hypnosphi** [comment]
Even if I use `registerChild`, `WindowScroller` doesn't seem to work with `StrictMode`:

https://codesandbox.io/s/react-virtualized-list-with-width-100-dunc2

You can see that if you scroll list down, new items don't appear. This can mean that there are side effect in places where they shouldn't be

https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by wuweiweiwu** [comment]
Thanks for bringing this up! I kinda lost track of some bugs. Will prioritize!

**Comment by makker** [comment]
Would be awesome to get the strict mode issue fixed. Thanks for the great work so far!

**Comment by HeikkiMoilanen** [comment]
Hello! Are there any news on this one? Would be awesome to get rid of those warnings cluttering the console :). Thank you for the effort and the nice library!

**Comment by mika-kaki** [comment]
I'd appreciate a fix for this. Thanks for great work!

**Comment by Kudo** [comment]
This [codesandbox](https://codesandbox.io/s/react-virtualized-list-with-width-100-dunc2) example seems to be fixed after upgrading to RV 9.22, maybe it is related to #1477

**Comment by kierancrowntrt** [comment]
> This [codesandbox](https://codesandbox.io/s/react-virtualized-list-with-width-100-dunc2) example seems to be fixed after upgrading to RV 9.22, maybe it is related to #1477

This codesandbox isn't working as of 30/09/20. New items are not being rendered

**Comment by timminata** [comment]
Also keen to see a fix for this. We use react-virtualized and are considering trialing React concurrent and I'm not sure if this will just be an annoyance or cause actual errors.

**Comment by sergeyzwezdin** [comment]
Not sure, why need `findDOMNode()` here if we already have ref there?

https://github.com/bvaughn/react-virtualized/blob/e360d958b99fa965fd3f1caed4506403ad652cd3/source/Table/Table.js#L342

**Comment by meotimdihia** [comment]
@bvaughn please take a look at this problem. It is annoying and takes up space when seeing it at the browser's console.
And we can't suppress this warning too.

**Comment by mleister97** [comment]
Is this lib still maintained? Issue exists still beginning of 2019...

**Comment by sebkasanzew** [comment]
Maybe this is a good alternative to this package. But I didn't have the time to try it yet.
https://github.com/tanstack/virtual

**Comment by michaelyohanes** [comment]
still occuring on 2024

**Comment by githubdev99** [comment]
Also this issue affects my website (which uses Next.js).
<img width="998" alt="image" src="https://github.com/bvaughn/react-virtualized/assets/63225364/0b9a4273-ed01-4552-8449-b0f4eadc4ab5">

**Comment by bayasdev** [comment]
This library will stop working with React 19
https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-finddomnode
