### ISSUE TITLE
Using AutoSizer/CellMeasurer with dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by carera** [bvaughn/react-virtualized#1359]
Hi there,
First of all, thanks for the awesome library! <3 Amazing job.

**Now onto my problem:** 
When the content of my rows is generated using `dangerouslySetInnerHTML` the `AutoSizer` gets confused and behaviour of the scrolling goes crazy, most likely caused by the fact that dangerouslySetInnerHTML is somewhat rendered asynchronously.
Now I found that `react-virtualized` offers `CellMeasurer`, but where am I supposed to put the `measure` callback in my dangerouslySetInnerHTML-hydrated component?

**Comment by X140Yu** [comment]
Same issue here. Have you figured out how to deal with it?

**Comment by carera** [comment]
Nah, left the project. Sorry.
