### ISSUE TITLE
ArrowKeyStepper seems to not work with List from 9.19.0 onwards

### ISSUE THREAD

**Issue by unkleho** [bvaughn/react-virtualized#1363]
Hi, been playing around with this library and enjoying it a lot.

I think there is an issue from version 9.19.0 onwards with ArrowKeyStepper:
https://codesandbox.io/s/j3y8jq63yw

The keyboard up and down arrows don't work on the List.

Here is the same code using 9.18.5:
https://codesandbox.io/s/jzq6joxn33

The keyboard up and down arrows work nicely.

|-------------------|----------|
| React             | 16.8.6         |
| React DOM         | 16.8.6         |
| react-virtualized | 9.19.0         |

Had a quick look in the commits for 9.19 in ArrowKeyStepper, but this was all I found:
https://github.com/bvaughn/react-virtualized/compare/9.19.0...master#diff-1b8d904622e4dbc4a8978578ecd8f2baL7

Any help here would be great. Will need to use 9.18.5 for now.
Thanks

**Comment by Shemlevy** [comment]
any new with that?

**Comment by sangdth** [comment]
It does not work on my project as well. The `scrollToRow` and `scrollToColumn` always 0.

react-virtualize: 9.20.1
react: 16.8.3

**Comment by RyanZhu1024** [comment]
https://github.com/bvaughn/react-virtualized/blob/9913953d5ebfd2caedadefea2f3b53978b6eb567/source/ArrowKeyStepper/ArrowKeyStepper.js#L67

this is where the issue locates.
When you scroll, it changes the `scrollToRow` in the state but it reset the value from prop.

**Comment by codechef97** [comment]
any update here?

**Comment by luka00001** [comment]
Is this fixed in the later versions or still open?
