### ISSUE TITLE
recomputeRowHeights function not working with material-ui expansion panel component

### ISSUE THREAD

**Issue by shyam-singh-zz** [bvaughn/react-virtualized#1365]
I am trying to utilize recomputeRowHeights along with clear when the expansion panel is expanded or collapsed but after expansion, the expanded content is coming on top of other rows. Here's my handleChange method:

`handleChange = index => (event, expanded) => {
    if (expanded) {
        this._cache.clear(index);
        window.self.listEl.recomputeRowHeights(index);
    } else {
        this._cache.clearAll();
        window.self.listEl.recomputeRowHeights();
    }
}`

If anyone has any feasible solution, kindly suggest.

**Comment by nichoriverae** [comment]
+1 we were able to have the expansion panel expand correctly after setting a timeout on the handleChange function but none of the panels would collapse correctly and obviously setTimeout is not ideal (read: doesn't render the transition phase). Our solution at the moment is to not use the expansion panel. We would love to see these two libraries play nicely together.

**Comment by jonasumland** [comment]
For me the Material-UI Expansion Panel works, if I disable all Transitions:
```
const styles = {
    disableTransition: {
        transition: "none",
    }
};
```
I used `withStyles` from `@material-ui/core/styles` to inject the style-classes to my component. 

```render() {  
    const { classes } = this.props;
    return (
        <ExpansionPanel 
            expanded={this.props.expanded}
            className={classes.disableTransition} 
            CollapseProps={{ 
                unmountOnExit: true, 
                classes: { container: classes.disableTransition } 
            }} 
            onChange={this.toggleExpanded}
        >
            <ExpansionPanelSummary 
                classes={ {content: classes.disableTransition, expandIcon: classes.disableTransition}} 
                className={classes.disableTransition} 
                expandIcon={<ExpandMoreIcon />}>
                <Typography>Index: {this.props.index} value: {this.props.value}</Typography>
            </ExpansionPanelSummary>
            <ExpansionPanelDetails className={classes.disableTransition}>
                <div style={{height:'100px', backgroundColor:'red'}}>
                    Expanded
                </div>
            </ExpansionPanelDetails>
        </ExpansionPanel>
    );
  }
```
I don't know if it's really necessary to disable all transitions. 
The downside of this is that obviously you loose all the animations...

**Comment by shyam-singh** [comment]
@jonasumland I will give it a try and see if it fits my use-case. Thanks for the suggestion and code snippet.
