### ISSUE TITLE
WindowScroller + Table. Blank spaces

### ISSUE THREAD

**Issue by DeylEnergy** [bvaughn/react-virtualized#1370]
Hello. First of all, thank you guys for your hard work. Really appreciate it. I guess the behavior is a bug.

### What is the current behavior?
[![table-windowscroller.gif](https://s3.gifyu.com/images/table-windowscroller.gif)](https://gifyu.com/image/9kKU)
When turning the mouse's wheel there are blank spaces for a second. I suppose it's due to 10 columns. It doesn't matter how many **rows** were provided to the table.
Sandbox: https://codesandbox.io/s/xlq5862m2w

### What is the expected behavior?
It should be smooth like in examples :)

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |  Version 73.0.3683.86 (Official Build) Arch Linux (64-bit)        |
| OS                |     Arch Linux (64-bit)     |
| React             |    16.9.0      |
| React DOM         |   16.9.0      |
| react-virtualized |    10.0.0      |

**Comment by XSmarter** [comment]
me too

**Comment by XSmarter** [comment]
Ask, do you have a solution?
