### ISSUE TITLE
Scrolling issue on 1M records

### ISSUE THREAD

**Issue by expertup** [bvaughn/react-virtualized#1372]
https://5zm1ypyo8n.codesandbox.io/

I want use react-virtualized for render big table. I will get partial data (by 1000 records) dynamically form server and save to array. In example I rendering 1 milions records.

I found 2 issues:
1.
When I try scroll table by clicking on them middle clicking (roll in mouse), on first records clicking is working. But when I scroll page on half height, middle clicking doesn't work properly and I can't scroll page.
![2019-05-07-19-36-46](https://user-images.githubusercontent.com/1708687/57320529-6978b300-70ff-11e9-8089-5a6a49261563.gif)

2.
When I try scroll table by one jump roll on thousands rows, scrolls to much records (example for 1M rows):
![2019-05-07-19-52-31](https://user-images.githubusercontent.com/1708687/57321416-929a4300-7101-11e9-9730-29530d0bf296.gif)

On smaller amount rows (1000 rows) scrolling works correctly:
![2019-05-07-19-55-07](https://user-images.githubusercontent.com/1708687/57321578-edcc3580-7101-11e9-9c5f-b78087f50256.gif)

On mobile (touch) is similar problem:
1M records:
![2019-05-07-20-00-05](https://user-images.githubusercontent.com/1708687/57321918-a09c9380-7102-11e9-926f-1f409825354c.gif)

1000 rows:
![2019-05-07-19-57-28](https://user-images.githubusercontent.com/1708687/57321951-b611bd80-7102-11e9-8d75-3b76d73520a0.gif)

EDIT 16.05.2019:
Update for 1st point:
I found that scroll middle click (mean click middle mouse and move cursor up/down) on 1M~ rows, in half scrolls list is only on Chrome and chrome engine. On Firefox work correctly. This issue in browser, not in script React-Virtual
https://stackoverflow.com/questions/56152363/scroll-page-by-roll-click-on-very-hight-page-not-working-correctly

But now I haven't resolved 2nd point - jumping too much row on one roll mouse scroll.

**Comment by hieuhlc** [comment]
I'm also having this issue with ~1M records. Scrolling seems too fast compared with under 1000 records

**Comment by hieuhlc** [comment]
This is my profiling result 

[Profile-20190516T111304.json.zip](https://github.com/bvaughn/react-virtualized/files/3185366/Profile-20190516T111304.json.zip)

Sometimes the Event (scroll) handler took too much time the browser triggered a warning. This maybe a clue but I don't know how to further investigate.

<img width="1096" alt="Screen Shot 2019-05-16 at 11 15 59" src="https://user-images.githubusercontent.com/4828178/57826099-fd1b4500-77cb-11e9-9858-32fe62f29a7f.png">

**Comment by expertup** [comment]
> This is my profiling result
> 
> [Profile-20190516T111304.json.zip](https://github.com/bvaughn/react-virtualized/files/3185366/Profile-20190516T111304.json.zip)
> 
> Sometimes the Event (scroll) handler took too much time the browser triggered a warning. This maybe a clue but I don't know how to further investigate.
> 
> <img alt="Screen Shot 2019-05-16 at 11 15 59" width="1096" src="https://user-images.githubusercontent.com/4828178/57826099-fd1b4500-77cb-11e9-9858-32fe62f29a7f.png">

Can You Show Yours code? I think about React-virtualized component and renderCell function?

**Comment by hieuhlc** [comment]
@expertup unfortunately I can't show my code because it belongs to my company. I can tell you my cellRenderer function is pretty basic, with 2 conditional returns and 1 onClick event.
