### ISSUE TITLE
Babel Runtime and corejs conflicts with babel 7+ versions

### ISSUE THREAD

**Issue by gaetan-puleo** [bvaughn/react-virtualized#1373]
Hello I have @babel/runtime installed as a dev dependency and in react-virtualized I can see that babel-runtime is used as a normal dependency.

I have a conflict between my version and yours.

**Comment by gunn4r** [comment]
Curious why you closed this @gaetan-puleo.  I am trying to upgrade my repo to latest babel 7.4.x using corejs 3 and it seems react-virtualized version of babel-runtime is causing issues for me. Did you find a solution that worked well?

**Comment by gaetan-puleo** [comment]
@gunn4r I reopen it.

I fixed this issue by installing core-js as peer dependencies in my package.json

```
  "peerDependencies": {
    "core-js": "2.6.5"
  }

```

**Comment by csvan** [comment]
We are having issues with this as well when it comes to upgrading to corejs 3 - it inevitably breaks react-virtualized. 

Babel 6 has been obsolete for a long time now. It would benefit this project and community at large if  an upgrade was made.

**Comment by csvan** [comment]
@gunn4r sadly that is not a solution. Core-js 2 is deprecated and tightly bound to the old way of doing things in Babel 6. People using Babel 7.4+ and core-js will not be able to integrate react-virtualized due to it.

**Comment by gaetan-puleo** [comment]
> > @gunn4r I reopen it.
> > I fixed this issue by installing core-js as peer dependencies in my package.json
> > ```
> >   "peerDependencies": {
> >     "core-js": "2.6.5"
> >   }
> > ```
> 
> Sadly that is not a solution. Core-js 2 is deprecated and tightly bound to the old way of doing things in Babel 6. People using Babel 7.4+ and core-js 3 will not be able to integrate react-virtualized due to it.

Yes I know, the contributors need to update the babel version and corejs.

Maybe I can help if needed. 

I will try to do a PR this week end if I have the time.

**Comment by jonasantonelli** [comment]
I had the same problem with the latest version of **core-js@3.1.4**
But it worked when I downgraded to version **core-js@2.6.5**

**Comment by gunn4r** [comment]
I can open a PR for this sometime this week if no one else gets to it first.

**Comment by jseminck** [comment]
Is there any way to have a build of react-virtualized without core-js included?

**Comment by betalb** [comment]
The common approach seems to be to ship `esnext` version of code. In case of react-virtualized original source can be used with flow annotations removed (if any)

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4
