### ISSUE TITLE
Infinite loop in v9.21.1

### ISSUE THREAD

**Issue by alxbradley** [bvaughn/react-virtualized#1375]
### Bug:
We're running into an infinite loop when a column has 0 width. The browser becomes unusable.

After digging a bit deeper I found that the it's related to the following PR:
https://github.com/bvaughn/react-virtualized/pull/1312

@trxcllnt  @wuweiweiwu

In the following line `nearestCellIndex` is always greater than `this._lastMeasuredIndex`:
https://github.com/trxcllnt/react-virtualized/blob/8fcc7031cbde72495e5fe3415e54c974b8d29880/source/Grid/utils/CellSizeAndPositionManager.js#L248

It seems that the problem is inside of the **linear-vector-layout** library function `indexOfInternal` or the handling of it's return index.

![react-virtualized-infinite-loop](https://user-images.githubusercontent.com/2887652/57955276-46da5d00-78aa-11e9-8704-4585e0681a77.gif)

### Bug seen in the following environment:
|                   |          |
|-------------------|----------|
| Browser           |     Chrome, Firefox     |
| OS                |     Windows    |
| React             |     16.6.3     |
| React DOM         |     16.6.3     |
| react-virtualized |     9.21.1     |

### Our Fix
Revert react-virtualized back to 9.21.0

**Comment by trxcllnt** [comment]
ooh yikes, my apologies @alxbradley. @wuweiweiwu do you think we could revert my PR until I have time to finish cleaning the library up and adding more tests? I'm about two thirds of the way done, but I'm slammed with other stuff at the moment.

**Comment by wuweiweiwu** [comment]
@trxcllnt @alxbradley will update thread when done

**Comment by trxcllnt** [comment]
@wuweiweiwu alternatively, I could add guards to disallow 0-sized elements for now.
