### ISSUE TITLE
Disable yellow focus outline

### ISSUE THREAD

**Issue by L3mmAa** [bvaughn/react-virtualized#1379]
How can i disable or change the outline that shows when i focus a table?
It looks like this:
![grafik](https://user-images.githubusercontent.com/36741683/58476504-326f4d80-8151-11e9-8839-aea924cd9e12.png)
Can i get rid of this outline, or can i change the color?

**Comment by DaanVandenBosch** [comment]
The following css removes the outline on chrome and related browsers:
```
.ReactVirtualized__Grid {
    outline: none;
}
```

You can also use outline to set a different width and color. The reason this outline appears is because the element has a tabindex attribute.
