### ISSUE TITLE
FlexTable: provide event to onRowClick

### ISSUE THREAD

**Issue by Guria** [bvaughn/react-virtualized#138]
I have a `FlexTable` with custom renderer on one of the `FlexColumn` which returns a Link.
I need a way to avoid running `onRowClick` callback when cell with Link was clicked.
My suggestion is to provide event as second argument.

**Comment by bvaughn** [comment]
I don't understand why that would be necessary. If your custom cell render wants to trap the click event, why not just trap it there?

```js
function yourCustomCellClickHandler (event) {
  event.stopPropagation()
  // Do whatever you do
}
```

**Comment by bvaughn** [comment]
Closing as a no-op.

**Comment by Guria** [comment]
@bvaughn tried your suggestion and it doesn't work for me because it breaks my Link component making SPA to hit the server and reload. Also it adds an extra div. Moreover, providing event just seems pretty natural for on*Click callbacks.

**Comment by bvaughn** [comment]
There's no reason to provide a click event to the `onRowClicked` callback so you can trap the click inside of a cell. You have the ability to trap the click inside of a cell as I mentioned above. I don't know what you mean by:

> it breaks my Link component making SPA to hit the server and reload

Wrapping your `Link` in a div that stops the event from bubbling should _not_ have any effect on your `Link` component unless you have your `Link` component misconfigured somehow (for example, by setting `target='_blank'` in your `Link` component which [causes it to be handled differently](https://github.com/reactjs/react-router/blob/master/modules/Link.js#L85)).

**Comment by cyberxndr** [comment]
Need to notice that the div from the example should be replaced with a span to avoid onclick dead zones (such as div is a block element). 
```javascript
cellRenderer={
  (cellData, cellDataKey, rowData, rowIndex, columnData) => (
    <span onClick={(event) => event.stopPropagation()}>
      <Link to='...'>Title</Link>
    </span>
  )
}
```

**Comment by bvaughn** [comment]
Nice catch, @cyberxndr.
