### ISSUE TITLE
Column cellRenderer is missing isVisible prop

### ISSUE THREAD

**Issue by brumm** [bvaughn/react-virtualized#1388]
Hey folks,

I'm in the process of doing some performance improvements in our app around image loading in a Table component during scrolling.

For this I'd like to use both `isScrolling` and `isVisible`. I assumed `isVisible` would be available to the Column's `cellRenderer`, but it's not passed on.

Is this intentional? If not, I'd like to create a PR to pass on this prop.

**Comment by paulhan221** [comment]
any update on this?
