### ISSUE TITLE
HOC as a functions (and optionally as decorators too)

### ISSUE THREAD

**Issue by Guria** [bvaughn/react-virtualized#139]
```js
import { AutoSizerDecorator, AutoSizerHoc, VirtualScroll } from 'react-virtualized'

@AutoSizerDecorator({ disableHeight: true }) // or AutoSizerDecorator({ disableHeight: true })(MyComponent)
class MyComponent extend React.Component {
  render () {
    var { width, onResize } = this.props
    /**/
  }
}

var ASVirtualScroll = AutoSizerHoc({ disableHeight: true }, VirtualScroll) // or just `AutoSizerHoc(VirtualScroll)`
```

**Comment by bvaughn** [comment]
This would kind of defeat the design change in version 5.0 that supports nested, composable HOCs (as shown [here](https://github.com/bvaughn/react-virtualized/blob/master/docs/usingAutoSizer.md#using-autosizer-with-infiniteloader)). A function/decorator/component that injects width/height properties can't be composed with other similar functions. (How would you use both an AutoSizerDecorator and a ScrollSyncDecorator? or any other combination?)

**Comment by bvaughn** [comment]
Closing this issue because I think it re-introduces too many constraints to be worth the effort. You could put together a HOC that wraps the existing `AutoSizer` though if you'd like for your personal projects. Probably shouldn't be too hard.
