### ISSUE TITLE
registerChild prop is missing from WindowScroller

### ISSUE THREAD

**Issue by vargajacint** [bvaughn/react-virtualized#1392]
Hi, i think it's enough for reporting the problem because it is valid.
I'm using:
- @types/react-virtualized: "^9.21.2"
- react-virtualized: "^9.21.1",

> Property 'registerChild' does not exist on type 'WindowScrollerChildProps'

https://pastebin.com/embed_js/UF3z8gps

@bvaughn

**Comment by mateja176** [comment]
I've come across the same issue while working with the WIndowScroller [example](https://github.com/bvaughn/react-virtualized/blob/master/source/WindowScroller/WindowScroller.example.js)

However, `registerChild` is not missing but rather does not exist on `WindowScrollerProps` ( please update the title ). My guess is that the prop has been deprecated in favor of *insert answer*.

**Comment by vargajacint** [comment]
I talked with a contributor and he told to me make a PR and we will fix. I haven't time, but if you have just make a PR.

(Sorry for the linguistic errors).

**Comment by alexandrzavalii** [comment]
Same here :( had to use the old version
