### ISSUE TITLE
Custom header for FlexTable?

### ISSUE THREAD

**Issue by cheahkhing** [bvaughn/react-virtualized#140]
Hi, is it possible to support customer header for FlexTable? I would like to add a filter textbox inside the header for each column. How can I do that?

**Comment by bvaughn** [comment]
Seems like a reasonable request. I'll need to give it a little thought in order to make sure not to break (or complicate) sortable header logic. But I think adding custom header support shouldn't be too hard.

**Comment by bvaughn** [comment]
This feature has been released with version 5.4.0.

Read about it [here](https://github.com/bvaughn/react-virtualized/blob/master/docs/FlexColumn.md#headerrenderer). See a demo [here](https://bvaughn.github.io/react-virtualized/?component=FlexTable) (the middle cell).
