### ISSUE TITLE
ScrollToIndex mades the virtualizated list gets stucked

### ISSUE THREAD

**Issue by Alkaendra** [bvaughn/react-virtualized#1410]
I'm using react-virtualized List to show a dynamic list of complex elements. I've implemented a ctrl+f search like component, that with up and down arrows changes de the row index I'm passing to scrollToIndex. If I scroll after that, the virtualization gets stucked and stops to work. Only the actual block of virtualized rows are rendered, if you scroll the rest goes blank.

After some checks, I think that scrollToIndex param is provoking that undesired beheaviour, but I need to force the virtualization to move to the row where the match is.

**Comment by ahmadmshatat** [comment]
I faced the same problem, I solved it by trick by reset the scrollToIndex to undefined

**Comment by lstrive-yn** [comment]
> I faced the same problem, I solved it by trick by reset the scrollToIndex to undefined

thanks so much; this answer help me resolve the problem that when I use it in dynamic chat component but I want to stop 'scrollIntoIndex' when scroll....
