### ISSUE TITLE
problem when use scrollToIndex in ios (chrome and safari)

### ISSUE THREAD

**Issue by ahmadmshatat** [bvaughn/react-virtualized#1416]
I used react virtualized to render List of products the code:

` rowRenderer({ index, key, style }) {
    indexPosition = index;
    const arrayOfProducts = [];
    const fromIndex = index * itemsPerRow;
    const toIndex = Math.min(fromIndex + itemsPerRow, this.props.products.length);
    for (let i = fromIndex; i < toIndex; i++) {
      const product = this.props.products.find(product => product.id === this.props.products[i].id);
      arrayOfProducts.push(
        <ProductCard
          product={product}
          key={product.id}
          setProductLike={this.props.setProductLike}
        />,
      );
    }
    return (
      <div key={key} style={style}>
        {arrayOfProducts}
      </div>
);
  }`

` <InfiniteLoader
            isRowLoaded={this.isRowLoaded}
            loadMoreRows={this.loadMoreRows}
            rowCount={this.props.products.length}
            minimumBatchSize={4}
          >
            {({ onRowsRendered }) => (
              <WindowScroller
                ref={this._setRef}
                scrollElement={window}
              >
                {({
 height, isScrolling, registerChild, onChildScroll, scrollTop,
}) => {
                    const scrollIndex = this.props.infinitScroll.currentScrollYPositions[this.props.name];
  return (
    <AutoSizer disableHeight>
      {({ width }) => {
                      itemsPerRow = 2;
                      let rowCount = Math.ceil(this.props.products.length / 2);
                      if (width > 700) {
                        itemsPerRow = 3;
                        rowHeight = 362;
                        rowCount = Math.ceil(this.props.products.length / 3);
                      }

                      return (
                        <div ref={registerChild}>
                          <List
                            autoHeight
                            height={height}
                            onScroll={onChildScroll}
                            onRowsRendered={onRowsRendered}
                            ref={(el) => {
                              window.listEl = el;
                            }}
                            className="list_react_vr"
                            overscanRowCount={2}
                            rowCount={rowCount}
                            rowHeight={rowHeight}
                            rowRenderer={this.rowRenderer}
                            width={width}
                            isScrolling={isScrolling}
                            scrollTop={scrollTop}
                            style={{ outline: 'none', '&>div': { display: 'flex', justifyContent: 'space-around' } }}
                            scrollToAlignment="start"
                            isRowLoaded={this.isRowLoaded}
                            scrollToIndex={scrollIndex}
                          />
                        </div>
);
                      }}
    </AutoSizer>
                );
 }
                }
              </WindowScroller>
            )}
          </InfiniteLoader>
`
### What is the current behavior?
when scrolling the cards to bottom and then click on any product
then go back to the last page 
expected: show the same products in the same position i leave, it's work in any OS expect IOS system
actual: the cards continue re-rendering as the video i attached.
this video show the problem from second 32
[https://www.youtube.com/watch?v=4E7HcYhYL-Q](url)
 
### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?

|                   |          |
|-------------------|----------|
| Browser           |    Chrome and safari      |
| OS                |      IOS    |
| React             |    16.8.6      |
| React DOM         |    16.8.6      |
| react-virtualized |       9.21.1   |

**Comment by tommymarshall** [comment]
We are running into this issue as well.
