### ISSUE TITLE
ArrowKeyStepper stop working after certain rows with react-virtualized table

### ISSUE THREAD

**Issue by anuj-webdev** [bvaughn/react-virtualized#1425]
### Use case
I am using react-virtualized table, and I have implemented Arrow key support using `ArrowKeyStepper` HOC, but it's not working properly after visiting certain rows in the table.

### Reporting a Bug? 
Yes

### What is the current behavior?
Currently, arrow key stops working on the react-virtualized table after going to a certain number of records either go up or down doesn't matter. In my view, this number of rows is the number which react-virtualized table feed for window size. That's why it will stop working on visiting more number of rows if I increase the height of the table so that window size got increased.

Initially, l suspect that this issue is because of ArrowKeyStepper HOC so I have tried just using regular JS keyboard events for this functionality but I have seen similar behaviour.
Here is the code for that behaviour
Using ArrowKeyStepper HOC
https://codesandbox.io/s/react-virtualized-table-with-arrowkeystepper-7v82v
Without using ArrowKeyStepper HOC
https://codesandbox.io/s/react-virtualized-table-with-arrow-key-events-vxlto

### What is the expected behavior?
It should go smoothly up and down on pressing respective keyboard arrow keys.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           | Chrome, Firefox         |
| OS                |   window10, ubuntu 18       |
| React             |   v16.4       |
| React DOM         |      v16.4     |
| react-virtualized |     v9.21     |

**Comment by JoshClose** [comment]
I'm running into this issue too. It seems to work fine with Grid, but not Table.

**Comment by jofrere** [comment]
Hi guys, I faced the same issue.
Have you tried this?

https://github.com/bvaughn/react-virtualized/issues/776
