### ISSUE TITLE
Difficulty in making react-select group header sticky with react-visrtualized List

### ISSUE THREAD

**Issue by Lekha30** [bvaughn/react-virtualized#1432]
I am using react-select for my project and Virtualized list to render the options. When doing so, I also group the options using react-select's Group component. Now that's all working, I want to set the group header sticky as I scroll down the select. I tried making use of the css to work this out, but isn't working due to react-virtualized list.

Is there any way as to make the group headers sticky ?
|                   |          |
|-------------------|----------|
| Browser           |    Chrome      |
| OS                |     Windows     |
| React             |      16.9.0    |
| React DOM         |     16.9.0     |
| react-virtualized |       9.21.0   |

**Comment by Ethorsen** [comment]
Did you find a solution?  I'm also looking into this and can't find a proper solution for react-virtualized.

I did find another library that seems to do this
https://github.com/marchaos/react-virtualized-sticky-tree

But I would rather not import another library just for this functionality

**Comment by yuzhva** [comment]
Looks like the `List` does not support the possibility to make a header fixed.

For the case when the Fixed header is required it's better to use `Table` or `Grid` components.
