### ISSUE TITLE
[Example request] React Portals

### ISSUE THREAD

**Issue by bogdancss** [bvaughn/react-virtualized#1443]
I am trying to render a `react-select` dropdown attached to each row in the table and initially hit the overscroll issue. Since then I've been trying to get this to work with React Portals, but I am unable to attach the portal to the individual cell in the row.

I would appreciate an example with React Portals.

**Comment by daniel-haim** [comment]
Hi @bogdancss ! Do you find an solution ? i have the same issue too

**Comment by bogdancss** [comment]
Hey @daniel-haim, unfortunately, I did not, so I had to fall back on the native select.
