### ISSUE TITLE
Get rid of dom-helpers dependency

### ISSUE THREAD

**Issue by ArtemZag** [bvaughn/react-virtualized#1458]
The last version of react-virtualized has dependency 
    "dom-helpers": "^2.4.0 || ^3.0.0",
But the last version of dom-helpers is 5.1.3.
My suggestion is to remove this dependency at all. You can simply copy the only required function (**scrollbarSize**) into your code.

**Comment by gsbelarus** [comment]
That is why I have to roll back to version 9.21.0. Our library which uses `react-virtualized` compiles well, but every project which uses this library now fails at webpack compilation stage with error message: 
> Module not found: Error: Can't resolve 'dom-helpers/util/scrollbarSize'
The message stands even after you add `dom-helpers` to projects `package.json` file.

**Comment by ArtemZag** [comment]
@gsbelarus , looks like it has been fixed in the last version. 9.21.2. So, closing the issue.

**Comment by gsbelarus** [comment]
I have this problem exactly with 9.21.2 and rolled back to 9.21.0.

**Comment by ArtemZag** [comment]
@gsbelarus , I see. So, for you the problem appeared because you had other package referencing old version of dom-helpers. In my case it was vice-versa - 9.21.2 solved my problem because now all my packages depend on the newest version of dom-helpers. Maybe you should better upgrade other packages which depend on older version of "dom-helpers" ? (if it's possible)

**Comment by gsbelarus** [comment]
We have a big mono repository maintained with lerna. All projects are updated to latest dependencies. With 9.21.2 we get an error during webpack compilation of a project which uses our library, which, in its turn, uses react-virtualized. The library itself compiles fine.

**Comment by gsbelarus** [comment]
Anyway, `dom-helpers` not so tiny as its name stands:

https://bundlephobia.com/result?p=dom-helpers@3.4.0

So, I would definitely recommend to get rid of it and just inline that single function.

**Comment by wuweiweiwu** [comment]
I see will update!

**Comment by wuweiweiwu** [comment]
hi! @gsbelarus as we are only using `dom-helpers` via import paths like `dom-helpers/scrollbarSize` the bundle size impact is trivial.

I can see from your error message that it is importing dom helpers from `dom-helpers/util/scrollbarSize` this should not be the case in the latest release of react-virtualized

**Comment by wuweiweiwu** [comment]
PR that upgraded https://github.com/bvaughn/react-virtualized/pull/1421
