### ISSUE TITLE
Who is using react-virtualized

### ISSUE THREAD

**Issue by jgoux** [bvaughn/react-virtualized#146]
Hi,

I'm looking for a library providing an autocomplete/select element with virtual-scrolling.

So far I couldn't find one, so maybe we could ask around who is using react-virtualized and create a list from the answers? :tada: 

Thanks for this great lib! :+1:

**Comment by bvaughn** [comment]
Thanks @jgoux. :)

I'm a little unclear on what the action-item is for this issue. Are you looking for a type-ahead component built on top of react-virtualized? Or are you just curious who is using this library so far? (I am also curious.)

I've created a type-ahead component using react-virtualized and [redux-search](https://github.com/treasure-data/redux-search) (a library that myself and a colleague released a couple of months ago) but I haven't considered open-sourcing it before.

**Comment by jgoux** [comment]
Basically, I'm looking for this component : https://material.angularjs.org/latest/demo/autocomplete (material design themed) but using React. :smiley_cat: 

I also think virtual-scrolling should be the default when using tabular/list components, so your library seems to be the best choice I've seen.

I tried react-select, material-ui's SelectField/Autocomplete, react-toolbox's Autocomplete but no one is using virtual-scrolling.

Finally, I'm also curious to see which components are built with this library. :mag:

**Comment by bvaughn** [comment]
Ah, thanks for clarifying. :) I too am curious which components have been built so far with react-virtualized. I've heard of a couple of pretty cool things. I'd love to compile a list somewhere but I'm not sure how best to do that.

Have you considered filing a feature request against JedWatson/react-select or one of the other libraries to integrate with react-virtualized? I'd be happy to help on my end if the library owner was interested. react-virtualized offers a lot of useful features beyond just basic windowing (like scroll-to-item, keyboard navigation, etc.) that the libraries might find convenient.

**Comment by jgoux** [comment]
The list could be shown either in a wiki page or in a specific section in the https://bvaughn.github.io/react-virtualized/ website ?

For the react-select / material-ui components, the idea of virtual-scrolling has been introduced in these issues : 
- https://github.com/callemall/material-ui/issues/2787#issuecomment-185340138
- https://github.com/JedWatson/react-select/issues/771 (there is a PR for this one)

**Comment by bvaughn** [comment]
Oh neat. I hadn't realized that such issues had been opened already :)

Yeah, displaying the list of users / uses wouldn't be the problem. I'd be happy to showcase them. I meant more that I'm uncertain how to gather such a list. :)

**Comment by jgoux** [comment]
Sorry for the misunderstanding!

I think making an issue + pinging members of the community with a lot of followers on Twitter to diffuse the info is a good start. :star2:

**Comment by bvaughn** [comment]
Sure. Let me close this issue then and create a new one (#147). (Clean slate.) I'll try to reach out on Twitter although I don't have much of a following. We'll see :)
