### ISSUE TITLE
Firefox warning 'Will-change memory consumption is too high' from Grid component

### ISSUE THREAD

**Issue by ewu02** [bvaughn/react-virtualized#1470]
Is the `will-change: transform` property still needed in https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L991 ? It's causing Firefox to print the warning 'Will-change memory consumption is too high' in console when used in a resource-intensive app.

From CHANGELOG (https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#553):  ''Added will-change property to Grid to work around a Chrome bug(?) that caused the entire grid to be repainted whenever a new row or column was added. This was negatively impacting scrolling performance for Chrome under certain conditions. This change is not expected to impact Firefox, Safari, or IE.' 

That was introduced back in early 2016. No noticeable scrolling performance was affected when I removed the property and tested in recent Chrome (Mac Chrome 79.0.3945)

Issue was produced on Firefox 70.0, Mac OS 10.14

**Comment by xaverric** [comment]
Also simulated the issue on Fedora with Firefox 70 (64bit).

Check the following article
https://www.maxlaumeister.com/articles/css-will-change-property-a-performance-case-study/
