### ISSUE TITLE
In Multigrid, Scrolling is not synced.

### ISSUE THREAD

**Issue by Sumit2105** [bvaughn/react-virtualized#1473]
In React virtualized multigrid, If we have the fixedRowCount as 0 and fixedColumnCount as N. If we scroll the left grid, The right grid is not synced.

In order to replicate this issue:
Take this example: https://bvaughn.github.io/react-virtualized/#/components/MultiGrid
Change the fixedRowCount to 0

**Comment by matheusroversi** [comment]
Hi, were you able to solve this problem?

**Comment by kendraodrunia** [comment]
I noticed a similar problem. I am using MultiGrid and CellMeasurer. When I scroll horizontally the rows are misaligned. 

https://user-images.githubusercontent.com/69160899/125359246-dd85f580-e31e-11eb-8581-469b2cdbbdf2.mov

(Chrome on the left, Safari on the right)

**Comment by taranek** [comment]
@bvaughn Do you know why it was marked as `stale`? Seems like a valid issue to me
