### ISSUE TITLE
Is it possible to have the last row of the table fixed?

### ISSUE THREAD

**Issue by VigneshSubramaniam** [bvaughn/react-virtualized#1479]
Hi @bvaughn  , I'm loving this Table and it provides almost all the required features. 
Two quick questions though. 
1. Is it possible to have a footer or something of that sort? Let's say i have 1000 rows and the last row is total. I want that to be displayed always. 
2. Is there any way to freeze the right columns as we do on the left? 
Any help would be appreciated. Thanks!

**Comment by truongnm97** [comment]
I ran into the same situation, Is there any solution yet?

**Comment by MarvanN** [comment]
same issue here, is there any solution for this

**Comment by rpetryshyn** [comment]
Same issue
Do we have a solution?
