### ISSUE TITLE
AutoSizer: widths or heights become 0 sometimes, especially when switching Chome Dev Tools on/off

### ISSUE THREAD

**Issue by derwaldgeist** [bvaughn/react-virtualized#1484]
Firs off, thanks for this library. In general, it works pretty well.

When we combined it with https://github.com/urbica/react-map-gl, we noticed that sometimes the map is not displayed correctly after changing the window size. In particular, this happened when toggling Chrome's dev tools on and off.

When trying to find the root cause, we found out that AutoSizer sometimes reports width and/or height as being 0, even if the window size is way different from that (this also happens when resizing the window using the window handles).

Right after providing the incorrect 0 values, the values snap back to the correct sizes in a second run of the closure function. But unfortunately,  https://github.com/urbica/react-map-gl, doesn't handle these frequent changes very well and gets stuck to the wrong values sometimes.

Is there any way to fix this behavior of AutoSizer?

**Comment by zhangjizhe** [comment]
new CellMeasurerCache()  set minHeight

**Comment by derwaldgeist** [comment]
Thanks for the info. But how can I apply this?

**Comment by zhangjizhe** [comment]
> Thanks for the info. But how can I apply this? 
`
const cache = new CellMeasurerCache({ defaultHeight: 28, fixedWidth: true,minHeight: 46, });
`

**Comment by zhangjizhe** [comment]
> Thanks for the info. But how can I apply this?

this minHeight
