### ISSUE TITLE
Windowscroller component doesn't work with scrollToIndex anymore.

### ISSUE THREAD

**Issue by pyaesone17** [bvaughn/react-virtualized#1498]
Reporting a Bug?

https://codesandbox.io/s/react-window-with-windowscroller-bk1ze

### What is the current behavior?

Windowscroller component doesn't work with scrollToIndex anymore. 

### What is the expected behavior?

Should be able to work like the example.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |      Chrome    |
| OS                |     Mac OS     |
| React             |       16.12.0   |
| React DOM         |      16.12.0    |
| react-virtualized |     9.20.0     |

**Comment by alitoiu** [comment]
Similarly, 

https://codesandbox.io/s/tender-meadow-moj5o 

works with the older dependencies in the sandbox, but stops working when upgrading them to 

react-dom: 16.13.1
react-virtualized: 9.21.2
on Firefox, Mac OS.

**Comment by c5inco** [comment]
I'm on react 16.4 and it breaks there when using 9.21.2.

My current project config is ☝️

**Comment by 189** [comment]
> Similarly,
> 
> https://codesandbox.io/s/p2w7jz04kj
> 
> works with the older dependencies in the sandbox, but stops working when upgrading them to
> 
> react-dom: 16.13.1
> react-virtualized: 9.21.2
> on Firefox, Mac OS.

https://codesandbox.io/s/gracious-mahavira-e48iy?file=/src/Hello.js
![image](https://user-images.githubusercontent.com/3614829/87937703-c6c01080-cac7-11ea-963e-ca2bb715855c.png)
react-virtual@9.20 broken. but react-virtual@9.19 works well.
