### ISSUE TITLE
Multiple mouseOver/mouseLeave events firing on scroll in Grid

### ISSUE THREAD

**Issue by amitgupta4078** [bvaughn/react-virtualized#1499]
## Reporting a bug

https://codesandbox.io/s/eager-cherry-5hr4r

### What is the current behavior?

I am using Grid component and rendering a plain div as React component inside each cell through cellRenderer. I have bound mouseover and mouseleave events on my child component. When I scroll the Grid and move my mouse a little near the bottom/top edge of a child component, even though I am inside the container, I see multiple enter and leave events firing. This issue does not happen if I remove React Virtualized from my project.

### What is the expected behavior?
Multiple events should not be fired

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue?
|                   |          |
|-------------------|----------|
| React             |    16.12.0      |
| React DOM         |    16.12.0      |
| react-virtualized |       9.21.2   |

**Comment by michellekphan** [comment]
I am experiencing the same with Table and Column. If I move my mouse in between columns but remain on the same row, mouseleave and mouseover both fire multiple times.

**Comment by yujingxiacai** [comment]
I also encountered same problem
