### ISSUE TITLE
React Virtualized Grid - last row repeats null elements if column count has fixed value

### ISSUE THREAD

**Issue by ashishkhandelwal2003** [bvaughn/react-virtualized#1500]
Hi bvaughn,

I am facing an issue with react virtualized grid over here that it repeats null elements in the last row if column count has a fixed value. For Eg. if column count is fixed to 3 and row count is 8 but if array binded to the grid holds only 22 values then the grid creates extra 2 elements to keep the layout to have 24 elements by adding 2 null values when rendered. Please let me know if there is any fix available already for this.

**Comment by leeminho5927** [comment]
I want to ask you how do you get the value of the array, rowIndex, colmnIndex not to get a certain value
