### ISSUE TITLE
Firefox - Empty rows after scroll and data filtering

### ISSUE THREAD

**Issue by alxbradley** [bvaughn/react-virtualized#1514]
### What is the current behavior?

In Firefox, if you scroll down and then update the table data (by some filter for example), only a subset of the rows will be rendered with blank space in between rows.

Here is the sandbox to reproduce:
https://codesandbox.io/s/react-virtualized-5ukgi

It seems to only happen when the table had scrollbars and after the update it no longer needs scrollbars. i.e. All the rows can fit in view.

![react-virtualized FF issue](https://user-images.githubusercontent.com/2887652/76372154-ba49d100-62f9-11ea-9b95-65b695878272.gif)

### What is the expected behavior?

All filtered rows show display.

I've tried to resolve this by `forceUpdateGrids` on MultiGrid ref, `forceUpdate` on my component after componentDidUpdate, etc... Nothing seems to work. Note: if there are horizontal scrollbars, and I scroll, it will reveal the

Any workaround would be much appreciated. I don't think I'll be able to upgrade at this point. Thanks in advance.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |     Firefox  (latest)   |
| OS                |     Windows     |
| React             |    16.8.6      |
| React DOM         |    16.8.6      |
| react-virtualized |     9.21.0     |

In the sandbox, it works in react-virtualized 9.7.5 and a few other versions above. I haven't been able to pinpoint at which version it breaks. I'll post more info as I go.

**Note:** I did try downgrading in my environment but it was still broken.

### Update
I found that this breaks in Firefox between version `9.18.5 --> 9.19.0` of react-virtualized.

Works: https://codesandbox.io/s/react-virtualized-forked-dcch6
Broken: https://codesandbox.io/s/react-virtualized-forked-n8kks

I'm still trying to debug what caused the issue, but my hunch is that it has to do with the deprecated React lifecycle methods:
https://github.com/bvaughn/react-virtualized/blob/9.19.0/CHANGELOG.md

None of the other commits seem to have any breaking changes.

@wuweiweiwu @bvaughn any ideas?

**Comment by alxbradley** [comment]
A simple workaround was just to change the key on our table container when the data size shrinks.

**Comment by kad3nce** [comment]
@alxbradley, can you expound on that workaround a bit? We're having a similar issue and I'm not sure what you mean in the context of your sandbox code.

**Comment by alxbradley** [comment]
@kad3nce In the sandbox code there's a div wrapper around the AutoSizer component with the class "table-wrapper". What I did was something like the following,

```javascript
componentDidUpdate(prevProps, prevState) {
  if (prevProps.data.length > this.props.data.length) {
    this.setState({
      tableKey: this.state.tableKey + 1  // update the key
    });
  }
}

render() {
  return (
    <div
      key={ 'my-table-' + this.state.tableKey }  // <--- a unique key that changes every time the data size is reduced
      className="table-wrapper"
      style={{ display: "flex", flex: 1 }}
    >
      <AutoSizer>{ ... }
```

The key will force React to re-build the DOM tree, and re-mount the Grid. Hope this helps!

**Comment by kad3nce** [comment]
Got it. Thanks!

**Comment by vidyaramachandran56** [comment]
Will this work for List ??

**Comment by alxbradley** [comment]
I found that this breaks in Firefox between version `9.18.5 --> 9.19.0` of react-virtualized.

Works: https://codesandbox.io/s/react-virtualized-forked-dcch6
Broken: https://codesandbox.io/s/react-virtualized-forked-n8kks

I'm still trying to debug what caused the issue, but my hunch is that it has to do with the deprecated React lifecycle methods:
https://github.com/bvaughn/react-virtualized/blob/9.19.0/CHANGELOG.md

None of the other commits seem to have any breaking changes.

@wuweiweiwu @bvaughn any ideas?

**Comment by alxbradley** [comment]
After playing around some more I found that this isn't an issue in React `v16.2.0`. Some change in React `16.3.0` seems to have caused this issue.
