### ISSUE TITLE
Please publish a new patch to npm

### ISSUE THREAD

**Issue by toddtarsi** [bvaughn/react-virtualized#1517]
I was wondering if we could get a new patch on NPM with this change in:

https://github.com/bvaughn/react-virtualized/commit/dc9e2dd4fb942f8d62cc790912096880b7ce0e2b

This seems like a good compatibility change, but (this is a lame reason I'm sorry) I don't want to change from 9.21.2 to some private fork of it or something like that.

Thanks, and let me know if I can help in any way!

**Comment by alumni** [comment]
+1 just for the dependencies upgrades - we're pulling in a lot of outdated packages together with react-virtualized

**Comment by rosskhanas** [comment]
@bvaughn is there any change to get the latest master published to NPM?

Thank you in advance.

**Comment by rosskhanas** [comment]
A new version was published recently, I guess the issue can be closed.
