### ISSUE TITLE
Unmeasured cells on initial mount of list

### ISSUE THREAD

**Issue by dheerajk30** [bvaughn/react-virtualized#1519]
I am using React Virtualized to window my items list which has the following functionality 1) onClicking on any item, the user will be prompted with a details panel where he will be able to update the details of the item. And when he goes back to the list, he will be able to see the details in the item cell in the list. He can add a lot of details to make it bigger or reduce the size by removing the details

2) He can delete the item, or add another item to the list with certain details or without details.

CellMeasurer serves my requirement as dynamic height is supported. But I am having following issues with it

1) initially when my list mounts for the first time, first few items are measured and shown correctly but as soon as I scroll to the end, items get overlapped with each other.(positining isnt correct, I am guessing the defaultHeight is being applied to the unmeasured cells). This works fine as soon as the list is rerendered again. 2) Also, when I am updating the details of an item the list doesnt update with the new height adjustments

I am sure that somewhere my implementation is incorrect but have spent a lot of time hammering my head for it. Please let me know what can be done here to fix this
```
ItemView = props => {
        const {index, isScrolling, key, style} = props,
            items = this.getFormattedItems()[index]
        return (
            <CellMeasurer
                cache={this._cache}
                columnIndex={0}
                isScrolling={isScrolling}
                key={key}
                rowIndex={index}
                parent={parent}>
                {({measure, registerChild}) => (
                    <div key={key}  style={style} onLoad={measure}>
                        <div
                            onLoad={measure}
                            ref={registerChild}
                            {...parentProps}>
                            <Item
                                onLoad={measure}
                                key={annotation.getId()}
                                {...childProps}
                            />
                        </div>
                    </div>
                )}
            </CellMeasurer>
        )
    }

renderDynamicListOfItems(){
   return (<div>
                <List
                    height={500}
                    ref={listComponent => (_this.listComponent = listComponent)}
                    style={{
                        width: '100%'

                    }}
                    onRowsRendered={()=>{}}
                    width={1000}
                    rowCount={props.items.length}
                    rowHeight={this._cache.rowHeight}
                    rowRenderer={memoize(this.ItemView)}
                    // onScroll={onChildScroll}
                    className={listClassName}
                    overscanRowCount={0}
                />
            </div>
     )
}
```
Also, I am manually triggering the remeasurement of my item in its componentDidUpdate like follows()
```
    Component Item 
    ...
    componentDidUpdate() {
        console.log('loading called for ', this.props.annotation.getId())
        this.props.onLoad()
    }
    ...
```
In the main parent I am recomputing the heights of the list every time the list has updated and triggering a forceupdate as follows
```
Component ParentList
...
    componentDidUpdate() {
        console.log("calling this parent recomputing")
        this.listComponent.recomputeRowHeights()
        this.listComponent.forceUpdateGrid()
    }
...
```

**Comment by JunlinZhu-Tommy** [comment]
Do we have any updates on this?

**Comment by dheerajk30** [comment]
@JunlinZhu-Tommy I had to use cache.clearAll() along with list.forceUpdateGrid() in my list container component's did mount function instead of recompute

**Comment by JunlinZhu-Tommy** [comment]
@dheerajk30 Thanks! I actually found that I messed up `parent` parameter in my rowRender function and everything works after I fixed it.
