### ISSUE TITLE
CSP Security issue: detectElementResize requires unsafe-inline styles-src enabled

### ISSUE THREAD

**Issue by Psvensso** [bvaughn/react-virtualized#1521]
### Do you want to request a *feature* or report a *bug*?
feature and/or bug

### What is the current behavior?
CSP enabled browsers refuses på apply the .resize-triggers style and throws an error in the console: 
"detectElementResize.js:133 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword"

### What is the expected behavior?
For the resize to work without the need of injected styles. 

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
Chrome (I think issue is with all CSP enabled modern browsers)
"react-virtualized": "^9.21.2"

Usure what this function even does, the react-window seems to work fine without it.

**Comment by kyle-johnson** [comment]
For folks searching, you can set the `nonce` on the AutoSizer:
https://github.com/bvaughn/react-virtualized/blob/ff2e15c87ed1f52891682c0764b7c27549aa9cba/docs/usingAutoSizer.md#applying-content-security-policy
