### ISSUE TITLE
Table is rendered incorrectly in Electron

### ISSUE THREAD

**Issue by yaronlevi** [bvaughn/react-virtualized#1524]
Hi (-:

I am trying to draw a basic table using react-virtualized inside an Electron app (created by [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)), but it gets rendered incorrectly.

I've cloned the electron-react-boilerplate, installed react-virtualized, and added some basic code to show a table:
```
import React from 'react';
import { Column, Table } from 'react-virtualized';

const list = [
  { name: 'brian', description: 'dog' },
  { name: 'garfield', description: 'cat' }
];

export default function Home() {
  return (
    <div>
      <Table
        width={500}
        height={500}
        headerHeight={50}
        rowHeight={50}
        rowCount={list.length}
        rowGetter={({ index }) => list[index]}>
        <Column label="Name" dataKey="name" width={200} />
        <Column width={200} label="Description" dataKey="description" />
      </Table>
    </div>
  );
}
```

The resulting table looks like this:

<img width="624" alt="Screen Shot 2020-03-28 at 19 24 05" src="https://user-images.githubusercontent.com/5398977/77827998-26b23600-712a-11ea-82d5-e32f45e54e38.png">

Just to make sure, I've also removed any CSS from the boilerplate that might cause this.

I've created a [repo](https://github.com/yaronlevi/electron-with-react-virtualized) to easily show the bug.

Just clone it, hit "yarn" and then "yarn dev"

Any help on issue would much appreciated 🙏

**Comment by luca-simonetti** [comment]
I know some time has gone by, but I think you're missing this on top:

`import 'react-virtualized/styles.css';`
