### ISSUE TITLE
Semantically correct HTML

### ISSUE THREAD

**Issue by crshmk** [bvaughn/react-virtualized#1525]
We like this tool very much, but we ran into a wall when the accessibility team reviewed our app. That the `ReactVirtualized__Grid__innerScrollContainer` in `Grid.js` is a `div`, rather than a `ul`, that contains `li`s makes it confusing for users on a screen reader. Moreover, a list of `li`s inside a `div` it is not semantically correct html. Could we please change this div 

```jsx 
<div
  className="ReactVirtualized__Grid__innerScrollContainer"
```
in [Grid.js](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js) to a `ul`?

This does presume list items would be a list of `li`s. If developers need the ability to render `div`s or some other element in the renderer, could we make the element type configurable? At the moment we see no way to achieve a semantically correct list, i.e. a `ul` with `li`s as direct children.

**Comment by tavgordon** [comment]
Bump for improved accessibility

**Comment by jbean96** [comment]
Would also like to bump this.

**Comment by RubenZx** [comment]
Any solution for this?
