### ISSUE TITLE
in loadMoreRows why we should use startIndex and stopIndex?

### ISSUE THREAD

**Issue by mahyAlpr18** [bvaughn/react-virtualized#1528]
...

**Comment by maksimf** [comment]
yes

**Comment by JunlinZhu-Tommy** [comment]
It's works like an indicator about if we need to load more rows.
Please check this line of code https://github.com/bvaughn/react-virtualized/blob/master/source/InfiniteLoader/InfiniteLoader.js#L94
and it's pretty straight forward.
