### ISSUE TITLE
bug(build): requestAnimationTimeout timeout is not defined

### ISSUE THREAD

**Issue by Sigura** [bvaughn/react-virtualized#1529]
### *BUG*

Looks like build issue with [requestAnimationTimeout](../blob/master/source/utils/requestAnimationTimeout.js#L32)

<img width="382" alt="Screenshot 2020-04-05 at 19 49 28" src="https://user-images.githubusercontent.com/428500/78504538-9f427380-7776-11ea-8a39-35e7f3423335.png">

### Versions

|                   |          |
|-------------------|----------|
| Browser           |    Safari, Chrome, Firefox,...      |
| OS                |    osX      |
| React             |    16.9.0      |
| React DOM         |    16.9.0      |
| react-virtualized |    9.21.2      |

All is fine with react-virtualized@9.8.0
Don't ask me why (

**Comment by wuweiweiwu** [comment]
interesting! will investigate
