### ISSUE TITLE
Arrow down - horizontal scrollbar hides last element

### ISSUE THREAD

**Issue by jamhall** [bvaughn/react-virtualized#154]
Hello!

When using a grid that has a horizontal scrollbar, when you reach the last row (with the mouse down key) it is hidden because of the horizontal scrollbar.

You can see this in effect with your grid example: https://bvaughn.github.io/react-virtualized/

Keep pressing the down key until you get to the bottom row and you'll see it is half hidden, however, if you then scroll down using the mousewheel, the element appears in full view.

Thank you for your amazing components.

Cheers

**Comment by bvaughn** [comment]
Thanks for reporting this issue, @jamhall. I'll see if I can make some time to look into it soon. :)

**Comment by bvaughn** [comment]
Actually @jamhall can you provide a little more information. I'm not able to reproduce the behavior you're describing using the Grid demo.

**Comment by bvaughn** [comment]
I believe PR #161 has resolved this issue as well. I will be release 5.5.6 with that fix momentarily.

Please let me know if that's not the case.

**Comment by jamhall** [comment]
@bvaughn Hello. 5.5.6 did indeed solve the problem. Thank you!

**Comment by bvaughn** [comment]
Happy to hear it! Credit goes to @jquense for the fix :)

**Comment by jamhall** [comment]
Thanks @jquense ! :)
