### ISSUE TITLE
AutoSizer: width is not updating on RTL

### ISSUE THREAD

**Issue by ejdzipi** [bvaughn/react-virtualized#1541]
### What is the current behavior?

AutoSizer is not properly updating width, when used in RTL element. There are two problems:

1. start with full screen width and try to resize screen to set smaller width - width should be decreasing, sometimes it updates, but you need to resize a lot.
2. set screen width to some small number, e.g. 200px. Then resize slowly, so width should increase pixel after pixel, but it will skip most of width changes.

Reproducible demo:
https://codesandbox.io/s/fancy-sky-corn0

### What is the expected behavior?

Width should be updated correctly on RTL

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue?

| Browser: Chrome 83
| OS: WIndows
| React: 16.12.0
| React DOM: 16.12.0
| react-virtualized: 9.21.2

**Comment by arthurpankiewicz** [comment]
bump
