### ISSUE TITLE
Unable to get dynamic list items working correctly

### ISSUE THREAD

**Issue by JamesIves** [bvaughn/react-virtualized#1542]
I'm using react-virtualized to render a list of dynamic content but I'm having problems getting it working properly. I'm using the `CellMeasurer` hoc with the `List` component to wrap my own components, it's possible for the component to contain either an image or just some text. The problem I'm having is that all of my cells end up being the same height, meaning that a cell with no content is as large as the largest one.

Here's my component:

```javascript
import React from "react";
import "react-virtualized/styles.css";
import {
  CellMeasurerCache,
  CellMeasurer,
  List,
  WindowScroller,
} from "react-virtualized";
import Icon from "./icon.png";

const Timeline = () => {
  const cache = new CellMeasurerCache({
    fixedWidth: true,
    keyMapper: () => 1,
  });

  const dummyData = Array.from({
    length: 100,
  }).map((item, index) =>
    index % 2 === 0
      ? {
          text: "Greatest cat",
          key: index,
        }
      : index % 5 === 0
      ? {
          text: "Your plan begins on August 1 2019. View Details.",
          image: Icon,
          key: index,
        }
      : {
          key: index,
        }
  );

  function rowRenderer({
    columnIndex,
    rowIndex,
    parent,
    key,
    index,
    isScrolling,
    isVisible,
    style,
  }) {
    const content = dummyData[index];
    return (
      <CellMeasurer
        cache={cache}
        columnIndex={columnIndex}
        key={`${key}-${dummyData[index].key}`}
        parent={parent}
        rowIndex={rowIndex}
      >
        {({ measure, registerChild }) => (
          <div className="item" style={{ ...style }} ref={registerChild}>
            {content.image ? (
              <div className="uic--row">
                <div className="uic--col-4">
                  <img alt="" src={content.image} onLoad={measure} />
                </div>

                <div className="uic--col-8">{content.text}</div>
              </div>
            ) : (
              content.text
            )}
          </div>
        )}
      </CellMeasurer>
    );
  }

  return (
    <WindowScroller>
      {({ height, isScrolling, onChildScroll, scrollTop }) => (
        <List
          height={height}
          isScrolling={isScrolling}
          onScroll={onChildScroll}
          scrollTop={scrollTop}
          width={1000}
          deferredMeasurementCache={cache}
          rowRenderer={rowRenderer}
          rowCount={dummyData.length}
          rowHeight={cache.rowHeight}
        />
      )}
    </WindowScroller>
  );
};

export default Timeline;
```

When I look at the DOM all of the height properties are the same despite the content with images being larger than the ones without. I feel like I'm missing something important in order to make this work properly. I've tried removing the WindowScroller wrapper too but that doesn't seem to have any effect either.

![Screen Shot 2020-06-04 at 3 46 29 PM](https://user-images.githubusercontent.com/10888441/83803448-938e0300-a67a-11ea-85aa-b2f3cefd89b1.png)

This is what this results in:

<img width="858" alt="Screen Shot 2020-06-04 at 3 48 56 PM" src="https://user-images.githubusercontent.com/10888441/83803643-f1bae600-a67a-11ea-9a77-9181e5564c33.png">

Any help would be greatly appreciated. 

**Sandbox:** https://codesandbox.io/s/condescending-flower-ehzh4?file=/src/App.js

**Comment by iamgrawal** [comment]
Hey @JamesIves, I am facing the same issue. Did you get any workaround to solve this?

**Comment by JamesIves** [comment]
Not yet :(

**Comment by n1ru4l** [comment]
This might help you: https://stackoverflow.com/a/45394513/4202031
