### ISSUE TITLE
loadMoreRows is invoked multiple times by applying filter or search in infiniteLoader List

### ISSUE THREAD

**Issue by mahesht** [bvaughn/react-virtualized#1543]
## Bug Report

loadMoreRows is invoked multiple times by applying filter or search with same startIndex and stopIndex. This triggers multiple data fetches to the server. It would be nice if InfiniteLoader fires this event once whenever filter is applied. @bvaughn Could you please give me reply on this.

**Comment by mahesht** [comment]
> ## Bug Report
Can anyone give reply asap as it is a urgent issue for us.

**Comment by dizel852** [comment]
I have a similar issue in react-window. @mahesht Have you find a way how to fix that?
