### ISSUE TITLE
How can I render an array in a column?

### ISSUE THREAD

**Issue by REDLIGHTFILMS** [bvaughn/react-virtualized#1545]
I have this data structure: 
[{
basicData:{
 name: "",
 website: "",
 tasks: [{title: "..."}, {title: "..."}]
},
basicData:{
 name: "",
 website: "",
 tasks: [{title: "..."}, {title: "..."}]
}
}]
How can I render the name, the website and the tasks in different columns? But the tasks in a cell should be rendered among each other. Do I have to apply .map() in cellDataGetter or do I have to do it in cellRenderer? How do I do that?

**Comment by iamjayk** [comment]
@REDLIGHTFILMS this is more of a question for stackOverflow and not an issue for GitHub.

If you checkout the docs, [Grid](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md) is the component you're looking for.
