### ISSUE TITLE
estimatedRowSize per Row?

### ISSUE THREAD

**Issue by dilizarov** [bvaughn/react-virtualized#1553]
## Feature Request

I'm using the List component and I've come across a situation. My rows have wildly varying row sizes, which means I cannot use the same estimate for each row.

I've come up with an extremely performant function that gets the height correct 95% of the time. It is off by 16 pixels 5% of the time.

Due to this, I unfortunately can't rely on the function to be give me the definitive row height. Also, it's far too complicated to get that last 5% perfect.

That said, my function is perfect as a per-row estimate. I was hoping to use the CellMeasurer to get the perfect heights of my rows, but with my function as a preliminary estimate.

The estimatedRowSize prop doesn't take a function and I'm not sure if there is any way to leverage the CellMeasurerCache to have my estimates pre-baked.   

Should this be a new feature? Is there an existing way to implement this?

**Comment by matpandino** [comment]
any updates on this please 🥲
