### ISSUE TITLE
VirtualScroll takes over arrow keys

### ISSUE THREAD

**Issue by jlongster** [bvaughn/react-virtualized#156]
I am rendering an input in an item, and the cursor inside the input cannot be controlled with the left/right arrows keys. What is taking over this behavior? Not much more to say about it, I'm sure you know what I'm talking about :) If not I can post a small test case.

Is there a way to turn it off?

**Comment by jlongster** [comment]
Sorry for the sucky bug report. I see in #121 that other components support keyboard navigation, but I don't see what that has to do with `VirtualScroll` which is not a specific grid/table component. I looked through the docs but I don't see anything concerning keyboard controls (for `VirtualScroll`).

I will post a test case tomorrow; it's late tonight and I thought you might know exactly where to look.

**Comment by bvaughn** [comment]
Hey @jlongster! Hope you're well.

[This method in `Grid`](https://github.com/bvaughn/react-virtualized/blob/58e60445ebb4ae36fee53574de2a9528c6753cbd/source/Grid/Grid.js#L671) is causing the issue you're referring to. Let me see what I can do. :)

**Comment by bvaughn** [comment]
I'll be honest. I think that approach/behavior was a mistake on my part. Especially now that you point out this unfortunate side effect it can have on inline inputs. I'll make a bugfix release for this.

**Comment by bvaughn** [comment]
I just published [version 5.5.4](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#554) which should improve the behavior you're talking about. I'm going to leave this issue open for more consideration though. It's not clear to me whether I should...

1. Make arrow-key navigation opt-in (disabled by default)
1. Allow users to disable arrow-key navigation
1. Require users to intercept key-down events (and prevent-default) if they want to disable arrow key navigation. I could update my key-down handler to ignore events where `defaultPrevented` is true.
1. Ignore arrow key events anytime `event.target` is an `input`, `textarea`, or other type of form control.

I'm leaning toward option 4.

**Comment by Guria** [comment]
4 is not best option since it wouldn't fit a case with control "selected" row from arrow keys.

**Comment by cgestes** [comment]
4 would have to take contenteditable into consideration also.

**Comment by jlongster** [comment]
I'm leaning towards #1. Why does `VirtualScroll` have this at all? It seems a little strange that `VirtualScroll` inherits from `Grid`, because the type of content that `VirtualScroll` has it up to the user. I'm sure it's just a naming thing and there's a lot technically shared, but I don't think keyboard navigation belongs in the base class. I never want to override the default browser behaviors, and I want up/down to scroll normally, not go to the next item. I can scroll with my trackpad as well, and `VirtualScroll` should act like a normal big div being scrolled. (I can `FlexTable` being different)

In fact, now that I'm looking, there is strange interaction with up/down. If I scroll with the trackpad so that half of the top item is cut off, pressing "down" jumps down items but the top item is still cut off because there's an offset. I'd very much prefer all of this to be opt-in.

**Comment by jlongster** [comment]
Thanks for a quick release also! That makes it a little better.

**Comment by jlongster** [comment]
FWIW in the latest release, pressing up/down scrolls the container even though the input is focused. As far as I know that shouldn't happen: if I'm in an input the browser doesn't scroll it's container. I know you did a quickfix but just wanted to explain other side effects.

No rush on this!

**Comment by bvaughn** [comment]
Thanks for the feedback folks. After sleeping on it, I'm leaning towards creating a HOC that manages arrow-key "snapping" behavior (so you scroll by exactly the width/height of a cell) and just leaving that off by default entirely.

Busy week for me but I'll try to see if I can't put together a release by the weekend.

**Comment by bvaughn** [comment]
> Why does `VirtualScroll` have this at all? It seems a little strange that `VirtualScroll` inherits from `Grid`, because the type of content that `VirtualScroll` has it up to the user.

@jlongster `VirtualScroll` and `FlexTable` compose a single-column `Grid` (rather than inherit). They're just decorator components that expose convenient alternative interfaces. This dramatically reduces my code duplication. :)

**Comment by jlongster** [comment]
I figured they share a lot of code, I think the `Grid` name is slightly confusing though. But that makes sense. I knew they didn't literally inherit, but rather compose, which is good :)

**Comment by bvaughn** [comment]
Really! Confusing? :) I thought grid, datagrid, etc. was a pretty standard name but... naming things is hard! I'd be curious what you would find a more appropriate name if you have any suggestions.

**Comment by jlongster** [comment]
I have no suggestions :) My initial impression of `grid` is the layout of multiple things both horizontally and vertically, while the `VirtualScroll` just optimizes a big list. It doesn't really matter, I think `grid` is an appropriate name if interpreted a different way! My confusion was short and it's easy to learn what each component does.

**Comment by bvaughn** [comment]
I believe I am starting to lean toward option 5: remove this functionality entirely. :)

I've been working on option 1 in a branch- removing the arrow-key handling from `Grid` and into a HOC and it ends up being kind of complicated/awkward.

**Comment by bvaughn** [comment]
I've put together PR #159 to illustrate my thoughts on the direction for option 1. Feedback is welcome. :)

**Comment by bvaughn** [comment]
Btw @jlongster, version 6 was released just a moment ago. You should be able to completely opt-out of key-arrow handling now (it is the default in fact). Thanks for raising this issue. :)
