### ISSUE TITLE
fix column count in multigrid fix columns in the left. How to fix columns in the right?

### ISSUE THREAD

**Issue by tithic** [bvaughn/react-virtualized#1569]
## Bug Report

Please include either a failing unit test or a simple repro. You can start by forking this Code Sandbox: https://codesandbox.io/s/03qpzq1p9p?module=%2FExample.js

### What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React and react-virtualized. Paste the link to your [Code Sandbox](https://codesandbox.io/s/03qpzq1p9p?module=%2FExample.js) below:

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |          |
| OS                |          |
| React             |          |
| React DOM         |          |
| react-virtualized |          |

**Comment by MarvanN** [comment]
Same issue here, any solution for this

**Comment by Braweria** [comment]
I would also love to easily fix my right column, this is where I want to have my context menu button for each row.

**Comment by rhlmalik17** [comment]
Any update on this? For now am thinking of creating right fixed columns using scrollSync
