### ISSUE TITLE
function rowHeight  is not full calculate of List 

### ISSUE THREAD

**Issue by eretica** [bvaughn/react-virtualized#1571]
## Bug Report

https://codesandbox.io/s/react-virtualized-row-height-nj2bl

|    first               |      end to scroll    |
|-------------------|----------|
| 5580px | 20200px |
|  <img width="50%" alt="スクリーンショット 2020-08-04 0 13 01" src="https://user-images.githubusercontent.com/16332352/89197963-7082bf80-d5e7-11ea-8299-772963bb88b7.png">  |  <img width="50%" alt="スクリーンショット 2020-08-04 0 13 07" src="https://user-images.githubusercontent.com/16332352/89197974-74aedd00-d5e7-11ea-91ad-c9922c8964bc.png"> |

If you use rowHeight (function), the height is not fully calculated。

### What is the current behavior?

If you use rowHeight (function), the height is not fully calculated。

Directly specifying it will result in a proper calculation.

In this example, the initial rendered height is not appropriate, and the height will be added as you scroll

### What is the expected behavior?

use the rowHeight (function) to calculate the full height

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |    84.0.4147.89      |
| OS                |     10.15.6     |
| React             |     16.12.0     |
| React DOM         |     16.12.0     |
| react-virtualized |       9.21.2   |

**Comment by DmitriyKylik** [comment]
If this still actual to you. I had the same issue, when i used List with WindowScroller and Autosizer. You can get list full height by calculating all rows height, that you have. I did something like this:
`  useEffect(() => {
    let currentListHeight = 0;
    for (let i = 0; i < data.length; i++) {
      // increment currentListHeight value here
    }
  }, [data]);`
Than I had the following structure:
` <WindowScroller
        ref={refList}
        scrollElement={window}>
         {({height, isScrolling, registerChild, onChildScroll, scrollTop}) => (
               <AutoSizer disableHeight>
                  {({width}) => (
                                         <div
                    ref={registerChild}
                    style={{
                      width: '100%',
                      height: `${listTotalHeight}px`,
                    }}
                  >
                    <List
                      style={{
                        height: '100%'
                      }}
                      ref={onMountRef}
                      autoHeight
                      className={styles.List}
                      height={height + 300}
                      isScrolling={isScrolling}
                      onScroll={onChildScroll}
                      overscanRowCount={14}
                      rowCount={data.length}
                      rowHeight={getRowHeight}
                      rowRenderer={renderRow}
                      scrollTop={scrollTop}
                      width={width}
                      noRowsRenderer={EmptyList}
                    />
                  </div>
                  )}
              </AutoSizer>
        )}
  </WindowScroller>
`
Thing is, I added wrapper to List component. This div wrapper has fully calculated height which depends on data.length. To List component i added 100% height styles to prevent scroll from jumping. Hope it helps!
