### ISSUE TITLE
Module not found: Error:

### ISSUE THREAD

**Issue by rathorebs** [bvaughn/react-virtualized#1576]
## Bug Report

Hi Team React-Virtualized,

I installed this ``"react-virtualized": "^9.21.2",`` and after this when ran my project then facing below errors.

01) ERROR in ../node_modules/react-virtualized/dist/es/Collection/CollectionView.js
Module not found: Error: Can't resolve 'dom-helpers/scrollbarSize' in

02) ERROR in ../node_modules/react-virtualized/dist/es/Grid/Grid.js
Module not found: Error: Can't resolve 'dom-helpers/scrollbarSize'

Issue 01)
Path not correct Inside the CollectionView.js for `import getScrollbarSize from 'dom-helpers/scrollbarSize';`
Solution 01) It's working fine when I used this path  `import getScrollbarSize from '../../../node_modules/dom-helpers/scrollbarSize';`

Issue 02)
Path not correct Inside the Grid.js for `import scrollbarSize from 'dom-helpers/scrollbarSize';`
Solution 02) It's working fine when I used this path  `import scrollbarSize from '../../../node_modules/dom-helpers/scrollbarSize';`

Please see attached images.

![Grid](https://user-images.githubusercontent.com/9293248/89711245-a4266680-d9a6-11ea-9ed4-6be2571bdc14.jpg)
![CollectionView](https://user-images.githubusercontent.com/9293248/89711249-af799200-d9a6-11ea-988d-a896945cd647.jpg)

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |  Version 84.0.4147.105 (Official Build) (64-bit)        |
| OS                |   Windows 10       |
| React             |      "react": "^16.4.0",    |
| React DOM         |   "react-dom": "^16.4.0",       |
| react-virtualized |     "react-virtualized": "^9.21.2"     |

Thanks,
BSR

**Comment by mbonaci** [comment]
@rathorebs I managed to get around this issue with this in `package.json`:
```
"resolutions": {
    "dom-helpers": "^5.1.3"
}
```
I'm guessing that you (or one of your dependencies) are using an older version of `dom-helpers`, which did not yet have `scrollbarSize`.

**Comment by rathorebs** [comment]
@mbonaci I have added above solution but still facing same error.
Please see attached [package.josn](`url`)
`ERROR in ../node_modules/react-virtualized/dist/es/Collection/CollectionView.js
Module not found: Error: Can't resolve 'dom-helpers/scrollbarSize' in '```
`{
  "name": "workmob-react-bp",
  "version": "8.0.0",
  "private": true,
  "description": "Workmob React App - React, Redux, Webpack 4",
  "license": "MIT",
  "main": "index.js",
  "scripts": {
    "test": "jest",
    "test:watch": "jest --watch",
    "coverage": "jest --coverage",
    "start-dev": "webpack-dev-server  --open",
    "start-dev-prod": "cross-env NODE_ENV=production webpack-dev-server --open",
    "build-pp": "rimraf build-pp && cross-env NODE_ENV=production-pp webpack --env.prod=true --env.sw=true",
    "build-sd": "rimraf build-sd && cross-env NODE_ENV=production-sd webpack --env.prod=true --env.sw=true",
    "build-prod": "rimraf build && cross-env NODE_ENV=production-prod webpack --env.prod=true --env.sw=true",
    "build-dev-api": "rimraf build-dev-api && cross-env NODE_ENV=production-dev-api webpack --env.prod=true --env.sw=true",
    "serve-pp": "pushstate-server build-pp/ 9494",
    "serve-sd": "pushstate-server build-sd/ 9696",
    "serve-prod": "pushstate-server build/ 9898",
    "serve-dev-api": "pushstate-server build-dev-api/ 9999",
    "deploy-pp": "aws s3 cp --recursive ./build-pp s3://preprod.workmob.com",
    "deploy-mobile": "aws s3 cp --recursive ./build-pp s3://mobile.workmob.com",
    "deploy-live-live": "aws s3 cp --recursive ./build s3://www.workmob.com",
    "perf": "rimraf *.report.dom.html && npm run build && (npm run serve & lighthouse https://localhost:3001 --view)",
    "perf-live": "lighthouse https://workmob.com --view",
    "lint": "eslint ./app -f table",
    "lint:fix": "eslint ./app -f table --fix",
    "update-types": "flow-typed install",
    "flow": "flow",
    "dll": "webpack --config webpack.config.dll.js",
    "postinstall": "rimraf .cache-loader & npm run dll",
    "__precommit": "lint-staged",
    "stats": " webpack --profile --json > compilation-stats.json"
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "npm run lint:fix",
      "git add"
    ],
    "*.{json,scss,sass,css,less}": [
      "prettier --write",
      "git add"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-modules-commonjs": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime-corejs2": "^7.0.0",
    "add-asset-html-webpack-plugin": "2.1.3",
    "autoprefixer": "8.6.3",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "8.2.3",
    "babel-loader": "^8.0.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "cache-loader": "^1.2.2",
    "copy-webpack-plugin": "4.5.2",
    "coveralls": "^3.0.1",
    "cross-env": "5.2.0",
    "css-loader": "^0.28.11",
    "enzyme": "3.3.0",
    "enzyme-adapter-react-16": "^1.7.0",
    "eslint": "4.19.1",
    "eslint-config-airbnb": "17.0.0",
    "eslint-config-prettier": "^2.3.0",
    "eslint-plugin-flowtype": "2.49.3",
    "eslint-plugin-import": "2.12.0",
    "eslint-plugin-jsx-a11y": "6.0.3",
    "eslint-plugin-prettier": "2.6.0",
    "eslint-plugin-react": "7.9.1",
    "file-loader": "1.1.11",
    "flow-bin": "^0.79.1",
    "flow-typed": "^2.5.1",
    "html-webpack-inline-source-plugin": "0.0.10",
    "html-webpack-plugin": "^3.2.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^23.1.0",
    "lighthouse": "^2.9.4",
    "mini-css-extract-plugin": "0.4.0",
    "node-sass": "^4.13.0",
    "optimize-css-assets-webpack-plugin": "4.0.1",
    "postcss-loader": "^2.1.5",
    "preload-webpack-plugin": "^3.0.0-beta.3",
    "prettier": "1.13.5",
    "pushstate-server": "3.0.1",
    "react-test-renderer": "16.4.1",
    "redux-logger": "^3.0.6",
    "redux-mock-store": "^1.5.1",
    "rimraf": "^2.6.2",
    "sass-loader": "7.0.3",
    "script-ext-html-webpack-plugin": "^2.0.1",
    "style-loader": "0.21.0",
    "sw-precache-webpack-plugin": "^0.11.5",
    "terser-webpack-plugin": "^1.2.3",
    "thread-loader": "^1.1.5",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "@material-ui/core": "^1.2.3",
    "@modus/react-idle": "1.0.1",
    "async": "^2.6.1",
    "autosuggest-highlight": "^3.1.1",
    "aws-iot-device-sdk": "^2.2.1",
    "aws-sdk": "^2.256.1",
    "axios": "^0.18.0",
    "classnames": "^2.2.6",
    "core-js": "^2.5.7",
    "d3": "5.5.0",
    "date-fns": "^2.0.0-alpha.7",
    "draft-js": "^0.10.5",
    "draft-js-emoji-plugin": "^2.0.6",
    "draft-js-export-html": "^1.2.0",
    "draft-js-hashtag-plugin": "^2.0.3",
    "draft-js-mention-plugin": "^3.0.4",
    "draft-js-plugins-editor": "^2.1.1",
    "draft-js-sticker-plugin": "^2.0.3",
    "draftjs-to-markdown": "^0.5.1",
    "file-type": "^8.0.0",
    "firebase": "^7.17.2",
    "husky": "^0.14.3",
    "immutable": "^3.8.2",
    "install": "^0.12.2",
    "lightbox-react": "^0.3.7",
    "lint-staged": "^7.2.2",
    "lodash": "^4.17.5",
    "material-ui-pickers": "^1.0.0-rc.6",
    "moment": "^2.22.2",
    "moment-duration-format": "^2.2.2",
    "mqtt": "^2.18.8",
    "npm": "^6.7.0",
    "prop-types": "^15.6.1",
    "react": "^16.4.0",
    "react-addons-css-transition-group": "^15.6.2",
    "react-autosuggest": "^9.3.4",
    "react-color-extractor": "^1.1.2",
    "react-copy-to-clipboard": "^5.0.1",
    "react-cropper": "^1.0.1",
    "react-date-picker": "^6.11.3",
    "react-dom": "^16.4.0",
    "react-drag-listview": "^0.1.6",
    "react-facebook-login-component": "^0.9.2",
    "react-file-drop": "^0.2.8",
    "react-fittext": "^1.0.0",
    "react-ga": "^2.7.0",
    "react-google-login": "^3.2.1",
    "react-google-recaptcha": "^1.0.5",
    "react-headroom": "^2.2.2",
    "react-helmet": "^6.1.0",
    "react-hls-player": "0.0.5",
    "react-hot-loader": "^4.3.3",
    "react-html5video": "^2.5.0",
    "react-id-swiper": "^3.0.0",
    "react-images": "^0.5.19",
    "react-imgpro": "^1.3.12",
    "react-input-range": "^1.3.0",
    "react-insta-stories": "^1.4.0",
    "react-inview-monitor": "^2.2.1",
    "react-lazyload": "^2.6.7",
    "react-lines-ellipsis": "^0.13.0",
    "react-masonry-component": "^6.2.1",
    "react-masonry-css": "^1.0.11",
    "react-material-ui-form-validator": "^2.0.0-beta.10",
    "react-measure": "^2.0.2",
    "react-medium-image-zoom": "^3.0.13",
    "react-moment": "^0.7.6",
    "react-motion": "^0.5.2",
    "react-owl-carousel": "^2.2.0",
    "react-owl-carousel2": "^0.2.1",
    "react-player": "^1.7.0",
    "react-progressive-image": "^0.3.0",
    "react-redux": "5.0.7",
    "react-reorder": "^3.0.0-alpha.7",
    "react-responsive-carousel": "^3.1.39",
    "react-router-dom": "^4.3.1",
    "react-router-redux": "5.0.0-alpha.6",
    "react-share": "^2.2.0",
    "react-slick": "^0.23.2",
    "react-smooth-scrollbar": "^8.0.6",
    "react-spring": "^5.0.1",
    "react-sticky": "^6.0.2",
    "react-sticky-box": "^0.8.0",
    "react-swipeable-views": "^0.12.13",
    "react-tap-event-plugin": "^3.0.3",
    "react-transition-group": "^2.3.0-beta.0",
    "react-truncate-html": "^0.1.7",
    "react-virtualized": "^9.21.2",
    "react-window": "^1.8.5",
    "readable-stream": "^2.3.6",
    "recordrtc": "^5.6.1",
    "redux": "4.0.0",
    "redux-thunk": "2.3.0",
    "reselect": "^3.0.1",
    "rgbaster": "^2.0.0",
    "smooth-scrollbar": "^8.2.7",
    "swiper": "^5.3.8",
    "uuid": "^3.2.1",
    "video.js": "^7.6.6"
  },
  "resolutions": {
    "dom-helpers": "3.2.1",
    "react-virtualized/dom-helpers": "^5.1.3"
}
}
`
D:\www\workmob\master2019\01_wd_dev_2021\wmd_dev_2021\node_modules\react-virtualized\dist\es\Collection'
 @ ../node_modules/react-virtualized/dist/es/Collection/CollectionView.js 12:0-57 170:27-43 217:30-46
 @ ../node_modules/react-virtualized/dist/es/Collection/Collection.js
 @ ../node_modules/react-virtualized/dist/es/Collection/index.js
 @ ../node_modules/react-virtualized/dist/es/index.js
 @ ./components/User/UserPost/index.js
 @ ./routes/User/UserPost/index.js
 @ ./components/User/index.js
 @ ./routes/User/index.js
 @ ./containers/Auth/index.js
 @ ./index.js
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:3002 webpack/hot/only-dev-server ./index.js

ERROR in ../node_modules/react-virtualized/dist/es/Grid/Grid.js
Module not found: Error: Can't resolve 'dom-helpers/scrollbarSize' in 'D:\www\workmob\master2019\01_wd_dev_2021\wmd_dev_2021\node_modules\react-virtualized\dist\es\Grid'
 @ ../node_modules/react-virtualized/dist/es/Grid/Grid.js 16:0-54 1301:20-33
 @ ../node_modules/react-virtualized/dist/es/Grid/index.js
 @ ../node_modules/react-virtualized/dist/es/ArrowKeyStepper/ArrowKeyStepper.js
 @ ../node_modules/react-virtualized/dist/es/ArrowKeyStepper/index.js
 @ ../node_modules/react-virtualized/dist/es/index.js
 @ ./components/User/UserPost/index.js
 @ ./routes/User/UserPost/index.js
 @ ./components/User/index.js
 @ ./routes/User/index.js
 @ ./containers/Auth/index.js
 @ ./index.js
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:3002 webpack/hot/only-dev-server ./index.js
i ｢wdm｣: Failed to compile.````

**Comment by rathorebs** [comment]
@mbonaci I'm reopening as still same error and not fixed.

**Comment by MohammedAl-Rowad** [comment]
I faced this issue today and wasted an hour trying to fix it by playing with the versions in the `resolutions` in `package.json` and I used [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) to force the correct version in all my dependencies.

unfortunately, I couldn't figure out a solution BUT I have a workaround if someone is using webpack 

as you can see from the error message somewhere in your dependencies the code tries to import from `dom-helpers/scrollbarSize` but in `dom-helpers` the scrollbarSize is inside `dom-helpers/uitl/scrollbarSize` 


so as a solution I added an alias for `dom-helpers/scrollbarSize` to point to the correct place

`webpack.config.js`
```js
module.exports = {
  entry: {
     .....
  },
  output: {
      ...
  },
  module: {
    rules: [....]
  },
  resolve: {
    modules: [
      path.resolve('./node_modules')
    ],
    alias: {
      'dom-helpers/scrollbarSize': path.resolve(__dirname, 'node_modules', 'dom-helpers', 'util', 'scrollbarSize'),
      .....
    }
  },
  plugins: [...]
};
```

just a temp solution I guess

**Comment by mbonaci** [comment]
> @mbonaci I'm reopening as still same error and not fixed.

What happens if you downgrade to `"react-virtualized": "9.21.0"`?

FYI I'm not affiliated with this project in any way.
