### ISSUE TITLE
CellMeasurerCache not working as expected

### ISSUE THREAD

**Issue by hmtri1011** [bvaughn/react-virtualized#1580]
![react-virtualize](https://user-images.githubusercontent.com/16288424/90422016-721eae00-e0e4-11ea-905a-eb78bb624561.png)

This is a component I use for rendering virtualize list with dynamic item sizes. However the `cache.rowHeight` does not work as expected, the `ReactVirtualized__Grid__innerScrollContainer` height always is 0.

If I change to use specific value (`300px` for example) on `rowHeight` property instead of` cache.rowHeight` then the list works perfectly. Am I doing something wrong? 

Any helps would be appreciated. Thanks guys!

**Comment by vuachicken6** [comment]
I get the same issue. The measured row Heigth always is minHeight  in  cache which i initialized at constructor.
Please, anyone met that can give me a help.Thank you!!

`_rowRenderer = ({ index, parent, key, style }) => {
    const column = getFieldValue('columns')[index];
return (
      <CellMeasurer
        key={key}
        cache={this.cache}
        parent={parent}
        columnIndex={0}
        rowIndex={index}
      >
        {({ measure, registerChild }) => (
          <div ref={registerChild} style={style}>
            <DragableBodyRow
            />
          </div>
        )}
      </CellMeasurer>
    );
  };`
`
 <WindowScroller ref={this._setRef} scrollElement={window}>
                  {({
                    height,
                    isScrolling,
                    registerChild,
                    onChildScroll,
                    scrollTop,
                  }) => (
                    <div>
                      <AutoSizer disableHeight>
                        {({ width }) => (
                          <div ref={registerChild}>
                            <List
                              ref={(el) => {
                                this.list = el;
                              }}
                              style={STYLE}
                              autoHeight
                              height={height}
                              isScrolling={isScrolling}
                              onScroll={onChildScroll}
                              overscanRowCount={0}
                              rowCount={rowCount}
                              rowHeight={this.cache.rowHeight}
                              rowRenderer={this._rowRenderer}
                              scrollTop={scrollTop}
                              deferredMeasurementCache={this.cache}
                              width={width}
                            />
                          </div>
                        )}
                      </AutoSizer>
                    </div>
                  )}
                </WindowScroller>
`

**Comment by vuachicken6** [comment]
Update: I find the problem. The problem is cell was measured before the component was rendered in real DOM that lead to element offsetHeight return 0 in  computing height.You can pass measure method to your ItemComponent and invoke in its componentDidMount method like this:
`<CellMeasurer
        cache={this.cache}
        columnIndex={0}
        key={key}
        parent={parent}
        rowIndex={index}
      >
        {({ measure, registerChild }) => (
          <div ref={registerChild} style={style}>
            <ItemComponent
              measure={measure}
              ... your props 
             />
          </div>
        )}
      </CellMeasurer>`
and invoke it in ItemComponent componentDidMount.
It seems  you are using functional component sorry i dont have exp in using that but I hope what I have found can help you !!
