### ISSUE TITLE
List: overscanRowCount not working properly after scroll

### ISSUE THREAD

**Issue by Ultre00** [bvaughn/react-virtualized#1582]
the overscanRowCount property on List isn't working properly.
This is also the case for the example provided : http://bvaughn.github.io/react-virtualized/#/components/List

When you inspect the element initially you can see that there are about 15 rows rendered (10 invisible rows are rendered).
This is expected behavior. 

After scrolling down and then back up to the top you can see that there are only 6 rendered rows.
What happend to the overscanRowCount  being at 10 ? There is only 1 invisible row rendered and not 10.

This is annoying since it will mount a new component when you scroll down. This results in a flicker when scrolling. This flickering is more obvious when the component being rendered is bigger then some simple text component.

Is the described behavior the intended behavior ? If so how can I make sure that there are x amount of hidden rows being rendered ?

**Comment by mikeyshing88** [comment]
I had to include a custom `overscanStartIndex` on my `List` to get it working correctly:

```tsx
overscanIndicesGetter={({
  cellCount,
  overscanCellsCount,
  startIndex,
  stopIndex,
}) => ({
  overscanStartIndex: Math.max(
    0,
    startIndex - overscanCellsCount,
  ),
  overscanStopIndex: Math.min(
    cellCount - 1,
    stopIndex + overscanCellsCount,
  ),
})}
```
