### ISSUE TITLE
Scroll position lost when inserting new data

### ISSUE THREAD

**Issue by alinvdu** [bvaughn/react-virtualized#1588]
# What is the current behavior?

In the current behavior when new data is inserted the scroll position remains unchanged and the selected rows are pushed down. The following codepen code illustrates the problem: https://codepen.io/alindumitru/pen/LYNjgVG. To properly visualize how the items are pushed down just select a row past index 10 and wait 5 seconds.

### What is the expected behavior?
Like in a DOM rendered list I would expect the scroll position to be adjusted by the number of inserted items +  row height (since row height is static).

Can this behavior be achieved by tweaking the scrollTop position from outside or other properties? If so I'm opened to any suggestion and I can help document because it seems to me that this is a trivial behavior that people would want in certain cases.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
Browser: Chrome, Firefox
OS: Macos, Windows
React-virtualized version 9.22.2
React version 16.13.1

**Comment by alindumitru25** [comment]
Any guidance on how to achieve the above mentioned behavior? I'm opened to dig in and contribute if no other work arounds are feasible, any guidance on where to start to tackle such issue?

**Comment by Evgeni67** [comment]
I would love to find a solution to this, if someone fixed it please reach out
