### ISSUE TITLE
JSX element type 'AutoSizer' does not have any construct or call signatures.ts(2604)

### ISSUE THREAD

**Issue by tahv0** [bvaughn/react-virtualized#1589]
This error comes with Typescript
`JSX element type 'AutoSizer' does not have any construct or call signatures.ts(2604)`

TS: 3.9.7
react-virtualized: 9.22.2
@types/react-virtualized: 9.21.10

**Comment by alinnert** [comment]
I hit the same error. But I think it's important to say that this only happens when you import like this:

~~~ ts
import AutoSizer from 'react-virtualized/dist/commonjs/AutoSizer'
~~~

It works fine if you do:

~~~ ts
import { AutoSizer } from 'react-virtualized'
~~~
