### ISSUE TITLE
Double rendering of cards

### ISSUE THREAD

**Issue by DVGY** [bvaughn/react-virtualized#1590]
[Code](https://codesandbox.io/s/suspicious-wescoff-vjpf3?file=/src/components/PostItem.jsx)

My PostItems.jsx (Card) are rendering twice in development as well as production. 

If you scroll and open dev tools you will see 13 renders or 26 renders. It is much more than the actual Card in dom ? Right? 

If i use overscanRowCount it loads 5 Card at a time but again, in the output it shows 10 Cards rendering. Why is this happening ?
Can anyone help me with it ?

**Comment by mouthzipper** [comment]
having the same issue with this. Keen to know more about the cause.
have you figured it out @DVGY ?

**Comment by DVGY** [comment]
> having the same issue with this. Keen to know more about the cause.
> have you figured it out @DVGY ?

No, I didn't waiting for the author to take a look at it
