### ISSUE TITLE
Unable to scroll the List using mouse scroll down when using with react-select

### ISSUE THREAD

**Issue by puru0019** [bvaughn/react-virtualized#1596]
## Bug Report

https://codesandbox.io/s/bvaughnreact-window-integration-with-react-select-forked-15ccs?file=/index.js

### What is the current behavior?

I am unable to scroll down the list in react-select with mouse scroll down.

### What is the expected behavior?

Should be able to scroll down using mouse scroll wheel

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |    Chrome      |
| OS                |    Windows      |
| React             |     16.13.1     |
| React DOM         |    16.13.1      |
| react-virtualized |     9.22.2     |

**Comment by devwebpeanuts** [comment]
Bug seems to be introduced with this pull request => https://github.com/JedWatson/react-select/pull/2861/files
