### ISSUE TITLE
Simple way to animate List scroll from position A to position B?

### ISSUE THREAD

**Issue by UCAudio** [bvaughn/react-virtualized#1605]
I'm using the react-virtualized List within a functional component. I have an onScroll function that is currently  capturing the scrollTop position of the scrolled list and storing it in fromPosition I also have a variable storing the toPosition I want to scroll to.

Does anyone have a clean way of enabling the List component to scroll from the fromPosition to the toPosition in a smooth animated way... and triggered when ever a certain piece of state changes (triggerVar)?

**Comment by DoneDeal0** [comment]
With React-Spring, you can do:

```js
 <Spring from={{ top: 0 }} to={{ top: lineHeight * (page.from - 1) }}>
          {(props) => (
            <List
              height={lineHeight * limit}
              rowCount={data.length}
              rowHeight={lineHeight}
              width={1}
              rowRenderer={row}
              containerStyle={{
                width: "100%",
                maxWidth: "100%"
              }}
              style={{
                width: "100%",
                overflow: "hidden"
              }}
              scrollTop={props.top}
            />
          )}
        </Spring>
```

It will make your list scroll like if a user was interacting with it. I'm trying to achieve the same result with Framer motion (library migration), if someone has an idea on how to do it, I'd be glad to hear from you!
