### ISSUE TITLE
Disable scrollToIndex when table is scrolling

### ISSUE THREAD

**Issue by oleg-kiriyenko** [bvaughn/react-virtualized#1607]
I have a table with continuously adding events (rows) and I have a requirement to display last event in table.
So I have made a prototype with timer adding events to ``state.events`` and set ``scrollToIndex={this.state.events.length - 1}``. The problem is when the table is being scrolled by user (user is keeping left mouse down on scrollbar) and new event comes in table scrolls to the end. I want to disable scrollToIndex while user is holding left mouse down on scroll bar (isScrolling). Is it possible?

```jsx
        <div className="flex-fill p-1">
                <AutoSizer>
                    {({width, height}) => 
                        <Table
                            width={width}
                            height={height}
                            headerHeight={20}
                            rowHeight={30}
                            rowCount={this.state.events.length}
                            scrollToIndex={this.state.events.length - 1}
                            rowGetter={({index}) => this.state.events[index]}>
                            <Column width={400} label="Timestamp" dataKey="t" />
                            <Column width={200} label="Address" dataKey="id" />
                            <Column width={200} label="Value" dataKey="value" />
                        </Table>
                    }
                </AutoSizer>
            </div>
```

**Comment by theromis** [comment]
@oleg-kiriyenko have the same issue, just don;t want to scroll anywhere after some list changes, did you found solution?
