### ISSUE TITLE
node-sass 5.0.0 incompatibility? 

### ISSUE THREAD

**Issue by LeoKeogh** [bvaughn/react-virtualized#1611]
Using `react-vertualized 9.22.2` and following the upgrade of node-sass from verson 4.14.1 to 5.0.0, we have encountered the following error:
```
./src/ReactVirtualized.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/ReactVirtualized.scss)
Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.
```

is there a solution other than reverting to `node-sass 4.14.1`?

Thanks for your help,
Leo.

**Comment by spumony** [comment]
npm uninstall node-sass
npm install node-sass@4.14.1
