### ISSUE TITLE
Set the property to set the smoothness of the scroll

### ISSUE THREAD

**Issue by wilderedin5** [bvaughn/react-virtualized#1612]
Hi, I have several scroll lists and they are linked. I really miss the property for setting the smoothness of the scroll movement for better visualization.

Can I somehow get to the ref of the scroll container and use scrollTo with the smooth option?

Are you planning to add this property? Can you tell me how to set the smoothness?

P.S: I may have missed something in the documentation. Thanks for your work :)

**Comment by danvoyce** [comment]
Bit late to the party, but hopefully this helps someone...

```js
const offset = listRef.current.getOffsetForRow({
      alignment: 'start',
      index: ???,
    });

listRef.current.Grid._scrollingContainer.scrollTo({
      top: offset,
      left: 0,
      behavior: 'smooth',
    });
```
