### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by cocreature** [bvaughn/react-virtualized#1616]
Currently, `react-virtualized` has a peer dependency on `react` and `react-dom` that constraints it to React 16. From my experiments, it already seems to work with React 17 so this might be as simple as just bumping the bounds.

**Comment by stheine** [comment]
This is getting more important when using React 17 and upgrading to npm 7.x, as there is a [breaking change](https://github.com/npm/cli/blob/latest/CHANGELOG.md#dependency-resolution) about the peer dependency resolution, resulting in
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm ERR! node_modules/react-virtualized
npm ERR!   react-virtualized@"9.22.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

the workaround is using `--legacy-peer-deps`, but it would be great if react-virtualized would officially support React 17.

**Comment by joachimklug** [comment]
As time flies I was wondering if there is any reason to hold back this PR? Or any way to contribute to get this done.

**Comment by tbrd** [comment]
Would be lovely to get this merged

**Comment by thexpand** [comment]
Why is this still not closed and the PR merged?

**Comment by reinisg** [comment]
Maybe this commend helps for now >  `npm install react-virtualized --legacy-peer-deps`

**Comment by PeterNitscheMGM** [comment]
@bvaughn 
Hi Brian,
the company I'm working for is really interested in the React 17 support.
Is there anything we can do to achieve this goal?

We are looking forward collaborating with you!

Best regards
Peter

**Comment by SeymurPasha** [comment]
> Maybe this command helps for now > `npm install react-virtualized --legacy-peer-deps`

This worked for me. Thanks

**Comment by rigobertoalag** [comment]
> Maybe this command helps for now > `npm install react-virtualized --legacy-peer-deps`

Work for me too!

**Comment by juzerzarif** [comment]
Can we get a version released with this change in it?

**Comment by cadentFE** [comment]
Is there any way I can help to get the peerDep react 17 update released?

**Comment by Mikeks81** [comment]
Is there anyway i can help to get the most recent updates released so that it include react17 as a peer dep?

**Comment by davidkiss96** [comment]
Guys if someone has the desire, contact him please:
[bvaughn](https://github.com/bvaughn) commented [6 days ago](https://github.com/bvaughn/react-virtualized/issues/1655#issuecomment-1051401739) • 
I haven't used this package in years. I don't have the mental bandwidth or the desire to maintain it. If someone else (preferably someone who actively uses it) wants to step up and publish this release (and deal with any potential breaks it causes, since there are several changes committed since the last release) then please email me.
