### ISSUE TITLE
FEATURE REQUEST: Add a way to start from the bottom of the list and scroll upward

### ISSUE THREAD

**Issue by nzayatz14** [bvaughn/react-virtualized#1622]
## Feature Request

It would be nice if there way a way to effectively reverse the virtualization of the table, in a way where the users scroll position starts at the bottom of the virtualized table, then scrolls up to load more rows.

* What's your use case? (Tell me about your application and what problem you're trying to solve.)

I am trying to create a virtualized chat window in my application. Generally speaking a lot of chat windows will show their latest data at the bottom, then the user will scroll up to see older messages.

* What interface do you have in mind? (What new properties or methods do you think might be helpful?)

I believe the only external interface you would need would be some sort of `reverse` or `scrollFromBottom` boolean. You would be able to set that and the table would just scroll from the bottom up.

* Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)

iMessage, Facebook Chat, Instagram Chat, etc

**Comment by MauroGL** [comment]
you could solve this by setting a state with scrollToIndex value and setting the initial value as listData.index - 1

**Comment by theromis** [comment]
@MauroGL doing it and it still scrolls ugly :( jumping, after `loadMore` focusing in wrong place, e.t.c

**Comment by shuiRong** [comment]
@theromis same here. Since then, have you found any solutions or alternatives?

**Comment by ForgoneReality** [comment]
is this not a feature yet? looking to implement a discord-like messaging system :/

**Comment by mihanizm56** [comment]
working on chat and have the same problem too!

**Comment by tchaton** [comment]
Any updates ?

**Comment by IgorKhomenko** [comment]
I tried many diff libraries during my career. The only lib which can be well used for Chat-like view is https://github.com/Flipkart/recyclerlistview

The only difficulty with recyclerlistview is that you need to measure each cell height and provide this value into the lib. But this can be managed.

**Comment by sikhaman** [comment]
to be honest `InfiniteLoader` its kinda wierd. Mby it is good to load entities, but just for load more items its overdose. I would like to see something rly simple like `onReachedBottom` and callback you can pass to load more items

**Comment by oyalhi** [comment]
> I tried many diff libraries during my career. The only lib which can be well used for Chat-like view is https://github.com/Flipkart/recyclerlistview

Also looking for a lib where it can start from the bottom without weird UI behavior. `recyclerlistview` doesn't look like it's maintained.

**Comment by jenyafomin** [comment]
I found a solution with [tanstack/virtual](https://tanstack.com/virtual/latest)
And here is a [guide on medium](https://medium.com/@rmoghariya7/reverse-infinite-scroll-in-react-using-tanstack-virtual-11a1fea24042). 

I hope it will be helpful to someone
