### ISSUE TITLE
scrollToIndex prop not working with List and WindowScroller

### ISSUE THREAD

**Issue by workboxsoftware** [bvaughn/react-virtualized#1623]
## Bug Report

The demo app is not working.
https://bvaughn.github.io/react-virtualized/#/components/WindowScroller

### What is the current behavior?

The scrollToIndex prop is ignored.
Run the demo and enter a number in the Scroll To field.

### What is the expected behavior?

The list will scroll to the entered index.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
I'm running this on Mac Chrome and Safari

**Comment by chyyran** [comment]
Encountering this behaviour as well on 9.22.3

**Comment by loborobo** [comment]
The last working version is 9.21.1.

**Comment by NicolasRannou** [comment]
Is it still happening (I'm guessing so from the demo), I can get the scrollTop `WindowScroller` working with a`List` as I try to set the "scrollTop" position of the `WindowScroller` on load...

Thanks!

**Comment by workboxsoftware** [comment]
Hi Brian - 

Thanks for looking into this.  I’ve actually switched to react-window (which is working perfectly!) so I’m not sure of the status of this item.   I didn’t close the item since it looked like other people were also having this problem.

Thank you very much for your work on this - react-window has made a huge difference in the performance of my app.

Bob

On May 10, 2021, at 11:09 AM, Nicolas Rannou ***@***.***> wrote:


Is it still happening (I'm guessing so from the demo), I can get the scrollTop WindowScroller working with aList as I try to set the "scrollTop" position of the WindowScroller on load...

Thanks!
