### ISSUE TITLE
Big list with max-height and overflow container don't show all list items

### ISSUE THREAD

**Issue by eduAbreu** [bvaughn/react-virtualized#1631]
## Bug Report

When having WindowScroller + AutoSizer + List with a container containing a `max-height` and `overflow: hidden auto;` is not showing all the list items.
https://codesandbox.io/s/goofy-feather-kkqg8?file=/src/App.js:2079-2083

Did anyone got the same issue?

**Comment by mateBe95** [comment]
bump

**Comment by ZafarAli110** [comment]
Did you manage to fix it?
