### ISSUE TITLE
Failed to execute 'createPolicy' on 'TrustedTypePolicyFactory'

### ISSUE THREAD

**Issue by codejunkienick** [bvaughn/react-virtualized#1634]
### What is the current behavior?

React-virtualized triggers this error
Failed to execute 'createPolicy' on 'TrustedTypePolicyFactory': Policy with name react-virtualized-auto-sizer already exists.

### What is the expected behavior?
react-virtualized checks for existing policy

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
Worked on previous versions. Most likely latest release with trusted types triggered this.
|                   |          |
|-------------------|----------|
| Browser           |         any |
| OS                |         any |
| React             |        16.4.0  |
| React DOM         |         16.4.0 |
| react-virtualized |        9.22.3  |

Code that triggers error is in `react-virtualized/dist/es/vendor/detectElementResize.js`
```
        element.__resizeListeners__ = [];
        (element.__resizeTriggers__ = doc.createElement('div')).className = 'resize-triggers';
        var resizeTriggersHtml = '<div class="expand-trigger"><div></div></div>' + '<div class="contract-trigger"></div>';
        if (window.trustedTypes) {
          var staticPolicy = trustedTypes.createPolicy('react-virtualized-auto-sizer', {
            createHTML: function createHTML() {
              return resizeTriggersHtml;
            }
          });
          element.__resizeTriggers__.innerHTML = staticPolicy.createHTML('');
```

**Comment by HZ-labs** [comment]
```
MiuiBrowser 12.9.3
XiaoMi Mi 10T
Android 10
```

**Comment by KurtPreston** [comment]
Reproducible by:
1. Enable the `#enable-experimental-productivity-features` Chrome flag on `chrome://flags`. (This is what causes `window.trustedTypes` to exist)
2. Mount two `<AutoSizer/>` components on the same page.

**Comment by KurtPreston** [comment]
Noticed this was fixed by #1627, though code has not yet been published to a new version.

**Comment by MaximeCheramy** [comment]
We're also impacted by this issue. @bvaughn it seems that the bug has already been fixed but not published. Is there something we could do to help?

**Comment by rxflamel** [comment]
Same here

**Comment by zhoushan1** [comment]
Same here+1

**Comment by Leonardo-zyh** [comment]
Same here+1
