### ISSUE TITLE
have some cell merge properties?

### ISSUE THREAD

**Issue by thiagokim17** [bvaughn/react-virtualized#1637]
I use the LIST component to display the data on screen, do you know if that component or any other has this option?

Something like that
![image](https://user-images.githubusercontent.com/45860666/109058286-95dd3500-76c1-11eb-82bb-3c8e86a7d3b9.png)

**Comment by LifeisFuckingMovie** [comment]
I have this problem too, have you solved it?

**Comment by akshit-mt** [comment]
any updates on this?, stuck on the same
