### ISSUE TITLE
ScrollSync problem - filtering in tables with fixed header

### ISSUE THREAD

**Issue by martinpesout** [bvaughn/react-virtualized#165]
I'm using `ScrollSync` solution for datatables with fixed header. I need to be able to scroll horizontally and vertically. It works nicely:

![snimek obrazovky 2016-03-22 v 13 25 53](https://cloud.githubusercontent.com/assets/239468/13951503/b405aad8-f031-11e5-80fc-14b15910e3ca.png)

Problem starts when I'm trying to add custom filters into column headers. Because Grid has `overflow: hidden;` I cannot display elements overflowing outside from the table. In my case I have problem with options list for selectboxes:

![snimek obrazovky 2016-03-22 v 13 29 56](https://cloud.githubusercontent.com/assets/239468/13951581/4019f3bc-f032-11e5-8fdb-013976be5af6.png)

Is there anybody who was trying to solve this problem? Is it possible to solve it somehow? Thanks a lot.

**Comment by Guria** [comment]
@martinpesout maybe [react-overlays](http://react-bootstrap.github.io/react-overlays/examples/) could be useful for you?

**Comment by martinpesout** [comment]
Thanks. I'm playing with this right now and it seems that this is impossible to make it work. Do you have any working example of `react-overlfays`? It seems that library calculates position of popup overlay always with `left: 0; top: 0;`

**Comment by bvaughn** [comment]
@Guria's recommendation is a good one. My team at Treasure Data uses react-virtualized and react-overlays overlays together to do what you're describing.

Also, all of react-virtualized's styles are customizable. You can either fork the styles.css file, or override the `.Grid` (or other) classes in your own smaller file, or you can attach custom class names to a given virtualized component. Lots of ways to change the overflow behavior if you find it inconvenient.

Since this is not a react-virtualized issue per-say, more of a discussion, I'm going to close this ticket. We can still chat here if you'd like.

**Comment by martinpesout** [comment]
@Guria okey. 

Can you show me how you are using `react-overlays` together with `react-virtualized`? This http://react-bootstrap.github.io/react-overlays/examples/#overlay solution works like a charm. But when I'm trying to integrate it into `Grid` in `react-virtualized`, `Overlay` is always aligned to the top left corner of the grid (with attributes `left: 0; top: 0;`).

**Comment by martinpesout** [comment]
I've found that problem starts when I'm using `react-overlays` inside `<ScrollSync>` component.

**Comment by bvaughn** [comment]
Can you post a fiddle or something, @martinpesout

**Comment by Guria** [comment]
@martinpesout sorry, haven't used overlays yet. Just shared a link I have found could be useful

**Comment by martinpesout** [comment]
I've found solution of this problem. This is my example:

```
<ScrollSync>
	{({ clientHeight, clientWidth, onScroll, scrollHeight, scrollLeft, scrollTop, scrollWidth }) => {
		return (
			<div>
				<div style={{
					position: 'relative',
					height: 70,
					width: this.state.tableWidth - scrollbarSize(),
				}}>
					<Grid
						className={'HeaderGrid'}
						columnWidth={300}
						columnsCount={5}
						height={70}
						renderCell={this._renderHeaderCell}
						rowHeight={70}
						rowsCount={1}
						scrollLeft={scrollLeft}
						width={this.state.tableWidth - scrollbarSize()}
					/>
				</div>

				<div
					style={{
						height: this.state.tableHeight - 70,
						width: this.state.tableWidth,
					}}
				>
					<Grid
						width={this.state.tableWidth}
						height={this.state.tableHeight - 70}
						columnWidth={300}
						rowHeight={this._getRowHeight}
						columnsCount={5}
						onScroll={onScroll}
						rowsCount={list.length}
						renderCell={({ columnIndex, rowIndex }) => list[rowIndex][columnIndex]}
					/>
				</div>
			</div>
		);
	}}
</ScrollSync>
```

For test purposes I've tried to add this example http://react-bootstrap.github.io/react-overlays/examples/#overlay

```
<ScrollSync>
	{({ clientHeight, clientWidth, onScroll, scrollHeight, scrollLeft, scrollTop, scrollWidth }) => {
		return (
			<div>
				<div style={{
					position: 'relative',
					height: 70,
					width: this.state.tableWidth - scrollbarSize(),
				}}>
					<Grid
						className={'HeaderGrid'}
						columnWidth={300}
						columnsCount={5}
						height={70}
						renderCell={this._renderHeaderCell}
						rowHeight={70}
						rowsCount={1}
						scrollLeft={scrollLeft}
						width={this.state.tableWidth - scrollbarSize()}
					/>
				</div>

				<div className='overlay-example'>
				  <button ref='target'>
					I am an Overlay target
				  </button>
				</div>

				<Overlay
				  show={true}
				  placement={'bottom'}
				  container={this}
				  shouldUpdatePosition={true}
				  target={ props => findDOMNode(this.refs.target)}
				>
				  <ToolTip>
					I'm placed to the: <strong>bottom</strong>
				  </ToolTip>
				</Overlay>

				<div
					style={{
						height: this.state.tableHeight - 70,
						width: this.state.tableWidth,
					}}
				>
					<Grid
						width={this.state.tableWidth}
						height={this.state.tableHeight - 70}
						columnWidth={300}
						rowHeight={this._getRowHeight}
						columnsCount={5}
						onScroll={onScroll}
						rowsCount={list.length}
						renderCell={({ columnIndex, rowIndex }) => list[rowIndex][columnIndex]}
					/>
				</div>
			</div>
		);
	}}
</ScrollSync>
```

React-overlay doesn't work. If I remove `<ScrollSync>` wrapper, situation will be fixed. But I need `<ScrollSync>` in my project. After small investigation, I've found that problem is in `findDOMNode(this.refs.target)`. Refs doesn't work. I've found a small trick to get it work:

```
var button = (
  <div className='overlay-example'>
    <button ref='target'>
      I am an Overlay target
    </button>
  </div>
);

<ScrollSync>
	{({ clientHeight, clientWidth, onScroll, scrollHeight, scrollLeft, scrollTop, scrollWidth }) => {
		return (
			<div>
				<div style={{
					position: 'relative',
					height: 70,
					width: this.state.tableWidth - scrollbarSize(),
				}}>
					<Grid
						className={'HeaderGrid'}
						columnWidth={300}
						columnsCount={5}
						height={70}
						renderCell={this._renderHeaderCell}
						rowHeight={70}
						rowsCount={1}
						scrollLeft={scrollLeft}
						width={this.state.tableWidth - scrollbarSize()}
					/>
				</div>

				{button}

				<Overlay
				  show={true}
				  placement={'bottom'}
				  container={this}
				  shouldUpdatePosition={true}
				  target={ props => findDOMNode(this.refs.target)}
				>
				  <ToolTip>
					I'm placed to the: <strong>bottom</strong>
				  </ToolTip>
				</Overlay>

				<div
					style={{
						height: this.state.tableHeight - 70,
						width: this.state.tableWidth,
					}}
				>
					<Grid
						width={this.state.tableWidth}
						height={this.state.tableHeight - 70}
						columnWidth={300}
						rowHeight={this._getRowHeight}
						columnsCount={5}
						onScroll={onScroll}
						rowsCount={list.length}
						renderCell={({ columnIndex, rowIndex }) => list[rowIndex][columnIndex]}
					/>
				</div>
			</div>
		);
	}}
</ScrollSync>
```

If I place definition of target element outside from `<ScrollSync>`, `react-overlays` example will be fixed.

Thanks for you time @Guria and @bvaughn

**Comment by bvaughn** [comment]
Makes sense. Thanks for sharing your solution. :)
