### ISSUE TITLE
Virtualized nested list react-beautiful-dnd (Cannot find droppable entry with id(uuid)) 

### ISSUE THREAD

**Issue by parkderick** [bvaughn/react-virtualized#1652]
## Bug Report
I’ve included here a code sandbox example link:
https://codesandbox.io/s/testdummy1-fe6xq?file=/src/App.js

### What is the current behavior?
I have 2 draggables within the virtual list
1. List - Dragging a list down the scrollbar works fine.
2. Card - Dragging a card down the scrollbar leads to “Invariant failed: Cannot find droppable entry with id ……”.

### What is the expected behavior?
Scrollbar to scroll down when dragging card as it does when dragging list.
My hypothesis: The virtual list reshuffles the wrong lists as a child of the virtual list is being dragged down.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           | Chrome Version 90.0.4430.85 (Official Build) (x86_64) |
| OS                |          |
| React             | 17.0.2 |
| React DOM         | 17.0.2 |
| react-virtualized | 9.22.3 |
| react-beautiful-dnd | 13.1.0 |

Any help would be much Appreciated! Thank you!

**Comment by bankangle** [comment]
did you find any solution? I got exact the same error with react-window package
