### ISSUE TITLE
Columns are overlapping when readmore options included

### ISSUE THREAD

**Issue by karthik1120** [bvaughn/react-virtualized#1654]
## Bug Report

I'm using the react-virtualized for a while. it's really cool, but I'm facing some overlapping issues sometimes while included the Readmore option if the column contains large text or it contains more than 350 characters. 

<img width="718" alt="Screenshot 2021-05-12 at 2 32 41 PM" src="https://user-images.githubusercontent.com/66789160/117948611-eb26fb00-b32e-11eb-99df-c49467a936a1.png">

### What is the current behavior?
it start overlapping when performing some actions inside the column, like Readmore or edit

### What is the expected behavior?
it should not overlap when I perform some action inside each column 

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |   chrome       |
| OS                |     mac     |
| React             |    16.12.0      |
| React DOM         |    16.12.0      |
| react-virtualized |     9.21.2     |

**Comment by ZafarAli110** [comment]
You will need to call recomputeRowHeights(rowIndex) whenever you change the height of the cell dynamically.
