### ISSUE TITLE
not installing without --force flag with react ^17.0.0

### ISSUE THREAD

**Issue by liesislukas** [bvaughn/react-virtualized#1655]
if there is no reason to not support react 17+ i suggest adding react ^17.0.0 to peer dependencies and there is ^17.0.1

I found many other libs to have ^17.0.0 and this is the only which has ^17.0.1

made PR for this, if agreed

![image](https://user-images.githubusercontent.com/2733862/119218287-4eabe800-bae8-11eb-87fd-b846906d9e21.png)

**Comment by balovbohdan** [comment]
We really need this update. There are warnings about incorrect peer deps.

**Comment by riteshahlawat** [comment]
I am also having this same issue, I'm using react-virtualized for electron and electron-builder npm installs all the packages and keeps failing. Not to mention that I can't add any arguments (like --force or --legacy-peer-deps). The temporary fix I have done for now is to manually change the peer deps on my own

**Comment by pierre-H** [comment]
ping @bvaughn 😃

**Comment by wallzero** [comment]
`npm install --legacy-peer-deps` works as an alternative to `--force`

**Comment by slutske22** [comment]
Good lordy I see that this was added to the package.json on the github repo:

```
"peerDependencies": {
    "react": "^15.3.0 || ^16.0.0-alpha || ^17.0.1",
    "react-dom": "^15.3.0 || ^16.0.0-alpha || ^17.0.1"
  },
```

However this is not yet published to npm.  It is causing a disastrous monstrosity to occur when trying to install. Please publish this up to npm so I don't have to hack my install with `--legacy-peer-deps`!

**Comment by rscotten** [comment]
@bvaughn please publish!  We're being blocked by this on Firebase cloud functions.

**Comment by bvaughn** [comment]
I haven't used this package in years. I don't have the mental bandwidth the maintain it. If someone else (preferably someone who actively uses it) wants to step up and publish this release (and deal with any potential breaks it causes, since there are several changes committed since the last release) then please email me.

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4
