### ISSUE TITLE
虚拟列表不会重新加载问题

### ISSUE THREAD

**Issue by kuiGe11** [bvaughn/react-virtualized#1664]
您好，按理来说在react中更改state后，组件就会重新加载，但是虚拟列表不会，只有页面发生改变的时候，比如说页面滚动，页面放大和缩小，组件才会重新加载，这是怎么回事呢？

**Comment by wdmxzf** [comment]
是不是数据更新了，你没有调用 forceUpdateGrid()方法，画面没有再次渲染啊！？或者使用CellMeasurer没有clearAll（）重新加载缓存啊！？

**Comment by wdmxzf** [comment]
> 您好，按理来说在react中更改state后，组件就会重新加载，但是虚拟列表不会，只有页面发生改变的时候，比如说页面滚动，页面放大和缩小，组件才会重新加载，这是怎么回事呢？



> 您好，按理来说在react中更改state后，组件就会重新加载，但是虚拟列表不会，只有页面发生改变的时候，比如说页面滚动，页面放大和缩小，组件才会重新加载，这是怎么回事呢？

是不是数据更新了，你没有调用 forceUpdateGrid()方法，画面没有再次渲染啊！？或者使用CellMeasurer没有clearAll（）重新加载缓存啊！？
