### ISSUE TITLE
Way to track active List Elements

### ISSUE THREAD

**Issue by shubham43MP** [bvaughn/react-virtualized#1665]
## Feature Request

I have found a use case where I need those elements from React Virtualised, that are rendered on the DOM.

In the current API, I dont think we have this facility to show out which elements are being rendered.

Some word about use case:
I am rendering a large list of Speech To Text data for a media (audio/video).
I need a sync for video with the list which I have already implemented.
But for every video part, I also need to add tracks (subtitles) and the data in that large list is allowed to be varied due to which I need to update all the subtitles and then again add new ones for the sync in the video.
If I have those list of rendered elements in React Virtualised, I only need to remove and add 10-12 tracks.
This can be efficient for the use case.

Any suggestions in current API that I may be missing is highly appreciated.

Thanks in advance!

**Comment by 18566246732** [comment]
I have the same needs, any update on this ?
