### ISSUE TITLE
table has blue outline when tested in Safari on MAC. 

### ISSUE THREAD

**Issue by davidlislc** [bvaughn/react-virtualized#1666]
## Bug Report

https://bvaughn.github.io/react-virtualized/#/components/Table

### What is the current behavior?

When visited by safari from MAC, when the virtalized table becomes active, it shows a blue outline. It is very ugly.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |    Safari      |
| OS                |      MAC    |
| React             |          |
| React DOM         |          |
| react-virtualized |    the latest
![Screen Shot 2021-06-30 at 6 14 02 PM](https://user-images.githubusercontent.com/4028680/124038717-9703d300-d9cf-11eb-8795-38aa0c039545.png)
      |

**Comment by cmmartin** [comment]
You can very easily remove it with a line of CSS
