### ISSUE TITLE
Cell hover effects

### ISSUE THREAD

**Issue by martinpesout** [bvaughn/react-virtualized#167]
I'm using `Grid` component and now I'm trying to implement hover effect for columns in `Grid`. Every time  I hover some cell, I'll call custom method and set the state:

```
this.setState({
    highlightedColumn: columnIndex,
});
```

This is working. But depends on this state in `highlightedColumn` I want to set custom class to rendered cells. I'm using `_renderCell` method:

```
_renderCell({ columnIndex, rowIndex }) {
		var cellClasses = classNames({
			'GridCell': true,
			'GridCell--odd-row': rowIndex % 2 === 0,
			'GridCell--highlighted': this.state.highlightedColumn === columnIndex,
		});

		return (
			<div className={cellClasses}>
				... CELL CONTENT ...
			</div>
		);
	},
```

Problem is that class doesn't update. RenderCell is called only when I scroll with the Grid. Is there any chance to re-render Grid also when I update state of component?

**Comment by bvaughn** [comment]
Tried using the React [`forceUpdate`](https://facebook.github.io/react/docs/component-api.html#forceupdate) method? I think the docs mention this somewhere but... I don't recall. :)

**Comment by bvaughn** [comment]
I'm going to close this issue since it's just a question and _I think_ I've actually answered it. But if not, we can keep chatting on the issue. I don't mind. I just don't like leaving non-actionable issues open.

**Comment by martinpesout** [comment]
`forceUpdate` doesn't work in this case. This is our example for big datatable with many columns and fixed header:

```
<ScrollSync>
	{({ clientHeight, clientWidth, onScroll, scrollHeight, scrollLeft, scrollTop, scrollWidth }) => {
		return (
			<div>
				<div style={{
					position: 'relative',
					height: headerHeight,
					width: tableWidth - scrollbarSize(),
				}}>
					<Grid
						className={'HeaderGrid'}
						columnWidth={this._getColumnWidth}
						columnsCount={5}
						height={headerHeight}
						onScroll={onScroll}
						renderCell={this._renderHeaderCell}
						rowHeight={headerHeight}
						rowsCount={1}
						scrollLeft={scrollLeft}
						width={tableWidth - scrollbarSize()}
					/>
				</div>

				<div
					style={{
						height: tableHeight - headerHeight,
						width: tableWidth,
					}}
				>
					<Grid
						width={tableWidth}
						height={tableHeight - headerHeight}
						columnWidth={this._getColumnWidth}
						rowHeight={this._getRowHeight}
						columnsCount={5}
						onScroll={onScroll}
						rowsCount={pagesCount}
						renderCell={this._renderTableCell}
						scrollLeft={scrollLeft}
					/>
				</div>
			</div>
		);
	}}
</ScrollSync>
```

When called `forceUpdate` I checked that `<Grid>` itself is re-rendered, but I expected also calling of `this._renderTableCell` again. This didn't happen. I set classes for each cell in `this._renderTableCell`. Is there any different way how to re-render cells?

Thanks

**Comment by bvaughn** [comment]
Works for me? ([live demo](https://rawgit.com/bvaughn/react-virtualized/master/playground/hover.html), [source code](https://github.com/bvaughn/react-virtualized/blob/master/playground/hover.js))

![untitled screencast](https://cloud.githubusercontent.com/assets/29597/14151889/12cd3d4a-f665-11e5-907a-3939c20c833b.gif)

**Comment by martinpesout** [comment]
Thanks. Your example help us to solve it. Problem was that I was trying to target Grid directly by `this.refs.Grid`. This syntax `this.refs.AutoSizer.refs.Grid` is right in this case.

**Comment by bvaughn** [comment]
Ah, glad to hear it :)
