### ISSUE TITLE
`scrollToIndex` doesn't work when `scrollTop` is set in List

### ISSUE THREAD

**Issue by aayushdutt** [bvaughn/react-virtualized#1675]
## Bug Report

I have to use both scroll-sync (which requires setting `scrollTop`) and `scrollToIndex` to navigate to a page, but scrollToIndex doesn't work seemingly due to scrollTop is already set by ScrollSync
Any idea?

**Comment by bartlomiejwendt** [comment]
Hello, I've occurred the exact same problem and for me downgrading the react-virtualized version to "9.18.5" worked like a charm.

**Comment by aayushdutt** [comment]
I got it working with a hacky workaround. Used a `useEffect` to set `scrollTop` to `null` when `scrollToIndex` changes.

**Comment by ibbeyo** [comment]
@aayushdutt This worked! Since i'm using `WindowScroller`, i ended up doing the following `scrollTop={isScrolling && scrollTopl}`
