### ISSUE TITLE
InfiniteLoader occasionally does not make a loadMore request after search filter changes

### ISSUE THREAD

**Issue by nrmad** [bvaughn/react-virtualized#1677]
I have a search using List and InfiniteLoader which can be used to display widgets within rows. Sometimes updating the rowCount with the new result count and setting the loadedMap in addition to the current set of data as empty is enough to cause the request but sometimes it is not. I cannot ascertain the reason. I have attempted to call the methods resetLoadMoreRowsCache() on the InfiniteLoader ref and forceUpdateGrid() on the registeredChild list subsequent to my API request however this does not fix the issue. 

I tried to do an issue for this before with a code sandbox but my code is complicated and I accidentally deleted it, gave up and now I am back. Having tried to fix this for several days, I will attempt a hack where I cause a remount of the entire component on event the filter inputs change to circumvent this or my brain will melt.

**Comment by AaronMcCloskey** [comment]
I also have this issue, did you find a solution?
