### ISSUE TITLE
Adding a node reference prop to the virtualized table as to avoid using findDOMNode

### ISSUE THREAD

**Issue by g1eb** [bvaughn/react-virtualized#1682]
ReactDom.findDOMNode is deprecated in React strict mode and is really vocal about it in the console.

Is it possible to add a new prop to the virtualized table with a direct node reference to the table? As to avoid doing 
 `findDOMNode` on this line here: https://github.com/bvaughn/react-virtualized/blob/e360d958b99fa965fd3f1caed4506403ad652cd3/source/Table/Table.js#L342

Similar to how we have `registerChild` on the window scroller: https://github.com/bvaughn/react-virtualized/blob/master/docs/WindowScroller.md#render-props 

An example of how the folks at `react-draggable` dealt with this:
https://github.com/react-grid-layout/react-draggable/pull/478

**Comment by giorgi-blackbird** [comment]
Hi, any updates on this?

**Comment by dor6-deepcred** [comment]
bump
