### ISSUE TITLE
Are there plans to update react-virtualized to the newer React version?

### ISSUE THREAD

**Issue by Braweria** [bvaughn/react-virtualized#1690]
An Error I am currently getting is that `findDOMNode` is getting deprecated and ref should be used instead. Looking at the library everything is written in Class Components.

I know of react-window, but it doesn't have the Masonry component and [according to you, the creator, people should use react-virtualized if they want to use the Masonry layout](https://github.com/bvaughn/react-window/issues/302#issuecomment-516522627).
So that made me wonder if there are any future plans for this library.

**Comment by alexander-agysov** [comment]
Did you try 'registerChild'?
https://github.com/bvaughn/react-virtualized/blob/master/docs/WindowScroller.md

**Comment by Braweria** [comment]
@bvaughn Could you give us an update on this?

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4
