### ISSUE TITLE
CellMeasurer with a function child instead of an element child changes scrolling behavior

### ISSUE THREAD

**Issue by cobyrne-pivot** [bvaughn/react-virtualized#1692]
## Bug Report

First, thank you for the useful library!

The problem I'm running into is that using `CellMeasurer` within a `List` with dynamically sized rows behaves differently based on whether its `children` is a function or an element. When given a function child, the scrollbar changes size while scrolling back up the list, which I'd like to avoid if possible.

### What is the current behavior?

I made a demo [here](https://plnkr.co/edit/hmwLtNtYnYdtI9dX). I'm loading data for each row asynchronously, so I'm giving `CellMeasurer` a function and then calling `measure()` when I know I've received and rendered the real data.

This works as expected when scrolling down: as real heights are calculated, the scrollbar shrinks as the scrollable area grows as real heights are calculated to be larger than the defaults. Not the greatest experience for users who prefer to drag the scrollbar but it's hard to imagine any way around that.

When scrolling up, though, the scrollbar grows again. The effect is kind of subtle in the demo, but it's extremely noticeable in my real scenario.

### What is the expected behavior?

It feels like since we've already calculated all the heights while scrolling down, we should be able to preserve the scrollable area height while scrolling up, and in fact this is how it works if you pass an element as the child of `CellMeasurer`, demo [here](https://plnkr.co/edit/Itf4bs6oolFJ5D5E).

Could `measure()` behave consistently with how it works for element children? I noticed `_measure` and `_maybeMeasureCell` are calling different methods on the parent, but  I'm not sure what effect that has. Alternatively, is there a better way to use `measure()` to get the behavior I want?

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |      Chrome    |
| OS                |       MacOS   |
| React             |       16.9.0   |
| React DOM         |    16.9.0      |
| react-virtualized |     9.22.2     |

**Comment by mdimitrov-finovation** [comment]
Hey @cobyrne-pivot, I have the same issue right now, do you have a solution for your issue?

**Comment by velidan** [comment]
The same

**Comment by vizath** [comment]
I found out that you can check your cache before calling `mesure()`.
`<OnLoadListener onLoad={() => !heightCache.has(index, 0) && measure()} />` in [your example](https://plnkr.co/edit/hmwLtNtYnYdtI9dX?preview)

This happen because [recomputeGridSize](https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.js#L146) seems to reset its internal cell height cache when you call `measure()` on one cell. I haven't dig too far in the Grid internals.
