### ISSUE TITLE
React-vertualized Multigrid scroll error? in chrome

### ISSUE THREAD

**Issue by Pyosoo** [bvaughn/react-virtualized#1694]
## Bug Report

Please include either a failing unit test or a simple repro. You can start by forking this Code Sandbox: https://codesandbox.io/s/03qpzq1p9p?module=%2FExample.js

### What is the current behavior?

https://bvaughn.github.io/react-virtualized/#/components/MultiGrid
scroll right side grid is not working(actually working very slowly)
this happen only in chrome.
i didnt write anything in code.

### What is the expected behavior?

scroll smoothly

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |          |
| OS                |          |
| React             |          |
| React DOM         |          |
| react-virtualized |          |

**Comment by cr1stimuresan** [comment]
I'm experiencing the same issue with chrome Version 94.0.4606.61 only on windows

**Comment by fangdu64** [comment]
Experiencing the same issue also with chrome Version 94.0.4606.61

**Comment by fangdu64** [comment]
Saw below issues reported in other places:
https://discuss.codemirror.net/t/scrolling-is-badly-impacted-by-chrome-94-0-4606-61/3567/7
https://bugs.chromium.org/p/chromium/issues/detail?id=1253766

**Comment by ralles-liu** [comment]
I am also experiencing this issue on chrome (safari works properly)

**Comment by LazzyLizzard** [comment]
> the cause of this is chorme version.

Any solution or bigfix planned for this case?
