### ISSUE TITLE
Row heights do not update after using placeholder

### ISSUE THREAD

**Issue by HarryBrooks** [bvaughn/react-virtualized#1697]
Hi,

I am using the List component with autosizer, cell measurer and cache and all works brilliantly (thanks for developing this, its amazing!). 

However, my issue arises when I use a placeholder due to the amount of data I'm loading in. After the placeholder has been used, I need to update the height of the row in the list, but I can't find the best place to clear the cache (for a row or the entire list). It generally ends with an infinite loop. I suspect this is a lack of understand on my part, but would you be able to advise me on where I should be calling cache.clear() or cache.clearAll(), as I feel that would solve my issue.

Thanks!

**Comment by AaronMcCloskey** [comment]
Also having this issue, did you find a solution?
