### ISSUE TITLE
AutoSizer should use default values if computed values are 0

### ISSUE THREAD

**Issue by Nokel81** [bvaughn/react-virtualized#1703]
## Feature Request

If AutoSizer is used as a child to a component that has `overflow: "scroll"` it computes values that are 0. This makes sense because there is no upper bound the the size. However, when used with items like `VariableSizeList` from `"react-window"` nothing is rendered.

It would be nice if the `defaultHeight` or `defaultWidth` props (or maybe some new props) could be used so that in the case where the height is incalculable there is a fallback value

**Comment by alexander-agysov** [comment]
Did you try 'estimatedRowSize' prop for a List?

**Comment by Nokel81** [comment]
I wasn't using that component so no
