### ISSUE TITLE
ScrollSync programmatically seems to sync breaks up

### ISSUE THREAD

**Issue by Mirza-Hassan** [bvaughn/react-virtualized#1706]
Hi,

I am facing an issue in ScrollSync doesn't seem to sync correctly. When scrolling programmatically due to an outside event the sync breaks up. How can you fix this? any help is appreciated. Thanks !

```
  useEffect(() => {
    scrollRef.current = scrollRef.current.slice(0, visits.length);
    scrollRef?.current[visits.length - 1]?.scrollIntoView({ block: 'nearest', inline: 'nearest' });
  }, [visits]);
```

<img width="579" alt="Screenshot 2021-10-29 at 4 48 07 PM" src="https://user-images.githubusercontent.com/17096257/139429472-ac9b9691-ef51-43fb-af3b-23c9da10e381.png">

**Comment by bogdanblunt** [comment]
Any update on this issue ?
