### ISSUE TITLE
Upgrade dependencies to support React 17

### ISSUE THREAD

**Issue by chrismatthieu** [bvaughn/react-virtualized#1711]
npm ERR! While resolving: app@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3

**Comment by helen508light** [comment]
Also waiting for it

**Comment by helen508light** [comment]
@bvaughn Am i right and now only react-virtualized allows render dynamic row's height in List(not react-window)?

**Comment by Rahul-joshi10** [comment]
Waiting this issue to get fixed.

**Comment by 777okhtar** [comment]
No updates?

**Comment by danielloczi** [comment]
+1

**Comment by poveilleux** [comment]
+1, I have faced this in our project today when trying to install React 17...

**Comment by stovmascript** [comment]
It's merged: https://github.com/bvaughn/react-virtualized/blob/master/package.json#L149-L152, but not released :|

**Comment by AaronLayton** [comment]
Lol same :-)

Anything I can do to help?

**Comment by deadlyicon** [comment]
Anyone maintaining this repo? Need help publishing for React 17?

**Comment by jjbell150** [comment]
Looks like react-virtualized has been dropped for react-window, which is pretty useless on its own as it doesn't even have support for table headers

React-base-tables seems to solve that problem though, it's built upon react-window and almost seems like a drop-in replacement for react-virtualized with more features

**Comment by vitormil** [comment]
+1

**Comment by huhm** [comment]
+1

**Comment by vova42matters** [comment]
+1

**Comment by pthanh1703** [comment]
+1

**Comment by AftabFalak** [comment]
any news?

**Comment by derwaldgeist** [comment]
+1

Just read in another thread that `npm install --legacy-peer-deps` works, but that's an ugly workaround.

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4
