### ISSUE TITLE
Suggestion - optimize calls to rowGetter

### ISSUE THREAD

**Issue by joewood** [bvaughn/react-virtualized#172]
In FlexTable the loop over _createColumn makes a call to rowGetter with the [same rowIndex number](https://github.com/bvaughn/react-virtualized/blob/0b9a6869541c74e55b17927c67434e6727c0c5b5/source/FlexTable/FlexTable.js#L325) for each column in the row. 

Could this call to `rowGetter` be pulled of this loop as it's expected to return the same object for each call? 

```javascript
    const renderedRow = React.Children.map(
      children,
      (column, columnIndex) => this._createColumn(
        column,
        columnIndex,
        rowGetter(rowIndex),
        rowIndex
      )
    )
```
I was using FlexTable and had this function constructing the object and doing some processing. The number of calls into this function could be reduced by simple taking the call out of the loop.

To:
```javascript
    const row = rowGetter(rowIndex);
    const renderedRow = React.Children.map(
      children,
      (column, columnIndex) => this._createColumn(
        column,
        columnIndex,
        row,
        rowIndex
      )
    )
```

**Comment by bvaughn** [comment]
Sure, seems a reasonable suggestion.

**Comment by bvaughn** [comment]
Version 6.0.3 was just released with this change. Thanks for the suggestion!
