### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by ServOKio** [bvaughn/react-virtualized#1727]
Hello 👋, I have a simple question - how can I install ? I think I've met a problem that I can't figure out

```bash
F:\PC2\documents\React\pere>npm install react-virtualized
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: pere@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized@9.22.3
npm ERR! node_modules/react-virtualized
npm ERR!   react-virtualized@"^9.22.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Wuwfm\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Wuwfm\AppData\Local\npm-cache\_logs\2022-03-11T00_26_42_819Z-debug-0.log
```

**Comment by ServOKio** [comment]
Okay, I was able to install using `--force`, but now I have another question - how can I designate my key or something else? I have messages, the number of which is replenished, but when new ones are received, this is what happens:
![2022-03-11_05-51](https://user-images.githubusercontent.com/51263003/157793315-88360fd1-72b9-479c-af8f-a61bc298dcf2.png)
How can I fix this ? Maybe I should change something in `CellMeasurerCache` ?

**Comment by AftabFalak** [comment]
same issue. any update?

**Comment by ServOKio** [comment]
> same issue. any update?

`npm install react-virtualized --force` 🤷‍♀️

**Comment by nemonemi** [comment]
I don't think it makes sense to start using a library that has no good support.

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4
