### ISSUE TITLE
Cut a new release please? 🙏🙏 

### ISSUE THREAD

**Issue by benatshippabo** [bvaughn/react-virtualized#1728]
## Feature Request

Hello @bvaughn @wuweiweiwu @TrySound so I saw that the [changelog got updated recently](https://github.com/bvaughn/react-virtualized/commit/2e962d8f8aebc22cb1168a8d147bcaa1d27aa326) and seems ready for a release to be cut. Could we get a release cut please 🥺

**Comment by tasawar-hussain** [comment]
https://github.com/bvaughn/react-virtualized/pull/1740#issuecomment-1369136122

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4
