### ISSUE TITLE
windowScroller/utils/onScroll import an useless variable

### ISSUE THREAD

**Issue by pengYYYYY** [bvaughn/react-virtualized#1736]
### What is the current behavior?

npm package windowScroller/utils/onScroll import an useless variable.in my vite environment import error。

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/35833812/160600690-b45d0595-5631-4ecd-ab63-b7a96602c255.png">

### What is the expected behavior?

There is no `bpfrpt_proptype_WindowScroller` in es/windowScroller/utils/onScroll

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| react-virtualized |    9.22.3      |

**Comment by pengYYYYY** [comment]
https://github.com/remorses/react-virtualized-fixed-import#9.22.3

**Comment by abemedia** [comment]
I wrote an esbuild plugin to fix this by stripping out the offending line at build time, rather than having to use a patched package: https://npmjs.com/package/esbuild-plugin-react-virtualized
