### ISSUE TITLE
Your website doesn't look safe

### ISSUE THREAD

**Issue by LitoMore** [bvaughn/react-virtualized#1738]
## Asking a Question?

The website http://www.reactvirtualized.com/ on this project homepage doesn't look safe.

1. It's using HTTP. Why not HTTPS?
2. It will redirect to another domain http://ww7.reactvirtualized.com. But why?

Shall we just use the GitHub Pages instead?

**Comment by zhouzi** [comment]
Just noticed this as well, here's the page it redirects to:

![](https://user-images.githubusercontent.com/2291025/162973008-1b52ebbe-916a-4082-9526-1c01d7398a02.png)
