### ISSUE TITLE
dependency conflict while installing

### ISSUE THREAD

**Issue by amogs4165** [bvaughn/react-virtualized#1743]
I'm using using react v-18, while i installing it shows a error of dependency conflict is it ok to use --force ?

**Comment by bvaughn** [comment]
Yes. A PR has been merged already that updates the peer deps but it hasn't been released b'c someone still needs to verify/test other changes that were landed in master. You should be okay to just force for now. Let me know if that doesn't work for some reason (aka if we have a problem with 18)
