### ISSUE TITLE
Release for accepting react 17/18?

### ISSUE THREAD

**Issue by LogyLeo** [bvaughn/react-virtualized#1744]
Hi! I've seen that package.json was updated 4 days ago to accept react versions ^17.0.0 and ^18.0.0, which I need desperately! When can we expect a package release that includes these changes? Thanks

**Comment by bvaughn** [comment]
The release should be made in the next few days. @rebelliard is testing master to make sure there are no regressions.

In the meanwhile, you can always force the resolution. (It's not a _real_ blocker just a nag.)

**Comment by timglabisch** [comment]
@bvaughn any news here?
