### ISSUE TITLE
Are u agree that this library is use in real life without remote data? So why is there not good doc for that? 

### ISSUE THREAD

**Issue by fabricioAburto** [bvaughn/react-virtualized#1751]
## Are u agree that this library is use in real life without remote data? So why is there not good doc for that? 

Is a very hard to code lib, very hard. Why like so  much complexity? 

Is there a example using?
- Infinite scroll
- AutoSizer
- List
- CellMeasurer

This is are real use case where people use in real life, all here are sure of that. Why is there not a single component to encapsulate all the so love complexity u do.

Tipical case founded here:
- Fixed list items height (which is unreal thinking)
- Faked Data (unreal thinking)
- infinite scroll do working

Real use case:
- nothing o.O' unreal

**Comment by wmcdk** [comment]
This is working as designed.
