### ISSUE TITLE
InfiniteLoader, maintain state on history back

### ISSUE THREAD

**Issue by doorman02** [bvaughn/react-virtualized#1754]
## Feature Request

Considering the following use case for the [InfiniteLoader](https://github.com/bvaughn/react-virtualized/blob/master/docs/creatingAnInfiniteLoadingList.md)

1. The infiniteloader has been scrolled and contains e.g. 100-1000 items
2. One item from the list is selected and the browser routes to a detail page.
3. The user navigates back using the browser back button.
4. The infiniteloader should show the previous items and scrolled to the same position in the list.

I did some experiements to handle this but without success.

Any suggestions how this could be achieved using the infiniteloader?

Thanks!

**Comment by johnvonneumann7** [comment]
Any progress on this?

**Comment by doorman02** [comment]
Not the optimal way but I ended up using iframes to maintain the history state.

**Comment by johnvonneumann7** [comment]
Okay, jeg bruger også WindowScroller, så det ser ud til, at jeg bliver nødt til at overveje et andet bibliotek.

**Comment by johnvonneumann7** [comment]
I see, I also use WindowScroller, so I guess I will have to consider another library.
