### ISSUE TITLE
Unexpected AutoSizer wrapper width

### ISSUE THREAD

**Issue by stephenotalora** [bvaughn/react-virtualized#176]
I am noticing that in some instances when I wrap a component with `AutoSizer`, it will most often than not wrap my components with a div an inline style, now I know this is due to the `AutoSizer` `render` method. The inline style I get is always === `"overflow:visible;width:0;"` note the width value .... I do get a proper width from the AutoSizer anonymous function but the inline style defeats the purpose. While this is an easy fix on my side, and before I take a deeper look, could there be something wrong that I'm doing? or is this just a bug?

Do note that I'm not disabling width on the autosizer component, so the AutoSizer component should not set the width to 0. 

The jsx looks as follows:

```jsx
{
... some method
return (
			<AutoSizer disableHeight={true}>
				{({width}) => (
						<ComposeComponent {...this.props} width={width} />
				)}
			</AutoSizer>
		);
}
```

and the `resulting` DOM element looks like this: 
![screen shot 2016-04-05 at 3 56 04 pm](https://cloud.githubusercontent.com/assets/6519974/14300687/022ccea6-fb47-11e5-8e8c-e5298e53dc64.png)

Feedback is appreciated...

**Comment by globexdesigns** [comment]
If you don't want width to be set to 0, use `disableWidth={true}`

**Comment by stephenotalora** [comment]
but I don't want to disable to disable width

**Comment by bvaughn** [comment]
Hey @stephenotalora,

The `AutoSizer` sets the wrapper element's size so that a parent container (eg. a flex box) can shrink when appropriate. For example, check out the demo [here](https://bvaughn.github.io/react-virtualized/?component=AutoSizer). Without the div wrapper's sizing logic, the parent flex box would grow when the checkbox was checked and then grow again when it was unchecked.

@globexdesigns is right though. You can prevent the 0 width (if you don't want it) by turning on `disableWidth`. That property means you want to manually manage the width of your component and you don't need `AutoSizer` to do it. If you do need `AutoSizer` to do it...then it uses the 0 width for reasons described above.

What problem is this causing you?

**Comment by stephenotalora** [comment]
whatever component is directly under the div with the style === `"overflow:visible;width:0;"` must have a hard width, otherwise the component doesn't render. adding an example shortly.

**Comment by stephenotalora** [comment]
ah okay. I see what is happening! 

That is the width of the `AutoSizer` that needs to be pass to the next underlying component div! 
In my case the width was getting lost since the children of AutoSize was wrapped in a div. However, the width was actually never set on that div, in better words the width wasn't being set to the most outer div of the underlying component. 

The `AutoSizer` is added conditionally, this is due to the rules of my component, since it doesn't always have to resize. I ended up fixing my issue by simply wrapping my ComposeComp like this: 

```jsx
{
... some method
return (
			<AutoSizer disableHeight={true}>
				{({width}) => (
                                           <div width={{width}}>
						<ComposeComponent {...this.props} width={width} />
                                           </div>
				)}
			</AutoSizer>
		);
}
```

that what I don't necessarily have to set a width on a component that is being decorated.

**Comment by bvaughn** [comment]
Ah. Yup, makes sense. So your `ComposeComponent` was overflowing your interstitial `<div>` and being clipped?

Glad you figured it out! :)

**Comment by stephenotalora** [comment]
not even clipped, the compose component wasn't showing at all! a decorated component DOM was rendering the following into the DOM: 

```html
<div style="overflow:visible;width:0;"> <!--- div from AutoSizer  --->
    <div></div> <!--- My Component :( -->
</div>
```

with the above solution problem solve :tada:
