### ISSUE TITLE
React-virtualized compatible with the new React versions 18^

### ISSUE THREAD

**Issue by AChristoff** [bvaughn/react-virtualized#1763]
Is there a way we can enjoy a new version compatible with the new React versions 17 18... React-virtualized  is awesome and one of the most performance wise library I have ever used, but it is not touched for quite some time : /

My question is, is there a plan for a new release any time soon?

I don't feel good about using "--legacy peer deps" or downgrading @types/react to make it work in my new projects.

Thanks in advance for the replies

**Comment by quantuminformation** [comment]
you could always ask your boss to sponsor a fix

**Comment by An6r** [comment]
@AChristoff check this thread - https://github.com/bvaughn/react-virtualized/pull/1625
the change for React 17 has been merged but guess what? we need to get a new version now ;)

**Comment by Fmstrat** [comment]
Any idea how long it usually takes to get this updated?

**Comment by vladir** [comment]
Any update on this?

**Comment by dangolbeeker** [comment]
Since  this issues open without a resolution I propose a solution.

Sponsor me instead
$scott8176 cashapp

**Comment by Lucienest** [comment]
haven't seen other repos where devs beg for sponsorship for fixes or improvements.

**Comment by LitoMore** [comment]
I opened an issue about this topic:

- https://github.com/bvaughn/react-virtualized/issues/1775
