### ISSUE TITLE
reactvirtualized.com Domain has been hijacked

### ISSUE THREAD

**Issue by tlindsay** [bvaughn/react-virtualized#1770]
Clicking the link from this Github repo to the `www.reactvirtualized.com` website redirects to `ww7.reactvirtualized.com` which seems to be controlled by one of those spammy domain-parking things. I'm not sure if there's anything overtly malicious on the other end, but it would probably we worth posting a warning or something until y'all can regain control of the domain.

<img width="336" alt="Screen Shot 2022-09-14 at 14 54 39" src="https://user-images.githubusercontent.com/2797532/190249935-64f1025d-4e15-4389-8b91-990a27294419.png">

**Comment by TemaSM** [comment]
Seems to be that package moved to unmaintained state. Even domain got out of date.
There're a lot of vulnerabilities in package's dependencies, and we are still waiting for a new minor version being released with this: https://github.com/bvaughn/react-virtualized/commit/005be24a608add0344284053dae7633be86053b2 and fix of this: https://github.com/bvaughn/react-virtualized/issues/1632

So, let's relax and see how this package will probably die in favor of someone fork or better version 😃 

_*Yeah, React ecosystem bad in compare with Vue, IMHO 🥲_

**Comment by lirbank** [comment]
@bvaughn The URL sent me to a page that wanted me to install a chrome extension to make my browser "safer" (but it didn't happen on the next attempt, after I cancelled). It would be awesome if you just removed the URL from the GitHub page so people don't click in.

![CleanShot 2023-01-29 at 17 52 41@2x](https://user-images.githubusercontent.com/2538130/215371460-e634d88c-4977-4025-8e89-eae857c4343f.png)

Related to/dupes:
https://github.com/bvaughn/react-virtualized/issues/1719
https://github.com/bvaughn/react-virtualized/issues/1735
https://github.com/bvaughn/react-virtualized/issues/1738
https://github.com/bvaughn/react-virtualized/issues/1788
