### ISSUE TITLE
List component horizontal scroll

### ISSUE THREAD

**Issue by tesla-cat** [bvaughn/react-virtualized#1773]
when there is a horizontal overflow, there is no scroll bar!

<img width="371" alt="image" src="https://user-images.githubusercontent.com/28215638/193190489-4384b0d7-00fd-4a83-80bc-01bb1c816d5b.png">

**Comment by omwagh28** [comment]
Assign me this issue

**Comment by Distrect** [comment]
How did you solve it? Or did you solve it?
