### ISSUE TITLE
Proposals to publish to npm

### ISSUE THREAD

**Issue by LitoMore** [bvaughn/react-virtualized#1775]
@bvaughn, cc @rebelliard I noticed your comment at https://github.com/bvaughn/react-virtualized/pull/1740#issuecomment-1107839255. I think we have two solutions.

### Option 1: Publish a beta version

I think we could publish a beta version instead.

Here are the steps:

1. Change the `version` fields in `package.json` to `9.23.0-beta.0`
2. Run `npm publish --tag=beta`

So that users can give you feedback after experiencing the latest code.

### Option 2: Publish a major version

We could publish a major version `10.0.0` or `10.0.0-beta.0` if we don't have confidence in the master branch.

Just keep moving, don't let the project stall. This is a new start for your project.

---

Please share your thoughts on this. Thanks.

**Comment by AmazingTurtle** [comment]
Just push a beta already, I don't wanna use patch-package for this for too long 👍

**Comment by rebelliard** [comment]
Unfortunately, I was not given publishing rights.

```
npm ERR! 403 Forbidden - PUT https://registry.npmjs.org/react-virtualized - You do not have permission to publish "react-virtualized". Are you logged in as the correct user?
```

**Comment by DavraYoung** [comment]
Any updates on this? May be publish to a separate npm?

**Comment by LitoMore** [comment]
@DavraYoung I'd recommend using `react-vituoso' instead.

**Comment by bvaughn** [comment]
Version 9.22.4 has been published with peer dependencies updated to include React 17 and 18. (No other changes from 9.22.3)

https://github.com/bvaughn/react-virtualized/releases/tag/v9.22.4
