### ISSUE TITLE
Some problem when render feeds like Twitter with React-virtualized 

### ISSUE THREAD

**Issue by duythinh-dev** [bvaughn/react-virtualized#1783]
I making a feeds like Twitter, i used React Virtualized for render feed, but i has some problem
- My feed is loaded rather slowly, i know this problem of my feed's performance, that make lag when i scroll up or down
- I cant control how many item feed render below when i scroll up and feed render on top when scroll down, I consulted quite a few documents but haven't seen this information, hopefully I miss this
- I cant know feed in viewport 
![image](https://user-images.githubusercontent.com/71651192/197933878-9e202021-5513-4aa8-84b3-592391a46450.png)

- I maked a example like this , very smooth, but not smooth with my feed :(
- I cant set min-height for List and this is dynamic (when load-more, size Feeds increase) , when can set min-height scroll bar
will not resize when scroll top, u can check in this example
https://codesandbox.io/s/kind-villani-sv5l3x

**Comment by 9267aakashsharma** [comment]
You can try `overscan` to pre-load some feeds further out of the viewport. Also try lazy loading the List Item i.e. your post component
