### ISSUE TITLE
www.reactvirtualized.com is redirect to ww7.reactvirtualized.com

### ISSUE THREAD

**Issue by ashen114** [bvaughn/react-virtualized#1788]
www.reactvirtualized.com is redirect to ww7.reactvirtualized.com

![image](https://user-images.githubusercontent.com/28629247/206446534-59382ffb-6d5e-4f07-8fc6-772ca141212a.png)

**Comment by reviewher** [comment]
https://github.com/bvaughn/react-virtualized/issues/1735 the domain was lost dropped in February and is now held by dropcatch.

According to [archive.org](https://web.archive.org/web/20211222210532/http://www.reactvirtualized.com/) the site redirected to https://bvaughn.github.io/react-virtualized/

@bvaughn is active on GitHub, and hopefully he'll see the messages and change the domain.
