### ISSUE TITLE
Getting only 22 rows rendered in the list. I have a large list of 1000 items and trying to render it using WindowScroll + AutoSizer + List only renders 22 items

### ISSUE THREAD

**Issue by sukhpreet96** [bvaughn/react-virtualized#1795]
Getting only 22 rows rendered in the list. I have a large list of 1000 items and trying to render it using WindowScroll + AutoSizer + List only renders 22 items

**Comment by javanoclaw** [comment]
> Getting only 22 rows rendered in the list. I have a large list of 1000 items and trying to render it using WindowScroll + AutoSizer + List only renders 22 items

me two

**Comment by roanrobersson** [comment]
The likely cause of the problem must be the lack of the 'scrollEment' prop:

const Test= () => {
  const scrollElementRef = useRef(null);

  return (
    <div className="overflow-y-auto h-full max-h-full" ref={scrollElementRef}>
      <WindowScroller scrollElement={containerRef.current ?? window}>
        {...}
      </WindowScroller>
    </div>
  );
};
