### ISSUE TITLE
React virtualization not working for me

### ISSUE THREAD

**Issue by sukhpreet96** [bvaughn/react-virtualized#1797]
I'm trying to use react-virtualization for optimizing the large list performance but it's not working in my project as i can see all the items in my DOM and they don't seem to load dynamically. 
Also it does not render all the items in the list but it's rendering only 40 items out of 100.
<img width="1792" alt="Screenshot 2023-01-10 at 10 41 36 PM" src="https://user-images.githubusercontent.com/25411987/211618004-622315b8-d9bf-4436-9be9-29ee75fea985.png">
Here is my code
<img width="1048" alt="Screenshot 2023-01-10 at 10 45 25 PM" src="https://user-images.githubusercontent.com/25411987/211618143-b42b8101-572e-44b1-b5af-8fb72083fd0f.png">

Not sure what i'm missing here, i would really appreciate help here

**Comment by tourshi** [comment]
I'm facing the exact same problem (rendering only first 40 elements and not responding to my scrolling beyond that). Oddly enough, my setup was working and I'm not quite sure what broke it but suddenly stopped working (despite any code changes or changes to the react-virtualized package.

**Comment by Alexanderbtw** [comment]
> Я столкнулся с точно такой же проблемой (рендеринг только первых 40 элементов и отсутствие реакции на прокрутку после этого). Как ни странно, моя установка работала, и я не совсем уверен, что ее сломало, но внезапно перестала работать (несмотря на любые изменения кода или изменения в пакете с виртуализацией react).

You are solve this problem?
