### ISSUE TITLE
vite prebuild error

### ISSUE THREAD

**Issue by pittleCheung** [bvaughn/react-virtualized#1799]
## Bug Report

Please include either a failing unit test or a simple repro. You can start by forking this Code Sandbox: https://codesandbox.io/s/03qpzq1p9p?module=%2FExample.js

### What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React and react-virtualized. Paste the link to your [Code Sandbox](https://codesandbox.io/s/03qpzq1p9p?module=%2FExample.js) below:

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |          |
| OS                |          |
| React             |          |
| React DOM         |          |
| react-virtualized |          |
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/114127651/215738114-4b6c62d9-25bd-49b4-ab01-258a8f3e8720.png">

**Comment by pittleCheung** [comment]
this is vite prebuild error

**Comment by abemedia** [comment]
I wrote an esbuild plugin to fix this which can also be used for vite: https://npmjs.com/package/esbuild-plugin-react-virtualized

```js
// vite.config.js
import { defineConfig } from 'vite'
import fixReactVirtualized from 'esbuild-plugin-react-virtualized'

export default defineConfig({
  optimizeDeps: {
    esbuildOptions: {
      plugins: [fixReactVirtualized],
    },
  },
})

**Comment by SQReder** [comment]
bump this
