### ISSUE TITLE
More than one whitespace not honored for row data

### ISSUE THREAD

**Issue by ahmedmmeky** [bvaughn/react-virtualized#1800]
Hey I'm wondering if this is expected behavior but when we pass in row data to the Table component, if a single row element has > 1 whitespace i.e "Ahmed.....Meky" (where periods represent whitespace) the table renders "Ahmed Meky" for that element. 

Here is another example:

<img width="1243" alt="Screen Shot 2023-02-01 at 12 24 22 PM" src="https://user-images.githubusercontent.com/85079266/216118987-1a157eaa-8b49-447a-90b2-e9ac4dcd6a70.png">

Is there anything we can do to ensure whitespace is detected by the table?

**Comment by VitoriaTangHeng** [comment]
set css style={{whiteSpace:"pre"}} can solve it

**Comment by VitoriaTangHeng** [comment]
<Column label="Name" dataKey="name" width={200} style={{ whiteSpace: "pre" }} />

**Comment by ahmedmmeky** [comment]
@VitoriaTangHeng Ahh perfect this works now. Thank you very much!
