### ISSUE TITLE
The virtual list is constantly shaking.

### ISSUE THREAD

**Issue by october-rain** [bvaughn/react-virtualized#1803]
### What is the current behavior?

The virtual list is constantly shaking.

https://user-images.githubusercontent.com/42743672/218029575-66225539-ce28-46cf-b896-db020c2591bf.mp4

### What is the expected behavior?

i think the list should be stable.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?

|                   |          |
|-------------------|----------|
| Browser           |   109.0.5414.119    |
| OS                |     MacOS      |
| React             |     18.2.0     |
| React DOM         |      18.2.0    |
| react-virtualized |    9.22.3      |

**Comment by october-rain** [comment]
this bug is because of the Inner container of Grid Component, its position property value is 'relative'. And I use List Component which doesn't have containerStyle property like Grid Component as well. 

so i think maybe we can offer containerStyle for List or change default position to 'static'.

**Comment by ivanauchynnikau** [comment]
Thanks a lot!
