### ISSUE TITLE
The web link is wrong.

### ISSUE THREAD

**Issue by daryl-z** [bvaughn/react-virtualized#1806]
[www.reactvirtualized.com](http://www.reactvirtualized.com/) 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/14013570/221554245-99275f9d-3c97-4152-a720-65f7b3ff937b.png">

**Comment by SerekKiri** [comment]
Bump 👍

**Comment by Vedican** [comment]
Went to www.reactvirtualized.com and it took me to some redirects and then "scanned" my computer. Tried once more and chrome was flagging it down. Maybe you lost the domain?
