### ISSUE TITLE
Is this Project Dead or Unmaintained? Which are the alternatives?

### ISSUE THREAD

**Issue by Briones** [bvaughn/react-virtualized#1810]
## Asking a Question?
I was trying to update a project that uses this library, when I noticed some errors already reported in the Issues, some of them even tag the author of this project and no answer whatsoever. 

So I wonder if we could considerate this project could be considered dead since the last release was on December 2020, and it has some "recent" commits from April 2022, but no official release. 

If this project is not longer supported I propose to put that on the Readme to alert new developers and avoid to use it on new projects, and also recommend some alternatives if they are.

**Comment by Jmzp** [comment]
Hi

The dev of this Lib recommended using this alternative instead of `react-virtualized`

https://github.com/bvaughn/react-window

**Comment by meotimdihia** [comment]
Don't use this library unless other libraries can't provide what you need.
`react-virtuoso`
`@tanstack/react-query`
