### ISSUE TITLE
Main link is broken

### ISSUE THREAD

**Issue by sikhaman** [bvaughn/react-virtualized#1817]
## Bug Report

Hi guys, just want to say your link in repo [www.reactvirtualized.com](http://www.reactvirtualized.com/) leads not clear where. can you remove it or change to not frustrate people? thanks!
![image](https://user-images.githubusercontent.com/127867873/235752310-3a47bcc7-e5bb-49cc-9cb6-faa8efaad4b8.png)

**Comment by harikrishnanp** [comment]
@sikhaman This issue seems to be fixed. Please check & close.
