### ISSUE TITLE
Support final version of react 15.0.0

### ISSUE THREAD

**Issue by pke** [bvaughn/react-virtualized#183]
It has been released and I'm unable to get this package to accept the new version `15.0.0` as peer dependency. Does the `-rc1` in the package peerDependencies matter anymore?

**Comment by bvaughn** [comment]
A dependency of `^15.0.0-rc.1` should match `15.0.0-rc.2` as well as versions like `15.0.0`. So I'm not sure what the problem was?

Either way, just pushed out 6.1.1 with updated dependency string.
