### ISSUE TITLE
`scrollToRow()` on `List` with `WindowScroller` not working

### ISSUE THREAD

**Issue by beschler** [bvaughn/react-virtualized#1834]
## Bug Report

**Background**

I'm using an implementation of [`react-virtualized`](https://github.com/bvaughn/react-virtualized) with:

- [`WindowScroller`](https://github.com/bvaughn/react-virtualized/blob/master/docs/WindowScroller.md) to allow scrolling to happen on the page (not within a container), and an `onResize` event handler to clear the `CellMeasurerCache` (for a responsive layout)
- [`AutoSizer`](https://github.com/bvaughn/react-virtualized/blob/master/docs/AutoSizer.md) for calculating automatic an width (for a responsive layout)
- [`List`](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md) to display basic content in one column (an image and text on every row)
- [`CellMeasurer`](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md) with an `<img />` `onLoad` to calculate the dynamic height of each row (they will all be different depending on what image/text is on that row), 

My reason for using `react-virtualized` is because the core of my site is an infinitely scrolling vertical list with large images, and the page will get very large very quickly if new elements were just appended to the bottom as you scrolled.

**Issue**

I am attempting to call the `List` public method [`scrollToRow()`](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#scrolltorow-index-number) so when you click on a button (will eventually be a nav link), you're scrolled to a particular row on the page. However it doesn't appear to be working. (I'm very new to `react-virtualized`.)

**Code**

CodeSandbox:
https://codesandbox.io/p/sandbox/photolist-react-virtualized-fzhtm9?file=%2Fsrc%2FApp.js

```js
import { useRef } from "react";
import {
  CellMeasurerCache,
  CellMeasurer,
  WindowScroller,
  AutoSizer,
  List,
} from "react-virtualized";

import "./styles.css";

const dummydata = [
  // ...
];

const cellMeasurerCache = new CellMeasurerCache({
  defaultHeight: 50,
});

function rowRenderer({ key, index, isScrolling, isVisible, style, parent }) {
  return (
    <CellMeasurer
      cache={cellMeasurerCache}
      columnIndex={0}
      key={key}
      parent={parent}
      rowIndex={index}
    >
      {({ measure, registerChild }) => (
        <div
          ref={registerChild}
          style={style}
          data-key={key}
          data-is-visible={isVisible}
        >
          <div>
            {dummydata[index].id} -- {dummydata[index].text}
          </div>
          <img
            className="img"
            onLoad={measure}
            src={dummydata[index].img}
            alt={dummydata[index].text}
          />
        </div>
      )}
    </CellMeasurer>
  );
}

export default function App() {
  const listRef = useRef();

  function goToRow(index, e) {
    // NOT WORKING
    listRef.current.scrollToRow(index);
  }

  function clearCellMeasurerCache() {
    cellMeasurerCache.clearAll();
  }

  return (
    <div className="App">
      <h2>PhotoList</h2>
      <div style={{ paddingBottom: "1em" }}>
        <button onClick={goToRow.bind(this, 9)}>SCROLL TO ROW 10</button>
      </div>
      <WindowScroller onResize={clearCellMeasurerCache}>
        {({ height, isScrolling, registerChild, onChildScroll, scrollTop }) => (
          <AutoSizer disableHeight>
            {({ width }) => (
              <div ref={registerChild}>
                <List
                  ref={listRef}
                  width={width}
                  height={height}
                  autoHeight
                  rowCount={dummydata.length}
                  deferredMeasurementCache={cellMeasurerCache}
                  rowHeight={cellMeasurerCache.rowHeight}
                  rowRenderer={rowRenderer}
                  isScrolling={isScrolling}
                  onScroll={onChildScroll}
                  scrollTop={scrollTop}
                />
              </div>
            )}
          </AutoSizer>
        )}
      </WindowScroller>
      <div>End</div>
    </div>
  );
}
```

### What is the current behavior?

I have created a button at the top of the `List` which has an `onClick` function which attempts to call the `List` public method `scrollToRow()` with an index value of `9` (the 10th row). Clicking the button does not scroll to row 10. No error is thrown.

No outside dependencies in my project.

### What is the expected behavior?

I expect the `List` to scroll to row 10 when the button is clicked.

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Device | MacBook Pro 16-inch, 2023, M2 Pro |
| Browser           | Google Chrome Version 123.0.6312.58 (Official Build) (arm64) |
| OS                | macOS Ventura 13.6.5 (22G621) |
| React             | 18.2.0 |
| React DOM         | 18.2.0 |
| react-virtualized | 9.22.5 |

**Comment by richardkc** [comment]
I have this problem too

**Comment by Ksrotem** [comment]
same issue here, using windowsScroller with a table

**Comment by mmontag** [comment]
Well, I don't know if this is the best solution, but I solved a similar problem as follows.

I am using `WindowScroller`, `ArrowKeyStepper`, and `List` components:
```jsx
<WindowScroller
  scrollElement={scrollContainerRef.current}
  onScroll={({scrollTop}) => {
    listRef.current.scrollToPosition(scrollTop);
  }}
>
  {({ height, registerChild, onChildScroll }) => (
    <ArrowKeyStepper
        ref={arrowKeyStepperRef}
        columnCount={1}
        rowCount={items.length}
        mode="cells"
      >
        {({ onSectionRendered, scrollToRow }) => (
          <List
            ref={listRef}
            onRowsRendered={({ startIndex, stopIndex }) => {
              onSectionRendered({ rowStartIndex: startIndex, rowStopIndex: stopIndex })
            }}
            scrollToIndex={scrollToRow}
            scrollToAlignment="auto"
            autoHeight
            height={height}
            width={500}
            onScroll={onChildScroll}
            // scrollTop={scrollTop} ← important, scrollTop prop is not set!
            rowCount={items.length}
            rowHeight={20}
            rowRenderer={({index, key, style}) => ...}
          />
       )}
    </ArrowKeyStepper>
  )}
</WindowScroller>
```
In my case `ArrowKeyStepper` plays the same role as your button that scrolls to row 10.
Here is how I understood the data flow (subject to change):

- User presses arrow key
- `ArrowKeyStepper` passes new `scrollToRow` value to the `List` in render props
- `List` rerenders, and calculates new internal `scrollTop` value based on `scrollToIndex`
  - But importantly, it will not scroll anything on its own, because `WindowScroller` is responsible for the scroll element
- `List` triggers the `onScroll` callback, which is assigned to the `WindowScroller` render prop `onChildScroll`
- Finally, the `WindowScroller`'s `onScroll` callback imperatively sets the `List` scroll position.

We have to set scroll position imperatively, and cannot pass `scrollTop`, because that breaks the `ArrowKeyStepper`.

I might be explaining some of these details wrong, but I do have all 3 of these components working together in my project. Hope this helps someone.

**Comment by AleksandrMatuka** [comment]
I have no idea what you went through to figure out that this would work, but this solution is truly a lifesaver for many because, when it comes to react-virtualized + WindowScroller, it's pretty much the only working option.

**Comment by AleksandrMatuka** [comment]
@mmontag 
Thanks! This is the only working solution I've seen so far in conjunction with the WindowScroller. The only thing is that it's better to replace it with scrollToRow={scrollToRow} to avoid potential issues when manually scrolling with `listRef.current.scrollToRow(index)`

**Comment by driskell** [comment]
I mentioned the issue in #1893 

It's an issue since 9.19.0 and 9.20.0
