### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode when using Table and AutoSizer

### ISSUE THREAD

**Issue by Jenis999** [bvaughn/react-virtualized#1848]
I'm receiving a deprecation warning related to findDOMNode when using react-virtualized components within React's Strict Mode. The warning suggests that findDOMNode is deprecated and will be removed in future releases of React.

--Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at Table (http://localhost:3000/static/js/bundle.js:6358:5)
    at div
    at AutoSizer (http://localhost:3000/static/js/bundle.js:2385:5)
    ...

**Comment by bvaughn** [comment]
This library doesn't really get updates anymore, so that warning is going anywhere. For people who can, I suggest moving to react-window. It doesn't have as many features/flexibility but it is more modern.
