### ISSUE TITLE
[React v19] Components cannot be used as JSX components

### ISSUE THREAD

**Issue by CHE1RON** [bvaughn/react-virtualized#1853]
Hey there,
since I could not find any issue on the topic, let me share my experience with the upcoming React v19 and your awesome `react-virtualized` library:

<img width="875" alt="Screenshot 2024-10-28 at 11 16 32" src="https://github.com/user-attachments/assets/4e7eb7f9-8fee-49aa-bd6d-9fead8b2f568">

Several components, such as `InfiniteLoader` & `Grid`, are seemingly incompatible with React's latest changes.

## Steps to reproduce

1. Install React v19, following the [official upgrade guide](https://react.dev/blog/2024/04/25/react-19).
2. Try to build project / library.

**Comment by ringge** [comment]
I'm using Nextjs 15 with React v19 and have exact same issue

**Comment by baba43** [comment]
@ringge did you solve this issue?

**Comment by ringge** [comment]
> @ringge did you solve this issue?

Hi not yet, I couldn't think of any way to solve it. Had to temporarily switch back to Next 14

**Comment by CHE1RON** [comment]
@baba43 you mean besides adding `@ts-ignore` / `@ts-expect-error` statements, right? 😅

**Comment by CHE1RON** [comment]
Either the latest `rc` version of React 19 OR switching `moduleResolution` to 'Node' fixed it for me 😉
