### ISSUE TITLE
peer dep on react-addons-shallow-compare

### ISSUE THREAD

**Issue by atuttle** [bvaughn/react-virtualized#186]
This dependency isn't mentioned in the readme. If it's necessary for some reason, could it be documented beyond the npm install warning?

```
react-virtualized@6.1.2 requires a peer of react-addons-shallow-compare@^0.14.0 || ^15.0.0 but none was installed.
```

**Comment by bvaughn** [comment]
Sure. I'll add it to the readme. It used to be a `dependency` but someone recently [suggested it be moved](https://github.com/bvaughn/react-virtualized/pull/184) to avoid potentially loading different versions of it. Thanks for the suggestion.

**Comment by bvaughn** [comment]
README has been updated: https://github.com/bvaughn/react-virtualized#dependencies

Sorry for the confusion.
