### ISSUE TITLE
infinite scroll list data merge on loadMoreRows

### ISSUE THREAD

**Issue by Raffiki** [bvaughn/react-virtualized#187]
Would love to do this on [Gitter](https://gitter.im/bvaughn/react-virtualized), but that room seems unavailable.

So I have this this stupid question, wrapped in companion code on [Plunkr](http://plnkr.co/edit/HDJnQ25mPRlgln0RsP5h?p=catalogue): if `loadMoreRows` returns a `Promise` with the next batch of data, are we supposed to merge this batch onto the previous one? I guess this beats the purpose of the `VirtualScroll` but still.

I'm asking because the `InfinitLoader` only displays the current data batch. On first render range [0, 22] was fetched and rendered:

![2016-04-13-154349_304x226_scrot](https://cloud.githubusercontent.com/assets/1446995/14499632/a53102e6-018e-11e6-8922-6cf627e63018.png)

After scrolling `loadMoreRows` was called for the next index, with result:

![2016-04-13-154401_298x240_scrot](https://cloud.githubusercontent.com/assets/1446995/14499633/a53174ec-018e-11e6-8a62-ef2ae0b0e4e5.png)

Maybe related: the actioncreator return by `loadMoreRows` is a Promise, however this codeblock is never entered: https://github.com/bvaughn/react-virtualized/blob/ad8e0a1c8c84a2a8a406aa879a49ea8f2407c27d/dist/es/InfiniteLoader/InfiniteLoader.js#L69-L77

**Comment by bvaughn** [comment]
You can always directly message me on Gitter. Others do.

My guess is you forgot to load/include the react-virtualized stylesheets (similar to #157). Docs mention this [here](https://github.com/bvaughn/react-virtualized#getting-started) though it's easy to overlook or forget about. I've done it myself before.

**Comment by bvaughn** [comment]
Closing this because I'm fairly confident my answer will help you out. Feel free to ask a follow-up question here (or [on Gitter](https://gitter.im/bvaughn/react-virtualized)) if not. :)
