### ISSUE TITLE
Hide the scroller of VirtualScroll

### ISSUE THREAD

**Issue by Staikov** [bvaughn/react-virtualized#199]
Hi,

First of all thanks for the great tool. It super easy for use and it is working very smooth. However I have problem with hiding the scroller of VirtualScroll can you give me some advices ?

I'm using it like this:
```
<VirtualScroll
  width={867}
  height={600}
  rowsCount={productNodes.length}
  rowHeight={300}
  overscanRowsCount={2}
  rowRenderer={
  index => productNodes[index]
}
/>
```

**Comment by bvaughn** [comment]
I'm not sure I understand what you mean. Hide the scrollbar? This can be done by CSS, no?

**Comment by Staikov** [comment]
Yes but when I try to edit the CSS to hide the scrollbar the VirtualScroller stop working.
I saw that the VirtualScroller is generating 2 div:  <div class="Grid VirtualScroll" ... > and <div class="Grid__innerScrollContainer" >  What i have tried is the following css:

```
.Grid, .VirtualScroll {
        overflow-y: hidden;
}

.Grid__innerScrollContainer {
       overflow: auto;
}
```

This is hiding the scroller but after that the Grid__innerScrollContainer can not be scrolled.

**Comment by bvaughn** [comment]
That's because that CSS disables scrolling. You don't want to do that. You want to hide the scrollbar (presumably?).

For that you should look at an approach more like this: https://css-tricks.com/examples/WebKitScrollbars/

I'm going to close this issue by the way since it doesn't seem actionable on my part. :)

**Comment by QuotableWater7** [comment]
@ghost did you end up finding a working solution?  I'm running into this issue now, and the example @bvaughn gave also appears to use `overflow-y: hidden`

**Comment by Taymindis** [comment]
just make your `<List width={largerAbitThanWindowsWidth} .... />` will solve the issue

**Comment by rolandin** [comment]
This is what worked for me: 

::-webkit-scrollbar {
    width: 0px;
}
