### ISSUE TITLE
Unmet peer dep for react 15.0.1

### ISSUE THREAD

**Issue by raphaelokon** [bvaughn/react-virtualized#201]
I am getting this on install:

`npm WARN react-virtualized@6.2.2 requires a peer of react-addons-shallow-compare@^0.14.0 || ^15.0.0 but none was installed.`

**Comment by bvaughn** [comment]
Unfortunately you'll need to install that yourself. All of the react NPM
packages need to be specified as peer dependencies to avoid version
conflicts from loading more than one copy. This is mentioned in the README
although I understand it's easy to overlook.
