### ISSUE TITLE
Best practices on using inline styles for a FlexColumn?

### ISSUE THREAD

**Issue by MikeMcElroy** [bvaughn/react-virtualized#204]
We use Radium for style management, and the emphasis there is on inline styles over classes.  What's the best way for me to use inline styles with a FlexColumn.  eg.
```js
render() {
  return (
    <FlexTable rowGetter={rowIndex => data[rowIndex]}
      width={50}>
      <FlexColumn displayKey="id"
        header="ID"
        style={{
          backgroundColor: 'blue'
        }}
        width={50}/>
    </FlexTable>
  );
}
```

**Comment by MikeMcElroy** [comment]
In the process of looking over this closer, I think I found the appropriate change should you want to support this.
#205

**Comment by bvaughn** [comment]
Version 7 supports what you've proposed so I'm going to close this issue. Look for a release of it momentarily. Thanks for the suggestion, @MikeMcElroy.
