### ISSUE TITLE
Support for inline styles

### ISSUE THREAD

**Issue by pke** [bvaughn/react-virtualized#208]
I wonder if there is support for inline styles planned in addition to `className`.
I have my app bootstrapped to set all `div` to be `flex` containers and with position `relative`.
Of course this does not work well with `VirtualScroll` because it gets its calculations wrong with the relative positioning.

**Comment by bvaughn** [comment]
Hey @pke,

Check out the discussion over on #197 (and also the [version 7 roadmap](https://github.com/bvaughn/react-virtualized/wiki/Version-7-Roadmap)).

tl;dr though is that I plan on changing react-virtualized for version 7 to support a `theme` property that will allow either custom styles or class names.

Going to close this issue as a duplication just to keep things tidy. :)
