### ISSUE TITLE
Scrolling doesn't work as expected

### ISSUE THREAD

**Issue by Sparragus** [bvaughn/react-virtualized#21]
I'm posting this here as suggested on https://github.com/treasure-data/redux-search/issues/25.

Scrolling is not working properly. Instead of scrolling the list, it scrolls a single row. (At least on https://treasure-data.github.io/redux-search/). If you notice, the row will slightly scroll up and down just a little bit. However, if you manage to drag the scroll bar on the side, you can scroll through the list with no problem.

I'm currently trying it using the trackpad on a Macbook Air with OSX 10.11.1 and using Firefox 42.0.

**Comment by bvaughn** [comment]
Thanks for reporting this issue @Sparragus! :)

I've updated the `react-virtualized` docs to warn against this particular issue.

**Comment by Sparragus** [comment]
Cool! Happy to contribute with bug reporting. :)
