### ISSUE TITLE
How to update a row in a VirtualScroll Component?

### ISSUE THREAD

**Issue by Pixlschmied** [bvaughn/react-virtualized#210]
Hi, 
The VirtualScroll component calls the "rowRenderer" callback function just on scroll. I have a click listener that updates the row, how's it possible to force the rowRenderer to be called?

I have prepared a very simple jsfiddle example to demonstrate the issue i'm currently struggling with:
https://jsfiddle.net/zob62mu6/3/

Appreciate any help!

**Comment by bvaughn** [comment]
Here you go: https://jsfiddle.net/bvaughn/db5mas0t/

Just add a ref (eg `ref='VirtualScroll') to your `VirtualScroll` and then tell it it needs to update in your on-click handler: 

```js
listItemClickHandler:function(i){
  this.list[i] = this.list[i] + 1;
  this.refs.VirtualScroll.forceUpdate();
}
```
