### ISSUE TITLE
Upgrade react dependencies to 15.0.1 

### ISSUE THREAD

**Issue by DmitroPustovit** [bvaughn/react-virtualized#214]
Hello, 

I want to use your library in my project, but I use react 15.0.1 and can't downgrade to 15.0.0 because of bug in this version. It's possible to update yours dependencies to 15.0.1 ? 

Thanks

**Comment by felipeleusin** [comment]
This shouldn't be an issue. Are you getting an error or something?

**Comment by bvaughn** [comment]
@DmitroPustovit: `react` is just a peer dependency, meaning that `react-virtualized` doesn't install it; it just expects you to. As for the version, my `package.json` is setup to match with ` "react": "^0.14.0 || ^15.0.0"` which means any bug-fix version of 0.14.x as well as 15.0.x and up. You should be able to use 15.0.1 just fine but you'll need to install it yourself, with your own `package.json` file.
