### ISSUE TITLE
VirtualScroll rowRenderer method is called many times while scrolling

### ISSUE THREAD

**Issue by yakirn** [bvaughn/react-virtualized#215]
Hi
I explained my issue here:
http://stackoverflow.com/questions/37049280/virtualscroll-rowrenderer-method-is-called-many-times-while-scrolling
but there's no react-virtualized tag, and I can't add one because I don't have enough SO points, so i'm also posting it here :)
I Would really appreciate any input on this, so comment wherever it seems right for you.
Thanks in advance!

**Comment by bvaughn** [comment]
Looks like Guria beat me to it and has created a `react-virtualized` for you. 

I'm going to close this issue and head over to Stackoverflow since we don't need both open. :)

**Comment by bvaughn** [comment]
Hi @yakirn,

Not sure if you saw my message on Stock Overflow, but if you would be willing to share any code samples with me regarding your slow render problem- I'd love to compare version 6 and 7 and see if it's been improved any.

Also, I published version `7.0.0-rc.1` to NPM this evening so feel free to check it out yourself if you'd like.

**Comment by yakirn** [comment]
Hey @bvaughn 
I saw your message, I will try to get to it later today. I will also try to test the RC.
btw thanks for the help! :)

**Comment by yakirn** [comment]
@bvaughn I just checked out the commit with the performance issues, but for some reason the problem isn't reproducing. I'm still trying, but I may not be able to provide you with code sample as promised.

**Comment by bvaughn** [comment]
No worries. :) Let me know if it crops back up.
