### ISSUE TITLE
InfiniteLoader + Collection

### ISSUE THREAD

**Issue by brandonchoe** [bvaughn/react-virtualized#221]
Do they work together? Are sections the same as rows? Hey!

**Comment by bvaughn** [comment]
Unfortunately they do not work together. InfiniteLoader loads rows as a user scrolls them into view. But a Collection's cells aren't in any particular order. The first cell may be top left and the a one may be bottom right. There is no way for InfiniteLoader to work, given the lack of constraints.

**Comment by bvaughn** [comment]
I will update docs to make this clearer.
