### ISSUE TITLE
Allow setting a scroll velocity at which `isScrolling` becomes true

### ISSUE THREAD

**Issue by tikotzky** [bvaughn/react-virtualized#223]
Right now as you as you begin scrolling, even a very slow scroll while browsing a list `isScrolling` is set to true. This means that if you want to slowly browse through a list you need to constantly scroll and stop to allow the cellRenderer to render the full cell contents.

Perhaps there should be a (configurable) scroll velocity at which `isScrolling` becomes true to allow you to slowly browse a list without triggering the scrolling renderer.

**Comment by bvaughn** [comment]
I don't think I want to implement any kind of velocity handling for scrolling. At the moment, that's a boolean flag and I think I'd like to keep it that way for simplicity.

You could implement a velocity threshold pretty easily though using the `onScroll` callback and just ignoring the `isScrolling` param passed to `cellRenderer`. If you'd like to share your code back with me I could add it to the recipes section of the README for others to reference?

**Comment by bvaughn** [comment]
I should point out that no one is forced to render a placeholder cell while `isScrolling` is true. It's there as an optional optimization.

**Comment by bvaughn** [comment]
This could even be implemented as a HOC by the way- similar to [`ScrollSync`](https://github.com/bvaughn/react-virtualized/blob/master/source/ScrollSync/ScrollSync.js). The HOC could listen for scroll events, determine when they exceed the threshold, and then pass the child function the appropriate `isScrolling` parameter. Then your cell renderers could just use _that_ parameter instead of the binary one provided by `Grid`.

**Comment by bvaughn** [comment]
I'm going to close this issue since I don't plan on taking any action on it. (Pruning the issues list regularly helps me a lot so I hope you'll understand.) We can continue to chat here if you have questions or ideas. :)

**Comment by tikotzky** [comment]
Thanks for the quick response! (and the awesome library)
I'll look into doing something similar to ScrollSync.

**Comment by bvaughn** [comment]
No problem. If you think the thing you build might be useful to others- let's talk more. Maybe it could make its way into this project _or_ maybe it could be released as a separate HOC that could be installed alongside react-virtualized. (That is, assuming you'd be interested.)

**Comment by mattvague** [comment]
@bvaughn I had a need for a similar thing so I came up with a prototype [here](https://gist.github.com/mattvague/6843385ad0415d12a89cbdd1ac363e28) which seems to work pretty well. Am I doing anything silly? If not would you accept a PR for this?

**Comment by bvaughn** [comment]
Sorry Matt. I totally missed this comment somehow.

Doesn't look silly. Not sure it's worth adding complexity to a perf-sensitive area such as scroll handler, since it's possible to implement in user-space.

**Comment by mattvague** [comment]
> Doesn't look silly. Not sure it's worth adding complexity to a perf-sensitive area such as scroll handler, since it's possible to implement in user-space.

Ah alright, well I might roll it into an add-on for your repo :-) Besides needing tests and stuff, any other recommendations if I were to do this?

**Comment by bellerus** [comment]
@mattvague Did you end up using your solution in a project? Would be interested in using your solution.

**Comment by mattvague** [comment]
@bellerus I didn't get it into any production-worthy but I have it in a WIP project and it seems to work fairly well. There are probably some edge cases and tweaking required, let me know how it works for you.
