### ISSUE TITLE
Collection missing recomputeCellSizesAndPositions function

### ISSUE THREAD

**Issue by phahn** [bvaughn/react-virtualized#232]
It looks like the `recomputeCellSizesAndPositions` function is missing on the `Collection` class. I was only able to access it through refs.CollectionView

**Comment by bvaughn** [comment]
Thank you for reporting this issue. I've added this method to `Collection` and released 7.0.2.

**Comment by phahn** [comment]
That was fast :) Thank you very much for the fix and this awesome library!
