### ISSUE TITLE
CellMeasurer throws "Only a ReactOwner can have refs" error under certain conditions

### ISSUE THREAD

**Issue by wasd171** [bvaughn/react-virtualized#235]
Hi!

When trying to render such construction
```
<div style={{flex: '1'}}>
    <AutoSizer>
        {
		({height, width}) => (
		        <CellMeasurer
		                cellRenderer={this._cellRenderer}
			        columnCount={1}
				rowCount={messages.size}
				width={width}
			>
				{
					({getRowHeight}) => (
						<Grid
							columnCount={1}
							columnWidth={width}
							height={height}
							overscanColumnCount={0}
							overscanRowCount={0}
							cellRenderer={this._cellRenderer}
							rowCount={messages.size}
							rowHeight={getRowHeight}
							width={width}
						/>
					)
				}
			</CellMeasurer>
		)
	}
</AutoSizer>
</div>
```

I get cryptic
```
invariant.js?4599:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

When it should be unmounted I get 
```
invariant.js?4599:38 Uncaught Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

`_this.cellRenderer` looks as following:

```
_cellRenderer({ rowIndex }) {
		"use strict";
		let {messages, userId} = this.props;
		const messagesArray = messages.toArray();

		if (messagesArray.length === 0) {
			return null;
		}

		const msg = messagesArray[rowIndex];
		return (
			<Message message={msg} id={userId}/>
		);
	}
```

Also for some reason only rows, which are visible on first render are rendered (so no new rows appear on scrolling)

**Comment by wasd171** [comment]
Replacing my `<Message/>` component with `<div>{message}</div>` seems to fix this problem

**Comment by bvaughn** [comment]
Hi @wasd171. Unfortunately the current approach I'm following in `CellMeasurer` is [a bit hackish](https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.js#L158). I've tried a couple of alternatives but haven't found any other approaches that work (that don't also require asynchronicity).

Help would be appreciated here if others have ideas to contribute.

**Comment by olslash** [comment]
I've run into this show-stopper as well, trying to render a grid with a CellMeasurer. 

Looking into it today, there are a couple things i can modify to make it work -- either remove the `scrollingContainer` ref from <Grid>, or remove the `renderToString` call in _measureCell. But it's still not clear to me how those are connected.

Obviously renderToString is being called on a component that is rendered outside of render() (the cell), resulting in a component that has no _owner, like the error says: "Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method". But nothing's trying to set a ref on that component, as far as i can tell.

What is getting a ref is the outer div of Grid (scrollingContainer). Removing that ref fixes the error. But I don't see why it should, since the Grid's render doesn't seem to be connected to the measuring process of CellMeasurer.

In any case, maybe these observations will help jumpstart someone else who can track down a fix for the issue.

**Comment by bvaughn** [comment]
I'm not able to reproduce this problem using `CellMeasurer` with `VirtualScroll` as I was initially able to but I can if I return a custom component (eg. the `Message` component above).

Setting a breakpoint in the React source it looks like the first few rows that are rendered have an `owner` that is a `ReactCompositeComponentWrapper` but the one that eventually errors has a `null` value for `owner`.

**Comment by olslash** [comment]
that squares with my experience, too -- i only see the error after the final row renders. Will lookagain from that angle and see if I can track anything down

**Comment by olslash** [comment]
BTW, would using CellMeasurer with VirtualScroll even be possible, given the difference in render fn signatures? (`rowIndex` vs `index`)

**Comment by bvaughn** [comment]
Yup, you just need to create an adapter function eg
```js
function cellRender ({ rowIndex }) {
  return rowRenderer({ index: rowIndex })
}
```

**Comment by olslash** [comment]
mentioned this on gitter, but here's the relevant react issue for anyone interested:
https://github.com/facebook/react/issues/3344

**Comment by chalda** [comment]
nice i actually hacked a solution together without cellmeasurer:

`<AutoSizer
                        disableHeight={true}
                        ref= {(ref) => {
                            this.autoSizer = ref;
                        }}
                        >
                        {({ width }) => {
                            if (this.autoSizer && this.mostRecentWidth !== this.autoSizer.state.width) {
                                const currentWidth = this.autoSizer.state.width;

                                if (currentWidth < 768) {
                                    this.rowHeight = 209;
                                } else if (currentWidth > 768 && currentWidth < 1126) {
                                    this.rowHeight = 137;
                                } else {
                                    this.rowHeight = 90;
                                }
                            }
                            if (this.autoSizer) {
                                this.mostRecentWidth = this.autoSizer.state.width;
                            }`
