### ISSUE TITLE
Examples should have overscan enabled by default

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-virtualized#241]
Scrolling the list is how users check if the library is viable.
Empty space looks frustrating and like bad UX, so I’m sure many close the tab after that.
We should set a default overscan of 5 or something.

**Comment by bvaughn** [comment]
Hey @gaearon, nice to hear from you. Overscan is actually set to 10 via `defaultProps` but it looks like I've stupidly overridden it to 0 in some of the examples. I'll update them momentarily.

**Comment by bvaughn** [comment]
Updated! :)

**Comment by gaearon** [comment]
👍
