### ISSUE TITLE
FlexColumn className property is just ignored

### ISSUE THREAD

**Issue by ArtemZag** [bvaughn/react-virtualized#247]
I tried to apply special css class to the cells for particular FlexColumn. But properties "style" and "className" do not make any effect.

**Comment by bvaughn** [comment]
They work fine for me. (I just double checked with the latest version before commenting.)

I'll need you to provide a reproduction test case (Plunker, JS Fiddle, etc) if you're seeing a problem.

**Comment by ArtemZag** [comment]
Thanks for your response. I'll try to create some draft example.
