### ISSUE TITLE
When using Grid with CellMeasurer for variable height rows, cells that should be visible render outside of viewable area

### ISSUE THREAD

**Issue by FeralWhippet** [bvaughn/react-virtualized#250]
Usually only about the first 35 or so rows render normally. After that it looks like you have to scroll down a ways before the rendering of the next cell is triggered, and when that cell is rendered it is rendered with the proper offset, which has by then been scrolled up out of the viewable area. As far as I have traced it through the code I have not seen any obvious errors in the bookkeeping.

Not doing anything fancy in the code at all, in fact have reduced the CellRenderer down to just a string.

```
  render: function () {
    var self = this;
    var props = self.props;
    return (
      <Modal show={true} bsSize="large" aria-labelledby="contents-title">
        <Modal.Header closeButton>
          <Modal.Title id="contents-title">{"Comments containing '"+props.name+"'"}</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <AutoSizer>
            {function (sizerArgs) {
              return (
                <CellMeasurer
                  cellRenderer={self._cellRenderer}
                  rowCount={props.refs.length}
                  columnCount={1}
                  width={sizerArgs.width - 20}
                >
                  {function(measurerArgs) {
                    return (
                      <Grid
                        columnCount={1}
                        columnWidth={sizerArgs.width - 20}
                        height={sizerArgs.height}
                        cellRenderer={self._cellRenderer}
                        rowCount={props.refs.length}
                        rowHeight={measurerArgs.getRowHeight}
                        width={sizerArgs.width}
                      />
                    );
                  }}
                </CellMeasurer>
              );
            }}
          </AutoSizer>
        </Modal.Body>
        <Modal.Footer>
          <Button onClick={props.onClose}>Close</Button>
        </Modal.Footer>
      </Modal>
    );
  },
```

Note: "Refs" is just a poorly chosen name, these are offsets in a list of comments, *not* React refs.
Note: "Modal" is from react-bootstrap

```
  _cellRenderer: function (cellArgs) {
    var ref = this.props.refs[cellArgs.rowIndex];
    return (
      <div className="content-cell">
        {"Row #"+(cellArgs.rowIndex+1)+"  "+this.props.contents[ref]}
      </div>
    );
    //    <div className="content-cell" dangerouslySetInnerHTML={{__html: "<p>Row #"+(cellArgs.rowIndex+1)+"</p>"+this.props.contents[ref]}} />
    //);
  }
```

Note: using innerHTML does let you render more complex structures in a cell without triggering the "Only a ReactOwner can have refs" error, this was not by design its just that my app loads html formatted strings which have been constructed on the server side (the information necessary to construct them is not otherwise sent to the app).

**Comment by bvaughn** [comment]
Hey @FeralWhippet,

Can you point me at a working example of this? A video would be helpful but ideally a Plunker or something similar (that I can actually inspect) would be helpful. I have not seen the behavior you've described and the code above- while helpful- would require me to spend time writing the missing parts in order to actually see what you're seeing.

**Comment by FeralWhippet** [comment]
Hey bvaughn,

I have tried to get an example running in Plunker with no luck, it fails on attempting to load react-virtualized.js with:

Uncaught TypeError: Super expression must either be null or a function, not undefined

 I found react-virtualized on cloudflare and attempting to load it from there, e.g.:

<script src="//cdnjs.cloudflare.com/ajax/libs/react-virtualized/7.1.2/react-virtualized.js"></script>

I have also tried via the data-require/data-semver form with same result. so, I can't verify that I am getting the same behavior with my excerpted example.

**Comment by bvaughn** [comment]
There are a few problems with the Plunker you linked to. First it's loading React 0.12 which is not a supported version. (react-virtualized supports 0.14 and 15.0). So you can change that by swapping in...

```html
    <script data-require="react@15.0.0" data-semver="15.0.0" src="//cdnjs.cloudflare.com/ajax/libs/react/15.0.0/react.js"></script>
    <script data-require="react-dom@15.0.0" data-semver="15.0.0" src="//cdnjs.cloudflare.com/ajax/libs/react/15.0.0/react-dom.js"></script>
```

Next it's trying to parent the React app in an element with id "container" but the HTML only has an element  "example".

Then it's referencing jQuery (`$.ajax`) but it hasn't been loaded (in the HTML) so there's an error.

Please take another pass at this. Perhaps take a look at these for an example: https://github.com/bvaughn/react-virtualized/tree/master/playground

**Comment by FeralWhippet** [comment]
yes I know about the other problems (jQuery etc...), but I was not getting that far for it to matter. the react versions I used were the ones inserted by plunker's "get latest version" function, I didn't think to look at them as I was assuming they were actually latest....

**Comment by bvaughn** [comment]
It failed to load _because of_ the React version.

**Comment by FeralWhippet** [comment]
yes, I got that. I was just saying that the little widget in Plunker that places the script tags in your index.html does not specify the most recent (or even close to recent versions). For example it generates a script tag for version 0.13.0 of react-bootstrap and the current version is 0.29.4 and so on. its just surprising that its so far off.

**Comment by FeralWhippet** [comment]
OK, it is working now. Its as ugly as sin, but shows the behavior. Just click on the line in the table (GBU ...) and it will render a grid. there are 80 rows in the data, but the Grid will start showing strange behavior at Row #28 (at least in the browser I am using, Chrome).

**Comment by bvaughn** [comment]
Sure. I understand that's not expected behavior of Plunker. But in the future, stick with the Plunker until it works instead of just tossing it over the fence to me. I'm helping out for free and my time is limited. :)

This issue is a great demonstration of why reproduction cases are important. It looks like the problem is because you're not including the react-virutalized styles. Add this line to your HTML and the issue should go away:
```html
<link rel="stylesheet" href="//npmcdn.com/react-virtualized@7.1.3/styles.css" />
```

**Comment by jgwconsulting** [comment]
@FeralWhippet Seriously - bad attitude and not a word of thanks? People spend their time working hard on open source IN SPITE of your approach here. Must try harder.
