### ISSUE TITLE
Render entire container scroll height for VirtualScroll

### ISSUE THREAD

**Issue by johnnyji** [bvaughn/react-virtualized#258]
Hi Brian,

I'm currently using `VirtualScroll` where I am manually changing the `scrollTop` when the user clicks on a button that should scroll them to a particular row. The reason I'm not using the provided `scrollToIndex` prop is because the scroll that I need to do requires animation.

However this becomes an issue if there are tons of rows being rendered and I need to animate the `scrollTop` to something not yet visible (ie. the last row). Because `VirtualScroll` only renders what is visible to the user, The container has a inaccurate scroll height representation; and only when the user begins to scroll further down, does the scroll height begin to increase and increase.

If I already know the expected scroll height of the container, would there be a way to add a prop for me to pass it down, so that the container would be the correct scroll height, but still render only the visible rows, the rest of the scroll area would just be whitespace.

In the `Grid` component that `VirtualScroll` uses, there is a `totalRowsHeight` variable to set the height of the of the div with the class `Grid__innerScrollContainer`.

`const totalRowsHeight = this._rowSizeAndPositionManager.getTotalSize()`;

Ideally, it would be great if we could so something like:

`const totalRowsHeight = this.props.totalRowsHeight || this._rowSizeAndPositionManager.getTotalSize();`

PS. I love this library, it's slick as hell!

Best,

- Johnny

**Comment by bvaughn** [comment]
Hey @johnnyji,

Thanks for the compliment. :)

When you say you already know the total height- do you mean your rows are all the same height? Or they're varying height, but not dynamically measured?

**Comment by johnnyji** [comment]
@bvaughn 

In my case, all the rows are the same height, and I know exactly how many rows there will be. Therefore I can do the calculation on my end to get the total height of all the rows.

If I can give `VirtualScroll` the total height of all the rows, and that in turn passes it down to `Grid`, then on mount, the `VirtualScroll` should be able to render the correct `overflow-y` for all the rows, instead of the overflow incrementally increasing as I scroll further down.

I hope I'm making sense with my description haha

**Comment by bvaughn** [comment]
I see. Maybe I'm missing something, but if your rows are all the same height- then [this line in `Grid`](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L580) should set the `estimatedRowSize` to be equal to your specified `rowHeight` which should cause the "estimated" height returned by [`getTotalSize`](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/utils/CellSizeAndPositionManager.js#L128) to be the exact, correct height, no?

**Comment by johnnyji** [comment]
@bvaughn Whoops. I got mixed up in my own head. My rows are **NOT** the same height. But I can calculate the sum height of all the rows.

**Comment by bvaughn** [comment]
Heh heh, ok. That makes more sense then.

Let me think about this some. I'm a little wary of adding a `totalRowsHeight` property. It seems a little too easy to mis-use and break things.

Any chance you have a Plunker or something you could point me at so I could get a sense of how "bad" this gradual resizing is? My hope was that using reasonable `estimatedRowSize`s would make the resizing pretty subtle. How much do your `rowHeight`s vary? Are you providing a custom `estimatedRowSize` or just using the default? :)

**Comment by bvaughn** [comment]
Check out new release 7.2.0.

Ended up going a slightly different way with this but I think it solves your problem while being a little safer. Updated docs here: https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#measureallcells

Basically there's a new method on `Grid` (`measureAllCells`) and `FlexTable` and `VirtualScroll` (`measureAllRows`) that allows you to force-measure.

**Comment by johnnyji** [comment]
@bvaughn 👏 👏 👏  Far better than I originally thought. Thanks a lot for the quick response and wicked library 👍
