### ISSUE TITLE
Is it possible to support async layout?

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#262]
It's currently possible to crash react-virtualized by setting a _very_ high number of rows (eg 1,000,000,000) and then dragging the scrollbar quickly so that millions of rows are passed by at once. In this case react-virtualized will try to just-in-time measure all of the rows being scrolled past and it will likely fail.

The only solution to this, I think, requires changing the layout algorithms to support async operations. I have not thought about this much so I don't have a sense of how much work this would be. In theory though, if this were done, it may be possible to perform some of the heavy layout crunching in a web worker and further speed up scrolling smoothness.

Filing this away for further thinking. It's likely pretty complicated and I don't have the time to tackle it at this moment.

**Comment by edulan** [comment]
Hi @bvaughn, have you consider also the use of throttling here?

If the layout algorithm is not fast enough to complete in less than 16ms per frame, maybe it's better to drop some calculations and only stick to the last one.

The problem I see for moving to a worker is that you'll need to keep both UI thread and worker in sync. So here you'd have the same problem plus a bit overhead for the serialization of data. So I can imagine the situation of UI sending lots of layout tasks to the worker and the worker not being able to complete them in the right time. By the moment worker sends back the results, they are no longer valid for the UI, as it'll be far ahead from that position by then.

Anyway this is just hypothesis. It'd be interesting to implement a small prototype with both approaches. I can help you if you want 😉. From my experience, moving from a sync world to an async one is a pita.

What do you think?

**Comment by bvaughn** [comment]
I have not put much thought into throttling, no. But it does seem like something worth considering! :)

Agreed the async could be a PITA.

This issue was mostly just opened as a placeholder for people to toss out ideas. Thanks for adding some thoughts. :)

**Comment by bvaughn** [comment]
Closing this for now because I don't foresee myself having time to pick it up in the near future and having open issues on the issues list isn't a good feeling. May pick it back up at some point. :)
