### ISSUE TITLE
Collection of items aren't loading on demos for IE10

### ISSUE THREAD

**Issue by jasonlee-alation** [bvaughn/react-virtualized#269]
The demo page on ie10 isn't loading its collection of items for all demos except 'Collection'. This is leading to empty grids/tables/virtual scrolls

This was tested on Browserstack windows 8 ie10. 
From what I understand react-virtualized _does_ support ie10 judging from the -ms- vendor specific flex attributes
<img width="895" alt="screen shot 2016-06-07 at 2 58 57 pm" src="https://cloud.githubusercontent.com/assets/11810015/15876618/3221878e-2cc3-11e6-966d-a6b0103141df.png">

**Comment by bvaughn** [comment]
Right. Unfortunately I think this is because Babel is using [`Object.setPrototypeOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf) which is not supported by IE9 / IE10. As for options to fix this, there's the [Babel plugin `babel-plugin-transform-proto-to-assign`](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-proto-to-assign). There's also [a polyfill](https://gist.github.com/edoardocavazza/47246856759f2273e48b#file-object-setprototypeof-ie9-js). There's also a more compact monkey patch that resolves it:

```js
(function() {
    if (!(Object.setPrototypeOf || {}.__proto__)) {
        var nativeGetPrototypeOf = Object.getPrototypeOf;

        Object.getPrototypeOf = function(object) {
            if (object.__proto__) {
                return object.__proto__;
            } else {
                return nativeGetPrototypeOf.call(Object, object);
            }
        }
    }
})();
```

I should probably update the demo app to at least monkey patch it.

**Comment by bvaughn** [comment]
Related to babel/babelify/issues/133

**Comment by bvaughn** [comment]
Let me think on this a bit. :)

**Comment by bvaughn** [comment]
I think the reason this recently broke was that I added `ScalingCellSizeAndPositionManager` which extends `CellSizeAndPositionManager` and sometimes calls `super` methods. Unfortunately as the [Babel caveats page](https://babeljs.io/docs/usage/caveats/) specifies:
> ##### Classes (10 and below)
If you’re inheriting from a class then static properties are inherited from it via __proto__, this is widely supported but you may run into problems with much older browsers.

> NOTE: __proto__ is not supported on IE <= 10 so static properties will not be inherited. See the protoToAssign for a possible work around.

> For classes that have supers, the super class won’t resolve correctly. You can get around this by enabling the loose option in the es2015-classes plugin.

There are a couple of ways of fixing this. Need to decide which is the best. :)

**Comment by bvaughn** [comment]
I think the path of least pain for react-virtualized users would be for me to convert to composition for these 2 libraries now. Working on that currently.

**Comment by bvaughn** [comment]
Check out version 7.3.3. Should work again for IE10+

Thanks for the detailed bug report, @jasonlee-alation. Sorry it took me a few hours to get around to resolving it. :)

**Comment by bvaughn** [comment]
PS Apparently my most recent deploy of the demo site is causing IE10 some other pain (not yet sure why) but this has to do with the bundling of my demo app itself. The local version of the demo app (with the update to react-virtualized) is IE10-compatible so hopefully this should unblock you. It's late here but I'll take a look at the demo site again tomorrow.

**Comment by bvaughn** [comment]
Demo page has been fixed for IE9 and IE10. :)
