### ISSUE TITLE
Handle Row Click

### ISSUE THREAD

**Issue by guykr-stratoscale** [bvaughn/react-virtualized#27]
How would one go about responding to row clicks?

setting `onClick` handler on FlexTable or FlexColumn has no effect.

**Comment by bvaughn** [comment]
That isn't currently supported but I would be happy to put together an updated release that provides `onRowClick` functionality to the table component. I'll try to get it releaed sometime today.

**Comment by bvaughn** [comment]
Version 2.2.0 has been released and supports an [`onRowClick`](https://github.com/bvaughn/react-virtualized/blob/master/docs/FlexTable.md#prop-types) property. Enjoy!

**Comment by guykr-stratoscale** [comment]
@bvaughn thanks for the quick turnaround!
as a token of appreciation I've submitted a pullrequest (#30)  for dynamic rowClassName. 
I needed it to implement proper row selection.

**Comment by bvaughn** [comment]
No problem :) Thank _you_ for contributing. I'll get that PR merged and released for you sometime soon.

**Comment by mattcolman** [comment]
is this only available on Table? What about for a List? Click handlers on rows within are List are not working for me :(

**Comment by bvaughn** [comment]
You render the entire `List` row. You can add whatever event handlers you want to it.

**Comment by individual11** [comment]
Sorry to jump on this thread, but it comes up in most of my google searches. Is the recommended way to handle _onClick_ for **List** is on the _rowRender_? If so, you should totally drop a note about it in the docs.

**Comment by reyanshmishra** [comment]
@bvaughn  onRowClick link is broken .
