### ISSUE TITLE
Preventing VirtualScroll contents from going under scroll bar

### ISSUE THREAD

**Issue by trevorr** [bvaughn/react-virtualized#279]
I've noticed that because the width of the `Grid__innerScrollContainer` is set to the same value as the `Grid`, the contents of a `VirtualScroll` go under the scroll bar. This is causing an issue for me with focusable rows because the right focus border is hidden by the scroll bar:

<img width="431" alt="screen shot 2016-06-15 at 1 58 07 pm" src="https://cloud.githubusercontent.com/assets/928766/16095533/a17d9c9c-330a-11e6-9648-0c84fb3e6fca.png">

Components like `react-virtualized-select` sidestep this issue by using background color to indicate focus, rather than an outline, though the rows still extend behind the scroll bar:

<img width="415" alt="screen shot 2016-06-15 at 1 42 28 pm" src="https://cloud.githubusercontent.com/assets/928766/16095551/b2f155ea-330a-11e6-97ed-ac55e5dff201.png">

For visual consistency with other (Bootstrap-based) components, I'd like to keep its focus styling, rather than just using background color. I thought about using right padding inside the rows, but that has several problems, including that the scroll bar may not always be present and, when it is, its width will vary across browsers. I think the ideal way to fix this is to specify `width="100%"` (rather than the fixed `Grid` width) for the `Grid__innerScrollContainer` and the contained rows/cells. Hacking these changes in at runtime yields the desired appearance:

<img width="430" alt="screen shot 2016-06-15 at 1 59 30 pm" src="https://cloud.githubusercontent.com/assets/928766/16095564/c000714e-330a-11e6-82df-99aae8cd6fc5.png">

Now I realize that because `VirtualScroll` is based on `Grid`, which supports bidirectional scrolling and multiple columns, achieving this may be tricky. Any thoughts on how it might be done? I can attempt to submit a PR if we can come up with an acceptable approach.

**Comment by bvaughn** [comment]
This is somewhat complicated, as you guessed, because of the inner `Grid` and its constraints. See related issues #222 (the most recent and so the most relevant), #154, #131, #116, #101, #80.

I'd welcome suggestions or ideas from you on how to improve this aspect of RV, so long as we could fix without a regression of one of the issues mentioned above.

**Comment by trevorr** [comment]
The best way I could come up with is to allow `Grid` column and row sizes to be specified as percentages, and then in `VirtualScroll`, specify the width of the single column as `100%`. While much more general than what `VirtualScroll` needs for this issue, generalizing the feature avoided complicating the API with additional properties and (excessively) complicating the lower-level `Grid` components. It also might be useful to `Grid` users as a more convenient alternative to `ColumnSizer` in some situations.

I had to actually try to implement it to see if it would work, but it was actually pretty straightforward: I added another subclass of `CellSizeAndPositionManager` that works in terms of percentages. When either the first/only column/row size is a percentage, `PercentCellSizeAndPositionManager` is used instead of `ScalingCellSizeAndPositionManager`. Because percentages are relative the visible region of the scroll container, much of the logic in `PercentCellSizeAndPositionManager` is trivial.

I also added a mode to the `Grid` demo that demonstrates percentage column sizes. (Obviously, it needs to bump the column count down to a reasonable number, since the columns must all fit.) You can see that by changing the row count to hide/show the vertical scroll bar, the contents automatically adjust to the available space.

I sent a pull request with the changes. Let me know what you think.

**Comment by bvaughn** [comment]
I'm a little curious how you're seeing the left focus border of your row in the first screenshot you sent. For me, I only see the top-bottom- and even then only after adjust z-index when focused:

<img width="467" alt="screen shot 2016-06-21 at 7 16 22 am" src="https://cloud.githubusercontent.com/assets/29597/16232623/2f3eab1a-3780-11e6-8517-70170c382462.png">

```css
.row:focus {
  z-index: 2;
  position: absolute;
  width: 100%;
}
```

**Comment by trevorr** [comment]
I'm using Bootstrap, which sets `outline-offset: -2px` for `a:focused`, and my dropdown menu is structured as `ul > li > a[tabindex=-1]`. So I'm focusing the row content, rather than the row container.

Regarding aesthetics, I'll agree that unbalanced left/right looks worse, but I hope you can understand that I'm not willing to drop the left/right focus edges due to a sizing bug. Everything else in Bootstrap uses a focus rectangle (via the `tab-focus` mixin, at least for Sass version). But even if it weren't for Bootstrap focus styling, it's not hard to imagine other styling issues from having the right edge hidden behind a scrollbar. Conceptually, since `VirtualScroll` only scrolls vertically, the contents should be completely visible horizontally.

**PS:** I have my React Bootstrap combo-box and virtualized add-on fully working now, so I'm now working on docs and demos in preparation for open-source release. The virtualized version has focus and keyboard navigation working perfectly aside from this minor issue (which is a testament to the completeness of `react-virtualized`, given that no one else seems to be using it quite this way). Hopefully, I'll have it on GitHub this week, so you can see exactly how I'm using `react-virtualized`.

**Comment by bvaughn** [comment]
Oh, exciting! I look forward to seeing it once you open source it. :) It's really cool to see things being built on top of react-virtualized.

Understood about the left/right focus thing. I'll give it some more thought. I'm super wary of adding more forking complexity to `Grid` because it means I have to support that going forward and I'm already stretched a bit thin on this project. We'll figure something out though!

**Comment by bvaughn** [comment]
7.11.3 has this fix.

**Comment by trevorr** [comment]
Great, thanks! Works like a champ. I'll send a link to my component once it's up on GitHub.

**Comment by trevorr** [comment]
@bvaughn: I just published my [Autosuggest](https://affinipay.github.io/react-bootstrap-autosuggest/) component, _not_ including the `react-virtualized` add-on. It took more work to document and prepare than I expected. 😓  Due to work and travel schedule, it will be a few more weeks to get the virtualized add-on ready, but I'll follow up when it's released.

**Comment by bvaughn** [comment]
Thanks for sharing @trevorr. It looks nice! Can't wait to see a react-virtualized option for larger lists :D
