### ISSUE TITLE
WindowScroller degraded performance due to assigned scrollTop

### ISSUE THREAD

**Issue by aduth** [bvaughn/react-virtualized#281]
Related: #270 cc @minheq 

I've been trying to incorporate the newly-introduced WindowScroller component into our application, and while I was successful in doing so, I noted that scrolling the page did not feel very smooth.

After some profiling, I found that this set of lines is triggered very frequently, causing many forced repaints:

https://github.com/bvaughn/react-virtualized/blob/19bcb10/source/Grid/Grid.js#L298-L318

Since with WindowScroller, the element being scrolled is the window, not the rendered grid, `this.refs.scrollingContainer` will always have a `scrollTop` of `0`, and so this assignment happens much more frequently than I imagine is expected. Removing this set of lines seems to improve the experience a bit, but obviously this would regress non-WindowScroller usage. Generally speaking, most of the `Grid.js` file appears to assume that scrolls will occur within the rendered container (understandable since WindowScroller was a later addition).

It's not immediately obvious to me how this could be solved, since Grid can't know whether the received `scrollTop` is from a WindowScroller or a ScrollSync (where the latter would want to assign the `scrollTop` of the `scrollingContainer`). Perhaps an extra prop like `windowContext` to avoid the `scrollTop` being assigned, or one to more generally indicate that overflow is visible, not scrolled?

Code: https://github.com/Automattic/wp-calypso/blob/update/cpt-infinite-list-2/client/my-sites/post-type-list/index.jsx
Demo: https://calypso.live/types/post?branch=update/cpt-infinite-list-2 (assumes active WordPress.com user session with a site containing enough posts for scrolling; unfortunately a decent amount of effort involved if not available to you already)

**Comment by aduth** [comment]
>or one to more generally indicate that overflow is visible, not scrolled?

D'oh, now that I think of it, that's more or less what `autoHeight` is, right? I wonder if it would be simple enough to key off of that prop, not checking against or trying to assign `scrollTop` if `true`. I might toy with this idea and submit a pull request if it works out.

**Comment by minheq** [comment]
I see :) I actually also encountered performance issues on the project I am working on, but only when I used development mode. With production build it is smooth though. But it could definitely be improved. Thanks for looking into this :D I will try to look into this in free time as well and try to optimise the HOC :)

**Comment by bvaughn** [comment]
I just released version 7.8 with significant scrolling performance improvements to `FlexTable`. Can you check again and let me know if this helps with any of your concerns? (I didn't specifically do anything related to this issue but I still wonder if the release helps with what you're seeing.)

**Comment by bvaughn** [comment]
Bummer. Had to revert the `tabIndex` change to `Grid` and release as 7.8.1 to avoid breaking keyboard accessibility too badly. This drops a couple of FPS because of focus causing repaints. But.... it's still a marked improvement for `FlexTable` over all.

**Comment by aduth** [comment]
@bvaughn In my case, since I'm using `VirtualScroll`, not sure I'd reap the benefits of any `FlexTable` improvements? But I'll give it a shot though, hopefully sometime today.

Yesterday I found some time to put together some changes to avoid assigning the `scrollTop`, which I think works and has a small benefit, but not a dramatic improvement. Still worth adding I think, but had some trouble with tests. Not sure if it's a PhantomJS thing with `scrollTop` DOM properties, but I'll drop it as a comment when I put together a pull request.

The other thing I noted was that `Grid` uses a `pointer-events` trick to improve performance, which we don't get to take advantage of with `WindowScroller` (since `onScroll` for `Grid` isn't fired). Think it might be worth improving `WindowScroller` to apply the `pointer-events` to `body` or a dynamically created overlay element?

**Comment by bvaughn** [comment]
D'oh! Sorry I must have misremembered when I read that comment. I thought I recalled you saying you were using `FlexTable` + `WindowScroller`.

Yes, `Grid` uses `pointer-events` while scrolling for performance reasons. Maybe we could add a prop (eg `disablePointerEvents`) so that `WindowScroller` could also trigger this optimization. It doesn't feel the cleanest separation but..._if_ it significantly improves performance I'd be willing to consider it. Maybe give it a try and let me know? :)

You can use the new FPS measuring util I wrote to compare~ bvaughn/fps-measurer

Examples of this can be found in playground~ https://github.com/bvaughn/react-virtualized/blob/master/playground/table.js

**Comment by bvaughn** [comment]
7.8.3 has been released with this change. Enjoy!
