### ISSUE TITLE
FlexTable's header columns become misaligned when using flexGrow

### ISSUE THREAD

**Issue by EvNaverniouk** [bvaughn/react-virtualized#289]
Using v7.9.0, when a FlexTable requires vertical scrolling (ie. more rows than can fit) and you use `flexGrow` on any column, the initial render of the table doesn't correctly align the column headers.

I have created a reproducible test case here: https://plnkr.co/edit/2iYYHNlDEcI29W2DgJBL?p=preview

Note the misaligned "Age" header title.

![screen shot 2016-06-21 at 4 48 21 pm](https://cloud.githubusercontent.com/assets/226640/16250144/ff95d21c-37cf-11e6-9681-abf509ef1824.png)

This will self-correct when you scroll down.

![screen shot 2016-06-21 at 4 48 25 pm](https://cloud.githubusercontent.com/assets/226640/16250146/02b5e770-37d0-11e6-83d4-47032ea4eb27.png)

- Calling `forceGridUpdate` doesn't seem to correct this
- Calling `forceUpdate` on the parent component doesn't seem to correct this
- Could it have something to do with the flexStyle caching that's being done in the Grid component?

**Comment by bvaughn** [comment]
Hm. Seems scrollbar related.

I'll try to take a look when I can. I'm getting a bit overwhelmed with features/issues though.

**Comment by bvaughn** [comment]
Hey @EvNaverniouk,

This issue has been fixed in 7.9.1! Thanks for the bug report and the repro Plunk!

**Comment by EvNaverniouk** [comment]
Fix confirmed!
