### ISSUE TITLE
Auto-size list based on height of children

### ISSUE THREAD

**Issue by oyeanuj** [bvaughn/react-virtualized#29]
(moving issues from #25 )

Today, the VirtualScroll component requires a rowHeight and a height for itself. This feature request is to for the plugin to not require -
 1. The component height but instead calculate based on the just the heights of the element itself.
 2. The rowHeight and instead base that on the content of the height

This would make the plugin immensely flexible and allow it to tackle cases where those heights either might be unknown or can change (expand/collapse based on user actions) or where the container height can be flexible.

My immediate use-case where this would be useful is for lazy-loading feeds (think Facebook, Twitter, etc).

If anyone has any other examples, use-cases or suggestions around this feature, please add them here.

**Comment by bvaughn** [comment]
> The component height but instead calculate based on the just the heights of the element itself.

I'm thinking of creating a wrapper component that will automatically expand a list or table to fill the available width and height. I'm thinking of something kind of like this:

```javascript
<AutoSizer
  child={VirtualScroll}
  rowsCount={list.length}
  rowHeight={20}
  rowRenderer={
    index => (
      <div key={index}>
        {list[index]}
      </div>
    )
  }
/>
```

> The rowHeight and instead base that on the content of the height

Supporting dynamic row height is pretty complicated. I actually created issue #23 to experiment with this.

**Comment by bvaughn** [comment]
Okay so I created an `AutoSizer` component as described above. I'd be interested in hearing your thoughts once you've had a chance to play with it. I'll try to release it in an update sometime this afternoon.

**Comment by bvaughn** [comment]
This component is available in release 2.5.0. Check it out.

**Comment by oyeanuj** [comment]
@bvaughn Sorry for disappearing but just getting a chance to get back to the project and this use-case. I am excited to try it out!

Couple of quick questions -

1. In the new demo, I noticed you added `useDynamicRowHeight` :) Is that also an acceptable property or expected to work with `Autosizer`?

2. The link to docs on `Autosizer` lead to an empty page. Not sure if that was the wrong link or you just haven't had a chance to add them. Either way, thought I should mention it.

Thanks again for your work and receptiveness to issues! :)

**Comment by bvaughn** [comment]
Happy new year to you also, @oyeanuj!

Thanks for pointing out the bad docs link. Looks like I forgot to actually _write_ those docs. (Whoops.) I will fix it momentarily. :)

**Comment by Hari-Shankar-3296** [comment]
Thanks for this wonderful library, @bvaughn. Which I have used in some places in different apps. But still, I am quite confused about some concepts. Is there any demo for chat messages virtualization which will have auto height rows and auto height List? i.e there is no fixed height for the list as well as rows.
