### ISSUE TITLE
Custom FlexColumn

### ISSUE THREAD

**Issue by pr0digy** [bvaughn/react-virtualized#294]
Would you consider removing FlexColumn type restriction in FlexTable children check?  That would allow using custom pre-configured FlexColumns.  For example: index column, column with an image/icon, or a link or a checkbox with certain behavior.

Also, some libraries, such as react-intl, provide an odd interface and require one to [inject](https://github.com/yahoo/react-intl/wiki/API#injection-api) its API into a component, which in turn changes component's type.  Therefore, at this point in time I cannot localize/customize FlexColumn without overriding FlexTable's propTypes...

**Comment by bvaughn** [comment]
Hey @pr0digy,

I'm not familiar with react-intl. Will it proxy the props for the "injected" component? Or does it just inject props into the component and render it? B'c if the latter- it wouldn't work as a `FlexTable` child.

Have you considered just using react-intl to wrap your rendered table cell instead? Here's what I'd try. Let me know if something like this works? :)

```js
import React from 'react'
import { injectIntl, intlShape, FormattedRelative } from 'react-intl'
import { FlexColumn, FlexTable } from 'react-virtualized'

const YourCellRenderer = ({ date, intl }) => (
  <span title={intl.formatDate(date)}>
    <FormattedRelative value={date}/>
  </span>
)

const IntlCellRenderer = injectIntl(YourCellRenderer)

function IntlFlexColumn (props) {
  return (
    <FlexColumn
      cellRenderer={IntlCellRenderer}
      {...props}
    />
  )
}

function renderIntlTable () {
  return (
    <FlexTable {...tableProps}>
      {IntlFlexColumn(columnProps)}
      {...otherColumns}
    </FlexTable>
  )
}
```

**Comment by pr0digy** [comment]
Thanks for you suggestion, Brian!

Rendering cells is not an issue, the problem lies within column header labels - there is no custom renderer for those. 

I should clarify, react-intl has a number of components, like FormattedMessage and I can use those within a renderer, but when it comes to inline attributes which require simple data types injectIntl API has to be used...  So, in this case, I can see two solutions: inject api into FlexColumn or add a custom renderer for header label.

**Comment by bvaughn** [comment]
> Rendering cells is not an issue, the problem lies within column header labels - there is no custom renderer for those.

Sure there is. :) You can pass `FlexColumn` a [`headerRenderer`](https://github.com/bvaughn/react-virtualized/blob/master/docs/FlexColumn.md#headerrenderer) too (or instead, in your case).

**Comment by pr0digy** [comment]
Oh, I feel silly now :) Sorry for bothering you for no reason.  Thanks for taking the time to explain!

**Comment by bvaughn** [comment]
No problem at all! Glad it works for you. :)
