### ISSUE TITLE
Add inline styles for the header row on FlexTable

### ISSUE THREAD

**Issue by KyleAMathews** [bvaughn/react-virtualized#306]
You can add inline styles for regular rows and for header columns but it looks like applying a style to the header row was overlooked.

In the meantime I can custom render the header so this isn't urgent but it seems like something that should be there.

**Comment by KyleAMathews** [comment]
Oh hmmmm... I assumed that you could supply a custom render function for the header but I guess not. Time to fire up the ol' css engine I guess :-)

**Comment by bvaughn** [comment]
Hey @KyleAMathews,

The header row can be styled too!

[Here](https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/FlexTable.js#L245) is where the row-class is fetched and [here](https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/FlexTable.js#L265) is where the row-style is set for the header row.

The `rowClassName` getter is passed an index of -1 for the header row. The `rowStyle` object is currently expected to just be an object vs a getter function. Maybe the real request here is just adding support for an Object _or_ a factory-Function?

**Comment by KyleAMathews** [comment]
ah yes, if `rowStyle` could be a function then I would have all the unicorns I want :-)

**Comment by bvaughn** [comment]
Sorry it took me a bit longer than usual to get around to this @KyleAMathews. Been a bit distracted this week preparing for an upcoming trip. 7.12.0 has this new feature!

**Comment by KyleAMathews** [comment]
💯 thanks!
