### ISSUE TITLE
Warning with React 15.2.0

### ISSUE THREAD

**Issue by levrik** [bvaughn/react-virtualized#310]
Hey there. I'm getting the following warning after upgrading to React 15.2.0

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `AutoSizer`. See https://fb.me/react-warning-keys for more information.
    in Column (created by AutoSizer)
    in AutoSizer (created by MyComponent)
```

Only happening if using a FlexTable inside.

**Comment by bvaughn** [comment]
Hey @levrik,

`FlexTable` displays an array of rows ([which have keys](https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/FlexTable.js#L469) and rows contain an array of columns ([which have keys](https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/FlexTable.js#L345)) so I don't think you should get that warning from `FlexTable` by default. Are you using a custom `cellRenderer` for any of the table columns? [The default renderer just returns a string.](https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/defaultCellRenderer.js) Maybe you're using a custom one that returns an array?

I'm using React 15.2 as well and I see no warnings when using `AutoSizer` + `FlexTable`. (We actually do a lot of this in our app at Treasure Data.)

**Comment by bvaughn** [comment]
I think I'm going to need a Plunker that reproduces the problem, as the new issue template requests.

> Here is a Plunker you can fork that has React Virtualized loaded and supports JSX syntax: https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1

**Comment by levrik** [comment]
Sorry, my bad, found the issue. I'm creating the FlexColumn's out of an array with the .map-method and used a undefined property for the key property of FlexColumn.
Closing this and still thanks for your help. Sorry, once again.

**Comment by bvaughn** [comment]
No worries! Glad it was something simple. :)

Been there, done that, with map.
