### ISSUE TITLE
Invalid height/scroll calculation for VirtualScroll

### ISSUE THREAD

**Issue by warent** [bvaughn/react-virtualized#323]
Hi there,

I love the components and I'm excited to use it for our production.

I'm currently working on a project which would make very good use of this extension, specifically VirtualScroll because you allow for dynamic heights. In your example of VirtualScroll dynamic height, you really more-so use what I would call multiple static heights, whereas for this project I'm attempting to achieve fully dynamic height.

One setback is that VirtualScroll asks for the element height before trying to render it, understandably. To get around this, I render the node in a hidden element and get the offsetHeight, which I then return to the VirtualScroll and then unmount the node for cleanup. This means every node needs to be rendered twice, but the performance losses, if any, are marginal and unnoticeable.

The only problem I'm running into is that even though I'm returning the correct node height, the VirtualScroll seems to be miscaluclating somewhere. Please see the screenshots:

![screenshot from 2016-07-23 14-59-28](https://cloud.githubusercontent.com/assets/13342266/17080274/2b235876-50e6-11e6-8aaf-e6c442249796.png)
![screenshot from 2016-07-23 14-59-35](https://cloud.githubusercontent.com/assets/13342266/17080275/35bafb36-50e6-11e6-98bb-7d7f852b268f.png)

Full source:
https://github.com/VYNYL/gulpnoir
Specifically:
https://github.com/VYNYL/gulpnoir/blob/master/app/containers/Home/index.jsx

simply `$ npm install` and `$ npm run dev`

The technology stack uses Electron + React + Webpack

Thank you for your time. I'll continue investigating and post here if I find a solution

**Comment by warent** [comment]
You should be able to ignore the visual anomalies of the other overlapping divs, etc. Those are minimal priority, I'm working on just getting base functionality working before clean-up

**Comment by warent** [comment]
It seems like for every one scroll down (one time clicking the scroll arrow) it moves four indices but only removes/renders two. It's seemingly off by half

**Comment by bvaughn** [comment]
Hey @warent,

Thanks for the compliment. :)

Looks like you're forgetting to include the stylesheet at a glance. Check out the [getting started section](https://github.com/bvaughn/react-virtualized#getting-started):

```js
import 'react-virtualized/styles.css';
```
...or...
```html
<link rel="stylesheet" href="path-to-react-virtualized/styles.css">
```

**Comment by warent** [comment]
Hi @bvaughn 

You bet :)
Thanks for the suggestion. I actually do have it included in https://github.com/VYNYL/gulpnoir/blob/master/app/index.jsx but just to be safe I went on ahead and included it in the `Home/index.jsx` file directly. Same results unfortunately.

I'm going to start the project from scratch and build from the ground-up to see if we can isolate the issue. I'm wondering if it's something with Electron or Material UI

I'll report back my results!

**Comment by bvaughn** [comment]
Okay! If you can reproduce it or share a link with me so I could take a
look that would be helpful.

Fwiw this issue has been reported a few times and it's always CSS related.
(Is your build tool converting class names to CSS modules?)

**Comment by warent** [comment]
@bvaughn 

Hahaha good call, that was a pretty novice oversight on my part! I have to import the CSS file as a module and apply the className, just like you did in your examples.

Thanks for your patience!

**Comment by warent** [comment]
Also the stylesheet wasn't being imported properly by webpack for some reason.

Future reference for anyone experiencing this problem, make sure your CSS is properly included. @bvaughn knows what he's doing!

**Comment by bvaughn** [comment]
Haha, glad to hear the solution was an easy one :)

**Comment by kwent** [comment]
In my case, i had to tell webpack to raw import css.

```javascript
import '!style!css!react-virtualized/styles.css';
```

Regards
