### ISSUE TITLE
Grid doesn't scroll horizontally if it only has one column

### ISSUE THREAD

**Issue by mwilliamson-healx** [bvaughn/react-virtualized#325]
If a `Grid` component only has one column and the total of its columns widths is greater than the width of the `Grid`, then a horizontal scrollbar doesn't appear as I would expect. A horizontal scrollbar does appear if the column count is greater than one.

This seems to be a regression in 7.11.3. Specifically, [the change to set the `width` to `auto` if there's exactly one column](https://github.com/bvaughn/react-virtualized/pull/300/files#diff-43c6f2c20a98e4816031a2f99092ecb4R583).

Demo of the issue: https://plnkr.co/edit/dxxnRlG1xAPiXPf36MiB?p=preview

**Comment by bvaughn** [comment]
This was kind of an intentional change, to avoid the possibility of scrollbars being shown and getting stuck (like they sometimes can if the size hovers right around the threshold). My assumption at the time was that if a `Grid` has only 1 column, you'd make the `Grid` width large enough to accommodate that column, and scroll the `Grid` itself if necessary. (After all, the primary purpose of a `Grid` is windowing- and if there's nothing to window...)

Like so:
https://plnkr.co/edit/2PrNKS930dhvWpDcTv4P?p=preview

**Comment by bvaughn** [comment]
This change also simplifies using single-column components like `VirtualScroll` within the context of eg a drop-down menu.

**Comment by mwilliamson-healx** [comment]
The problem with setting the width of an outer element is that you can't see the vertical scrollbar without scrolling to the right e.g.

https://plnkr.co/edit/n6KKSQH6wTa7i0qcDaU1?p=preview

Both the horizontal and vertical scrollbars need to be on the same element to provide the experience that a user expects.

More generally, I feel like having a special case for one column makes the behaviour of the component surprising.

**Comment by bvaughn** [comment]
D'oh. Good point about the scrollbars. As an OS X user, I too frequently overlook this case. Sorry!

I need to decide how best to reconcile this with functionality added in [7.11.3](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#7113) since that is also important to RV users.

**Comment by svikasg** [comment]
+1.

Also, consider the scenario or a feature where one would like to have a column on the left/ right to stick during the scroll. Doing a sticky header (and first row) can also be a scenario in conjecture with the sticky column. It would be nice to think of such a scenario when you are trying to come up with a solution to a related feature - scrollbars

**Comment by bvaughn** [comment]
This was fixed and released last night as [`7.16.0`](https://github.com/bvaughn/react-virtualized/releases/tag/7.16.0). Github was down at this time so I couldn't mark the ticket as closed and it slipped my mind this morning. :)

**Comment by mwilliamson-healx** [comment]
Great, thanks!
