### ISSUE TITLE
VirtualScroll doesn't define forceUpdate function 

### ISSUE THREAD

**Issue by sunvooker** [bvaughn/react-virtualized#326]
VirtualScroll has no 'forceUpdate' function, but InfiniteLoader use it,

in source code , is this a bug???
// infiniteLoader (line 110)
            if (this._registeredChild) {
              this._registeredChild.forceUpdate()
            }
//

**Comment by bvaughn** [comment]
`forceUpdate` is a method available on all React `Component`s: https://facebook.github.io/react/docs/component-api.html#forceupdate

So unless you're seeing some broken behavior- I don't think there's any bug (that I'm aware of). Going to close this issue for now. Please reply back with more info if there are still concerns. :)
