### ISSUE TITLE
Collection re-render as no content when calling recomputeCellSizesAndPositions() method

### ISSUE THREAD

**Issue by coluccini** [bvaughn/react-virtualized#328]
I'm working in a responsive layout base on Collection and I need to recalculate cells sizes and position every time the window size changes. I've been told that for achieving this I need to call method `recomputeCellSizesAndPositions()`, but every time I do that the component Collection seems to loose cells information and fired up the `noContentRenderer()` method (even when every cell was perfectly rendered before resizing the window). 
Have anybody cross this problem or had used `recomputeCellSizesAndPositions()` successfully? Even if @bvaughn told me that it looks like a component bug, I think that could be that I'm doing something wrong (I'm brand new in React):

I've put the test code in this repo just in case someone can take a look at it:
https://github.com/coluccini/virtualized-test/

The important part happens in this component: 
https://github.com/coluccini/virtualized-test/blob/master/src/components/ListPage.js

Thanks a lot in advance!

**Comment by bvaughn** [comment]
Seems a legit `Collection` bug. Can be reproduced in the test harness app with the following modifications:
```diff
diff --git a/source/Collection/Collection.example.js b/source/Collection/Collection.example.js
index 53c2844..4efc5f8 100644
--- a/source/Collection/Collection.example.js
+++ b/source/Collection/Collection.example.js
@@ -68,6 +68,10 @@ export default class CollectionExample extends Component {
           </label>
         </ContentBoxParagraph>
 
+        <button onClick={() => this.Collection.recomputeCellSizesAndPositions()}>
+          recomputeCellSizesAndPositions
+        </button>
+
         <InputRow>
           <LabeledInput
             label='Num cells'
@@ -99,6 +103,7 @@ export default class CollectionExample extends Component {
               className={styles.collection}
               height={height}
               noContentRenderer={this._noContentRenderer}
+              ref={(ref) => this.Collection = ref}
               scrollToCell={scrollToCell}
               width={width}
             />
```

**Comment by bvaughn** [comment]
Whoops. Spoke too soon. Forgot about how I was generating random data on-demand in that component. The correct diff would be...
```diff
diff --git a/source/Collection/Collection.example.js b/source/Collection/Collection.example.js
index 53c2844..8826a4d 100644
--- a/source/Collection/Collection.example.js
+++ b/source/Collection/Collection.example.js
@@ -68,6 +68,15 @@ export default class CollectionExample extends Component {
           </label>
         </ContentBoxParagraph>
 
+        <button
+          onClick={() => {
+            this._columnYMap = []
+            this.Collection.recomputeCellSizesAndPositions()
+          }}
+        >
+          recomputeCellSizesAndPositions
+        </button>
+
         <InputRow>
           <LabeledInput
             label='Num cells'
@@ -99,6 +108,7 @@ export default class CollectionExample extends Component {
               className={styles.collection}
               height={height}
               noContentRenderer={this._noContentRenderer}
+              ref={(ref) => this.Collection = ref}
               scrollToCell={scrollToCell}
               width={width}
             />
```
...which dose not demonstrate the problem. Hm.

**Comment by bvaughn** [comment]
Haha! Looks like your demo project followed this same format, so the fix was actually the same thing. :)

```diff
diff --git a/src/components/ListPage.js b/src/components/ListPage.js
index f46ad18..63cb526 100644
--- a/src/components/ListPage.js
+++ b/src/components/ListPage.js
@@ -35,6 +35,7 @@ export default class ListPage extends Component {
   }
 
   handleResize() {
+    this._columnYMap = []
     this.setState({ width: window.innerWidth, height: window.innerHeight });
     this.refs.Collection.recomputeCellSizesAndPositions();
   }
```

Just reset your `_columnYMap` so when the sizes are re-measured, you aren't doubling things up. :)

**Comment by coluccini** [comment]
We've just met and I think I already love you! Thanks you so much! We are going to use this in a production site. So I'll let you know how it goes and about any change we could end up doing. Thanks again for the help and for this amazing module!
