### ISSUE TITLE
[DOCS] Confusing discrepancy while using Wizard

### ISSUE THREAD

**Issue by ajgreenb** [bvaughn/react-virtualized#329]
**Please close this if it shouldn't be an issue on the main repository.** It's not a question about how to use React Virtualized, but it's not exactly a bug or feature request.

I'm using the Wizard with the following configuration.

![image](https://cloud.githubusercontent.com/assets/8922554/17213776/cc242794-54a3-11e6-9e62-7a7fdd1ef4a4.png)

It recommends using a `<CellMeasurer/>` with a `<FlexTable/>`. Is this an okay thing to do? I gathered from the [docs][cell-measurer-docs] that `<CellMeasurer/>`s are currently only compatible with raw `<Grid/>`s.

[cell-measurer-docs]: https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md

**Comment by ajgreenb** [comment]
Also in that example, I checked "Are all of your rows the same height?" and "Do you know the height of your rows ahead of time?", but the `<CellMeasurer/>` passes in the `getRowHeight` callback. Since I didn't check "Do you know the width of your columns ahead of time?" shouldn't it pass in `getColumnWidth`?

This discrepancy is still visible if you deselect "Should all your columns be visible at once?", which changes the `<FlexTable/>` to a `<Grid/>`. In that case, the passed callback is still `getRowHeight`, but the `<Grid/>` uses `getColumnWidth`:

![image](https://cloud.githubusercontent.com/assets/8922554/17214020/002d9402-54a5-11e6-8b83-03161f13cf63.png)

**Comment by bvaughn** [comment]
> It recommends using a `<CellMeasurer/>` with a `<FlexTable/>`. Is this an okay thing to do? I gathered from the docs that `<CellMeasurer/>`s are currently only compatible with raw `<Grid/>`s.

Ah. Looks like the reason for this is that you've unselected the "do you know the width of your columns ahead of time" option - which usually means the cells need to be measured. I can see how it's ambiguous in the case of `FlexTable` though. I'll address this edge-case in the wizard.

> Also in that example, I checked "Are all of your rows the same height?" and "Do you know the height of your rows ahead of time?", but the `<CellMeasurer/>` passes in the `getRowHeight` callback. Since I didn't check "Do you know the width of your columns ahead of time?" shouldn't it pass in `getColumnWidth`?

Yup! Definitely should. I had a typo.

Both of these issues have been fixed. (Although it may take a few minutes for Github's cache to invalidate.) Thanks for the detailed report. :)
