### ISSUE TITLE
Replace sort indicator icon

### ISSUE THREAD

**Issue by ellenc345** [bvaughn/react-virtualized#332]
Is it possible to change the sorting arrow to another svg icon?
I tried to edit the FlexTable__sortableHeaderIcon class but it doesn't work

**Comment by bvaughn** [comment]
Hi @ellenc345 ,

Yes. It's possible. `FlexColumn` allows you to specify your own [`headerRenderer`](https://github.com/bvaughn/react-virtualized/blob/master/docs/FlexColumn.md#headerrenderer) which can use any sort indicator you like. (Doesn't even have to be an SVG.)

**Comment by bvaughn** [comment]
Let me know if you have more questions. I'm going to close this for now since (I think) the initial question has been answered. :)

**Comment by ellenc345** [comment]
Thanks, its working now :)
