### ISSUE TITLE
Unknown prop type (Latest React version issue)

### ISSUE THREAD

**Issue by dsifford** [bvaughn/react-virtualized#334]
I _believe_ this issue is stemming from react-virtualized. If it isn't please disregard.

I'm getting warnings in the console due to the fact that (I think) the Autosizer component you have uses non-standard proptypes (specifically, `minWidth`). React did away with this [in the latest update](https://fb.me/react-unknown-prop).

Here's the full warning: 

```
warning.js?8a56:44 Warning: Unknown prop `minWidth` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by AutosizeInput)
    in div (created by AutosizeInput)
    in AutosizeInput (created by Select)
    in div (created by Select)
    in div (created by Select)
    in Select (created by VirtualizedSelect)
    in VirtualizedSelect (created by Menu)
    in div (created by Menu)
    in div (created by Menu)
    in div (created by Menu)
    in Menu (created by ReferenceList)
    in ReactCSSTransitionGroupChild (created by ReactTransitionGroup)
```

Thanks for your work on this! 👍 

**Edit:** I suppose it should be noted that I'm using react-virtualized indirectly through react-virtualized-select

**Comment by bvaughn** [comment]
Hey @dsifford,

The only place `minWidth` (or `maxWidth`) is used in `react-virtualized` is as a `FlexColumn` prop. In this case though the prop is used to set a `style` value; it isn't passed on to any DOM elements like an `<input>`. (In fact, `react-virtualized` doesn't have any `<input>` tags.)

`AutoSizer` doesn't render anything directly. It uses the child function pattern to pass named `width` and `height` parameters to be used however people want.

The problem in this case seems to be coming from another repo, JedWatson/react-input-autosize, although it looks like Jed has [already fixed this issue](https://github.com/JedWatson/react-input-autosize/blob/d0a408c18a1f67bd0a1c2f7b175b0d9dd8adfe3d/src/AutosizeInput.js#L92-L114) by removing unsupported props. I'm guessing that fix went out in a version that's newer than the version you're using?

**Comment by bvaughn** [comment]
Looks like `react-input-autosize` is currently at version 1.0.0 and `react-select` is using version 1.1.0 (which I guess is a pre-release version Jed's testing locally? Not sure...)

Either way, my repo- [bvaughn/react-virtualized-select](https://github.com/bvaughn/react-virtualized-select/)- is using the latest version of `react-select` that's been released. So there's not much I can do about it at the moment. :D

Hopefully it will be fixed automatically when Jed releases the next `react-select` release candidate!

**Comment by bvaughn** [comment]
Closing for now since it's not a react-virtualized problem. :D

**Comment by dsifford** [comment]
Ah, very good! Thanks for the quick reply 😃

**Comment by bvaughn** [comment]
Haha, no problem! I was just patting myself on the back for the unusually fast turn-around time on this one 😉 😜  lol

**Comment by dsifford** [comment]
Update: It was totally my own fault. I had `react-select` listed as a dependency as well (likely from before I found react-virtualized-select) and that created a dependency version conflict between itself and your package. 

Removed the stale dependency and now everything is all set 👍

**Comment by bvaughn** [comment]
Great! Glad to hear. :)
