### ISSUE TITLE
VirtualScroll scrollBar not showing up when item size change

### ISSUE THREAD

**Issue by jkiepura** [bvaughn/react-virtualized#335]
I'm trying to use VirtualScroll (with autoSizer) with items that can change their height when clicked. Everything work well except when the height of the list of items is shorter than the container height before any item expansion (in which case the scrollbar does not appear). I'm joining a small example. 

In this example, you have access to 2 lists of items: "NotDefined" and "Plausible". The "Plausible" list of items makes the scrollbar appear. When you click on an item in the list, the scrollbar adjust itself to the new height, which is expected behaviour. The "NotDefined" list contains only 2 items and the scrollbar does not appear. Clicking on an item to expand it does not make the scrollbar appear, even if the total height of the list is longer than the container. I tried to use the public methods of VirtualScroll to refresh the state of the scroller in order to make the scrollbar appear, but it has no effect on the scrollbar visibility.

Is this a bug or a misuse of the component from me?

[vs-scrollbar-problem.zip](https://github.com/bvaughn/react-virtualized/files/404342/vs-scrollbar-problem.zip)

**Comment by bvaughn** [comment]
Hi @jkiepura. Can you provide your source code before uglification?

**Comment by jkiepura** [comment]
Sorry, here's the source code (without the node_modules folder). I'm using webpack and Babel. The VirtualScroll is in the src\components\Observations component. The code has been modified from a bigger project, many properties are hard coded, and the autoSizer is not dynamicly expanding.


[vs-scrollbar-problem-source.zip](https://github.com/bvaughn/react-virtualized/files/404376/vs-scrollbar-problem-source.zip)

**Comment by bvaughn** [comment]
Thank you.

**Comment by bvaughn** [comment]
Hm. One problem is that you're hard-coding the list `rowHeight={80}`.

**Comment by bvaughn** [comment]
This is only _kind of_ working in the 2nd example b'c `react-virtualized` stylesheets aren't being loaded. :)

**Comment by jkiepura** [comment]
yes, but I cannot evaluate dynamically the height of an item at runTime, with a dynamic function. And I cannot omit rowHeight since it's required. I'm using a custom rowStyle to let the items grow on-demand.

Sorry about the package, maybe it's missing some files

**Comment by bvaughn** [comment]
> yes, but I cannot evaluate dynamically the height of an item at runTime, with a dynamic function. 

That's what `CellMeasurer` is for.

Regardless, react-virtualized can't work unless it knows the height (and/or width) of its children. That's a fundamental part of windowing. Scrollbars aren't shown because RV is being told the wrong dimensions.

**Comment by bvaughn** [comment]
Anyway, after investigating, I'm confident that this isn't a react-virtualized bug. So I'm going to close this issue for now. I'll try to find some more time to help debug what's going on with your sample project, but my time is a bit limited at the moment and I need to switch gears at the moment b'c I have a meeting coming up. :)

**Comment by jkiepura** [comment]
No problem, I will look into CellMeasurer, I would prefer calculating the height at runtime with a function. Thanks for your very fast answers!

**Comment by bvaughn** [comment]
That's essentially what `CellMeasurer` does. You could always replace it with your own calculate-and-cache approach too, if you'd rather use a component like `react-height` (or something you write yourself). The main thing is that you'll need to tell `VirtualScroll` the actual height. And if the height changes, you'll need to call [`recomputeRowHeights`](https://github.com/bvaughn/react-virtualized/blob/master/docs/VirtualScroll.md#recomputerowheights-index-number) to let it know to clear its cache for that row.
