### ISSUE TITLE
overscanRowCount property in Collection component?

### ISSUE THREAD

**Issue by coluccini** [bvaughn/react-virtualized#342]
I think a property like VirtualScroll's overscanRowCount it would really useful on Collection too. It would be really important to try reduce flickering during scrolling (especially) on mobile browers that usually delay when onscroll event is triggered.

@bvaughn has proposed implementing as horizontalOverscan and verticalOverscan and I think that would be perfect!

**Comment by bvaughn** [comment]
Added in 1b8f019. Going out momentarily as version 7.19.0.

**Comment by bvaughn** [comment]
[`7.19.0`](https://github.com/bvaughn/react-virtualized/releases/tag/7.19.0) just released. Enjoy!

**Comment by coluccini** [comment]
You're the best @bvaughn! I'm making a few tests and seeing that scrolling starts to act kind of weird on mobile when I set a value to verticalOverscan. But I'm not sure if directly related to this of if it's coming from some other place. I'll let you know.
¡A million thanks, again!

**Comment by coluccini** [comment]
I'm still working in the issue, but everything is point that the weird scroll thing is coming from my implementation rather than de component itself 👍  ¡thanks again!

**Comment by bvaughn** [comment]
Gotcha! Thanks for the update. :D
