### ISSUE TITLE
tabIndex defaults to 0, not null

### ISSUE THREAD

**Issue by scriptguru** [bvaughn/react-virtualized#343]
Docs say that `tabIndex` defaults to `null` but in fact it defaults to `0`.

This results in impossibility to create an element without `tabIndex` attribute, and all elements with `tabIndex` attribute have some default styles (bluish border in Chrome) when the element is focused.

For sure it's possible to re-define those styles, but it's a workaround.

**Comment by bvaughn** [comment]
> This results in impossibility to create an element without `tabIndex` attribute

That's not true. :) You can see `tabIndex={null}` if you truly don't want to support tab. It's enabled by default though for a11y. (The `defaultProps` value only gets used if the specific prop is `undefined`.)

This is a docs bug. I'll update them momentarily. :)

**Comment by bvaughn** [comment]
Fixed~

**Comment by scriptguru** [comment]
Got it, thanks

**Comment by bvaughn** [comment]
No problem. Thanks for pointing out the docs error :D

**Comment by Mario-Eis** [comment]
But it seems not to be possible to pass tabIndex={null} to the row renderer
