### ISSUE TITLE
flextable - removing border on table/row click

### ISSUE THREAD

**Issue by ranuser99** [bvaughn/react-virtualized#344]
Table/rows display a border when clicked.

Even after carefully searching using Chrome dev tools, I cannot find the CSS styles that are the culprits.  

Any pointers on how to disable/override?

Thank you

**Comment by bvaughn** [comment]
How on earth did I miss this issue...

This is a focus outline. You can disable it via see if you want:
```css
:focus {
  outline: 0;
}
```

But you should define an alternate focus style if you do this- in order not to harm accessibility.

**Comment by shoxter** [comment]
> How on earth did I miss this issue...
> 
> This is a focus outline. You can disable it via see if you want:
> 
> ```css
> :focus {
>   outline: 0;
> }
> ```
> 
> But you should define an alternate focus style if you do this- in order not to harm accessibility.

I think this is still an issue? I'm getting this on 9.21.2.
