### ISSUE TITLE
[Optimization Idea] Render in Chunks

### ISSUE THREAD

**Issue by mrtnbroder** [bvaughn/react-virtualized#353]
Just looked at how the lib works and figured that a render is triggered as soon as one element leaves the visible area. This works for fine so far, but is considerable more performance-intensive as when you would render everything within chunks.

So a chunk is defined by the container height + some buffer, and would consist of x elements that fit within the chunk. There must be at least two chunks as well for this to work reliably.

Let's say you're at the top of your list, and your list height is 600px, and you have around 100 items within it, each one having a height of 100px, which leads to 6 items being visible at all times (7 if you scroll a bit up or down).

Currently, you'd see the first Chunk, with a Chunk-height of let's say 900px (ratio of 1.5 times the container height). Additionally, the next Chunk is also already attached to the DOM, given a total Chunk-height of 1800px (Chunk 1 + Chunk 2)

Now, if you scroll down the list and reach the midpoint of Chunk 2, an update would fire, which would attach the next chunk to the DOM (chunk 3). So that gives us 3 chunks being attached to the DOM at this moment and a total chunk height of 2700px (Chunk 1 + Chunk 2 + Chunk 3).

This is the point where the whole loop basically starts. If you scroll further down and reach the midpoint of Chunk 3, Chunk 1 would be swapped with Chunk 2, Chunk 2 with Chunk 3, and Chunk 3 with Chunk 4 (the new one) until you reach the very bottom where only the last two remaining Chunks would be attached to the DOM.

This would lead to exactly one render operation every ~900px. At the point where we hit the midpoint of Chunk X.

I hope you can follow me this far. Here is an illustration of what I mean to make it easier to understand maybe:

<img alt="First" src="https://cloud.githubusercontent.com/assets/1118826/17732916/6881c5da-6474-11e6-8e64-fd04d6904db2.jpg" width="200"/>
<img alt="Second" src="https://cloud.githubusercontent.com/assets/1118826/17732922/6dc95044-6474-11e6-8bc0-6ebe6c41c223.jpg" width="200"/>
<img alt="Third" src="https://cloud.githubusercontent.com/assets/1118826/17732924/70dcfd58-6474-11e6-8d25-4001b0a5f994.jpg" width="200"/>

**Comment by bvaughn** [comment]
This is related to the discussion on issue #350. Rather than "chunks" that discussion is framed around overscanned rows.

I think `Grid` makes both a little more complicated (because of the fact that we're virtualizing in 2 directions) but I'm overall a fan of the idea. I think the only somewhat-tricky part is efficiently detecting when to invalidate the overscanned rows (or "chunks").

**Comment by bvaughn** [comment]
Going to leave this issue (and that one) open for reference and reminder when I have more time to do some perf testing and playing with either idea. I'm very busy this week but hope to have more time for experimentation next week!

**Comment by bvaughn** [comment]
It may seem counter intuitive, but this idea doesn't seem to improve performance (at least not base on my local testing). I've tried a couple of ways of implementing it (using min/max x/y of most recently rendered rows, using min/max row/col indices, etc). It actually causes jumps at the boundaries between "chunks" of rows.

**Comment by mrtnbroder** [comment]
@bvaughn wow really? That doesn't sound much like an optimisation 😅 

mind uploading your branch so I can take a look?

I'm actually running a self-made version of something like this and it runs pretty smooth. In my case though, my items are of different kinds that look completely different. So it performs a bit slower when react has to 'move' the different looking nodes up and down within in the DOM, instead of just replacing the content, because thats not possible.

Maybe my use-case is pretty edge-case, but it works better when I do it in batches vs each item.

**Comment by bvaughn** [comment]
Makes sense that it wouldn't optimize _too much_ since I'm caching already-rendered-cells and taking care not to force unnecessary flow/paint with the browser when new cells are added.

So you're not testing this with react-virtualized but some other windowing component? 😅

**Comment by mrtnbroder** [comment]
I'm actually running my own infinity list component, correct 😅 

If I had known react-virtualized before @jgoux told me about it, I'd use that.

I'm just sharing my knowledge that this actually works pretty good in my case. I did not test it with react-virtualized, yet.

**Comment by bvaughn** [comment]
Haha, gotcha. No worries! I appreciate the suggestion. 😁

react-virtualized has a lot of optimizations backed in to reduce the cost of rendering while scrolling (such as temporary row/column caching). So- having tested this batching approach- it doesn't actually make a noticeable improvement.

Worth a shot though! 😄
