### ISSUE TITLE
flex-basis: auto for FlexColumns

### ISSUE THREAD

**Issue by olslash** [bvaughn/react-virtualized#358]
Hey

According to MDN, [flex basis can be 'auto'](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis), and in fact auto is it's default value. 

Right now, the FlexColumn `width` prop is required to be a number, and is [hardcoded to be a string with 'px' ](https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/FlexTable.js#L505) in the shorthand for flex-basis. 

We need to be able to set the basis to auto to fix a subtle IE bug, according to my css wizard. Is there a standard workaround I'm missing? What do you think about a change to let FlexColumn width be oneOfType string or number?

**Comment by bvaughn** [comment]
Hey @olslash,

Ah, right. That is a valid value for `flex-basis`; `auto` means that the column is sized based on its content. Unfortunately I don't think that value makes sense in the context of a component like `FlexTable` (or anything that's trying to mimic an HTML `<table>` or grid layout). Each row likely has different content (eg text of different lengths) which would result in a weird looking table.

For example, this layout...
<img width="464" alt="screen shot 2016-08-23 at 6 41 07 pm" src="https://cloud.githubusercontent.com/assets/29597/17915685/4c47866a-6961-11e6-8367-0232e9668995.png">

Would become this...
<img width="460" alt="screen shot 2016-08-23 at 6 42 19 pm" src="https://cloud.githubusercontent.com/assets/29597/17915694/58bc8544-6961-11e6-8326-d2211e4c156f.png">

To see this for yourself, load the [`react-virtualized` demo page](https://bvaughn.github.io/react-virtualized/) and run the following code in the console:

```js
document.querySelectorAll('.FlexTable__rowColumn').forEach(
  (col) => col.style['flex-basis'] = 'auto'
)
```

The only way this CSS value would work would be if each row had content of the exact same width- but at the point, why not just set a numeric `flex-basis`?

**Comment by bvaughn** [comment]
Going to close this issue for now. I don't think it makes sense as a feature for a grid-layout component. Let's chat more if you have concerns or disagree though! Maybe I'm overlooking something? :D

**Comment by olslash** [comment]
gotcha-- i'll have to figure out exactly what we're hacking with auto and make a test case that might shed some light on why it's useful
