### ISSUE TITLE
How about variable row-height?

### ISSUE THREAD

**Issue by fritx** [bvaughn/react-virtualized#36]
Is it possible to support variable `rowHeight` in VirtualScroll?

**Comment by bvaughn** [comment]
It is very complicated to do without negatively affecting performance. I have some ideas (and a branch in progress) but smooth scrolling is jerky and I haven't found a way around it yet.

I created issue #23 to track this. I hope you don't mind but I am going to close this one as a duplicate of that one. Just subscribe to it to stay updated on the progress. I hope to get some time over the next week to look into it more but no promises. :)

**Comment by fritx** [comment]
Oh cool ! Thx

**Comment by bvaughn** [comment]
FYI @fritx this is now supported in version [2.6.0](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#260) :)
