### ISSUE TITLE
Can't get trivial example with AutoSizer working.

### ISSUE THREAD

**Issue by mtchllbrrn** [bvaughn/react-virtualized#366]
I'm having issues with adding AutoSizer to an otherwise-functional component. [Here's an example app that recreates the problem](https://github.com/mtchllbrrn/autosizer-ex).

If you remove AutoSizer from this repo's `List` component (substituting arbitrary `height` and `width` props), it works perfectly fine. When AutoSizer is there, however, `rowRenderer` never gets called.

I must be doing something silly, but I can't for the live of me tell what it is.

**Comment by bvaughn** [comment]
Hey @mtchllbrrn :)

Add this to your HTML `<head>`:

```html
<style>
  html, body, #root {
    width: 100%;
    height: 100%;
  }
</style>
```

**Comment by mtchllbrrn** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/3/3b/Paris_Tuileries_Garden_Facepalm_statue.jpg)

**Comment by bvaughn** [comment]
No worries 😁
