### ISSUE TITLE
Jittering behavior from VirtualScroll in Safari

### ISSUE THREAD

**Issue by mtchllbrrn** [bvaughn/react-virtualized#370]
I'm seeing a strange jittering problem while scrolling in Safari. My initial thought is that it was performance related, but I'm starting to think it's related to the vertical position of the viewport jumping as heights are calculated. It *maybe* seems like the jitters spike when DOM elements are pushed/popped during the normal operation of VirtualScroll.  Check out [this gif](https://cl.ly/3h0R2x1T2F0X)

[Here's an example repo](https://github.com/mtchllbrrn/rv-jitter-ex). It's Meteor, but you can just run `npm start` to get it going.

@bvaughn, this is the problem I spoke of in #160.  Running the app in Safari Technology Preview doesn't fix the problem, but it does seem slightly better. This may be placebo, though.

**Comment by bvaughn** [comment]
I think this is related to what's being discussed on #357- at least if I'm understanding correctly. (You're talking about the small jitter toward the tail/end of the scrolling animation?)

**Comment by mtchllbrrn** [comment]
I'll check out #357 and see if I can contribute in any way.  The jittering is very difficult to capture with these gifs, due to the framerate constraints, but it's easiest to spot if you keep your eyes on the scroll bar. Around the middle of the gif, you'll see it kind of "hop." This is the behavior I'm seeing in person, and it's happening constantly while scrolling (though it doesn't show in the gif).

Have you tried the sample repo? Do you see the same behavior?

**Comment by bvaughn** [comment]
> Have you tried the sample repo? Do you see the same behavior?

Haven't had time yet, unfortunately.

**Comment by brene** [comment]
In my development environment I had a VERY laggy experience but once I set the environment to production, the tables really "flies". Maybe you should try that. Also @bvaughn, maybe put this "trick" in the README.MD because it was actually crazy the amount of speed increase that I got.

**Comment by bvaughn** [comment]
FWIW @brene: React 15.3.1 really does a lot to helping address dev-mode performance problems. If you're not using it- you should consider upgrading :)

**Comment by jch254** [comment]
I'm experiencing this too. Silky smooth in Chrome but really jittery in Safari.

**Comment by dolfelt** [comment]
I am as well. Jittery in Safari and super smooth in Chrome. Also a tiny bit of jitter in Firefox.

**Comment by dolfelt** [comment]
I tried this out using a production build and it's still having the same jittering issues. Also using React 15.3.1.

**Comment by bvaughn** [comment]
Share your code+app with me so I can repro and profile?

**Comment by mtchllbrrn** [comment]
@bvaughn Have you tried the repo I provided in the original post? It should be a good testing ground for the issue.

**Comment by bvaughn** [comment]
Sorry for the slow response @mtchllbrrn. I was traveling back to the US from China and also trying to finish up an RC.

Yes, I have. But more repro cases are better. 😄

**Comment by bvaughn** [comment]
@mtchllbrrn: WRT [your demo project](https://github.com/mtchllbrrn/rv-jitter-ex), I think the recently-release version 8 RC seems to improve Safari jitter. Here's a patch for your demo project to make the upgrade. Let me know if you see improvement too?

```diff
diff --git a/client/components/List.jsx b/client/components/List.jsx
index d999961..6d1b84b 100644
--- a/client/components/List.jsx
+++ b/client/components/List.jsx
@@ -1,11 +1,15 @@
 import React from 'react';
-import { AutoSizer, VirtualScroll } from 'react-virtualized';
+import { AutoSizer, List as VirtualScroll } from 'react-virtualized';
 import 'react-virtualized/styles.css';
 import UserListItem from './UserListItem';
 
 export default class List extends React.Component {
-  rowRenderer(index, data) {
-    return <UserListItem data={data[index]} />;
+  rowRenderer({ data, index, key, style }) {
+    return <UserListItem
+      data={data[index]}
+      key={key}
+      style={style}
+    />;
   }
 
   render() {
@@ -22,8 +26,8 @@ export default class List extends React.Component {
               width={width}
               rowCount={data.length}
               rowHeight={90}
-              rowRenderer={({ index }) => {
-                return this.rowRenderer(index, data);
+              rowRenderer={({ index, key, style }) => {
+                return this.rowRenderer({ data, index, key, style });
               }}
             />
           )
diff --git a/client/components/UserListItem.jsx b/client/components/UserListItem.jsx
index da8cbb3..cd20165 100644
--- a/client/components/UserListItem.jsx
+++ b/client/components/UserListItem.jsx
@@ -3,9 +3,10 @@ import React from 'react';
 class UserListItem extends React.Component {
   render() {
     const user = this.props.data;
+    const style = this.props.style;
 
     return (
-      <a key={user._id} href="" className="w-inline-block directory-contact-link">
+      <a href="" className="w-inline-block directory-contact-link" style={style} >
         <div className="w-clearfix field border">
           <img className="user-photo-list"
             src={'/images/UserFace-60x60.png'}
diff --git a/package.json b/package.json
index de565e6..8491bb5 100644
--- a/package.json
+++ b/package.json
@@ -13,7 +13,7 @@
     "react-addons-pure-render-mixin": "^15.3.1",
     "react-addons-shallow-compare": "^15.3.1",
     "react-dom": "^15.3.1",
-    "react-virtualized": "^7.19.4"
+    "react-virtualized": "^8.0.0-rc.3"
   },
   "devDependencies": {
     "eslint-config-poetic": "^1.0.2"
```

**Comment by bvaughn** [comment]
I think I can improve it a bit more. I'll report back in a few with (hopefully) an RC4. :)

**Comment by bvaughn** [comment]
Hello! I believe the newly-released version 8 fixes this issue (at least in my testing).

Check out the [upgrade steps](docs/upgrades/Version8.md) for instructions on how to migrate from version 7. And let me know if you run into any problems!

**Comment by jch254** [comment]
Cheers @bvaughn working nicely for me!

**Comment by bvaughn** [comment]
Fantastic! Thanks!

**Comment by mtchllbrrn** [comment]
@bvaughn I'm not seeing anything in the browser when I apply that patch. No helpful errors, either. I've pushed the patch to the `potential-fix` branch, here: https://github.com/mtchllbrrn/rv-jitter-ex/tree/potential-fix

**Comment by bvaughn** [comment]
@mtchllbrrn Just to be clear- you also ran `npm i` after applying?

**Comment by mtchllbrrn** [comment]
Yes, indeed. `react-virtualized` is up to date.

**Comment by bvaughn** [comment]
Okedoke. Let me take a look then. 😄

**Comment by bvaughn** [comment]
@mtchllbrrn:

```diff
diff --git a/client/components/List.jsx b/client/components/List.jsx
index 971a92f..1e5aa00 100644
--- a/client/components/List.jsx
+++ b/client/components/List.jsx
@@ -4,7 +4,15 @@ import 'react-virtualized/styles.css';
 import UserListItem from './UserListItem';
 
 export default class List extends React.Component {
-  rowRenderer({ data, index, key, style }) {
+  constructor (props, context) {
+    super(props, context)
+
+    this.rowRenderer = this.rowRenderer.bind(this)
+  }
+
+  rowRenderer({ index, key, style }) {
+    const { data } = this.props
+
     return (
       <UserListItem
         data={data[index]}
@@ -15,7 +23,6 @@ export default class List extends React.Component {
   }
 
   render() {
-    // if (this.props.loading) return <p>Loading...</p>;
     const { className, data } = this.props;
 
     return (
@@ -28,9 +35,7 @@ export default class List extends React.Component {
               width={width}
               rowCount={data.length}
               rowHeight={90}
-              rowRenderer={({ index, key, style }) => {
-                this.rowRenderer({ data, index, key, style });
-              }}
+              rowRenderer={this.rowRenderer}
             />
           )
         }
```

**Comment by mtchllbrrn** [comment]
@bvaughn Thanks for that patch, I've got it running. The performance is significantly better, but it seems to have killed momentum scrolling:  On my Macbook Pro, two-finger swiping quickly & releasing causes the list to suddenly jolt to a stop, rather than continue scrolling with its momentum.  This wasn't the behavior previously, so it seems it must be related to the v8.0 update?

**Comment by bvaughn** [comment]
Glad to hear the perf is better for you at least. 😄

Safari momentum scrolling has been a problem forever. It seems to be completely fixed in the newer version of Safari (10) as well as the Safari Technology Preview though.

The problem with Safari 9 _seems_ to be related to changing the DOM during scroll. I don't think there's any way I can get around that problem. (I spent a _lot_ of time trying different approaches and found no real fix.)

**Comment by mtchllbrrn** [comment]
Updating Safari to v10.0 has indeed solved the problem. It's too bad about v9.0, but this is still very helpful.

Thanks a lot for your time!

**Comment by bvaughn** [comment]
Yeah. It's a bummer, I know. I'm really glad that Safari 10 fixed it - and I haven't seen a similar behavior in any other browser (including IE or mobile browsers) so hopefully it's gone entirely now. But it frustrates me still that I wasn't able to fix it for Safari 9.

You're welcome. :)
