### ISSUE TITLE
Disable `outline` on Grid component

### ISSUE THREAD

**Issue by nhducit** [bvaughn/react-virtualized#381]
I think we should disable `outline` on `Grid` class. If it's fine, I will submit a pull request.

<img width="689" alt="screen shot 2016-09-08 at 2 16 10 pm" src="https://cloud.githubusercontent.com/assets/4246176/18340412/f7827106-75ce-11e6-9b2a-f21150e5de98.png">

**Comment by bvaughn** [comment]
@nhducit Outline is an important usability mechanism for keyboard-only users. As such, I want it to be enabled by default for focusable elements.

You're free to disable it yourself via a custom `className` or inline style (eg `style={{ outline: 'none' }}`). react-virtualized supports both. :)

**Comment by nhducit** [comment]
@bvaughn It's OK. Thanks a lot ^^

**Comment by bvaughn** [comment]
No problem. 😄

You aren't the first one to ask this! I just think it's important that react-virtualized be as accessibility-friendly as possible by default. People can choose to disable accessibility features (like outline) if they think it's appropriate to their applicate. 😁

**Comment by zhuhan0** [comment]
Is there a way to disable a MultiGrid's child Grid's outline?

**Comment by zhuhan0** [comment]
Never mind. Fixed by setting styleBottomRightGrid
