### ISSUE TITLE
Possible to use CellMeasurer in FlexTable?

### ISSUE THREAD

**Issue by johnnyji** [bvaughn/react-virtualized#382]
I'm currently using `FlexTable`, but one of my requirements is that a column could possibly resize itself based on the widest cell.

I'm a bit lost on how to do so with `CellMeasurer` (or if it's even possible).

Looking at the docs, it seems like I can return the result of `cellRenderer()` from my `rowGetter` handler in `FlexTable`. But where is `cellRenderer` coming from? It doesn't seem like it can be imported from `CellMeasurer`.

@bvaughn  Amazing library, thank you for your contribution to the open source community!

Best,

- Johnny

**Comment by bvaughn** [comment]
> @bvaughn Amazing library, thank you for your contribution to the open source community!

Thanks @johnnyji! 😁

`FlexTable` and `CellMeasurer` are incompatible. The docs hint at this (saying it works with `Grid` and `VirtualScroll` and leaving `FlexTable` out) but maybe they're not clear enough.

The reason for this is that the `cellRenderer` of a `FlexTable` is its entire row (all of the columns).

You may be able to make the 2 work together but it would require some manual glueing. (You'd have to give `CellMeasurer` a fake renderer that renders a single column of your `FlexTable`, etc. I don't think I can easily support this in the library via the existing reusable components.

**Comment by bvaughn** [comment]
I'm going to close this issue for now because I don't think it's a feature I can support without (at least) significant refactoring. `FlexTable` is meant to be a simple HOC for convenience. If you want to use `CellMeasurer` perhaps you could just directly use a `Grid`. 😄
