### ISSUE TITLE
babelHelpers is not defined - Integration issue with react-boilerplate

### ISSUE THREAD

**Issue by raizyr** [bvaughn/react-virtualized#391]
See additional in mxstbr/react-boilerplate#962. 

When trying to use `react-virtualized` with `react-boilerplate` I was seeing the console error `babelHelpers is not defined`.   After some digging  I found information about [babel-plugin-transform-runtime](http://babeljs.io/docs/plugins/transform-runtime/) which talks about creating "a sandboxed environment" to avoid polluting globals.   I believe in my case I was getting the error because react-boilerplate does not have [babel-external-helpers](https://babeljs.io/docs/plugins/external-helpers/) by default.  

Since `react-virtualized` is library code, I decided to test `babel-plugin-transform-runtime`.  See pr #390. 

I am not 100% sure this is the right way to fix this, as I am far from a `babel` expert, but it seems to solve the issue for me.

**Comment by bvaughn** [comment]
Version 7.24.3 (just published) should include your changes! Thanks again!

**Comment by raizyr** [comment]
Just checked it out this morning and it seems to work great.  Thanks for the quick turn around!

**Comment by bvaughn** [comment]
No problem! Happy to accept a quality contribution!

**Comment by mbrevda** [comment]
Seeing the same when trying to use rollup. is there any special configuration needed?

**Comment by bvaughn** [comment]
Which version of RV are you using @mbrevda? I don't think that particular error should apply to newer releases.

**Comment by mbrevda** [comment]
```
cat package.json |grep virt
    "react-virtualized": "^8",
```

**Comment by bvaughn** [comment]
And you're getting the error "_babelHelpers is not defined_" ?

`babelHelpers` does not appear anywhere in the built distribution of react-virtualized 8. That helpers lib was removed in version 7.24.3.

**Comment by mbrevda** [comment]
grep would confirm what your saying, could it be coming from react-virtualized-select though?

**Comment by bvaughn** [comment]
`react-virtualized-select` also does not contain any references to `babelHelpers`

**Comment by mbrevda** [comment]
This is what I'm seeing (just reinstalled the module to be certain):

```js
cat node_modules/react-virtualized-select/dist/es/VirtualizedSelect/VirtualizedSelect.js | grep babelHelpers
  babelHelpers.inherits(VirtualizedSelect, _Component);
    babelHelpers.classCallCheck(this, VirtualizedSelect);
    var _this = babelHelpers.possibleConstructorReturn(this, Object.getPrototypeOf(VirtualizedSelect).call(this, props, context));
  babelHelpers.createClass(VirtualizedSelect, [{
      return React.createElement(SelectComponent, babelHelpers.extends({}, this.props, {
        babelHelpers.extends({
```
Is this something on my end? Do you want to move this to a different repo?

**Comment by bvaughn** [comment]
Hm. Looks like you are correct. Not sure why my grep didn't find that locally, unless I've made changes locally (which I don't recall doing).

Sure. Feel free to file an issue on RVS. If you feel generous, feel free to submit a PR similar to #390. 😁

**Comment by mbrevda** [comment]
sure thing!

**Comment by mbrevda** [comment]
https://github.com/bvaughn/react-virtualized-select/pull/27

**Comment by bvaughn** [comment]
Thanks! I'll try to get a release out this morning.
