### ISSUE TITLE
[Possible Feature] WindowScroller, provide custom scroll event hook (e.g for using WindowScroller inside nested scrollable container)

### ISSUE THREAD

**Issue by iyn** [bvaughn/react-virtualized#392]
Hey, I have a question about possible feature.

Say I have layout similar to this one: https://jsfiddle.net/JonMoore/LLfcL28u/19/ - that is: fixed top header and scrollable content/container. I want to use WindowScroller inside the content to display my data (instead of nesting table inside the content which already has one scrollbar). Right now, the WindowScroller listens to scroll events on the window, but these are not fired up while I scroll the content container. I'm considering implementing this feature for my usecase, where I can provide a way to listen for scroll events other than just on `window` (in my case, scroll events come from the content container, in the linked jsfiddle that is the part with 'slides'). So, I have a 3 questions:

1. Does anybody can comment, whether this won't destroy performance?
2. Maybe this already can be implemented but I failed to see the solution. If so, I'd appreciate pointing me in the right direction :)
3. If/when I implement this feature for myself, should I make a PR with it this feature or you're not interested in such use case and I should rather provide simple example, how one can achieve this with some hacks?

Thanks!

**Comment by bvaughn** [comment]
Hi @iyn,

Not sure I understand the use-case fully. If you have a fixed header like that example, why not just use `AutoSizer` instead? `WindowScroller` is intended for when you want the header to scroll out of view as a user scrolls down the body. `AutoSizer` also avoids the scroll-container event you mentioned- since `Grid` (or whichever virtualized component you use) manages scrolling itself.

**Comment by iyn** [comment]
As I understand, without the WindowScroller, the table will have its own scrollbar (which I want to avoid)?

I want to achieve something similar to this layout: https://app.dealroom.co/companies but in my case, the table itself would be in a scrollable container (but table itself should not have scrollbar), like in the layout I posted in the first post. Let me know if this is still confusing, I'll provide some kind of graphics/diagram. I'm a little bit tired atm, so my explanation is/could be chaotic.

**Comment by iyn** [comment]
OK, I decided to change my layout to easily incorporate react-virtualized WindowScroller into my project, so I'm closing the issue. Thank you for your time!

**Comment by bvaughn** [comment]
No problem @iyn. I'm pretty focused on getting version 8 RC out the door at the moment but I'll give this a little more thought once that's done.
