### ISSUE TITLE
Changing Grid scrollLeft/scrollTop props should trigger onScroll callback

### ISSUE THREAD

**Issue by jas-per** [bvaughn/react-virtualized#399]
If you handle the scrollbar externally similar to WindowScroller and supply the scrollTop-property to the Grid inside VirtualScroll/List using scrollToIndex disconnects the link between the two: The Grid will have a different state in scrollTop than WindowScroller because there is currently no way to inform WindowScroller that scrollTop in Grid has changed.

Wouldn't Grid._setScrollPosition() have to use a callback to WindowScroller in this case and get the new scrollTop passed down as a prop?

**Comment by bvaughn** [comment]
I'm not sure I understand what you're describing, @jas-per. If you want to set the `scrollTop` position of a `Grid` (or a `List` or `Table`) you should be setting the `scrollTop` property- not the `scrollToIndex` property. This is what `WindowScroller` does.

`scrollToIndex` is useful when you only want to ensure that a given row is visible (without caring about the specific `scrollTop` offset).

I _think_ this is just a misunderstanding of how the 2 properties work and I _think_ I've provided enough clarification to close this issue- but please ask additional questions if not. I'll be happy to further clarify. 😄

**Comment by jas-per** [comment]
My description was a bit sloppy I guess - I am using the scrollTop-property, but also scrollToIndex: scrollTop to handle external scrolling and scrollToIndex for events where I want to ensure that a given row is visible

The usecase is a playlist for a music player, where I need to control scrolling externally to integrate [react-dnd-scrollzone](https://github.com/azuqua/react-dnd-scrollzone). Works fine, but when the next song starts playing, scrollToIndex gets called to jump to that song in the playlist.

This sets scrollTop in the Grid, but currently there is no way for the wrapping Component (that takes care of scrolling) to know that the scroll position needs to be changed. Because its own scrollTop-property (that gets passed down to the Grid) isn't adjusted weird things happen on the next prop/state change

hope this helps and thanks for trying to understand the issue

**Comment by bvaughn** [comment]
Ah! I see. 😄

> This sets scrollTop in the Grid, but currently there is no way for the wrapping Component (that takes care of scrolling) to know that the scroll position needs to be changed.

Why not something like...

```jsx
class WrappingComponent extends Component {
  render () {
    return (
      <Grid
        {...gridProps}
        onScroll={::this._onScroll}
      />
    )
  }

  _onScroll ({ scrollTop }) {
    if (scrollTop !== this.state.scrollTop) {
      // Grid's scrollTop has changed as the result of :scrollToIndex
    }
  }
}
```

This is over-simplified but I think you could use this basic approach to keep the 2 in sync.

**Comment by jas-per** [comment]
yes, thats what I tried but onScroll wasn't triggered - maybe I messed things up at that stage, will have a closer look tomorrow and give an update

**Comment by jas-per** [comment]
hmm onScroll gets attached to the scrollingContainer div .. since that element is not the one that does the scrolling, onScroll never gets called

I really appreciate the flexibility to be able to control scrolling from the outside with the WindowScroller approach, although it makes proper encapsulation non trivial I guess - my usage seems a bit of an edgecase, hopefully still a valid one ;)

**Comment by bvaughn** [comment]
Ah, I see. I was under the impression that the `onScroll` callback would fire when the `scrollTop` was adjusted programmatically too. I was mistaken. (I have not used `WindowScroller` myself outside of the demo app so I'm not very familiar with it TBH.)

So a "fix" for this issue could just be to ensure that the `onScroll` callback fires when position is set externally _as well as_ when a user scrolls. Would that suffice?

**Comment by jas-per** [comment]
to avoid general overhead calling onScroll in Grid.js 806 `if (scrollTop !== calculatedScrollTop) ` would be sufficient for this issue .. I'd say .. just got familiar with react-virtualized two days ago, thanks a lot for your work on these components!

**Comment by bvaughn** [comment]
That's not how I'd implement it exactly, but that's okay. I was mostly just asking to confirm with you that - if you could use my suggested `onScroll` approach above - would that suffice.

**Comment by bvaughn** [comment]
PS You're welcome :)

**Comment by bvaughn** [comment]
FYI this change is now available via version 8.0.5. 😄

**Comment by jas-per** [comment]
hi and thanks, once more for your quick response, very much appreciated!

`  _onScroll ({ scrollTop }) if (scrollTop !== this.state.scrollTop) ..`
worked fine, but I quickly realized, that I want all the goodness from the internal Grid component - especially the scaling part for bigger lists. so in the end I modified react-dnd-scrollzone to be used as HOC on the List/Grid - MUCH better performance!

since I'm a bit unsure if the [change](https://github.com/bvaughn/react-virtualized/commit/674cb66c7e9dfece84ffe7aa82a1cf9bbed68b35) doesn't potentially degenerate performance a little I left a comment there

**Comment by bvaughn** [comment]
I appreciate that. I responded to your comment there. 😄

I'd love to see your solution if it's somewhere you can share it.

**Comment by jas-per** [comment]
OK, [react-dnd-scrollzone](https://github.com/jas-per/react-dnd-scrollzone) is basically a slim wrapper that just adds drag and drop scrolling behaviour - useful if you don't need all the bell&whistles of [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) eg when using [react-dnd](https://github.com/gaearon/react-dnd) for fine-grained/site-wide dnd

sent a PR to [react-dnd-scrollzone master](https://github.com/azuqua/react-dnd-scrollzone), in case they want to go the hoc-route and will come back to leave a comment on #147 when our app is released on github

cheers!

**Comment by bvaughn** [comment]
Cool! I've used react-dnd with react-virtualized before to implement resizable `Table` and `Grid` columns and I've found it to work really nicely. 😁
