### ISSUE TITLE
v8.0.2 introduced horizontal scrollbar to `<Table />`

### ISSUE THREAD

**Issue by EvNaverniouk** [bvaughn/react-virtualized#400]
If you visit https://bvaughn.github.io/react-virtualized/#/components/Table (the official preview for the Table component). You will see it has a horizontal scrollbar for no reason. I suspect it's related to the scrollbar as the scroll value is about the width of the scrollbar.

There appears to be no way to remove this scrollbar via any props or CSS styling. This issue was not occurring in v7.x.x

**Comment by bvaughn** [comment]
Thanks for pointing this out @EvNaverniouk!

**Comment by bvaughn** [comment]
Fixed via 8.0.4!
