### ISSUE TITLE
CellMeasurer should account for scrollbar size

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#401]
Refer to issue #338 or jump to [this comment](https://github.com/bvaughn/react-virtualized/issues/338#issuecomment-247989389).

Essentially the problem is that `CellMeasurer` renders outside of the context of the eventual parent `List` or `Grid` and so it doesn't account for the amount of space that will be taken up by a scrollbar (if one is used).

**Comment by bvaughn** [comment]
If I had written `CellMeasurer` when I first created react-virtualized, I would have designed things slightly differently. However `CellMeasurer` was added several months later and as such, has some constraints imposed by the existing design. These constraints make it hard for me to envision a solution for this problem.

`Grid` requires some size metadata about the underlying collection it is displaying _in order to render itself_. Unfortunately the cells in this case also partially depend on `Grid`s rendering. The scrollbar appears or disappears based on the size and number of the cells (but in this case the cell size is also dependent on the presence of a scrollbar).

Not sure of a solution yet. Will have to leave this issue open and give it more thought.

**Comment by chrisvasz** [comment]
I would happily accept a solution where the scrollbar is always visible via overflow-y: scroll, meaning CellMeasurer measures as if the scrollbar is always present. A grayed-out scrollbar next to a short list is totally acceptable for us. Thoughts?

**Comment by bvaughn** [comment]
Hmm, interesting suggestion. I wonder initially if everyone would share that same point of view. I'd be a little reluctant to just assume it.

**Comment by turnerniles** [comment]
Just ran into / noticed this issue on a project. How could the scrollbar calculate much space to take up without going through all of the data to determine all widths of all columns?

The main issue for me is that the mouse position becomes unaligned with the scrollbar and it's not possible to scroll to the end of the data when dealing with a large number of columns. For me it would be okay, if the scrollbar got smaller as it continues to calculate how much left is scrollable as the user is able to continue dragging all the way to the end. Would it be possible to modify the mouse position as the user scrolls to account for the difference?

You can see this on the demo if you scroll to the right on one long drag you won't be able to get to the end:
https://bvaughn.github.io/react-virtualized/#/components/CellMeasurer

**Comment by bvaughn** [comment]
> How could the scrollbar calculate how much space to take up without going through all of the data to determine the widths of all columns?

You're thinking of the _length_ of the scrollbar (eg vertical scrollbar height). This issue is referring to its thickness (eg vertical scrollbar width).

> Would it be possible to modify the mouse position as the user scrolls to account for the difference?

No. This would interfere with and stop the browser's scroll animation.

> You can see this on the demo if you scroll to the right on one long drag you won't be able to get to the end

This is just a limitation of deferred measurement, which is itself a _very important_ performance optimization. I agree it's not _ideal_ but I think it's well worth the performance trade-offs given that this library is all about performance. 😄

**Comment by mbrevda** [comment]
If I'm understanding this issue correctly I'm having this issue, too (i.e. scrollbars covering cell content on non-scrollbar-auto-hidden platforms like os x). I wonder if it wouldn't be simplest to [detect always visible scrollbars](http://stackoverflow.com/a/32490737/747749), and than increase the Grid (or decress the available cell area) by the scrollbar width?

**Comment by mbrevda** [comment]
As a hacky workaround, I've added this to my `Grid` for now:

```js
const isWindows = window.navigator.platform.toUpperCase().indexOf('WIN') > -1
...
height={height + (isWindows ? 20 : 0)}
```

**Comment by chrisvasz** [comment]
I have been thinking more about the idea of calculating width as if a scrollbar is always present. react-virtualized is a windowing solution, which means that the majority use case targets containers with scrollbars. It feels pretty reasonable to assume that a scrollbar will be present because if there was no need for a scrollbar, there would be no need for react-virtualized either. When the list of items is too short to require a windowing solution, then windowing solutions don't add value.

The exception would be when the virtualized component doesn't manage its own scrollbar -- when rendering to the body for instance.

Thoughts?

**Comment by bvaughn** [comment]
I generally agree with this statement for vertical scrollbars, but what about horizontal? `Grid` can window in either direction, but I have used RV in applications where `Grid`s often contain a wide range of columns (many, not many, etc).

**Comment by mbrevda** [comment]
> targets containers with scrollbars

While this may be true for desktop Windows users, this not the case for Mac and mobile platforms. On those platforms, the scrollbar actually _does not take up space_ and floats on top of the content while scrolling and hides when not. Hence, **always** adding the scrollbar width to the Grid seems like it would fix some platforms (WIndows), but break other platforms. (which is why my workaround above targets windows specifically)

**Comment by linclark** [comment]
> While this may be true for desktop Windows users, this not the case for Mac and mobile platforms. On those platforms, the scrollbar actually does not take up space and floats on top of the content while scrolling and hides when not.

I recently found out it's a little more complicated than that... there's a setting on Macs to always show the scroll bars. In Settings, search for "scroll bar behavior".

![image](https://cloud.githubusercontent.com/assets/105464/20536656/d61ae2c2-b0b7-11e6-9445-f6dd61fac92f.png)

**Comment by mbrevda** [comment]
True, which is whybos-specifc code isn't a good idea. See my comment (above)[https://github.com/bvaughn/react-virtualized/issues/401#issuecomment-258822982] for scrollbar detection code

**Comment by bvaughn** [comment]
Yup, OS X further complicates matters but hiding scrollbars by default. :|

I think scrolling/scrollbars are one of the most difficult remaining UI challenges in the browser (not counting things like fancy 3d game engines or what-not).

**Comment by chrisvasz** [comment]
This is an interesting discussion!

@bvaughn Good point! I wasn't thinking about horizontal scrollbars and Grids since my use case is accomplished with a List.

@mbrevda The [scrollbar width detection techniques](http://stackoverflow.com/questions/23494468/detect-different-kind-of-scrollbars-eg-normal-hidden-osx/32490737#32490737) that I know of would return `0` for the scrollbar width on mobile and OS X. In those cases, subtracting the scrollbar width from the cell size wouldn't change anything since the scrollbar width would be 0. I believe this technique would also return the right answer when the "Always show scroll bars" setting is chosen in OS X, though I don't have an easy way to test that right now.

Is it accurate to say that this issue only applies to environments where the scrollbar takes up layout space? We are seeing this issue on our sites. It doesn't create any serious problems for us -- just some visual artifacts that I would prefer to avoid if possible.

**Comment by bvaughn** [comment]
Detecting the scrollbar width/height is doable. The problem here is that-
at the time a cell is measured- CellMeasurer has no way of knowing if it
will need to take horizontal or vertical scrollbar size into account.
What's more, that may change if the Grid/List is resized or the data is
filtered.

It's actually kind of complex. We don't want to measure/remeasure each time
resizing happens, and I'd prefer not to measure all possible combinations
of scrollbar/no scrollbars.

**Comment by mbrevda** [comment]
> CellMeasurer has no way of knowing if it
will need to take horizontal or vertical scrollbar size into account

Im not sure CellMeasurer would need to know about scrollbars. It would seem that only Grid (or whatever container) would have to know, no?

**Comment by bvaughn** [comment]
Sorry, that was poor wording on my part. My attention has been spread too thin lately and that was an email reply from my phone (as the awkward formatting hints at). Replace `CellMeasurer` with `Grid` above and the message fits.

`CellMeasurer` measures things like height based on width. The absence or presence of a scrollbar impacts width on certain browsers and so it potentially impacts height. Similarly the height of children determines the need for a vertical scrollbar. The 2 are related.

Let's say we're measuring the height of columns in row index 0. At this time `Grid` does not know if it needs a vertical scrollbar. Let's say we continue measuring columns until we reach row X at which point we know we _do_ need a vertical scrollbar. Currently this means our measurements from row 0 to X are now potentially (but not necessarily) invalid.

As was mentioned above, we could assume the presence of a vertical scrollbar _always_ which would handle most use-cases correctly. The same problem exists for measuring width though with regard to a horizontal scrollbar. This is probably a much less common concern _but_ I'm not sure it's fair to always assume the presence of a horizontal scrollbar. I think it's less clear cut in this case.

Currently...I would lean towards always assuming the presence of a vertical scrollbar and never assuming the presence of a horizontal one _but_ the latter seems kind of arbitrary and I'm uncertain how I feel about it.

**Comment by bvaughn** [comment]
Happy to say that the re-written `CellMeasurer` in version 9.0.0 fixes this long-standing issue.

**Comment by mbrevda** [comment]
Cool! Can you explain how in a line or two?

**Comment by bvaughn** [comment]
From the issue description:
> Essentially the problem is that `CellMeasurer` renders outside of the context of the eventual parent `List` or `Grid` and so it doesn't account for the amount of space that will be taken up by a scrollbar (if one is used).

`CellMeasurer` renders _in_ the `Grid` (or `List`) now. The old repro (the chat app) no longer repros so...unless I hear differently or see a different bug manifestation, I think it's fixed.

**Comment by mbrevda** [comment]
Sweet! Thanks!

**Comment by ChoppinBlockParty** [comment]
I still can see this problem in firefox, react-virtualized version 9.21.

**Comment by ChoppinBlockParty** [comment]
Issue observed only in Firefox: If the number of rows * defaultHeight < the height of the list Cell Measurer considers that there is no scoll bar. When the calculations are done, the actual height of the all rows > the list height. That results in having a scrollbar width what affect flex children and changes the row height, eventually producing row overlaps.
 
```
cellMeasurerCache = new CellMeasurerCache({
    defaultHeight: window.innerHeight,
```
fixes the problem.
