### ISSUE TITLE
List docs use `rowIndex` in example `rowRenderer`

### ISSUE THREAD

**Issue by IanVS** [bvaughn/react-virtualized#402]
The [List example](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#examples) in the docs uses the proposed-but-not-implemented `rowIndex`:

```js
function rowRenderer ({ key, rowIndex, style}) {
  return (
    <div
      key={key}
      style={style}
    >
      {list[rowIndex]}
    </div>
  )
}
```

**Comment by bvaughn** [comment]
Toss up a PR to fix it? :)

**Comment by bvaughn** [comment]
I'm not at my computer atm.

**Comment by IanVS** [comment]
> Toss up a PR to fix it?

Of course!

**Comment by bvaughn** [comment]
Thanks! :grin:
