### ISSUE TITLE
Ship flow typings

### ISSUE THREAD

**Issue by andreypopp** [bvaughn/react-virtualized#405]
I see React Virtualized annotated with Flow. It would nice if React Virtualized was distributed with flow typings.

**Comment by bvaughn** [comment]
Hey @andreypopp. This seems like a nice suggestion. 👍

Know of any libraries that do this [that I could use as a reference]?

**Comment by andreypopp** [comment]
So what I do usually if library already uses flow is just copy original sources along by change their extension to `.js.flow` (Flow uses them instead of compiled JS to get type info from).

**Comment by andreypopp** [comment]
Also you are using `propTypes` now, it might be beneficial to switch to types for `props` because types can express much more type info: for example callbacks will describes what arguments they accept.

Flow types for props then can be compiled to `propTypes` (with the help of corresponding [Babel plugin](https://github.com/brigand/babel-plugin-flow-react-proptypes)) for consumers who don't use Flow yet.

I can help with that.

**Comment by bvaughn** [comment]
> So what I do usually if library already uses flow is just copy original sources along by change their extension to .js.flow (Flow uses them instead of compiled JS to get type info from).

Copy to..? (Would it go where the ES6 modules go?)

> Also you are using `propTypes` now, it might be beneficial to switch to types for `props` because types can express much more type info

Yeah, I've been meaning to make the `propTypes` => `props` switch for a while but I just haven't had the time. If you'd like to help- I'd welcome it! 😄

**Comment by andreypopp** [comment]
>> So what I do usually if library already uses flow is just copy original sources along by change their extension to .js.flow (Flow uses them instead of compiled JS to get type info from).

> Copy to..? (Would it go where the ES6 modules go?)

That's an interesting question... probably in both locations then... this needs a little more investigation.

**Comment by bvaughn** [comment]
Agreed 👍

**Comment by turadg** [comment]
> So what I do usually if library already uses flow is just copy original sources along by change their extension to .js.flow

Would `flow gen-flow-files` be preferable?
```
  gen-flow-files  EXPERIMENTAL: Generate minimal .js.flow files for publishing to npm.
```

I mean, if it works :)

**Comment by bvaughn** [comment]
> Would `flow gen-flow-files` be preferable?

Yes! 😄

**Comment by sammkj** [comment]
[flow-copy-source](https://github.com/AgentME/flow-copy-source) is another alternative. It's used in React Motion

**Comment by bvaughn** [comment]
Closing this issue for now due to lack of interest. (I don't have the time to tackle it and having open issues that you don't plan on resolving adds stress to a project's maintenance.) If someone would like to pick it up and own it though- that would be fantastic. 🙇

**Comment by SavePointSam** [comment]
I know it has been a year, but I'm very interested in this. I was rather surprised that they weren't already available after looking at the source when forking some of the internal renderers. An example I'd love to have work:

```
// @flow

import React from 'react';
import { SortIndicator } from 'react-virtualized';

import type { HeaderRendererParams } from 'react-virtualized';

type Props = HeaderRendererParams & {
  onLabelClick: () => void,
};

const HeaderRowRenderer = ({
  columnData,
  dataKey,
  disableSort,
  label,
  sortBy,
  sortDirection,
  onLabelClick,
}: Props) => {
  const showSortIndicator = sortBy === dataKey;

  const children = [
    <span
      className="ReactVirtualized__Table__headerTruncatedText"
      key="label"
      title={label}
      onClick={onLabelClick}
    >
      {label}
    </span>,
  ];

  if (showSortIndicator) {
    children.push(
      <SortIndicator key="SortIndicator" sortDirection={sortDirection} />,
    );
  }

  return children;
};
```

**Comment by SavePointSam** [comment]
Upon further review, there is references to the flow types being finalized over prop-types in a variety of places (listed below). Even reference to they [being part of version 10](https://github.com/bvaughn/react-virtualized/issues/658#issuecomment-354561085). Are flow types officially supported? I found some [typescript types](https://www.npmjs.com/package/@types/react-virtualized). The `dist` files have `.js.flow` but everything just pulls from `prop-types` which I assume is work done by the Babel plugin.

External sources: https://github.com/bvaughn/react-virtualized/pull/930/files, https://github.com/bvaughn/react-virtualized/pull/905/files,  https://github.com/bvaughn/react-virtualized/pull/950/commits,

**Comment by TrySound** [comment]
@SavePointSam Flow is currently supported only in `dist/es/WindowScroller` and `dist/es/AutoSizer`.

**Comment by SavePointSam** [comment]
Anything I could do to help?

**Comment by TrySound** [comment]
Not, yet. There's a big rewrite, which may conflict with new changes. Maybe a bit later.
