### ISSUE TITLE
VirtualScroll should honor row keys

### ISSUE THREAD

**Issue by ppershing** [bvaughn/react-virtualized#406]
Right now, `VirtualScroll` uses `Grid` which generates its own element keys. While this works nice in most cases, having surrogate keys creates a mess once you start shifting the entries (e.g., by inserting to the top of the list) -- optimally, we would like for the components to be reconciled the same way as in React.
My suggestion is to therefore use `key` from the element `rowRenderer` returns as the underlying key and use the surrogate key only if the `key` prop is not defined there.

**Comment by bvaughn** [comment]
I'm afraid I don't understand this issue.

Grid assigns a row key based on the item index. That's the only safe way I've thought of to do things, given that react-virtualized supports dynamic row heights and therefore may have a varying number of rows visible at any time (making a key pooling/recycling approach difficult).

As of version 8, Grid defers the assignment to the rowRenderer anyway, although it passes a suggested key.

**Comment by ppershing** [comment]
What I am looking for is the exactly opposite behavior -- `rowRenderer` telling `Grid` what `key` the row should have. Basically, if I wasn't rendering with `react-virtualized`, I would use something like this
```
render = () => (
 <div>
   {this.props.items.map((item) => <MyFancyItem key={item.dbPrimaryKey} />}
 </div>
)
```
This ensures that if I insert some new item to the list, React can properly reconcile components.

I don't see any reason why using my supplied keys would be unsafe with `Grid` as long as the keys are unique.

**Comment by bvaughn** [comment]
Like I said before,
> As of version 8, Grid defers the assignment to the rowRenderer anyway, although it passes a suggested key.

😄 `Grid` _suggests_ a key but it's ultimately up to the `rowRenderer` which key it wants to use. So long as you use something unique- it will work.

> This ensures that if I insert some new item to the list, React can properly reconcile components.

I think there's a hidden assumption here that will cause problems. If you're re-arranging your data (inserting items into your list or moving them around) without _telling_ react-virtualized, that may cause problems- particularly if row heights are dynamic, or the total list size changes. When the underlying collection changes, you should let RV know, at which point its own (suggested) keys will reflect the new data.

**Comment by bvaughn** [comment]
I don't think there's any action for me to take here so I'm going to close the issue.

Happy to continue discussing it though. 😄 If it turns out that I'm wrong and there is some required action on my part, I'll re-open the issue!

**Comment by ppershing** [comment]
Silly me,  version 8 does exactly what I was hoping for. Thanks again for this awesome project :-)

**Comment by bvaughn** [comment]
Woo hoo! That's great. 😁

I was getting confused 😅

You're welcome. Thanks for the kind words.
