### ISSUE TITLE
Alignment issue due to table rows padding

### ISSUE THREAD

**Issue by fmal** [bvaughn/react-virtualized#408]
Hi @bvaughn ,

thanks for all the effort you put into this wonderful library. I have just upgraded to version 8 and ran into a minor issue. Before 8.0 `FlexTable__row`s were wrapped within `Grid_cell` which had fixed width same as `<Table>` regardless of the scrollbar existence in `Grid__innerScrollContainer`. To account for the scrollbar `padding-right: 17px;` was set on the rows. After removal of `Grid_cell` rows widths are affected by the scrollbar (they become narrower) but `padding-right` rule is still present. This causes some misalignment issues as shown below (header cells are not aligning with the body cells):

version 7.x:
![3](https://cloud.githubusercontent.com/assets/927591/18706956/49d0f598-7ff4-11e6-8b7d-de4e1f2eeaec.png)

version 8:
![4](https://cloud.githubusercontent.com/assets/927591/18706971/55a6d73e-7ff4-11e6-9062-831ac7522c54.png)

Removing `padding-right` on `.ReactVirtualized__Table__row` fixes these issues. Seems like it's no longer needed.

**Comment by bvaughn** [comment]
Hi @fmal,

Great catch! I'll put out a bugfix release with this change shortly. 😄

**Comment by bvaughn** [comment]
Fixed in 8.0.7
