### ISSUE TITLE
Add natural sorting (original order) to FlexTable

### ISSUE THREAD

**Issue by sriverag** [bvaughn/react-virtualized#410]
When a sortable column is clicked, the only options are ascending and descending and there is no way to return to the original order. Previously, I were using FixedDataTable and implemented a values sorting functionality that included ASC, DESC and NATURAL sorting. Example of a scenario that would be useful:

NATURAL 
-------------
1
8
6

Header Clicked!

ASC ^
-------------
1
6
8

Header Clicked!

DESC v
-------------
8
6
1

Header Clicked!

ASC ^
-------------
1
6
8

There is no way to return to NATURAL sorting.

**Comment by bvaughn** [comment]
Ah! You can actually do this in your application code. (Maybe I should write up some docs on how to do it?). 😄 Anyway, here's the basic idea:

```jsx
export default class TableExample extends Component {
  render () {
    const { list, ...rest } = this.props
    const { sortBy, sortDirection } = this.state

    // List sorting should not be done in render()
    // But I'm showing it here as an example
    if (sortBy) {
      list = list.sortBy(item => item[sortBy])
      if (sortDirection === SortDirection.DESC) {
        list = list.reverse()
      }
    }

    return (
      <Table
        {...rest}
        sort={this._sort}
        sortBy={sortBy}
        sortDirection={sortDirection}
      >
        {/* <Column>s go here */}
      </Table>
    )
  }

  _sort ({ sortBy, sortDirection }) {
    const {
      sortBy: prevSortBy,
      sortDirection: prevSortDirection
    } = this.state

    // If list was sorted DESC by this column
    // Rather than switch to ASC, return to "natural" order
    if (prevSortDirection === SortDirection.DESC) {
      sortBy = null
      sortDirection = null
    }

    this.setState({ sortBy, sortDirection })
  }
}
```

**Comment by bvaughn** [comment]
Great! 😁
