### ISSUE TITLE
Consider refactoring <Table /> not to use children prop for column specification

### ISSUE THREAD

**Issue by andreypopp** [bvaughn/react-virtualized#414]
I'm working on a datatable implementation which is based off (forks) `<Table />` code.

I think `<Table />` code itself could be simplified (and even be more performant probably) if it uses `columns` prop (being an array column specifications, just POJSO objects) instead of `children` with pseudo-React elements.

For example all those calls to `React.Children.forEach/map` will go away. What do you think?

**Comment by andreypopp** [comment]
Another problem with `<Column />` is that it doesn't adhere to standard React composition semantics: what if I do `<MyFancyColumn />` and pass it into `<Table />`? It will break (good we have a warning for it).

**Comment by bvaughn** [comment]
This is a reasonable suggestion. Personally, I like declaring the columns as children vs a props-array, but that's just a subjective thing.

I wish this issue had been filed before version 8 was released. As it is, I don't think it warrants another major release and I don't think I want to add forks to support both. (Hope you understand.)

The `MyFancyColumn` scenario you mention is supported, just not via JSX syntax. Instead you could make a factory method that would work something like this:

```jsx
function MyFancyColumn (columnProps) {
  // Do whatever makes your column fancy
  return (
    <Column {...columProps} />
  )
}

function renderTable () {
  return (
    <Table {...tableProps}>
      <Column {...column1Props} />
      {MyFancyColumn(column2Props)}
    </Table>
  )
}
```

**Comment by bvaughn** [comment]
I'm going to go ahead and close this issue for now because I don't plan on taking immediate action on it and doing so helps me keep the backlog somewhat maintainable. But we can continue to discuss the topic here. 😄

**Comment by andreypopp** [comment]
Makes sense. Totally does warrant another major release alone.

**Comment by andreypopp** [comment]
Er... I mean't "doesn't warrant another major release".

**Comment by bvaughn** [comment]
lol, no worries. I understood what you meant. 😄

**Comment by bvaughn** [comment]
It _is_ a reasonable suggestion though. I'll think on it a bit more. If you'd like to toss up a PR with a suggested implementation in the meanwhile- (one that maintains backwards compat)- I'd be happy to look over it and further consider.
