### ISSUE TITLE
Dead estimatedRowSize property?

### ISSUE THREAD

**Issue by oliviertassinari** [bvaughn/react-virtualized#417]
Having a look at the source code, I can't find any [relevant use](https://github.com/bvaughn/react-virtualized/search?l=javascript&q=estimatedRowSize&utf8=%E2%9C%93) of the `estimatedRowSize` property.
Is this a dead property?

**Comment by bvaughn** [comment]
That's weird.

No, it's not. Its use is as the docs describe. `Grid` passes [it](https://github.com/bvaughn/react-virtualized/blob/5fe6e551fc324bc11728659234729baf4f0ac2b3/source/Grid/Grid.js#L705-L709) to the [size and position manager](https://github.com/bvaughn/react-virtualized/blob/5fe6e551fc324bc11728659234729baf4f0ac2b3/source/Grid/Grid.js#L230-L234) which uses it to guestimate an initial [total scrollable area size](https://github.com/bvaughn/react-virtualized/blob/5fe6e551fc324bc11728659234729baf4f0ac2b3/source/Grid/utils/CellSizeAndPositionManager.js#L92-L96) that is gradually corrected as cells are actually measured and rendered.

**Comment by oliviertassinari** [comment]
Oh right, looks like the index of Github is out of date. Thanks.

**Comment by bvaughn** [comment]
No problem!
