### ISSUE TITLE
List (version 8.0.9), problem with scrollToIndex={} while using scrollTop={} too

### ISSUE THREAD

**Issue by UXDart** [bvaughn/react-virtualized#418]
Hello
I'm using a List inside a WindowScroller, so I'm passing the scrollTop to the List. this is a dynamic height row list.. and I'm updating the list items all the time. the problem is that if I add new items on top of the list, I recalculate the new rowIndex of the old last visible rowIndex and pass it to scrollToIndex={newPos} but it doesn't work. it shows another new position of the list, not the one of that rowIndex.

is it possible this is because the dynamic height of each row?

do I have anyway to fix that? any tip? I need to keep the last position inside the list, if not it will jump to one position to another all the time. 

I think the problem is that inside 'updateScrollIndexHelper' it calls 'this._updateScrollTopForScrollToRow({ ...this.props, scrollToRow })'

and that method just sets the last position of the offset, but the offset now changed (because of the new rows on the top).

any idea?

TIA!

**Comment by bvaughn** [comment]
`List` caches each row-size and position for efficiency. (This is an especially important optimization when used with a component like `CellMeasurer`.) If you push new items onto the end of the collection this is not a problem. If your rows are all the same height it's not a problem. But if your rows vary in size _and_ you add new items to the beginning (or change them in the middle) then `List` will have incorrect sizes and that will cause its `scrollToIndex` calculations to be incorrect.

Fortunately there is a simple fix for this: [`recomputeRowHeights `](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#recomputerowheights-index-number). Just call this function on `List` whenever your data changes and give it the lowest index that changed (eg if rows 4, 6, and 9 change- give this function 4). It will reset the cached values and re-render which should resolve your problem.

**Comment by UXDart** [comment]
thanks! I'm doing this atm:
`  this.setState(state, function () {
      this.listM.resetMeasurements();
      this.listA.recomputeRowHeights();
     }.bind(this));
`
so it sets the new state with the state.items, the problem is that (I tried many variants) the recompute...() takes place "after" the items are on the <List /> so it already did a scrollToIndex while it didn't had the real height row values.... when should I call the recompute...() or the resetMeasures methods? (I couldn't find it googling and on GH issues)

Thanks!!

**Comment by bvaughn** [comment]
Reset measurements in componentWillUpdate- before you pass it the updated
scrollToIndex.

**Comment by UXDart** [comment]
Thank you!
can you please check this code test case: https://jsfiddle.net/yvpje37s/5/
run it, scroll down, and click on any cell... it will refresh with new heights... but it doesn't go to the row 3. what I'm missing?

my real use case, is a lot more complex, but I found the same problem in that sample. if you could check it, would be great!

TIA

**Comment by UXDart** [comment]
I think the problem is that updateScrollIndexCallback is never called... is there anyway to force the call? (so the scrollToRow happens) TIA

**Comment by bvaughn** [comment]
Regarding your Plunker, you shouldn't be calling `resetMeasurementForRow` every time `componentWillUpdate` is invoked. This will blow away your cache after every render and is not good for performance. You should call this method right before you call `List` (aka `this.listA.recomputeRowHeights`).

Unfortunately the rest of what you're trying to do looks like an edge-case that falls through due to the way I'm detecting changed sizes [here](https://github.com/bvaughn/react-virtualized/blob/efa351f7dfe460f3e5eba5dac227875d84f00b82/source/Grid/utils/updateScrollIndexHelper.js#L32-L39). Essentially I ignore row heights if the height is a getter function instead of a number. I _may_ be able to relax this without hurting performance but I'd like to think about it a little bit.

In the meanwhile, if you update your fiddle to this, it should work:

```jsx
var Hello = React.createClass({
  getInitialState() {
    return {
      hh: 10,
      lastRow: 3
    };
  },
  
  onC(e) {
    console.log('1: onClick');
    this.hh = Math.trunc(Math.random()*10);
    console.log('1: new hh:'+this.hh);
    this.setState({
      lastRow: undefined,
      hh: this.hh,
    }, function() {
      console.log('1.B: recomputing');
      this.listM.resetMeasurementForRow();
      this.listA.recomputeRowHeights();
      this.setState({
        lastRow: 3
      });
    }.bind(this));
  },
  
  render: function() {
    var countTotal = 100;
    var width = 400;
    var cellRenderer = function({index, key, style}) {
      style.border = '1px solid red';
      return <div style={style} key={key} onClick={this.onC}>aaaaa {index}</div>;
    }.bind(this);
    var onRows = function(param) {
    
    };
    var hh = this.state.hh;
    var lastRow = this.state.lastRow;
    var calcRowHeight= function({index}) {
      return 20+20*Math.trunc(index % (hh || 10));
    }.bind(this);

    return (
      <ReactVirtualized.CellMeasurer
        cellRenderer={cellRenderer}
        columnCount={1}
        rowCount={countTotal}
        width={width}
        ref={(ref) => { this.listM = ref; }}
      >
        {({ getRowHeight, resetMeasurementForRow }) => (
          <ReactVirtualized.List
            ref={(ref) => { this.listA = ref; }}
            onRowsRendered={onRows}
            height={400}
            overscanRowCount={3}
            rowRenderer={({ index, key, style }) => cellRenderer({ index, key, style })}
            rowCount={countTotal}
            rowHeight={calcRowHeight}
            width={width}
            scrollToIndex={lastRow}
            scrollToAlignment="start"
          />
        )}
      </ReactVirtualized.CellMeasurer>
    );
  }
});

ReactDOM.render(
  <Hello name="World" />,
  document.getElementById('container')
);
```

**Comment by UXDart** [comment]
perfect! thank you!!
