### ISSUE TITLE
scrollToRow on List not working always

### ISSUE THREAD

**Issue by UXDart** [bvaughn/react-virtualized#420]
Hi! I wrote in another issue about this, but now I found a sample that replicates the problem, I'm using Chrome last version on OSX, in this snippet https://jsfiddle.net/yvpje37s/6/ if you scroll and click some times, you will see that sometimes it doesn't go to the lastRow, the top of the rows is in the middle. also if I don't change the lastRow there is no way to force the List to anyway go to that row.

not sure how, but it would be great if in the case that you force a update/refresh, it goes to the same last row with the same offset it had. I could check the last row in my code checking for onRowRendeder, but anyway if you can check the sample, I must be doing something wrong or there is a bug, not sure... I tried a lot of cases and had the same result

TIA

**Comment by UXDart** [comment]
I would like to write a component to "keep scroll position", like a container maybe, would you merge it if I create a PR? Thanks

**Comment by bvaughn** [comment]
Hi @UXDart. No need to open new issues. 😄 We can still talk on the other issue, as we were. My response times might not be very fast but that's because this project only has 1 maintainer and I do it in my spare time. I'm going to close this issue for now and we can continue discussion on #418.
