### ISSUE TITLE
declarative alternative to forceUpdateGrid

### ISSUE THREAD

**Issue by jedwards1211** [bvaughn/react-virtualized#431]
I always prefer to avoid using refs and calling component instance methods when possible.  Here is one way a declarative alternative to `forceUpdateGrid` would look:

```es6
<List
  renderProps={{myData: [...]}}
  rowRenderer={({index, key, style, myData}) => <MyRow key={key} data={myData[index]} />}
/>
```
This way whenever `renderProps` changes `List` will do the same thing as `forceUpdateGrid`.

I implemented my own wrapper that provides that API as shown below.  But would you like this or a similar API to be a core part of `<List>` etc in `react-virtualized`?  I'd like to make a PR.
```es6
import React, {Component} from 'react'
import {List as WrappedList} from 'react-virtualized'

export default class List extends Component {
  componentDidUpdate(prevProps) {
    if (this.list && prevProps.renderData !== this.props.renderData) this.list.forceUpdateGrid()
  }
  render() {
    const {rowRenderer, renderData, ...props} = this.props
    return (
      <WrappedList
        {...props}
        ref={c => this.list = c}
        rowRenderer={props => rowRenderer({...props, ...renderData})}
      />
    )
  }
}
```

**Comment by bvaughn** [comment]
Hey @jedwards1211 😄

This topic is mentioned briefly [in the main `README`](https://github.com/bvaughn/react-virtualized/#pure-components) as an alternative to the public methods.

Both `List` and `Table` already pass-thru any additional `props` to `Grid` which should be sufficient to pass the `shallowCompare` check.

Am I overlooking something? (I might be. Sorry if I am!)

**Comment by jedwards1211** [comment]
Oh gosh, no, I'm sorry, I was overlooking that.  Thank you!

**Comment by bvaughn** [comment]
No problem at all! Thanks :smile:
