### ISSUE TITLE
[Docs] cellGroupRenderer seems to not be a required prop for Collection

### ISSUE THREAD

**Issue by mnquintana** [bvaughn/react-virtualized#433]
According to the docs [here](https://github.com/bvaughn/react-virtualized/blob/master/docs/Collection.md#prop-types) and the propTypes declaration [here](https://github.com/bvaughn/react-virtualized/blob/master/source/Collection/Collection.js#L30), `cellGroupRenderer` is a required prop for `Collection`, but then there's a default prop defined [here](https://github.com/bvaughn/react-virtualized/blob/master/source/Collection/Collection.js#L52) in case it's not provided.

**Comment by bvaughn** [comment]
Fixed docs.
