### ISSUE TITLE
Dynamic require()'s incompatable with es6 modules

### ISSUE THREAD

**Issue by mbrevda** [bvaughn/react-virtualized#435]
AutoResizer dynamically [includes code](https://github.com/bvaughn/react-virtualized/blob/master/source/AutoSizer/AutoSizer.js#L53) at runtime using `require()`. This is an issue for es6 bundlers (i.e. rollup) as they a. don't necessarily handel `require()` calls and b. can't properly handle dynamic imports.

I'm not sure where the better place to handle this is, so feel free to close if you thinks its a package-tooling issue.

/cc https://github.com/rollup/rollup-plugin-commonjs/issues/89

**Comment by bvaughn** [comment]
Hmm. That `require` is deferred for server-side rendering support (see #41).

I suppose I could convert the `detectElementResize` file to a factory-function and just defer its execution until `componentDidMount`. Initially I hoped to fork that code as little as possible, but I've already made several performance opts at this point so I might as well.

**Comment by bvaughn** [comment]
The above change has been released with version 8.1.0.

Let me know if you notice any issues. Thanks @mbrevda!
