### ISSUE TITLE
Add ability to cache previously rendered items in List

### ISSUE THREAD

**Issue by ianks** [bvaughn/react-virtualized#437]
# What's your use case?

I am building a recursive tree component, where each node needs to keep track of whether or not it expanded. Therefore, each node will be stateful. Since `react-virtualized` will re-render each item in `List` on demand, I lose the state of the tree when I scroll away.

#### Before
![before](https://s3-us-west-1.amazonaws.com/adhawk-random-public/react-virtualized-before.png)

#### After scrolling away
![after](https://s3-us-west-1.amazonaws.com/adhawk-random-public/react-virtualized-after.png)

I would like a way to cache previously rendered components. This would ensure that items in the `List` do not get replaced by brand new items. It has two major benefits:

1. Allows for stateful components when necessary
2. Saves a render cycle for an item in a `List`

# What interface do you have in mind? 

Something like:

```typescript
class List {
    // ...
    cacheRenderForRow(index: number): void;
}
```

This would be a public method which would signal that `react-virtualized should use a previously rendered component when it encounters this index.

**Comment by bvaughn** [comment]
Hi @ianks,

Thanks for the detailed feature request. 😄

The ability to manage a custom cell cache is already available, although with a different API. The relevant docs are here: https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md#customizing-cellsizecache

In this case though, I would suggest that your item's "state" should be stored somewhere (other than the cached, rendered item). The simplest way to do this would be for your list parent component to use internal React `state`. For example:

```jsx
class MyComponent extends Component {
  constructor (props, context) {
    super(props, context)

    this.state = {
      openRows: {}
    }

    this.toggleRow = this.toggleRow(bind)
  }

  render () {
    return (
      <List
        {...this.props}
        rowRenderer={
          (rowProps) => (
            <YourStatefulRowComponent
              {...rowProps}
              isOpen={!!this.state.openRows[rowProps.index]}
            />
          )
        }
      />
    )
  }

  toggleRow ({ index, isOpen }) {
    this.setState({
      openRows: {
        ...this.state.openRows,
        [index]: isOpen
      }
    })
  }
}
```

**Comment by ianks** [comment]
> The ability to manage a custom cell cache is already available, although with a different API.

Yes yes I am aware! It is a useful API, but I do not need to use a cell measurer in this case and it would not solve the current problem.

> "state" should be stored somewhere (other than the cached, rendered item).

It seems like this may be the only way. It is going be rather dirty since we can have arbitrarily nested recursive trees, but I think I can make it work. 

Either way, consider my proposal. I think it can be a useful feature for allowing state and reducing the number or renders for performance gains.

**Comment by bvaughn** [comment]
Ah, sorry. I didn't mean to link to `CellMeasurer`. That was a multi-task fail. I actually meant to link you to _this_ thread: https://github.com/bvaughn/react-virtualized/pull/163#issuecomment-249709856

Namely this example:

```jsx
import { defaultCellRangeRenderer, List } from 'react-virtualized'

const cellCache = {}

function cellRangeRenderer (cellRangeRendererProps) {
  const { cellRenderer } = cellRangeRendererProps

  function cellRendererWrapper (cellRendererProps) {
    return cellRenderer({
      ...cellRendererProps,
      isScrolling: false
    })
  }

  return defaultCellRangeRenderer({
    ...cellRangeRendererProps,
    cellCache, // Provide your own, permanent cache
    isScrolling: true, // Trick default renderer into always-caching
    cellRenderer: cellRendererWrapper
  })
}

function CustomizedList (props) {
  return (
    <List
      cellRangeRenderer={cellRangeRenderer}
      {...props}
    />
  )
}
```

Essentially just showing how you could override the cache used by `Grid` (or the `List` wrapper) to manage your own caching.

**Comment by bvaughn** [comment]
Maybe worth adding that- in general, I'm not a huge fan of adding more public methods to components since those methods require the usage of refs. I prefer approaches that rely only on injected props. 😄

**Comment by bvaughn** [comment]
I'm pretty sure, given the above code snippet, that what you're requesting (caching of cells) is already possible and relatively trivial. So I'm going to go ahead and close this issue for now. But I'll still happily discuss pros and cons, answer any questions you may have, etc.

I can always reopen the issue again if I'm overlooking anything. 😄

**Comment by ianks** [comment]
:+1: Thank you, I think this should resolve my issues!
