### ISSUE TITLE
defaultHeaderRenderer and disableSort property

### ISSUE THREAD

**Issue by alolis** [bvaughn/react-virtualized#439]
Hello,

I was trying to enable the sort indicator for multiple columns by setting `disableSort={false}` to each column and I wasn't noticing any difference so I started digging around and found the following:

https://github.com/bvaughn/react-virtualized/blob/master/source/Table/defaultHeaderRenderer.js#L17

```javascript
const showSortIndicator = sortBy === dataKey
``` 

Shouldn't the `showSortIndicator` flag be dependent on `disableSort` as well in order to be able to force the indicator to show if desired? Does this look like a bug or was it intended? 

If yes, then the `key` in the following line should be changed as well:

https://github.com/bvaughn/react-virtualized/blob/master/source/Table/defaultHeaderRenderer.js#L31

```javascript
 key='SortIndicator'
```

A `key='SortIndicator_' + dataKey` will probably be more appropriate if all the above is true.

The user has no way to know which columns are sortable beforehand by just looking at the list, if he does not move the mouse over the header first, so I believe showing the indicator at all times would be better regarding user experience.

**Comment by bvaughn** [comment]
Hi @alolis,

I think there's a small misunderstanding here about how the default header and sort indicator works.

If a `sort` prop is passed to the `Table`, and a `Column` is not sort-disabled, then clicking on it will invoke the `sort` function (letting the parent container know that the user wants to re-sort the data).

Separately, if a given `Column` has a `dataKey` that matches the `sortBy` prop passed to the parent `Table` then its header will display a sort indicator, letting the user know that the data is currently sorted by this column.

Does this clear things up any?

Headers are not all meant to show sort icons, only the one that's currently "active". If you want to display sort arrows in all of the headers by default, then you can just provide your own `headerRenderer` prop to `Column`. 😄

**Comment by alolis** [comment]
Hi @bvaughn ,

Thanks for getting back to me. It was pretty clear to me the way it worked but I just wanted to clarify if it's intentional or not because from a user experience perspective, I believe it's pretty standard to show the indicator for all the columns that are sortable at all times, and not the one which is currently being sorted. 

That being said, I think it will be a good idea to have this functionality included as default in the `headerRenderer`. Until then, I will just override it :)

**Comment by bvaughn** [comment]
If you'd like to share your idea of a better header renderer (via a Pull
Request) maybe we could add it as a built-in option as well? In my
experience, the current behavior works well, but my experience is very
limited.
