### ISSUE TITLE
Investigate `will-change` optimization

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#44]
It's not clear that this would have a net positive performance impact but it seems worth profiling.

For example the [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) say (emphasis added):
> Give it sufficient time to work. This property is intended as a method for authors to let the user-agent know about properties that are likely to change ahead of time. Then the browser can choose to apply any ahead-of-time optimizations required for the property change before the property change actually happens. So it is important to give the the browser some time to actually do the optimizations. **Find some way to predict at least slightly ahead of time that something will change, and set will-change then.**

Similarly [dev.Opera](https://dev.opera.com/articles/css-will-change-property/) says (emphasis added):
> The optimizations that the browser makes for changes that are about to occur are usually costly and, as we mentioned earlier, can take up much of the machine’s resources. The usual browser behavior for optimizations that it makes is to remove these optimizations and revert back to normal behavior as soon as it can. However, will-change overrides this behavior maintaining the optimizations for much longer than the browser would otherwise do.
> As such, **you should always remember to remove will-change after the element is done changing**, so the browser can recover whatever resources the optimizations are claiming.

Given the nature of `react-virtualized` we can't really comply with either of the above suggestions and so it may be better to let the browser's default behavior handle things.

**Comment by cesarandreu** [comment]
You can just set it when you start scrolling, and remove it when the timer is finished. At least that's the scenario I was envisioning.

**Comment by bvaughn** [comment]
The sources I linked to above specifically suggest _not_ doing that. (At
least that's how I'm interpreting them.)

**Comment by cesarandreu** [comment]
You could add it when you hover over the table :P, that's likely to mean you're gonna start scrolling.

**Comment by bvaughn** [comment]
That's true for devices with mouses, but not for touch.
