### ISSUE TITLE
Add integration of infiniteloader with custom or 3rd party tables (for example material-ui's table)

### ISSUE THREAD

**Issue by apedyashev** [bvaughn/react-virtualized#447]
I use material-ui in my project and it seems that InfiniteLoader cannot be used with  table from this library. I only able to render rows using `rowRenderer`, but table, thead, tbody  tags cannot be rendered since react throws error:
```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <tbody>
```

**Comment by bvaughn** [comment]
Sorry @apedyashev. `InfiniteLoader` is only intended to work with other react-virtualized components. It's not realistic for me to support integration with arbitrary 3rd party libraries since I don't control their Apis.

**Comment by anyayunli** [comment]
for anyone has similar errors, try to set component and variant on the tablecell
`   <TableCell component="div" variant="body" />;
`
