### ISSUE TITLE
Possibility of disable cache for cellRangeRenderer while scrolling Grid

### ISSUE THREAD

**Issue by morozow** [bvaughn/react-virtualized#448]
I need to have support for manage cache while scrolling Grid.
In my realization I have navigation with arrows (up/down) and in case when I use long time arrow push I have incorrect render behavior of new rows (after I reach table's end while scrolling with arrows).

https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/defaultCellRangeRenderer.js#L55
This issue related to this code.

**Comment by bvaughn** [comment]
You can manage your own cache by providing your own `cellRangeRenderer`. I don't currently have plans to change that API. 😄

```jsx
import { defaultCellRangeRenderer, List } from 'react-virtualized'

const cellCache = {} // You can do whatever you want with this

function cellRangeRenderer (cellRangeRendererProps) {
  return defaultCellRangeRenderer({
    ...cellRangeRendererProps,
    cellCache
  })
}

function CustomizedList (props) {
  return (
    <List
      cellRangeRenderer={cellRangeRenderer}
      {...props}
    />
  )
}
```
