### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by vgoklani** [bvaughn/react-virtualized#45]
Apologies in advance, I'm still new with all this... 

I installed via: "npm install react-virtualized --save"

but when I run gulp, I get this error:

Error: Cannot find module '!!./../../node_modules/css-loader/index.js?modules&importLoaders=1!./../../node_modules/cssnext-loader/index.js!./AutoSizer.css' from '/Users/vgoklani/metricle/apps/web_app/static/scripts/viewer/node_modules/react-virtualized/dist'
    at /Users/vgoklani/metricle/apps/web_app/node_modules/resolve/lib/async.js:46:17
    at process (/Users/vgoklani/metricle/apps/web_app/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/vgoklani/metricle/apps/web_app/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/vgoklani/metricle/apps/web_app/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/vgoklani/metricle/apps/web_app/node_modules/resolve/lib/async.js:92:31)
    at /Users/vgoklani/metricle/apps/web_app/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

I have several other react libraries running, and they all work fine. I'm not sure why I get error.

**Comment by bvaughn** [comment]
Hi @vgoklani,

No problem with asking a question. I'm not sure why you're seeing that error since the code you're referencing shouldn't actually be executing.

I just updated my dist-build to run through uglify and remove that chunk of dead code entirely. Try the 2.7.4 build and let me know if it works for you?

**Comment by vgoklani** [comment]
2.7.4 works correctly, thanks!

**Comment by bvaughn** [comment]
Weird! But I'm excited to hear that. :) Thanks for reporting back!
