### ISSUE TITLE
Cells aren't visible when dir=rtl

### ISSUE THREAD

**Issue by mbrevda** [bvaughn/react-virtualized#450]
When using `<html dir="rtl">`, grid cell aren't visible. They seem to be rendered thought, but aren't visible and cannot be scrolled to. 

DEMO:  add 'dir="rtl"' to the <html> tag in https://bvaughn.github.io/react-virtualized/?component=Grid#/components/Grid and scroll around a bit

Workaround
===
Until this is resolved, adding the following to `Grid` enables the visibility of cells, with the downside that scrolling is ltr.
```js
style={{direction:'ltr'}}
```

**Comment by mbrevda** [comment]
As a theory, I'm wondering if positioning isn't backwards in RV + RTL. It would seem that `CellSizeAndPositioningManager` always starts [at `0`](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/utils/CellSizeAndPositionManager.js#L82) and then increments [from there](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/utils/CellSizeAndPositionManager.js#L69). That would put the first cell on the left of the container (at offset 0) and the next cell to the right of it - even though _scrolling_ starts at the right.

If this is correct, cell rendering should use the right most point (probably `offset + width`) and subtract the cell width to get the _left_ position of the first cell. Then subtract the width of each additional cell to get its left position.

As a side note, overscanning will have probably also need to be adjusted.

**Comment by bvaughn** [comment]
Initial gut reaction to the thought of forking the positioning logic is... "yuck". That's a chunk of code, and this would essentially be doubling it.

Setting `direction: ltr` on the `Grid` and `direction: rtl` on the cells seems like a reasonable work around to avoid complicating (and slightly slowing down, as forks do) the code. This should be a pretty minimal app-side change. Thoughts?

**Comment by mbrevda** [comment]
> yuck

Agreed, i18n isn't easy! But digging in to the code, I imagine neither was RV.

> this would essentially be doubling it

I'm not sure it's necessary to fork/duplicate the logic. All the horizontal positioning would stay the same. And if my theory is correct, vertical positioning requires just a handful of ternaries (`offset = isRtl ? x : y`)

> Setting direction: ltr on the Grid

Atm RV is BROKEN with rtl. The work around will at least "unbroke" it. Hence, forcing ltr should probably by included in RV so that devs arent required to fix RV app side. A note/disclaimer about the lack of proper rtl support in the docs is probably o good idea.

> seems like a reasonable work around

about as reasonable as asking all Hebrew and Arabic speakers to please learn English...

The logical flow of data in rtl languages is from the right. Left hand menu's, top left icon, back buttons - all these get reversed in rtl. I think that in order to be properly compatible, RV needs some way to be reversed, too.

**Comment by bvaughn** [comment]
Your responses are a little inflammatory. 😕 My suggestion to tag ltr on the main `Grid` component and rtl on the cells is in _no way_ equivalent to suggesting Hebrew/Arabic speakers learn English. And the use of all caps (eg BROKEN) is...unnecessary.

RV is a library maintained by a _single_ developer, _for free_. I can't accommodate every request. If an issue/feature can be fixed simply (by which I mean "not much code") on the application side- then it's not unreasonable for me to suggest that workaround be used.

If there's a reason that the suggested workaround (initially mentioned by you) _doesn't work_ then that's worth discussing. If it's just the principle though... then please, feel free to submit a PR yourself.

**Comment by mbrevda** [comment]
I'm sorry, I didn't mean to come across like that. I appreciate what the lib provides and the resources needed to maintain it. I'll leave my response above for context, but please consider them redacted. Ill respond again, below, more sensibly.

**Comment by bvaughn** [comment]
No worries. 😄 Let's back up and start over.

I _do_ see one advantage to adding this capability into the size-and-position-manager util: it would enable RV to easily support reverse mode as well (something that's often requested for chat apps but is currently a little awkward to implement).

**Comment by mbrevda** [comment]
> Setting direction: ltr on the Grid and direction: rtl on the cells seems like a reasonable work around

It solves part of the issue. In it's current form, cells aren't displayed at all. Adding the `direction` style allowed them to be show, albeit in the "wrong" direction.

I would suggest hardcoding the direction for the time being, and then taking a more thought out long term approach which could include a more generalized "reverse" ordering.

**Comment by bvaughn** [comment]
That sounds like a reasonable initial step, for sure.

Supporting RTL fully is going to be a difficult performance challenge for dynamically measured cells unless the refactoring idea I have (but have not yet gotten the time to try) pans out. eg for me to know the width of a grid, I'll have to measure all columns within it and- if CellMeasurer is involved- this will be slow.

**Comment by mbrevda** [comment]
I'm probably just missing something obvious, but I would imagine that performance shouldn't be that different. Couldn't you just calculate from the `left + width` point, get the cells width and work from there? That's pretty much how (it seems to me) to work today, only the formula for a cells position is `left + lastOffset` and now it would be `lastOffset - cellWidth`

**Comment by bvaughn** [comment]
Currently, horizontal position is basically 0 + the-width-of-every-column-before-me. This works out well is _most_ cases because I only have to incrementally measure those columns before as a user scrolls right. (There are some exceptions, when the user uses `scrollToColumn`, but as long as `scrollToColumn` and `CellMeasurer` aren't used together- there's no real problem.)

RTL alignment would require knowing the width of the entire grid (eg all of the columns) in order to place the "first" one (the right-most one). Without calculating this width ahead of time, scrolling from the right to the left might leave things misaligned eventually. (Not sure if this makes sense outside of my head or if I'm just explaining it in terms that only I understand.)

**Comment by mbrevda** [comment]
Yeah, makes sense, actually. So what we really need is a way to flip the entire grid (a la ` transform: rotateY(180deg)`) and then we can save all this work. Not sure thats the _best_ idea, it might just be another workaroudn

**Comment by mbrevda** [comment]
Just tested this. God knows what it does to performance, but `direction: ltr; transform: rotateY(180deg);` on the grid and another `transform: rotateY(180deg)` on the cell actually seem to get the job done!

**Comment by bvaughn** [comment]
Okay, so, firstly- thanks for bringing this issue to my attention. Proper RTL support is as important to me as proper accessibility support. Unfortunately my time is stretched very thin at the moment but that doesn't change the importance.

That being said, I have temporarily added a `direction: ltr` default style to `Collection` and `Grid` so that neither will break catastrophically (as you observed) in an RTL context. That's not a "fix" so much as a bandaid for now. (This was released as version 8.4.1.)

The transform you mentioned is a little scary 😅 but worth investigating as a better bandaid (if nothing else). I'll try to test i ta bit sometime soon. In the meanwhile if you have any bandwidth to perf-test it, I'd love to get your input.

**Comment by bvaughn** [comment]
I am surprised to see that- at a glance- it does indeed seem to work. 😅 Even `scrollToColumn` seems to work correctly.

**Comment by bvaughn** [comment]
Just played for a minute with Google spreadsheets in RTL mode and noticed a difference though. Spreadsheets scrolls left/right in the direction you swipe. `Grid` (with the stacked rotations) scrolls left when you swipe right and vice versa. I assume Spreadsheets is behavior correctly in this case.

**Comment by bvaughn** [comment]
So the original bug here has been fixed. (Cells are visible now.) Mind updating the title/description to be something about more generic support of RTL? As it is now, it's misleading.

**Comment by mbrevda** [comment]
Sure. Would you prefer a new issue?

**Comment by bvaughn** [comment]
That would probably be better still 😉

**Comment by mbrevda** [comment]
fixed in https://github.com/bvaughn/react-virtualized/commit/7595de7cf7dc8beef39b6383f8fbbeb0f5f9eddf, general RTL discussion continued in #454. Thanks @bvaughn!

**Comment by bvaughn** [comment]
You rock. Thanks
