### ISSUE TITLE
Disabled table header shortens table height

### ISSUE THREAD

**Issue by Jakehp** [bvaughn/react-virtualized#459]
**Example of current functionality / 'Issue'**
https://plnkr.co/sMsCl49eLCjXyxQAv6qn

**Proposition**
When the table header is disabled, make the available row height use the table height and do not reduce it by the header height.

**Result**
When a table's header is disabled, the table height will be what was specified and not shortened by header height.

**Use Case**
The table's height dimension is proportional or equal to parent element, and when header is disabled the table looks short of the expected height.

https://github.com/bvaughn/react-virtualized/pull/460

**Comment by bvaughn** [comment]
If only all issue reports came with repro cases and PRs. Thanks again!

**Comment by bvaughn** [comment]
Version 8.5.1 is being published now with this fix.
