### ISSUE TITLE
CellMeasurer increases AutoSized grid infinitely

### ISSUE THREAD

**Issue by mquan** [bvaughn/react-virtualized#467]
Thanks for creating react-virtualized. I'm trying to create a Grid-based component that grows vertically with the window. When adding CellMeasurer to dynamically adjust column widths, I found that the container height keeps increasing even after all the rows finished rendering. It seems like there is a feedback loop that just makes the height grows out of bound. Here's a simplified version of my component.

```javascript
class MyTable extends React.Component {
  render() {
    const columnCount = 20
    const rowCount = 50
    const rowHeight = 60

    return (
      <div>
        <AutoSizer disableHeight>
          {({ width, height }) => (
            <div>
              <h3>Current height {height}</h3>
              <CellMeasurer
                cellRenderer={this._renderCell}
                columnCount={columnCount}
                rowCount={rowCount}
                height={height}
              >
                {({ getColumnWidth }) => (
                  <Grid
                    columnCount={columnCount}
                    columnWidth={getColumnWidth}
                    height={height} // <---- this makes height grows infinitely
                    overscanColumnCount={0}
                    overscanRowCount={0}
                    cellRenderer={this._renderCell}
                    rowCount={rowCount}
                    rowHeight={rowHeight}
                    width={width}
                  />
                )}
              </CellMeasurer>
            </div>
          )}
        </AutoSizer>
      </div>
    )
  }

  _renderCell = ({columnIndex, key, rowIndex, style }) => {
    return (
      <div
        key={key}
        style={style}
      >
        <div style={{padding: '10px'}}>
          {`cell ${rowIndex},${columnIndex}`}
        </div>
      </div>
    )
  }

  shouldComponentUpdate(nextProps, nextState) {
    return shallowCompare(this, nextProps, nextState)
  }
}
```

Apologize if I'm misusing `CellMeasurer`.

**Comment by bvaughn** [comment]
This likely has nothing to do with `CellMeasurer` persay, as it measures cells relative to the root. It's probably due to an ancestor of `AutoSizer` (eg is it inside of a flex container?) If so, see [here](https://github.com/bvaughn/react-virtualized/blob/master/docs/usingAutoSizer.md#can-i-use-autosizer-within-a-flex-container)

**Comment by mquan** [comment]
You're right. The problem still persists even after removing CellMeasurer. It turns out my simplified code introduced the bug. Thanks for the answer

**Comment by bvaughn** [comment]
Yup! 😁 Glad to hear you solved it.
