### ISSUE TITLE
Replace react-addons-shallow-compare with PureComponent?

### ISSUE THREAD

**Issue by cesarandreu** [bvaughn/react-virtualized#469]
According to the docs, [react-addons-shallow-compare](https://facebook.github.io/react/docs/shallow-compare.html) is a legacy addon. Have you considered replacing it with [React.PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent)?

**Comment by bvaughn** [comment]
Doesn't seem appropriate for a lib, considering `PureComponent` is a recent addition and I'm trying to maintain backwards compatibility. I could make that upgrade in the next major release- but it would be backwards-breaking.

**Comment by cesarandreu** [comment]
Ah, that's totally understandable. Do you know if there's any public metrics that show each version's usage?  Would it be safe to assume your plan is to follow along with react and drop v14 support when v16 is released?

**Comment by bvaughn** [comment]
Hm, no clue. I don't know if even the React team knows that, although I'll ask Ben when I see him.

Yes, that would be reasonable to assume. 😄

**Comment by bvaughn** [comment]
Closing for now 😄 We can revisit when next React version drops

**Comment by dsifford** [comment]
@bvaughn Can we revisit this? Dropping shallow-compare would be nice because it frees up that pesky peer dependency.

**Comment by bvaughn** [comment]
We can revisit once React 16 lands _or_ with the next major react-virtualized released. 😄

**Comment by dsifford** [comment]
Sounds good! Sorry, I suppose I should have prefaced that last message with "I have no idea what version React was at when you guys first had this conversation".

** subscribes to thread **

**Comment by bvaughn** [comment]
No problem 😄  This ticket was from November '16 and React 15 has been out since April '16, so same major version.

**Comment by bvaughn** [comment]
FYI thought you might like to know that the [upcoming react-virtualized version 9](https://github.com/bvaughn/react-virtualized/pull/577) will drop support for `shallowCompare` in favor of using `React.PureComponent`.
