### ISSUE TITLE
WindowScroller: provide scrollHeight on render callback

### ISSUE THREAD

**Issue by Strate** [bvaughn/react-virtualized#470]
I want to use window scroller to trigger load rows from server on scrolling to the edge of window. It sould be pretty simple just comparing scrollTop & scrollHeight with some threshold. But window scroller does not provide scrollHeight, I want to suggest you to provide it.

**Comment by bvaughn** [comment]
`WindowScroller` doesn't really have any special information about `scrollHeight`. It just passively observes the scroll position of the document and relays that down. `scrollHeight` is determined by the size of the body and the elements it contains- which often include things _outside of_ react-virtualized components (eg headers, footers).

I think it's probably reasonable for application code to query the body for its size if that information is useful. What prevents you from doing this out of curiosity?

**Comment by Strate** [comment]
Okay, it is not tricky to implement it. Seems that it is outside the scope of component, so I close it.

**Comment by bvaughn** [comment]
Cheers :)
