### ISSUE TITLE
Allow WindowScroller to be used with scroll containers besides window?

### ISSUE THREAD

**Issue by andrewbranch** [bvaughn/react-virtualized#474]
Wondering if you would consider a PR adding a `scrollElement` (name up for debate) prop to WindowScroller such that it could be used with containers that are neither window nor constrained only to the boundaries of a fully on-screen list. (As an example, imagine an app layout with multiple independently scrolling side-by-side panels.)

At a super quick glance, it looks like instances of `window` in WindowScroller could fairly easily be replaced with a custom element, but I haven't yet tried it, and I wanted to see if it had already been attempted, or if you knew of a reason why it couldn't be done. Or if you would be terribly opposed to the idea since it could make "WindowScroller" a misnomer. 😛

I'm probably going to give it a shot either way, but if it's something you're interested in incorporating, I can let you know how it goes and eventually open a PR.

**Comment by bvaughn** [comment]
> As an example, imagine an app layout with multiple independently scrolling side-by-side panels.

`WindowScroller` is unique because it allows the top-level browser scrollbar to control the position of windowed content. What you're describing sounds to me like a couple of vanilla, side-by-side `List`s. (They can be independently scrolled.) I imagine you wouldn't want the browser's scrollbar to control one, so the only useful function of `WindowScroller` is not applicable. 😁

Maybe I'm misunderstanding you?

**Comment by bvaughn** [comment]
In other words, why not this: https://plnkr.co/edit/A2zDoCWQTvzwW1C53bhS?p=preview

**Comment by andrewbranch** [comment]
Yeah, that's not _quite_ it. What I meant to describe was [a layout like this](https://plnkr.co/edit/ogVK1Sa4UemJ5U8BNAOU?p=preview).

**Comment by bvaughn** [comment]
Oh interesting. I see.

That layout _could_ be accomplished by providing your own `cellRangeRenderer`. (Doing that really gives you a _ton_ of extra control over the innards of the list/grid/whatever.) But it would be more straight forward to do with something like `WindowScroller`. Hm... sure, share a PR. 😄 Happy to review it.

**Comment by andrewbranch** [comment]
Cool! Appreciate the feedback so far. I’ll let you know what happens!

**Comment by bvaughn** [comment]
Released in [8.10.0](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#8100)
