### ISSUE TITLE
Replace `react-addons-shallow-compare` with `PureComponent`

### ISSUE THREAD

**Issue by MikeMcElroy** [bvaughn/react-virtualized#477]
Just a feature request to use React's PureComponent class (if available in the currently used version of React) and get rid of some boilerplate code in `shouldComponentUpdate`s.

[React Docs for PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent)

**Comment by bvaughn** [comment]
Hey Mike. Did you see #469? This seems like a dup

**Comment by MikeMcElroy** [comment]
I didn't see it in the issues list when I looked -- must have not been paying attention.  Closing, and sorry for the dupe!

**Comment by bvaughn** [comment]
No worries! :)

**Comment by bvaughn** [comment]
FYI thought you might like to know that the [upcoming react-virtualized version 9](https://github.com/bvaughn/react-virtualized/pull/577) will drop support for `shallowCompare` in favor of using `React.PureComponent`.

**Comment by MikeMcElroy** [comment]
\o/ :-)
