### ISSUE TITLE
estimatedRowSize not passed from List to Grid

### ISSUE THREAD

**Issue by azeem** [bvaughn/react-virtualized#479]
It seems that the `estimatedRowSize` prop is not used anywhere in `List`. Shouldn't this be passed down to the `Grid`? https://github.com/bvaughn/react-virtualized/blob/master/source/List/List.js#L136

**Comment by bvaughn** [comment]
It is passed [here](https://github.com/bvaughn/react-virtualized/blob/007a939474923b97b0a3acc24c0b0410aab8e9f1/source/List/List.js#L137) with all of the other same-name props.

**Comment by azeem** [comment]
@bvaughn ah i see. my bad. thanks for clarifying :)

**Comment by bvaughn** [comment]
No prob!
