### ISSUE TITLE
Separate styles for easier use in universal apps

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#48]
Borrowing inspiration from [zippyui/react-date-picker](https://github.com/zippyui/react-date-picker) and [JedWatson/react-select](https://github.com/JedWatson/react-select/)...

Split the current CSS styles into 2 categories:
* Structural styles (eg. `position`, `overflow`) should be defined as inline styles.
* Presentation styles (eg. `text-transform`, `color`) should go into a CSS file that must be imported manually

#### react-virtualized with default styles

```js
import { VirtualScroll } from 'react-virtualized'
import 'react-virtualized/theme.css'
```

#### react-virtualized with custom styles

```js
import { VirtualScroll } from 'react-virtualized'
import './react-virtualized-custom-theme.css'
```

This allows users more flexibility to when overriding styles. It also simplifies things WRT universal/isomorphic apps since styles won't be automatically loaded by react-virtualized components (see issue #41 for more context).

**Comment by bvaughn** [comment]
Initial testing seems promising but I've hit a snag with regard to CSS modules. Essentially if a project is using CSS modules then `theme.css` is imported with scrambled class names that don't match the static class names defined in react virtualized.

It seems like [zippyui/react-date-picker](https://github.com/zippyui/react-date-picker/) would have this same problem and so I've [reached out to them](https://github.com/zippyui/react-date-picker/issues/59) to see if they have any thoughts on the general approach.

**Comment by bvaughn** [comment]
I could potentially go the route of using [markdalgleish/react-themeable](https://github.com/markdalgleish/react-themeable) to support either classes or styles and at least give CSS modules users an option.

**Comment by dzannotti** [comment]
https://github.com/martinandert/babel-plugin-css-in-js is also a good source of inspiration. I would +1 to ship separate js + css, to give the final user the freedom of choice over what they want to do with the css

**Comment by bvaughn** [comment]
Hey Daniele! Thanks for chiming in. :)

The more I think about this the more I want to completely get away from external CSS though. The _only_ reason I didn't opt for inline styles a while ago was that I was afraid they would be too limiting for users wanting to override the default appearance (since inline styles always trump CSS-specified styles, unless users go down the hacky route of using `!important`)...

@cesarandreu and I were chatting about this this morning and he pointed out the [react-native Stylesheet](https://facebook.github.io/react-native/docs/stylesheet.html). That gave me the idea to maybe define my presentational styles as a plain JavaScript object and expose them via a static proeprty (eg. `VirtualScroll.defaultStyleSheet `). Then each component could accept a `styleSheet` property that defaulted to its own static `defaultStyleSheet` and users could just supply their own style sheet if they wanted to override the default.

The reason for exporting the static defaults would be...
* It would enable users to easily create new styles based heavily on the initial defaults.
* It would allow users to override styles for _all_ instances of a given component. (Is this too janky?)

**Comment by dzannotti** [comment]
I quite like that idea too sadly opens to auto-prefixing issues.  A theme giving component that passes down the theme as context could also be an idea (and would allow global or local customisation).
Radium does a nice work too (quite similarly to how react-native stylesheet work), sadly from my experience css/inline styles in react ecosystem it's a minefield in which you need to accept loads of (bad) compromises, https://github.com/michelebertoli/css-in-js offers a great comparison between each library.

**Comment by bvaughn** [comment]
You make a solid point about auto-prefixing. Rats... Thanks for the link to css-in-js. That's a great resource to have bookmarked. :)

Separate CSS/JS is actually what I implemented initially (in PR #49) but when testing with the [erikras/react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) boilerplate I realized that CSS modules broke that approach and I needed something a little more flexible.

**Comment by bvaughn** [comment]
Okay so I've resolved this issue in PR #49 but I'm not sure how I feel about the added complexity. I'd love to get a second opinion if any of you feel like taking a look. :)

**Comment by bvaughn** [comment]
Any by "any of you" I mean @oyeanuj, @frankleng, or @dzannotti :)

**Comment by dzannotti** [comment]
I think its great, not sure i understand the thinking behind why stylesheet is state and not props (with default props)

**Comment by bvaughn** [comment]
Thanks man.

It's in `state` because what comes into `props` gets auto-prefixed before being consumed in the `render` function.

**Comment by bvaughn** [comment]
Which... I also felt a little uncertain about. But it seemed like it would make the components easier to work with. :)

**Comment by radubrehar** [comment]
Hi there,

@bvaughn has just requested my opinion on this, see https://github.com/zippyui/react-date-picker/issues/59 so here are my two cents:

For app-specific components, I'm totally in favor of inline styles/css modules & other new/fancy styling solutions. But for reusable components, published with the exact purpose of being used by people in various projects/setups, my opinion is that it's best to use plain-old css for styling (of course, you can/should use autoprefixer and also your css preprocessor of choice). The idea is that when people use your component  in their own projects, they should just need to include a css file. This ensures your component makes no assumption about the host setup where it's being used, and guarantees you a very broad adoption.

Using inline styles limits styling options for component users and adds css priority issues which can be easily avoided with a "boring" CSS approach. I tend to favor BEM for reusable components.

My exported css usually has static css class names: eg: react-date-field__input, etc
A step further is to use some auto-generated class names (see https://github.com/webpack/css-loader/issues/93 issue - solved by [babel-plugin-webpack-loaders](https://github.com/istarkov/babel-plugin-webpack-loaders)), but at every build, your classnames are updated, so users cannot hook into those, so use them sparingly, only for things that should not change. Optionally you could use a mix of auto-generated and static class names.

Conclusion: For now, for all widely-distributed components I stick to plain-old css. Boilerplate projects and react examples **should never use css-modules for loading packages from node_modules**. They should use the simple css loader for loading files from node_modules, and css-loader with css-modules for loading app-specific files.

Hope this helps. It's been my experience in over a year maintaining popular react components.

**Comment by bvaughn** [comment]
Thanks for sharing that info Radu.
