### ISSUE TITLE
Feature Request - Ability to bypass scroll checks

### ISSUE THREAD

**Issue by DerFlatulator** [bvaughn/react-virtualized#488]
## What's your use case?

We are using a custom variant of [perfect-scrollbar](https://github.com/noraesae/perfect-scrollbar) where the scrollbars are rendered outside of the `.ReactVirtualized__Grid` element. It works great, but we are forced to override the overflow properties of the grid in a parent component's `componentDidUpdate`.

```js
element.style.overflowX = element.style.overflowY = 'hidden';
```

I can imagine this thrashing causing a performance issue.

## What interface do you have in mind?

A prop on `List`/`Grid` called `externalScrollbars` of type `boolean`, defaulting to false that would bypass calculating scrollbar height/width, and always set the overflow X and Y properties to `'hidden'`.

https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L533

**Comment by bvaughn** [comment]
Hi @DerFlatulator,

Thank you for the articulate write-up.

Fortunately, this is already supported in a slightly different way, via the `style` property. If you specify an external `style` object, any properties it define will override any default styles used by `Grid`. In your case then you can achieve what you want like so:

```jsx
<Grid
  {...gridProps}
  style={{
    overflowX: 'hidden',
    overflowY: 'hidden'
  }}
/>
```

I am going to close this issue as I don't think any changes are required from me at this time in order to support your use case. I will happily answer any follow-up questions you may have.

**Comment by DerFlatulator** [comment]
Turns out we tried almost exactly that, using `overflow: 'hidden'` instead of overflowX and Y.

Setting the properties explicitly worked. Thanks.

**Comment by bvaughn** [comment]
Glad to hear. You are welcome.

**Comment by leonprou** [comment]
We have some similar issue with the scrollbar.
We want to scroll the table both horizontally and vertically, problem with the vertical scrollbar that it renders at the end of the line. So to see and use the vertical scrollbar we must move the horizontal scrollbar  (shown in the two screenshots).
Horizontal scrolling is working as we want it, is there  a way to make vertical scrollbar to behave the same way?
![scrollbar1](https://cloud.githubusercontent.com/assets/7228844/21294372/81e6854e-c543-11e6-846d-6a95f4c22a4d.png)
![scrollbar2](https://cloud.githubusercontent.com/assets/7228844/21294373/8206e29e-c543-11e6-86fc-af6c72d7931b.png)

**Comment by bvaughn** [comment]
The `Table` component does not support horizontal scrolling. Unfortunately there's no simple way to do this that doesn't result in awkward scrollbars like you describe. Probably best to make your own `Table`-like-abstraction on top of `Grid` _or_ perhaps wait for me to finish the `MultiGrid` component (in progress [here](https://github.com/bvaughn/react-virtualized/pull/499)).

I realize this is probably not the answer you were hoping for. Happy holidays though!
