### ISSUE TITLE
AutoSizer + Table is calculating height: 0

### ISSUE THREAD

**Issue by sontek** [bvaughn/react-virtualized#492]
If I use AutoSizer with a Table the width is calculated to zero and so nothing but the header is rendered.

Here is the code:
http://codepen.io/sontek/pen/yVvdWw?editors=1010

**Comment by bvaughn** [comment]
`AutoSizer` and `Table` work fine together. (See them in action [here](https://bvaughn.github.io/react-virtualized/#/components/Table).) No different than `Grid` or `List`.

In your CodePen, the html, body, and #example elements need to have a `height: 100%;` style set. Without that, their default height will be 0. `AutoSizer` does not stretch its parents; it grows to fill them. 😄

**Comment by Gadeoli** [comment]
> `AutoSizer` and `Table` work fine together. (See them in action [here](https://bvaughn.github.io/react-virtualized/#/components/Table).) No different than `Grid` or `List`.
> 
> In your CodePen, the html, body, and #example elements need to have a `height: 100%;` style set. Without that, their default height will be 0. `AutoSizer` does not stretch its parents; it grows to fill them.

A millions kisses for you. With large lists i couldn't scroll/reorder etc... 
With virtualized activated the list get blank. I saw old comments about height, but only 100% height works. 

```
<ErrorBoundaryUserTenancy>
    <DndProvider backend={dndBackend}>
    <div style={{height: '1000px'}}>
	    <div style={{ height: '100%', overflow: 'auto' }}>
	    <SortableTree
	    	    {* sortable props *}
            />	    
    </DndProvider>
</ErrorBoundaryUserTenancy>
```
