### ISSUE TITLE
Usage with react-test-renderer

### ISSUE THREAD

**Issue by arbesfeld** [bvaughn/react-virtualized#493]
I'm trying to unit test components that render RV components with the `react-test-renderer`, and running into this error: https://github.com/facebook/react/issues/7371.

It seems like an issue with the usage of `findDOMNode`. What is the recommended way to unit test RV components?

**Comment by bvaughn** [comment]
Some components (eg `AutoSizer`, `CellMeasurer`) require a real (or at least reasonable) DOM. You can try to mock things out but I think it would be particularly difficult for `CellMeasurer`

Other components (eg `WindowScroller`, `CellMeasurer`, `Table`) depend on `findDOMNode`. You could try to mock it, as Dan suggests [here](https://github.com/facebook/react/issues/7371#issuecomment-263411431). Or you could just do what I do to test react-virtualized itself (eg [example test](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.test.js)).

Most react-virtualized components don't need a real DOM and so can be tested with Jest. However `AutoSizer`, `CellMeasurer`, and `WindowScroller` are not Jest-compatible b'c they require DOM methods that JSdom doesn't implement. I haven't had much luck mocking them out either; it ends up being too complex and brittle.

**Comment by silvenon** [comment]
A very awkward way to mock AutoSizer. 🤣 

```jsx
// MyComp.js
import React from 'react';
import { Grid } from 'react-virtualized';
let { AutoSizer } = require('react-virtualized');

if (process.env.NODE_ENV === "test") {
  AutoSizer = require('react-virtualized/dist/commonjs/AutoSizer');
}

class MyComp extends React.Component {
  render() {
    return (
      <AutoSizer>
        {({ width, height }) => (
          <Grid
            width={width}
            height={height}
            {/* ... */}
          />
        )}
      </AutoSizer>
    );
  }
}
```

```jsx
// MyComp.test.js
import React from 'react';
import MyComp from './MyComp';

jest.mock('react-virtualized/dist/commonjs/AutoSizer', () => {
  const width = 1024;
  const height = 768;
  return ({ children }) =>
    <div>{children({ width, height })}</div>;
});

// ...
```

**Comment by silvenon** [comment]
Actually, that's completely unnecessary, you can do this instead:

```jsx
<AutoSizer>
  {({ width, height }) => {
    let actualWidth = width;
    let actualHeight = height;
    if (process.env.NODE_ENV === 'test') {
      actualWidth = window.innerWidth;
      actualHeight = window.innerHeight;
    }
    // do something with these dimensions
  }}
</AutoSizer>
```

The contents of AutoSizer will not re-render on resize, but that's E2E territory anyway.

**Comment by izakfilmalter** [comment]
Even easier solution:

```jsx
<AutoSizer>
  {({ width, height }) => (
    <List
      height={height || 100}
      width={width || 100}
    />
  )}
</AutoSizer>
```

**Comment by rickarubio** [comment]
@izakfilmalter nice solution, thanks for sharing!

**Comment by slinto** [comment]
```
<AutoSizerdefaultWidth={100} defaultHeight={100}></AutoSizer>
```

**Comment by thielium** [comment]
Given the above caveats about mocking the DOM, I adapting [the AutoSizer's mock](https://github.com/bvaughn/react-virtualized/blob/9.21.0/source/AutoSizer/AutoSizer.jest.js#L71-L78), though it's a little white-boxy.

```jsx
describe("My Test", () => {
  const originalOffsetHeight = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'offsetHeight');
  const originalOffsetWidth = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'offsetWidth');

  beforeAll(() => {
    Object.defineProperty(HTMLElement.prototype, 'offsetHeight', { configurable: true, value: 50 });
    Object.defineProperty(HTMLElement.prototype, 'offsetWidth', { configurable: true, value: 50 });
  });

  afterAll(() => {
    Object.defineProperty(HTMLElement.prototype, 'offsetHeight', originalOffsetHeight);
    Object.defineProperty(HTMLElement.prototype, 'offsetWidth', originalOffsetWidth);
  });
  // Your tests
})
```

I've noticed some issues that are pretty challenging to reproduce by defaulting the value of `AutoSizer` to the grid (column sizes aren't recalculated though the width has changed). That's the only real reason to mock rather than to default. If I can repro, I'll make a bug.

**Comment by mzedeler** [comment]
This works for me:

```
jest.mock('react-virtualized-auto-sizer', () => ({ children }) => children({ height: 600, width: 600}))
```

**Comment by AnnyCaroline** [comment]
@mzedeler 

I'm having this error

![image](https://user-images.githubusercontent.com/17753656/82673454-480a3c80-9c18-11ea-9e73-13dacc494782.png)

**Comment by lokeshpathrabe** [comment]
@mzedeler Thanks for the workaround. It worked for me. 
@AnnyCaroline I guess you need to find from where you are importing AutoSizer. This is what worked for me: 

`jest.mock('react-virtualized/dist/es/AutoSizer', () => ({ children }) =>
  children({ height: 600, width: 600 }),
);`

**Comment by AnnyCaroline** [comment]
Thanks @lokeshpathrabe . Your code solved the errors but my virtualized list don't seem to render its items.

Instead, I ended up using this code, based on @thielium answer:
```
jest.spyOn(HTMLElement.prototype, 'offsetHeight', 'get').mockReturnValue(1500)
jest.spyOn(HTMLElement.prototype, 'offsetWidth', 'get').mockReturnValue(1500)
```

**Comment by ldavidpace** [comment]
For the next person who struggles to get it importing. I am using typescript and import `Autosizer` like this:

```
import {
    AutoSizer,
} from 'react-virtualized';
``` 

To get the mock to work I had to re-export the rest of react-virtualized like so:

```
jest.mock('react-virtualized', () => {
  const ReactVirtualized = jest.requireActual('react-virtualized');
  return {
    ...ReactVirtualized,
    AutoSizer: ({
      children,
    }) => children({height: 1000, width: 1000}),
  };
});
```

**Comment by IgorKharkiv** [comment]
> For the next person who struggles to get it importing. I am using typescript and import `Autosizer` like this:
> 
> ```
> import {
>     AutoSizer,
> } from 'react-virtualized';
> ```
> 
> To get the mock to work I had to re-export the rest of react-virtualized like so:
> 
> ```
> jest.mock('react-virtualized', () => {
>   const ReactVirtualized = jest.requireActual('react-virtualized');
>   return {
>     ...ReactVirtualized,
>     AutoSizer: ({
>       children,
>     }) => children({height: 1000, width: 1000}),
>   };
> });
> ```

@ldavidpace, thanks a lot! You saved my day.

**Comment by yangfei4913438** [comment]
> For the next person who struggles to get it importing. I am using typescript and import `Autosizer` like this:
> 
> ```
> import {
>     AutoSizer,
> } from 'react-virtualized';
> ```
> 
> To get the mock to work I had to re-export the rest of react-virtualized like so:
> 
> ```
> jest.mock('react-virtualized', () => {
>   const ReactVirtualized = jest.requireActual('react-virtualized');
>   return {
>     ...ReactVirtualized,
>     AutoSizer: ({
>       children,
>     }) => children({height: 1000, width: 1000}),
>   };
> });
> ```

it's ok. thanks very much!

**Comment by yangfei4913438** [comment]
> Thanks @lokeshpathrabe . Your code solved the errors but my virtualized list don't seem to render its items.
> 
> Instead, I ended up using this code, based on @thielium answer:
> 
> ```
> jest.spyOn(HTMLElement.prototype, 'offsetHeight', 'get').mockReturnValue(1500)
> jest.spyOn(HTMLElement.prototype, 'offsetWidth', 'get').mockReturnValue(1500)
> ```

It is ok! thanks a lot!

**Comment by gap777** [comment]
> Thanks @lokeshpathrabe . Your code solved the errors but my virtualized list don't seem to render its items.
> 
> Instead, I ended up using this code, based on @thielium answer:
> 
> ```
> jest.spyOn(HTMLElement.prototype, 'offsetHeight', 'get').mockReturnValue(1500)
> jest.spyOn(HTMLElement.prototype, 'offsetWidth', 'get').mockReturnValue(1500)
> ```

This *kinda* works, but ends up making every HTML element think it's 1500px tall... including Menus (and Popover), which complain bitterly:

> Material-UI: The popover component is too tall.
> Some part of it can not be seen on the screen (748px).
> Please consider adding a `max-height` to improve the user-experience.

**Comment by keeganbrown** [comment]
> > Thanks @lokeshpathrabe . Your code solved the errors but my virtualized list don't seem to render its items.
> > Instead, I ended up using this code, based on @thielium answer:
> > ```
> > jest.spyOn(HTMLElement.prototype, 'offsetHeight', 'get').mockReturnValue(1500)
> > jest.spyOn(HTMLElement.prototype, 'offsetWidth', 'get').mockReturnValue(1500)
> > ```
> 
> This _kinda_ works, but ends up making every HTML element think it's 1500px tall... including Menus (and Popover), which complain bitterly:
> 
> > Material-UI: The popover component is too tall.
> > Some part of it can not be seen on the screen (748px).
> > Please consider adding a `max-height` to improve the user-experience.

In my case 500px for each dimension was unnecessary. I was able to use a value of 2 and it worked just as well: 
```
    jest.spyOn(HTMLElement.prototype, 'offsetHeight', 'get').mockReturnValue(2);
    jest.spyOn(HTMLElement.prototype, 'offsetWidth', 'get').mockReturnValue(2);
```

**Comment by mjangir** [comment]
> @mzedeler Thanks for the workaround. It worked for me.
> @AnnyCaroline I guess you need to find from where you are importing AutoSizer. This is what worked for me:
> 
> `jest.mock('react-virtualized/dist/es/AutoSizer', () => ({ children }) => children({ height: 600, width: 600 }), );`

What if I import it using `import AutoSizer from 'react-virtualized-auto-sizer';`?

**Comment by MoSattler** [comment]
@mjangir see this https://github.com/bvaughn/react-virtualized/issues/493#issuecomment-631093196

**Comment by john-wego** [comment]
> Noting the above caveats about mocking the DOM, I adapted [the AutoSizer's mock](https://github.com/bvaughn/react-virtualized/blob/9.21.0/source/AutoSizer/AutoSizer.jest.js#L71-L78), though it's a little white-boxy.
> 
> ```js
> describe("My Test", () => {
>   const originalOffsetHeight = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'offsetHeight');
>   const originalOffsetWidth = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'offsetWidth');
> 
>   beforeAll(() => {
>     Object.defineProperty(HTMLElement.prototype, 'offsetHeight', { configurable: true, value: 50 });
>     Object.defineProperty(HTMLElement.prototype, 'offsetWidth', { configurable: true, value: 50 });
>   });
> 
>   afterAll(() => {
>     Object.defineProperty(HTMLElement.prototype, 'offsetHeight', originalOffsetHeight);
>     Object.defineProperty(HTMLElement.prototype, 'offsetWidth', originalOffsetWidth);
>   });
>   // Your tests
> })
> ```
> 
> I've noticed some issues that are pretty challenging to reproduce by defaulting the value of `AutoSizer` to the grid (column sizes aren't recalculated though the width has changed). That's the only real reason to mock rather than to default. If I can repro, I'll make a bug.

Thanks for this!!
