### ISSUE TITLE
UNMET PEER DEPENDENCY react-addons-shallow-compare@^0.14.0 || ^15.0.0

### ISSUE THREAD

**Issue by ssuhat** [bvaughn/react-virtualized#494]
I'm using `react ^15.4.1` and this is my first time installing `react-virtualized`.

Upon the installation i got error `UNMET PEER DEPENDENCY react-addons-shallow-compare@^0.14.0 || ^15.0.0`.

Any solution?

**Comment by ssuhat** [comment]
My current solution is install it `react-addons-shallow-compare` manually.

**Comment by bvaughn** [comment]
This is mentioned in the README, [here](https://github.com/bvaughn/react-virtualized#dependencies). :)

If you're using Yarn, I believe it will install peer dependencies for you. Npm will not. This is intentional. 😄
