### ISSUE TITLE
More granular scroll position access

### ISSUE THREAD

**Issue by bigbee** [bvaughn/react-virtualized#496]
Hi,

I am currently working on an application which is, essentially, an ebook reader. I am trying to use the List component for managing the scroll position and amount of pages to render into the DOM.

We have a homebrewed implementation as well, which we are considering moving away from, should virtualized prove to be a good fit for our use-cases. Currently react-virtualized seems _incredibly_ good, but we still have some use cases we need to rope in.

One of our use-cases involve saving and restoring the page the user was last on. In virtualized terms we need to save the row startIndex and the delta between scrollTop and the internal offset from the startIndex row. Currently I have not found any public API exposing the information needed - but can see it is definately present inside the private

`Grid._rowSizeAndPositionManager._cellSizeAndPositionManager._cellSizeAndPositionData[startIndex]`

We do this restoring/maintaining of the relative position on componentDidMount and when rowitems (pages) report new heights (due to resizing of the window).

Would you consider making this information available via a more public API? We are a couple of people working on it, and would also be willing to contribute.

**Comment by bvaughn** [comment]
react-virtualized exposes 2 types of information via callbacks- _visible indices_ via the `onSectionRendered` or `onRowsRendered` (depending on the component) callbacks and _scroll offset_ via the `onScroll` callback. Sounds to me like you really just want to use the 2nd. If you listen for changes to `scrollTop` (using `onScroll`) and store them somewhere, then you can restore them by passing in a `scrollTop` prop to your `List` when it's later shown.

**Comment by bvaughn** [comment]
I _think_ I've sufficiently answered this question and so I'm going to close this issue. If I've misunderstood, we can re-open. I'll also see follow-up questions so feel free to ask any.

**Comment by bigbee** [comment]
Thank you for the swift answer - I did think of 'wrapping' the needed knowledge in a parent container, but am still unsure whether it is enough for our use-case.

The needed measurements are, obviously, also available outside of virtualized since we feed them in order to get the correct heights. I do have a question though:
Can we expect the scrollOffset to never be displaced? As in if we determine index 1 + 2 + 3 has a total height of 3000, setting scrollTop to 3000 will place us right at index 4?


One of our specific cases:
- we are at visible startIndex 10
- index 6 reports a new height and saves it into local state
- we rerender the list with `recomputeRowHeights(6)`

When the above is done, the visible area is displaced by the delta change in height from index 6. This means the user experiences a not-initiated-by-the-user jump in the visible rows/pages.

Currently we fix this by
- we are at visible startIndex 10
- index 6 reports a new height and saves it into local state
- calculate (currently using virtualized private state) the current scroll offset onto the visible startIndex 10.
- rerender the list with `recomputeRowHeights(6)`
- Set a new scrolltop of the new scrolltop for startIndex 10 (gotten from virtualizedprivate state) + the recorded scroll offset.

All of the above logic could probably happen inside react-virtualized - would a stickyScrollPosition attribute doing the above be of use?

**Comment by bvaughn** [comment]
> Can we expect the scrollOffset to never be displaced? As in if we determine index 1 + 2 + 3 has a total height of 3000, setting scrollTop to 3000 will place us right at index 4?

Yes. That's how positioning in `Grid` works. Things that would display (eg parent padding) should be done in the ancestor, not in `Grid` itself. I also recommending using `box-sizing: border-box` to simplify this sort of thing further.

> When the above is done, the visible area is displaced by the delta change in height from index 6. This means the user experiences a not-initiated-by-the-user jump in the visible rows/pages.

If the offsets changed due to resizing, it would result in a new `onScroll` event with the new offsets. You would still be able to track them by listening to that event.
