### ISSUE TITLE
8.8.0-alpha.1 mistakenly published as latest

### ISSUE THREAD

**Issue by billyjanitsch** [bvaughn/react-virtualized#497]
8.8.0-alpha.1, being a prerelease, should be tagged on npm as `react-virtualized@next`. Instead, it was tagged as `latest`.

You can see this by running `npm view react-virtualized`:

```
{ ...
  'dist-tags': {
    latest: '8.8.0-alpha.1',
    beta: '8.5.3-beta'
  },
  ...
}
```

As a result, `npm install react-virtualized` installs the alpha prerelease.

This can be fixed by someone with npm privs running:
```sh
$ npm dist-tag add react-virtualized@8.8.0-alpha.1 next
$ npm dist-tag add react-virtualized@8.7.1 latest
```

**Comment by bvaughn** [comment]
Thanks @billyjanitsch. This has been corrected.
