### ISSUE TITLE
MultiGrid examples are missing

### ISSUE THREAD

**Issue by sontek** [bvaughn/react-virtualized#498]
https://bvaughn.github.io/react-virtualized/#/components/MultiGrid

The links to docs/source are gone but the demo is exactly what I'm trying to do.  Where did these go?

**Comment by bvaughn** [comment]
`MultiGrid` is a new component introduced in the upcoming 8.8 release. It's currently in a preview release (8.8.0-alpha.1) for users to test and give feedback. You can see its branch here: https://github.com/bvaughn/react-virtualized/tree/multi-grid

Once it's done, docs and stuff will be merged into master. Until then, please with the branch and give me feedback. There are a few known issues (that I'll be addressing with an alpha-2 release this evening).
