### ISSUE TITLE
Cannot find renderCellRanges implementation (of Grid) in react-virtualized source code

### ISSUE THREAD

**Issue by make2514** [bvaughn/react-virtualized#508]
Hi guys!
I have seen renderCellRanges  mentioned in releases' changelog and a few issues, but I have not been able to find its implementation or API reference in the document of Grid or in react-virtualized source code. Did it get renamed to cellRangeRenderer?

Any help would be really appreciated! Thank you very much!

**Comment by TkDodo** [comment]
do you mean `defaultCellRangeRenderer` ?
https://github.com/bvaughn/react-virtualized/blob/89de97e7b937275d546eb582a9606986908bbcd2/source/Grid/defaultCellRangeRenderer.js

**Comment by make2514** [comment]
I think  defaultCellRangeRenderer's functionality seems to be the one that I needed. Thank you for your reply!
