### ISSUE TITLE
autoWidth option

### ISSUE THREAD

**Issue by romulof** [bvaughn/react-virtualized#510]
I'm using `WindowScroller` with a `List`, so I'm basically using `AutoSizer` only for calculating a property that will not be used for virtual scrolling.

My suggestion is to create an option, similar to `autoHeight` to allow the grid use style `width: auto`.

In addition to that also little change in the propTypes to prevent duplicate props, since width/height are required but useless when using `autoHeight/autoWidth`:
```es6
static propTypes = {
  height: React.PropTypes.oneOfType([
    React.PropTypes.number,
    React.PropTypes.oneOf(['auto']),
  ]).isRequired,
  width: React.PropTypes.oneOfType([
    React.PropTypes.number,
    React.PropTypes.oneOf(['auto']),
  ]).isRequired,
  ...
};
```

**Comment by bvaughn** [comment]
I don't understand the need for this property. Why can't you just pass an arbitrary `width` and specify a style override (eg `<List style={{ width: 'auto' }} {...props} />`)?.

**Comment by romulof** [comment]
I thought that this style props were for an enclosing `div` 😅

Thanks for the help, but I still think the interface would look a lot better the way I suggested.

**Comment by bvaughn** [comment]
I understand you're POV, but from a maintainer POV, I don't think it's with
adding/supporting additional props for something that's possible to do
already with the style prop. =)

I'm going to pass on this feature for now, given the work around.
