### ISSUE TITLE
Consider using css modules to provide style

### ISSUE THREAD

**Issue by legomind** [bvaughn/react-virtualized#514]
[react-toolbox](https://github.com/react-toolbox) uses css modules to allow theme overrides and css-classname compilation.

I provides a great level of control.

**Comment by bvaughn** [comment]
Thanks for raising the suggestion. I've already considered this some time ago though (see [here](https://github.com/bvaughn/react-virtualized/issues/197) for example) and decided against it. The current approach is as flexible as possible for users who prefer static CSS, inline styles, or CSS modules.

RV aims to avoid all presentational styles anyway, focusing only on functional styles. These don't really lend themselves to needing to be customized in the same way as a UI component library. 

Cheers. :smile:
