### ISSUE TITLE
How can I disable Keyboard Scrolling?

### ISSUE THREAD

**Issue by tUrG0n** [bvaughn/react-virtualized#52]
Each of the rows i'm putting in the VirtualScroll contain a selectable dropdown where the user can select options with his keyboard.
However, pressing the down button, starts to scroll the VirtualScroll List.

Would disabling this scroll fix the issue for me?

**Comment by bvaughn** [comment]
Ah, right. Currently it is not possible to disable keyboard scrolling for a `VirtualScroll` component. I could add such a feature if needed but I don't think you need it in this case. In your keyboard event handler, if you decide that an event has meaning (like an up/down arrow), then you can stop it from bubbling up to `VirtualScroll` like so:

```javascript
event.preventDefault()
event.stopPropagation()
```

**Comment by bvaughn** [comment]
Going to close this as answered for now. Please let me know if you still have questions though :)

**Comment by tUrG0n** [comment]
Yeah no worries abwt closing it :)
I'm not sure though i understand how I would implement the bubbling of the event. I do not currently have an keyboard event handler.
Could u provide a sample case? Pseudo code would do :)

**Comment by bvaughn** [comment]
Ah, I see.

I am suggesting that you could listen for the event you care about (in this case the keyboard event) and prevent it from getting up to the `VirtualScroll` parent if you want to prevent the default behavior.

**Comment by tUrG0n** [comment]
yeah but that's annoying cuz then i'd need to pass it to the [other library](https://github.com/prakhar1989/react-tags) i want to listen to that even.
What if i did a manual disable of that in the react-virtualized source code? Is there a method that if removed would disable the even listening?

**Comment by bvaughn** [comment]
No, you wouldn't. You could just wrap the other library you're using and stop up/down arrow events from bubbling up any further. Something like...

```html
<VirtualScroll>
  <div onKeyDown={yourEventHandler}>
    <TheOtherLibrary/>
  </div>
</div>
```

**Comment by jquense** [comment]
I'm taking a look at using the VirtualScroll component but the lack of bubbling events is a dealbreaker. IN our case I need the key events to propagate to a higher component that manages state like the currently selected cell, (think like excel's keyboard navigation). I appreciate the value that the keyboard scroll adds...is the stopPropagation necessary? PreventDefault should already kill any scroll behavior no?

**Comment by bvaughn** [comment]
Good suggestion, @jquense. I believe you're right. :)

**Comment by bvaughn** [comment]
@jquense check out 4.6.1. I've removed `stopPropagation` and left `preventDefault` as you suggested.
