### ISSUE TITLE
Rendering problem with 40k+ rows

### ISSUE THREAD

**Issue by vysinsky** [bvaughn/react-virtualized#524]
React-virtualized version: 8.8.1

Rows are disappearing when you scroll with 40 000 and more rows. It happens also in your demo: https://bvaughn.github.io/react-virtualized/#/components/Grid. It affects 

I will try to revert to previous versions to identify where it happened.

Edit: version 8.7.1 seems to be ok.

**Comment by bvaughn** [comment]
Interesting. Thank you for reporting this!

I am able to scrollbar-scroll through a couple hundred thousand rows, _but_ wheel-scrolling does indeed break as you mention.

So this worked in 8.7.1 but broken in 8.8.0 huh... that would mean it's probably related to the cached inline style objects.

**Comment by bvaughn** [comment]
If you have any time to dig into it before I do- I would appreciate the hand.

**Comment by bvaughn** [comment]
FYI @vysinsky: This issue has been fixed with the recent 8.9.0 release.

Just verified that [the demo page](https://bvaughn.github.io/react-virtualized/#/components/Grid) works with 500,000 rows.

cc @cheton RE bvaughn/react-virtualized/issues/524

**Comment by vysinsky** [comment]
Awesome. Thank you @bvaughn!

**Comment by cheton** [comment]
Thank you!
