### ISSUE TITLE
InfiniteScroll + cellCache behavior

### ISSUE THREAD

**Issue by nickclaw** [bvaughn/react-virtualized#526]
Smaller bug since it's so easy to get around by customizing the `cellRangeRenderer`, but I noticed that while scrolling a grid that's wrapped in an InfiniteScroll, cells that were not loaded when the scrolling started do not get a chance to update when the data is loaded until after the `scrollingResetTimeInterval` delay.

![grid](https://cloud.githubusercontent.com/assets/2576091/21662970/ff3dde24-d291-11e6-9166-f5da016f7c74.gif)

**Comment by bvaughn** [comment]
Ah, yes. It used to be sufficient just to tell `Grid` (or `List`) to re-render. Now that cells and styles are cached while scrolling that is no longer enough. `InfiniteLoader` now needs to tell `Grid` to clear its cached styles by calling [`recomputeGridSize `](https://github.com/bvaughn/react-virtualized/blob/b5b8e29e1ffd086551c2f2b4718a08c780a0c73b/source/Grid/Grid.js#L261-L279) (or [`recomputeRowHeights `](https://github.com/bvaughn/react-virtualized/blob/b5b8e29e1ffd086551c2f2b4718a08c780a0c73b/source/List/List.js#L117-L123) in the case of `List`).

The code that needs to change is [here](https://github.com/bvaughn/react-virtualized/blob/b5b8e29e1ffd086551c2f2b4718a08c780a0c73b/source/InfiniteLoader/InfiniteLoader.js#L103).

Would you be interested in submitting a PR? 😄  Bonus points if you write a new unit test for this as well.

**Comment by nickclaw** [comment]
Definitely, thanks for pointing me in the right direction.

**Comment by bvaughn** [comment]
Sweet! It's all yours then. 😄  I look forward to reviewing the PR. Thanks!
