### ISSUE TITLE
Consider avoiding timers/promises where possible.

### ISSUE THREAD

**Issue by nickclaw** [bvaughn/react-virtualized#529]
Hey there, great library! I've been having a great time using it so far and I hope I can help contribute some stuff back.

Anyways, I learned to my dismay today that Chrome will [delay timers](https://blog.chromium.org/2015/08/scheduling-timers-to-improve-input.html) that it thinks will take a long time to load.

In my profiling with a very tall Grid, this can cause multi seconds delays.

<img width="928" alt="screen shot 2017-01-05 at 8 05 16 pm" src="https://cloud.githubusercontent.com/assets/2576091/21707221/74ba1f6e-d382-11e6-9e16-3de5a5b786a0.png">

The chunk starting at 5500ms is the promise returned from `loadMoreRows` finally resolving (~2.5s late) and the `_debounceScrollEndedCallback` finally being called (~1.5s late)

I haven't tested this yet, but I think if loadMoreRows was notified via callback instead of Promise it could be force updated _much_ sooner. I'll do some actual testing tomorrow. Thoughts on the feasibility of this?

**Comment by bvaughn** [comment]
> I've been having a great time using it so far and I hope I can help contribute some stuff back.

I hope so too! I'd welcome the help. 😁

Hm... so this is the debounced scroll-stop timeout is what's late? or the load more rows `Promise`? I wouldn't expect the `Promise` to be delayed based on the post you linked to, but it seems like maybe that's what you're suggesting. (Sorry if I'm misunderstanding.)

**Comment by nickclaw** [comment]
Both actually. I'm using bluebird for Promises and I assume it uses setTimeout or setImmediate under the hood but I assume native Promises obey the same timing rules. 

This might actually be less of an issue for me personally if native Promises are exempt from the delays (I'll test that out tomorrow as well).

**Comment by nickclaw** [comment]
Anyways, the terrible delays on setTimeout might cause issues for this library at some point.

It's a terrible hack, but apparently it looks like some people have had luck listening for common global events (mouseover, mousemove, etc..), which are not artificially delayed, to see if the timer _should_ have fired and fire it manually. I'll probably explore that too and see if it alleviates the delay.

**Comment by bvaughn** [comment]
> It's a terrible hack

Ugh ☹️ Sure is! Yuck.

Ok. Keep me posted.

**Comment by nickclaw** [comment]
I've actually had some success with this! I replaced the `setTimeout` and `clearTimeout` calls in the `Grid` with a custom implementation based off of a common `requestAnimationFrame` loop.

With the `scrollingResetTimeInterval` at the default of 150ms, the `_debounceScrollEndedCallback` function was called a whopping ~1.5s after the last scroll event. Using a raf loop it was triggered only ~160ms after the last scroll.

<img width="1029" alt="screen shot 2017-01-06 at 3 10 46 pm" src="https://cloud.githubusercontent.com/assets/2576091/21736100/20e15b0e-d423-11e6-920a-ec5df1542a12.png">

**Comment by bvaughn** [comment]
Which browser version are you using? Is this Chromium?

**Comment by nickclaw** [comment]
All chromium, afaik they're the only ones who do this artificial delay.

**Comment by nickclaw** [comment]
Additionally, by modifying the `loadMoreRows` logic of InfiniteScroll to provide a callback instead of expecting a promise. I was able to trigger updates to the grid without any artificial delay by wrapping the work in a requestAnimationFrame. But that's a little harder to demo until I set up an actual project so you can see for yourself.

**Comment by bvaughn** [comment]
I see!

Whew. I'm pretty nervous about this change. I hope it doesn't make it into Chrome. Seems like it would wreak havoc with a lot of things (eg bluebird, raf polyfills, etc). Yuck. 😦

**Comment by nickclaw** [comment]
If you're interested in chasing down any of these paths. I can open some actual PRs and some example project that you can profile.

**Comment by nickclaw** [comment]
Sorry, I edited my comment. I am using Chrome.

**Comment by bvaughn** [comment]
Oh yuck. So this has already made its way into an actual release huh? I was hoping it was still behind an experiment flag or something.

**Comment by bvaughn** [comment]
I would welcome your help with this - yes! If you're willing.

**Comment by nickclaw** [comment]
Apparently it has already caused lots of problems https://bugs.chromium.org/p/chromium/issues/detail?id=570845

**Comment by bvaughn** [comment]
I was under the assumption that this change recently made its way into Chrome (not as an experimental feature that is). This issue is from 2015. Has it really been around this long?

**Comment by nickclaw** [comment]
Apparently! The article I linked was from August 2015, although it's news to me too.

And take my profiles with a grain of salt, they're taken with most of the profiling checkboxes checked, as well as with the developer build of React and it's many checks/assertions. The performance in my production build is much better, and these delays are pretty rare.

If I can't make a demo that compelling enough in a production style environment it's probably not worth adding more complexity. But I probably wont get to that for a couple days.

**Comment by bvaughn** [comment]
No rush on my side. I'm thrilled to have you help with this. 😄

**Comment by juliojerrick** [comment]
requestAnimationFrame 👍

**Comment by bvaughn** [comment]
I'm cleaning up a couple of tasks this morning that I don't plan to take immediate action on and this is one of them. I don't think this task is unimportant- and I'm still happy to discuss things (on this issue) and to review a PR if you would like to submit one in the future. It just helps me reduce stress by closing things I'm not actively working on. Hope you understand. Cheers!

**Comment by estorski** [comment]
hope this eventually go into the lib, since those ~2 second delays are driving crazy
