### ISSUE TITLE
Allow a 'margin' for rendering elements for VirtualScroll

### ISSUE THREAD

**Issue by aquach** [bvaughn/react-virtualized#53]
I'm using VirtualScroll on mobile and it's awesome! However, because the renderer often can't keep up with my scrolling, I can see elements pop in as I scroll (as opposed to desktop, where the illusion is perfect). Popping isn't the worst thing, but it would be nice to provide a top and bottom "margin" where elements not visible but close to the visible viewport are still rendered to reduce the popping. At a high level, this would provide a balance parameter between the benefits of virtual scroll (hiding what's not visible for speed) and normal scroll (less popping but slower).

I do have a hacky version of this here (https://github.com/pennyapp/react-virtualized/commit/b019a145304b30f74401c9ccebb5bdfb49942e01) that I'm experimenting with for our project, but I doubt I'll take the time to reify it into something better unless there's strong demand.

**Comment by bvaughn** [comment]
Thank you :)

I haven't tested much on the mobile to be honest. I really should.

Let me give it some thought, but I think I could add a property that supports the type of margin you're talking about without too much difficulty. :)

**Comment by bvaughn** [comment]
Check out the new `overscanRowsCount ` property in PR #64

Let me know what you think after you've given it a spin on your mobile device(s).

**Comment by bvaughn** [comment]
Pinging @aquach for feedback on this issue.

**Comment by bvaughn** [comment]
Note that Glorious-G on Reddit point out that this problem only happens for him when using react-virtualized within the iOS webview and not on Safari. This might enable me to reproduce it myself as I have been unable to so far.

**Comment by aquach** [comment]
Oh, right. I discovered this while debugging the issue but forgot to relay that here, sorry! It's definitely an issue when using UIWebView, but there's a new web view for iOS called WKWebView which I haven't tried at all.

Re: overscanRowsCount: Sorry, I'll definitely give it a whirl in the next few days!

**Comment by bvaughn** [comment]
Note that I _think_ this is the same issue reported on #87. My testing seems to suggest that this branch resolves that issue (at least for Firefox 44 which is where I was able to reproduce it).

**Comment by bvaughn** [comment]
FYI in my testing, this update resolves the issue. Since I haven't heard back from @aquach in 10 days I am proceeding with the fix.

**Comment by bvaughn** [comment]
FYI this went out as release 4.10.0
