### ISSUE TITLE
MultiGrid onScroll not work

### ISSUE THREAD

**Issue by Pana** [bvaughn/react-virtualized#534]
Pass an onScroll method to MultiGrid through props, it is not invoked !

**Comment by bvaughn** [comment]
`MultiGrid` currently [uses it's own `onScroll`](https://github.com/bvaughn/react-virtualized/blob/master/source/MultiGrid/MultiGrid.js#L436) but it would be simple enough to support a user-provided one as well. Interested in contributing a PR? 😄

**Comment by Pana** [comment]
Sure !

**Comment by bvaughn** [comment]
Resolved with PR #537
