### ISSUE TITLE
Migrate to Jest (mostly)

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#539]
* Karma + Jasmine + PhantomJS is slow.
* PhantomJS is unstable. (CI has been failing since b5b8e29 due to PhantomJS crashing in the middle of tests; I am unable to reproduce this behavior locally.)
Jasmine

I'd love to migrate the whole project to Jest because it's much faster. Unfortunately a couple of components (`AutoSizer` and `CellMeasurer`) depend on a more robust browser than JSDOM and currently that's all that Jest supports.

So my proposal for now:
* Split NPM `test:unit` script into 2 child tasks: `test:unit:jasmine` and `test:unit:jest`
* Rename all tests that can be run in Jest from `*.test.js` to `*.jest.js`

**Comment by elevine** [comment]
On a related note, this seems to work for anyone who needs to mock out AutoSizer for snapshot testing:

```
// __mocks__/react-virtualized.js
import React from 'react';

const reactVirtualized = jest.genMockFromModule('react-virtualized');

const MockAutoSizer = () => {
  return <div />;
};

reactVirtualized.AutoSizer = MockAutoSizer;

module.exports = reactVirtualized;
```

Then at the top of your test file, do:
`jest.mock('react-virtualized');`

**Comment by bvaughn** [comment]
Thanks for sharing that approach @elevine. 😄  My suggestion for _testing_ RV components in an external project is actually to structure your code like so:

```jsx
/** components/MyAutoSizedComponent.js **/
import React, { Component, PropTypes } from 'react';
import { AutoSizer } from 'react-virtualized';

// Production code uses this for convenience.
export class MyAutoSizedComponent extends Component {
  render () {
    <AutoSizer>
      {({ width, height }) => (
        <MyAutoSizedComponentImpl
          {...this.props}
          height={height}
          width={width}
        />
      )}
    </AutoSizer>
  }
}
export default MyAutoSizedComponent;

// Test code imports this and injects explicit size peops.
export class MyAutoSizedComponentImpl extends Component {
  static propTypes = {
    height: PropTypes.number.isRequired,
    width: PropTypes.number.isRequired
  };

  // Other stuff ...
}
```

And then your test might look like this:
```jsx
/** components/MyAutoSizedComponent.testjs **/
import { MyAutoSizedComponentImpl } from './MyAutoSizedComponent'

// Inject explicit size props for easier testing
<MyAutoSizedComponentImpl
  {...otherProps}
  height={200}
  width={400}
/>
```

**Comment by elevine** [comment]
Thank you @bvaughn ! That totally makes sense.  

One concept I'm struggling with though is how would you apply that approach as you get higher up in your app's hierarchy.  For example, let's say I have a modal with a search input and a list of results that is structured like this:

```
<MySearchModal>
  <MyModal>
    <MySearchComponent>
      <MySearchBox />
      <MySearchResultsList>
        <AutoSizer>
          <List />
        </AutoSizer>
      </MySearchResultsList>
    </MySearchComponent>  
  </MyModal>
</MySearchModal>
```
One thought I have is that you can apply your approach to testing `MySearchResultsList` and use Jest mocking to handle RV components while testing `MySearchModal`.  This way you get coverage for everything.  I'd love to hear your input though.

**Comment by bvaughn** [comment]
You could use Jest to mock the component (swap the auto-sized with manually sized).

I've also, occasionally, used props like `heightForTest` and `widthForTest` and used those _instead of_ the `AutoSizer` values if present. That's kind of a hack though.

**Comment by oliviertassinari** [comment]
@bvaughn Thanks for all your work!

> Jest because it's much faster

Unless I'm missing something, the build now takes around [4 min](https://circleci.com/gh/bvaughn/react-virtualized/1298) while it was taking [3 min](https://circleci.com/gh/bvaughn/react-virtualized/1248) before.
From my experience at @doctolib jest runs about 7 tests/minutes while mocha + karma handles 20 tests/minutes. I don't understand that performance argument, I guess the value come from somewhere else. Please enlighten me 💡 .

**Comment by bvaughn** [comment]
I'd love to learn more about your benchmarking experience with Jest and Mocha. Jest's running of tests in parallel is much faster in my anecdotal experience (within this project).

More to your point though, build times were never a concern for me with this project. Iterating on tests (running in watch mode) was. Jest is _much_ more responsive for the use-case. I'd like to eventually migrate everything to use Jest but...I'm stuck with a few tests in PhantomJS because of lack of certain JSDom layout features.

**Comment by oliviertassinari** [comment]
> I'd love to learn more about

We have around 1800+ tests, we have tried to migrate to jest, but that was way too slow.
We reverted to our Mocha + Karma + PhantomJS test suite.

> Iterating on tests (running in watch mode) was.

I guess that's what I was looking for! We haven't looked at the iterating response time.
That need more investigation from my part. Thanks.

**Comment by bvaughn** [comment]
No problem. That's interesting to learn! I'm not using Mocha so that may
also account for some of the difference in our impressions.

I've been really impressed by Jest's mocking and snapshot functionalities.
I hope to take advantage of both going forward.

Also worth pointing out that PhantomJS has been crashing for me in CI
environment for weeks. Could not reproduce locally. Overall seemed very
flaky. Despite its limitations, JSDom seems more robust.

Given its limitations for that matter- I'm surprised you would see faster
results from Mocha+PhantomJS than from Jest+JSDom just because of the
browsers alone.

Oh well. :grin: Glad you started this conversation either way. It's
interesting.
