### ISSUE TITLE
I need load old data by scroll up

### ISSUE THREAD

**Issue by duminhtam** [bvaughn/react-virtualized#54]
When I use to prepend some old data to the list
`list.unshift('old msg')`
the current position is change. How to keep it at old position?

**Comment by bvaughn** [comment]
This is a little tricky. You could try using a combination of `onRowsRendered` (to monitor which row the user has recently scrolled to) and `scrollToIndex` (to ensure that that row is still visible after you've unshifted. But in general I don't try to support this because a change in `rowsCount` could mean entirely new data.

**Comment by bvaughn** [comment]
I'll leave this issue open for discussion for now. Let me know if that approach has any promising results.

**Comment by duminhtam** [comment]
This will bad on UX, it's not smooth
I recommend we need to have a config to display As A Chat or Message Box (displayBottomUpwards mode) to get the old msg.

**Comment by bvaughn** [comment]
Fair enough. But realistically I don't think I'll have the bandwidth to get to this any time too soon.

I'll leave the ticket open, tagged as "help wanted", in case anyone else feels more inclined to implement this though. :)

**Comment by duminhtam** [comment]
Hi how about we have a config to prepend on the DOM like jQuery prepend a div?

Check this demo:
http://musician-peggy-71735.bitballoon.com/

**Comment by bvaughn** [comment]
I don't see how that would work with a library like react-virtualized. Allowing external code to modify the DOM in any way would make the virtualization too fragile.

**Comment by bvaughn** [comment]
Closing for now due to lack of a response and/or a clear path forward.
