### ISSUE TITLE
Broken link on CellMeasurer docs

### ISSUE THREAD

**Issue by ramarivera** [bvaughn/react-virtualized#542]
Hello, before anything let me congratulate you on the library you have built, it's both amazing and useful, and the perfect companion to almost any react app!!

I had a trouble reading the docs, you see, i'm trying to implement a ReactVirtualized,List with dynamic height, and for that i found you suggested the use of the CellMeasurer component.

In said doc, there's this line:

> `CellMeasurer` is intended for use with `Grid` components but [can be adapted to work with `List` as well](#using-cellmeasurer-with-list).

Alas, the link provided doesn't work :(

**Comment by bvaughn** [comment]
Sorry for the missing doc @ramarivera! I'll fix it. In the meanwhile here's an example of how you could adapt `CellMeasurer` to work with `List`:

```jsx
<CellMeasurer
  cellRenderer={
    // CellMeasurer expects to work with a Grid
    // But your rowRenderer was written for a List
    // The only difference is the named parameter they
    // So map the Grid params (eg rowIndex) to List params (eg index)
    ({ rowIndex, ...rest }) => this._rowRenderer({ index: rowIndex, ...rest })
  }
  columnCount={1}
  rowCount={ROW_COUNT}
  width={width}
>
  {({ getRowHeight, setRef }) => (
    <List
      className={styles.BodyGrid}
      columnCount={10}
      columnWidth={COLUMN_WIDTH}
      height={150}
      overscanColumnCount={0}
      overscanRowCount={0}
      ref={setRef}
      rowCount={ROW_COUNT}
      rowHeight={getRowHeight}
      rowRenderer={this._rowRenderer}
      width={width}
    />
  )}
</CellMeasurer>
```

**Comment by bvaughn** [comment]
Here you are https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md#using-cellmeasurer-with-list
