### ISSUE TITLE
scrollToIndex does not account for horizontal scrollbar height

### ISSUE THREAD

**Issue by implausible** [bvaughn/react-virtualized#543]
When using scrollToIndex with the auto scrollToAlignment, react-virtualized scrolls to the row without checking horizontal scrollbar height. This causes any scrollToIndex events at the bottom of the grid not to fully scroll rows into view as they are obscured by the horizontal scrollbar. This was discovered/tested in chrome.

https://plnkr.co/edit/fe24AK90QAwzXOGA2ZvD?p=preview

**Comment by bvaughn** [comment]
Nice repro Plnkr! Thanks for putting one together that so clearly shows the problem. 😄

**Comment by zsherman** [comment]
+1 also seeing this on rv@next

**Comment by bvaughn** [comment]
Fixed in 9.0.3

**Comment by barbalex** [comment]
I just updated to v9.0.4 and still need to set `overflow-x: hidden` on `.ReactVirtualized__Grid` to see the list row that was scrolled to
