### ISSUE TITLE
Internal grid width / height estimation issue

### ISSUE THREAD

**Issue by kachkaev** [bvaughn/react-virtualized#546]
When `Grid`'s `columnWidth` or `rowHeight` prop is a function, the overall internal width or height is approximated rather than calculated precisely. I'm new to `react-visualized`, but I think I understand the purpose behind this design decision.

A negative side-effect being introduced by such an optimization is in that the scrollbars may start behaving unpredictably. The further a user scrolls, the better the approximation of the actual internal size of the grid, but the bigger the offset between the cursor and the scrollbar. This effect can be easily demonstrated in the [official demo](http://bvaughn.github.io/react-virtualized/#/components/Grid): 

![anim](https://cloud.githubusercontent.com/assets/608862/22111678/14937528-de58-11e6-8e8c-1ff6d17b7fc3.gif)
(the same happens with the vertical scrollbar when row height is set to be dynamic)

The reason why the size estimate is so wrong here is because the second and the third columns are rather wide while hundreds of the remaining ones are relatively narrow. The situation may be opposite, e.g. the grid may contain quite a compact title row and column followed by very large cells with charts and maps. In this case, the scroll bar will end up being behind the cursor, which may cause the cursor to run out of the browser window and thus unexpectedly reset the scroll position.

Although the existing approach to size estimation works well in most of the cases, introducing an option that would calculate all column widths and row heights in a grid feels potentially useful. It can be helpful for the grids that are large in size, but do not contain too many cells, i.e. in situations when calling all possible `getColumnWidth` / `getRowHeight` is very cheap, but the cost of a wrong guess is quite high. Perhaps, configuring _estimate_ vs. _precise_ calculation mode can be done independently for rows and columns.

What do you guys think of this potential extra option?

**Comment by bvaughn** [comment]
The way `Grid` is currently working (shown in your example) is by design. I think it's pretty reasonable to be honest. Deferred measuring is an intentional performance optimization. `Grid` exposes `estimatedColumnSize` and `estimatedRowSize` props which can be used to provide a better default if you know enough about your data to provide this. 😄 

`Grid` does offer an API method `measureAllCells` though which should do what you're asking for, if you think force-measuring all columns/rows is the right way to go for your app.

Cheers!

**Comment by kachkaev** [comment]
Thanks for your advice @bvaughn and for a suggestion to use `measureAllCells`! This looks like something that can help me in dealing with scroll bars.

I quickly checked if ths this method exists for `MultiGrid` and [discovered `measureAllRows` instead of `measureAllCells` there](https://github.com/bvaughn/react-virtualized/blob/8b74fc6c84455c707f6692c1a916cba76c6300d5/source/MultiGrid/MultiGrid.js#L55). Should not it be renamed to match `Gird`'s API? Covering this method with tests could be also useful.

Because `measureAllCells` is a method rather than a prop, it'd be great to see a usage example or at least some hint on where to place it. My current far-from-optimal implementation looks like this:

```js
/*
inside render():
 ...
   <Grid
       ref={(r) => this.grid = r}
...
*/


  componentDidMount() {
    this.grid.measureAllCells();
  }
  componentDidUpdate() {
    this.grid.measureAllCells();
  }
```

**Comment by bvaughn** [comment]
> I quickly checked if ths this method exists for `MultiGrid` and discovered `measureAllRows` instead of `measureAllCells` there.

Whoops, that's surely an oversight. Fixed with 8.11.2.

> Because `measureAllCells` is a method rather than a prop, it'd be great to see a usage example or at least some hint on where to place it.

I have a lot of examples of using refs mixed around the docs. It's hard (and probably not worth it) to try and show every possible example in the docs. Too much maintenance effort. 😄  But sure, something like this:

```jsx
class ForcedMeasureGrid extends React.Component {
  componentDidMount() {
    this._grid.measureAllCells();
  }

  componentWillReceiveProps(nextProps) {
    // Note that your invalidation conditions may be different.
    // The important part is: don't remeasure on every update.
    // That's wasted work.
    // Only remeasure if relevant props have changed.
    if (
      this.props.columnWidth !== nextProps.columnWidth ||
      this.props.rowHeight !== nextProps.rowHeight
    ) {
      // Clear cached sizes and then remeasure.
      this._grid.recomputeGridSize();
      this._grid.measureAllCells();
    }
  }

  render() {
    return (
      <Grid
        ref={
          (ref) => this._grid = ref
        }
        {...this.props}
      />
    )
  }
}
```

**Comment by kachkaev** [comment]
Hmmm... Won't `this._grid.measureAllCells();` always calculate dimensions based on the old props since it's called before `render()`? Or is `this._grid.measureAllCells();` async?

**Comment by bvaughn** [comment]
Yeah, good catch, @kachkaev. I'll update my example to use `componentDidUpdate` instead.
