### ISSUE TITLE
MultiGrid different row heights for top/bottom grids

### ISSUE THREAD

**Issue by natew** [bvaughn/react-virtualized#550]
Feature request: This one is relatively simple, but we'd enjoy being able to make the top grid shorter than the content grid area. Proposed props would either be:

```
styleTopRightGrid={{ rowHeight: 10 }}
```

or 

```
topRightGridConfig={{ rowHeight: 10 }}
```

Or similar, which would allow other config options in the future.

**Comment by codingbull** [comment]
@natew The rowHeight prop of MultiGrid can be a function (which takes a rowIndex), which allows you to do this currently

**Comment by bvaughn** [comment]
Thanks @codingbull for adding this response. Could have sworn I replied to this issue already but clearly I either forgot to hit "send" or...I don't know what.

I'd like to avoid adding a lot of quadrant-specific props to `MultiGrid`. In this case, the way to specify a different size for cells in one of the 4 `Grid`s is as @codingbull says- use a function prop. 😄

**Comment by natew** [comment]
Ah interesting. Any performance implication? Because I do want them both fixed height. I understanding wanting less props, but at least these props are of the same complexity. I'll give it a try right now. Thanks for answers.

**Comment by natew** [comment]
Seems to not be an issue!

**Comment by bvaughn** [comment]
Shouldn't be 😄 `Grid` has a few optimizations in place to limit the perf impact. Thanks for verifying!
