### ISSUE TITLE
Minifications breaks child type check

### ISSUE THREAD

**Issue by leMaik** [bvaughn/react-virtualized#558]
First of all, thank you for this great library, it has improved my page's performance a lot! While pushing my code to our production system, I found this issue. It would be kind if you could provide a fix for this or maybe tell me some work-around.

When I use minification, the function names and thus `Grid` and `MultiGrid` get mangled. Unfortunately, the check inside `ColumnSizer` uses the constructor name to check the type, which of course doesn't work anymore after mangling the name.

Wouldn't it be possible to check if `child instanceof Grid` (after importing the `Grid` class)? This way, the actual name wouldn't matter anymore. Or maybe the check could be skipped at all in production?

Thanks in advance!

**Comment by bvaughn** [comment]
Thanks for the kind words, @leMaik. Sorry to learn of this minification issue.

Check out version 8.11.4 and let me know if this issue still persists for you.

**Comment by leMaik** [comment]
Thanks for the fast response and fix @bvaughn. Works like a charm now. :+1:
