### ISSUE TITLE
missing MultiGrid.forceUpdateGrid()

### ISSUE THREAD

**Issue by oallouch** [bvaughn/react-virtualized#559]
Hi,
I just used this lib for the first time. I needed a MultiGrid...then came love. Great work !
Anyway, a forceUpdateGrid method is missing.
The obvious workaround was to use _bottomLeftGrid, _bottomRightGrid (etc) properties.

Thx in advance,
Olivier from Paris

**Comment by bvaughn** [comment]
This would be a great first contributor issue. You interested? :)

**Comment by bvaughn** [comment]
Fixed via 8482ad8; will release with version 9 (see PR #577). `MultiGrid` now has a method `forceUpdateGrids`
