### ISSUE TITLE
flextable example index column not rendering properly

### ISSUE THREAD

**Issue by olslash** [bvaughn/react-virtualized#56]
I noticed on the example page, the flexTable "index" column is no longer populated. Bisect shows:

f07effd1c08bffa115d870e803cd073c70560498 is the first bad commit
commit f07effd1c08bffa115d870e803cd073c70560498
Author: Brian Vaughn <brian.david.vaughn@gmail.com>
Date:   Sun Jan 10 15:00:49 2016 -0800

    Added InfiniteLoader example and refactored demo app/components to share mock data

 I won't have a chance to look at it closely for a bit but thought i'd put up a flag.

**Comment by bvaughn** [comment]
Haha, nice catch. I remember doing this. Whoops. :D

**Comment by bvaughn** [comment]
Fixed via 5034040
