### ISSUE TITLE
Issue on rowRender's TypeDefinitions?

### ISSUE THREAD

**Issue by kikemx78** [bvaughn/react-virtualized#574]
Had an issue using Typescript while trying to pass style on rowRenderer. TypeDefinitions for rowRenderer may be wrong.

rowRenderer: (info: { index: number, isScrolling: boolean }) => React.ReactNode;

Shouldn't that be: 
rowRenderer: (info: { index: number, isScrolling?: boolean, style: any, key: any }) => React.ReactNode;

**Comment by bvaughn** [comment]
Sounds like an issue that should be filed against `DefinitelyTyped/DefinitelyTyped` (for `@types/react-virtualized`). I don't maintain that project (or use TypeScript). 😄 Sorry!
