### ISSUE TITLE
Grid might call setState in componentWillUpdate

### ISSUE THREAD

**Issue by wasd171** [bvaughn/react-virtualized#585]
Hello!

Grid might call setState during componentWillUpdate lifecycle via _setScrollPosition, which is, according to React documentation, [forbidden](https://facebook.github.io/react/docs/react-component.html#componentwillupdate).

I caught this error when trying to use ScrollSync with 2 active controlling components.

I believe it's a bug, perhaps you wanted to use componentWillReceiveProps instead?

**Comment by bvaughn** [comment]
Good observation @wasd171

**Comment by wasd171** [comment]
I believe this might be an issue for CollectionView too

**Comment by bvaughn** [comment]
Fixed in 38b3a40, released in 9.0.2. Thanks for pointing this out.

**Comment by wasd171** [comment]
Thanks!
