### ISSUE TITLE
Recipe type demos links are broken

### ISSUE THREAD

**Issue by alexandro81** [bvaughn/react-virtualized#586]
Hey,
just a heads up about the hyperlinks that show "recipes" for using react-virtualized components, they're curently broken.

https://rawgit.com/bvaughn/react-virtualized/master/playground/tree.html
https://rawgit.com/bvaughn/react-virtualized/master/playground/grid.html
https://rawgit.com/bvaughn/react-virtualized/master/playground/chat.html
https://rawgit.com/bvaughn/react-virtualized/master/playground/hover.html

**Comment by bvaughn** [comment]
Thanks for pointing this out. They've been updated.
