### ISSUE TITLE
Scrolling not inertial on mobile safari

### ISSUE THREAD

**Issue by aquach** [bvaughn/react-virtualized#59]
When using VirtualScroll in an iOS app, the scrolling is not inertial. I think this can be fixed by adding `-webkit-overflow-scrolling: touch` to the `VirtualScroll` div, but I thought I'd flag it here so you could investigate it on mobile yourself.

**Comment by bvaughn** [comment]
Great suggestion. Thank you! I will try this. :)

**Comment by aquach** [comment]
Sure thing! I'm now looking into issues relating to https://www.tjvantoll.com/2012/08/19/onscroll-event-issues-on-mobile-browsers/ : the onScroll handler will not fire until the very end of the inertial scroll, which means new elements will not be rendered until the scroll stops. I'm looking into how we can fire onScroll events during the middle of the inertial scroll so that this doesn't happen.

**Comment by bvaughn** [comment]
Initial testing seems promising (at least in the simulator).

**Comment by aquach** [comment]
Cool! Regarding my other issue: I've found that scrollTop is not updated until the end of the scroll when using UIWebView (but not Safari), which makes it impossible to update the visible cells during the inertial scroll :(

**Comment by bvaughn** [comment]
@aquach Can you check out the [issues/53-and-59](https://github.com/bvaughn/react-virtualized/tree/issues/53-and-59) branch?

**Comment by bvaughn** [comment]
I think I'm going to proceed with a point release of this feature only and leave #53 as a separate issue until I hear back from you. :)

**Comment by aquach** [comment]
Awesome, thanks! I'll check out the other one.
