### ISSUE TITLE
Setting Grid containerStyle css left property will break ScrollSync

### ISSUE THREAD

**Issue by mauron85** [bvaughn/react-virtualized#598]
Imagine you have defined Grid with **containerStyle** (basically offset 300px)

```
      <Grid
        containerStyle={{ position: 'absolute', left: 300 }}
        onScroll={onScroll}
        ...
      />
```

And you would you to synchronize scrollLeft of that Grid with some other component using ScrollSync HOC. The problem is the onScroll event will cease to be triggered after some srollLeft is reached because of [following line](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L1041).

```
const scrollLeft = Math.min(Math.max(0, totalColumnsWidth - width + scrollbarSize), event.target.scrollLeft)
```

It's not counting the containerStyle offset.

**Comment by bvaughn** [comment]
Could this not be solved by wrapping your `Grid` in a positioned or padded div?

```jsx
<div style={{ position: 'absolute', left: 300 }}>
  <Grid onScroll={onScroll} ... />
</div>
```

**Comment by mauron85** [comment]
Unfortunately not in my case, because scrollbars will then start at offset 300px and I would like them to start at 0. Will add example in a moment.

**Comment by bvaughn** [comment]
Then how about something like this:
```jsx
    <Grid
      height={(width - PADDING_LEFT)}
      style={{
        // Overwrite the box-sizing to content-box to able to use the height without the padding
        boxSizing: 'content-box',
        // Add padding to the offset however much you want
        paddingLeft: PADDING_LEFT
      }}
      containerStyle={{
        // Position items relative tot he inner container
        position: 'relative'
      }} 
      ....
    />
```

**Comment by mauron85** [comment]
Will try that. 
This is the example https://jsfiddle.net/mauron85/Lyc52ac2/1/
As you can see it stop updating scrollLeft after `const scrollLeft = Math.min(Math.max(0, totalColumnsWidth - width + scrollbarSize), event.target.scrollLeft)`

**Comment by mauron85** [comment]
Excellent. That did the job. Thank you once again. ;-)

**Comment by mauron85** [comment]
Just for reference. Fixed example https://jsfiddle.net/mauron85/Lyc52ac2/2/

**Comment by bvaughn** [comment]
Glad to hear. 😄  Thanks for the Plnkr. Nice to see the sorts of things people are building.

**Comment by mauron85** [comment]
Yes, your module, saved my lot of time and also inspired me a lot. Thank you for spending your time on it.
