### ISSUE TITLE
Scrollbar handle is collapsed on Firefox for Ubuntu 16.04

### ISSUE THREAD

**Issue by mauron85** [bvaughn/react-virtualized#599]
Not sure if it's specific to Ubuntu's theme, but scrollbar handle is collapsed and expands to normal height on mouse over.

![peek 2017-02-27 18-28](https://cloud.githubusercontent.com/assets/359450/23372146/b95fa76c-fd1a-11e6-8394-be1cb0c0f3a4.gif)

**Comment by mauron85** [comment]
Seems not only specific to react-virtualized, but generally to any scrollbar.

**Comment by bvaughn** [comment]
This library doesn't set presentational styles (with the exception of minor formatting for `Table` headers) and only then if you manually include a CSS file. 😄
