### ISSUE TITLE
scrollToRow: no visual change if row is visible

### ISSUE THREAD

**Issue by XeniaSiskaki** [bvaughn/react-virtualized#602]
I'm not sure if this is a bug or feature request. Guess it depends on your answer.

I am using the `InfiniteLoader` with a `Table` in order to display some logs. The logs have different levels, like `DEBUG`, `WARNING` etc. For this reason, I store the indices of the logs with a specific level so that the user can easily go through them by clicking on a button, instead of scrolling and looking for them. 

Works nicely, if the index of the next log is not visible, since it's then scroll into view and shown on top of the `Table`. However, if the index the user wants to scroll to is visible, then there is no visual change. I would expect the visual index to be again shown on top as if it wasn't visible.

As I said, not sure if this is a bug. If it's not, please let me know if such feature is feasible to implement.

**Comment by bvaughn** [comment]
Check out the `scrollToAlignment ` prop in the [`Table` docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md). You can see a demo of it [here](https://bvaughn.github.io/connect-tech-2016/#/26/3). Sounds like you want to use `scrollToAlignment="start"`

**Comment by XeniaSiskaki** [comment]
Awesome, thanks!
