### ISSUE TITLE
scrollToRow moves rows to left

### ISSUE THREAD

**Issue by XeniaSiskaki** [bvaughn/react-virtualized#603]
I created the following [Plnkr](https://plnkr.co/a74MCU) to show better what I mean. If you click the scrollToRow button, you can see that all rows are moved a little to the left, so first column get's somewhat hidden. The header seems to be untouched. Not sure if it has to do with style or if it is a bug

**Comment by bvaughn** [comment]
I wonder what's different about your Plnkr than [the `Table` demo](https://bvaughn.github.io/react-virtualized/#/components/Table) which does not demonstrate this behavior...

At a glance, I'm guessing it has to do with commit 08d4227.

Looks like a bug, or at least something I want to look into further.

**Comment by bvaughn** [comment]
Thanks for the bug report. This has been fixed. The fix will go out with the 9.2.0 release in a few moments.
