### ISSUE TITLE
MultiGrid 9.2.1 shifts last header cell with fixedColumns = 0

### ISSUE THREAD

**Issue by aronhelser** [bvaughn/react-virtualized#609]
Hi!
With the fix for headers being offset in 9.2.1, it introduced a bug.

It can be seen in the MultiGrid example, by setting fixedColumnCount to 0, and scrolling all the way to the right. The last header item is rendered above the scrollbar, instead of in the last column.

It is also a bit weird to get the extra cellRenderer call with column 0 and row 1 past the declared size of your table. Not sure what the requirements are to solve the original scroll-offset problem, though.

**Comment by bvaughn** [comment]
Ah! I see what you're describing. Let me push a quick fix. Sorry!

**Comment by bvaughn** [comment]
Fixed in 9.2.2!

**Comment by aronhelser** [comment]
Great, thank you! I tried it and it works for me, too. 

Related, but not the same issue:
If I have a fixed column, should I be seeing a call to cellRenderer in that column with a row index one past the size of the table?

**Comment by bvaughn** [comment]
No. `MultiGrid` [renders a placeholder](https://github.com/bvaughn/react-virtualized/blob/master/source/MultiGrid/MultiGrid.js#L222-L232) for that cell for you.

**Comment by aronhelser** [comment]
Yes, I see that's what's supposed to be happening. I'll see if I can track
down if something is different in my use-case and open another issue if
needed.
