### ISSUE TITLE
MultiGrid has latency aligning grids on Chrome when scrolling with a MacBook trackpad

### ISSUE THREAD

**Issue by paulbrom** [bvaughn/react-virtualized#621]
Hey Brian.  I'm the developer who is trying to use react-virtualized's table with horizontal scrolling.   A few weeks ago I opened this PR, which you closed with the suggestion that we should use MultiGrid to accomplish horizontal scrolling instead:  https://github.com/bvaughn/react-virtualized/pull/604

Unfortunately, we are seeing some rather severe lag when letting MultiGrid coordinate the scrolling between the 2 grids.   The lag is only noticeable when you use a Mac trackpad to perform scrolling (using a mouse to drag the scroll bar does not repro the issue).

This lag can be reproed using the MultiGrid demo if you use Chrome and a MacBook, and use the 'two-finger' drag on the trackpad: https://bvaughn.github.io/react-virtualized/#/components/MultiGrid.   The amount of lag is small on this demo, but with a more complex cell renderer, the lag becomes very noticeable.

Are you aware of this issue?   We would love to switch to MultiGrid and abandon the changes we made to Table to support horizontal scroll, but our QA department won't accept this horizontal scroll lag and we don't repro a similar issue with scroll latency using our changes to Table, because those changes simply transform:translate the header div.

Looking forward to hearing your thoughts.

**Comment by paulbrom** [comment]
After spending hours trying to fix this in both our app and in the react-virtualized project directly, I noticed that the MultiGrid demo did not exhibit this bug in Firefox (Our app only runs in Google Chrome, so I couldn't test it on FF).  I then suspected that maybe, just maybe, this is a bug in Chrome.   Sure enough, when I upgraded Chrome to 57.0.2987.110 (64-bit), the problem went away.

**Comment by bvaughn** [comment]
Thanks for the follow up. 👍

**Comment by paulbrom** [comment]
Hey Brian.  Sorry, I'm not sure what happened when I thought upgrading Chrome fixed this (might have been working too late), but it is indeed still an issue in the latest Chrome.   My analysis of this issue is that we are not getting scroll events at the same rate at which the screen is updating.  This does not repro except on Chrome, and only when using a Mac trackpad.  I'm not sure if this issue can be solved in the MultiGrid code...

**Comment by paulbrom** [comment]
Unfortunately without a fix for this issue we will need to abandon our plan to switch to MultiGrid and go back to doing what we did before, which was in PR 604.

**Comment by paulbrom** [comment]
Ok, i think I have figured out why I thought this was fixed.  The issue seems intermittent, in that if I have multiple tabs open with MultiGrids, the issue goes away.  But with a single tab with a MultiGrid, I repro the issue.   I think there is 99% chance this is a bug in Chrome.

**Comment by bvaughn** [comment]
> My analysis of this issue is that we are not getting scroll events at the same rate at which the screen is updating. This does not repro except on Chrome, and only when using a Mac trackpad. I'm not sure if this issue can be solved in the MultiGrid code...

You probably already know this, but scrolling lives on a separate thread (not the one JS runs in). JavaScript is only notified periodically, so there's some lag that's unavoidable. As long as your JS is fairly quick though this is usually not a problem (although other things going on in the browser can factor in as well).

> if I have multiple tabs open with MultiGrids, the issue goes away. But with a single tab with a MultiGrid, I repro the issue. I think there is 99% chance this is a bug in Chrome.

Can't say I've ever seen something like that, but if you're seeing what you just said- it would sound like a bug outside of react-virtualized yes, in which case there isn't much I could do about it and I would probably end up closing this issue.

**Comment by paulbrom** [comment]
Ok, I dug into this a bit more.  It looks like executing a React update cycle (by calling setState) during a scroll event causes this issue, or at least, the issue can be avoided if a React update cycle is not triggered during a scroll event.

This is why my PR 604 hack didn't suffer from t his sort of issue, because I was directly applying transform: translate to the DOM element in the scroll event, rather than triggering an update cycle.

I've changed my implementation to use two grids, which I am coordinating directly by applying transforms in the onScroll event without a React update.

I would agree, this issue is probably a bug in Chrome, so I'm cool with closing it until Chrome fixes this issue.

**Comment by bvaughn** [comment]
> This is why my PR 604 hack didn't suffer from t his sort of issue, because I was directly applying transform: translate to the DOM element in the scroll event, rather than triggering an update cycle.

Hm, unfortunately this would break virtualization since- without a `render` call- no new cells would be created and eventually the visible ones would scroll off the viewport.

> I've changed my implementation to use two grids, which I am coordinating directly by applying transforms in the onScroll event without a React update.

Could you elaborate? Without "React update"s- how does the windowing algorithm work?

**Comment by paulbrom** [comment]
Right... so for our use cases, we always know which columns we want in advance.  It's only rows which can grow to large numbers.  Therefore it is not necessary for our use cases to generate or remove columns, since we only have a relatively small number of them.  Despite the fact we typically have <10 columns, we still need a x-scrollbar in many of our UI use cases.   This is why Table is perfect for us, except for the fact it will does support x-scroll.

We do the grid alignment in a non-Reacty way, which is admittedly a hack, in that we directly apply a CSS transform to the "header" grid using ReactDOM in response to the scroll event.   We would love to not do that, but it seems to be the only way to avoid a fairly obvious delay in the alignments.  Applying the exact same transforms inside a render() reproduces the issue, but applying it outside the render cycle does not repro it.  It's possible this may be due to some kind of performance issue in our render cycle, but since this issue never reproduces if I use a mouse to drag the scrollbar, where I always see perfect alignment no matter how smoothly or quickly I scroll, whereas there is a quite obvious lag in aligning the tables only if I use the trackpad to scroll, I think there is something else going on here external to our code, and probably external to react-virtualized.  

Anyway, I'm not proud of this hack, but it seems necessary to avoid this very obvious lag when using a trackpad to scroll.   I'm going to go ahead and close this again since we have this workarond, and since I don't think this issue has a fix within react-virtualized.

**Comment by bvaughn** [comment]
Thanks for elaborating 😄
