### ISSUE TITLE
onScroll for List is not called when scrolling is horizontal

### ISSUE THREAD

**Issue by offsky** [bvaughn/react-virtualized#630]
If you are using a List with rows that are wider than the container and then you scroll horizontally to see the end of the row, the List.onScroll callback is not called with the horizontal parameters.  Actually, it's called once when scrollLeft deviates from zero, but then it isn't called again, and it doesn't pass in the horizontal values.

**Comment by bvaughn** [comment]
> If you are using a List with rows that are wider than the container

This isn't really a supported use-case. `List` rows are intended to be the width of the `List`.

**Comment by offsky** [comment]
Ok, but you should know that it works fine if the rows are wider than the list, with the above caveat.  I'll see about switching to a Grid with a single column. That might be what I need.

**Comment by bvaughn** [comment]
Fair enough! 😯  `List` specifically sets its row widths to 100% though so the expectation is that it won't horizontally scroll.

**Comment by offsky** [comment]
I forgot that I ignore the 100% width in my case. Sorry.  I understand now. Will switch to a Grid with a single column.
