### ISSUE TITLE
defaultCellRenderer.js has incorrect param cellDataKey

### ISSUE THREAD

**Issue by r0g83r** [bvaughn/react-virtualized#636]
In react-virtualized/source/Table/defaultCellRenderer.js the param cellDataKey should be dataKey.

```
export default function defaultCellRenderer ({
  cellData,
  cellDataKey, // <---
  columnData,
  rowData,
  rowIndex
}: CellRendererParams): string {
  ...
```

The documentation for Column does have the correct definition:

```
function ({
  cellData: any,
  columnData: any,
  dataKey: string,
  isScrolling: boolean,
  rowData: any,
  rowIndex: number
}): node
```

**Comment by bvaughn** [comment]
Looks like the param is out of sync with the docs, yes. But the default renderer doesn't use the key anyway. It just returns the data, to-string-ed. The docs (the public facing things) are correct which seems the most important. 😄
