### ISSUE TITLE
Improve combination of CellMeasurer and ColumSizer

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#637]
After commit 952ccc6, can I now remove [these](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/defaultCellRangeRenderer.js#L71) [lines](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/defaultCellRangeRenderer.js#L73)?

Because `CellMeasurer` sets "auto" for me using `hasFixedWidth`/`hasFixedHeight`- can I also remove [these](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/defaultCellRangeRenderer.js#L70) [lines](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/defaultCellRangeRenderer.js#L72)

**Comment by cp** [comment]
Hey Brian, following up from Slack this afternoon, here's the Plnkr that demonstrates the issue I was running into. Notice how all the columns are 30px tall, when the second from the last row should be given more height. https://plnkr.co/edit/9Dg1bHi3ehTQxcGY39VC?p=preview

**Comment by bvaughn** [comment]
Unfortunately the idea I had didn't resolve the issue you've reported and I got side-tracked fixing a high-priority regression from 9.4.0 so...this is still an open issue. I'll see if I can look again tomorrow. Not convinced it's a bug in RV yet vs app code. Just haven't spent enough time looking into it.

**Comment by bvaughn** [comment]
Finally found some time to sit down and dig into this issue. It seems like trying the first thing I recommended in chat (storing the computed `columnWidth` and setting that on the inline cell-style) worked for me. You can see the updated Plnkr here: https://plnkr.co/edit/MMGRB2kSPymNAv5sysm9?p=preview

This step is necessary because `CellMeasurer` initializes inline cell-styles to have a width and height of "auto". I considered _not_ doing this, but rather using the `defaultWidth` or `defaultHeight` when `fixedWidth` or `fixedHeight` is true. I chose _not_ to do this though because it would require recreating (or at least re-configuring) the `CellMeasurerCache` each time a `List` or `Table` resized (since the default width/height would need to change to match the exact width/height).

Anyway, not sure if that explanation made much sense but hopefully the updated Plnkr should help unblock you. 😄

**Comment by cp** [comment]
@bvaughn Ah, great. Thanks for the help Brian. Looks like I had some wonky css being applied to the cells causing their heights to be incorrect even with your workaround implemented. All fixed!
