### ISSUE TITLE
Column label, string => node

### ISSUE THREAD

**Issue by hnordt** [bvaughn/react-virtualized#642]
For some columns, I would like to be able to send React nodes, e.g.:

![image](https://cloud.githubusercontent.com/assets/1625399/24675010/f73d8c7a-1953-11e7-9d7d-ac9922834fb6.png)

So I recommend changing `label: PropTypes.string,` to `label: PropTypes.node,` on https://github.com/bvaughn/react-virtualized/blob/master/source/Table/Column.js#L55

**Comment by bvaughn** [comment]
If you'd like to submit a PR for this that:
1. Makes the suggested change
1. Adds at least one Jest test
1. Updates `Column` docs

Then I'd be happy to review it. Otherwise though, I don't plan on making this change. 😄

**Comment by hnordt** [comment]
@bvaughn sure, I'll do that when I have time.

That's good to know you'll accept it if I do. 👍

**Comment by bvaughn** [comment]
Yup! Sounds like a change I'd be happy to accept.

**Comment by bvaughn** [comment]
FYI @hnordt looks like @EnrikoLabriko submitted a PR for this change and it will go out with the next release. 😄

**Comment by hnordt** [comment]
Awesome! Thank you.

I forgot to send the pill request. I'm sorry. 😐
