### ISSUE TITLE
Incorrect prop name spelling

### ISSUE THREAD

**Issue by iamjager** [bvaughn/react-virtualized#645]
Hey @bvaughn (and the rest of contributors), first of all — thanks for all the time you've spent building this great set of tools, really appreciate your work. 👍 

However, it seems that there's a minor issue with InfiniteLoader's `treshold` prop name: it's spelling is incorrect, according to most of the dictionaries (e.g. https://www.merriam-webster.com/dictionary/threshold). Not a major issue, but it constantly gets my IDE's spellchecker started. :)

Thanks again!

**Comment by bvaughn** [comment]
Hm, where is this typo? Searching the project for the text "treshold" doesn't yield any results. And looking at `InfiniteLoader` and its doc page show "threshold" (the correct spelling).

**Comment by bvaughn** [comment]
Whoops, I hit close before I meant to. (I did mean to close the issue, but not before explaining _why_.)

Searching this repo for mention of the term "treshold" (results [here](https://github.com/bvaughn/react-virtualized/search?utf8=%E2%9C%93&q=treshold&type=)) yields no matches. So I assume this bug report is a mistake. 😄 Please point me at the offending code if not!

**Comment by iamjager** [comment]
Oh, I'm so sorry — looks like it was actually my own typo. Such an embarrassment, I've even checked the documentation before posting this. Anyway, thanks for your attention — turns out you were right to hit close right away lol.

**Comment by bvaughn** [comment]
No worries 😄
