### ISSUE TITLE
Is the "Creating An Infinite Loading List" example code still valid?

### ISSUE THREAD

**Issue by romeroadrian** [bvaughn/react-virtualized#654]
I was wondering if this guide (https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md) is still valid, since the `loadMoreRows` in the example points to a redux action creator and the current documentation expects this function to return a promise.

**Comment by bvaughn** [comment]
Docs were written thinking of redux-thunk (so the action-creator would return a promise)

I believe the docs are still valid. If you find a problem with them though feel free to submit a PR. If you have any questions, hop in the Slack and ask :)
