### ISSUE TITLE
the height of the container is not fixed.

### ISSUE THREAD

**Issue by foisonocean** [bvaughn/react-virtualized#656]
There is a live demo: https://codepen.io/hronro/details/bWdjqe
![screenshot](https://cloud.githubusercontent.com/assets/15059605/25082665/d99fe86c-2384-11e7-8b64-9107ece2127f.gif)

**Comment by bvaughn** [comment]
You're using the `autoHeight` parameter in the example you've linked, so the height grows.

You're providing a callback for function height- so an estimated height is used until a row is actually rendered. The default estimated height is much smaller than the example you've linked to so the initial height estimated is much smaller than what it gets refined to as you scroll down. You can use the `estimatedRowSize` prop to specify a more accurate default.
