### ISSUE TITLE
Fast scrolling causes scrollToTop to fire when using WindowScroller

### ISSUE THREAD

**Issue by samouri** [bvaughn/react-virtualized#664]
Hi @bvaughn!

First off, thank you for React-Virtualized. Its such a great library!

Now to the bug I may have found:
When using WindowScroller and quickly scrolling I noticed that very often I will get bounced back to the top of the list. 

Plunker: https://plnkr.co/edit/gj1zaNt8yQXfIH6ahMpU?p=preview

**Comment by bvaughn** [comment]
You're welcome!

Looks like a bug. Thanks for reporting with a repro!

**Comment by leoasis** [comment]
Looks like it bounces back when reaching the end of the list when there's still some scrolling inertia left.

**Comment by samouri** [comment]
Update!

The plunker can be fixed just by adding the `autoHeight` attribute to List!

Closing this now, feel free to reopen if there is more nuance to explore.

**Comment by bvaughn** [comment]
Thanks Jake!
