### ISSUE TITLE
sub-links in docs page don't work on refresh

### ISSUE THREAD

**Issue by djkirby** [bvaughn/react-virtualized#665]
ex:

- Go to https://bvaughn.github.io/react-virtualized
- Click InfiniteLoader tab (https://bvaughn.github.io/react-virtualized/#/components/InfiniteLoader)
- Refresh
- It brings me to https://bvaughn.github.io/react-virtualized/#/components/List

**Comment by bvaughn** [comment]
Thanks for pointing this out. Was probably broken by the recent update from RR 4 beta to final.

Going to tag it as a good first bug in case anyone wants to contribute a fix. 😄

**Comment by joecritch** [comment]
I'd love to take this one! Just going to set up my fork.

**Comment by bvaughn** [comment]
Nice! It's all yours 😁

**Comment by joecritch** [comment]
@bvaughn @djkirby Done! Although not sure if I should contribute again with this number... #666

**Comment by bvaughn** [comment]
Haha! Thanks!
