### ISSUE TITLE
Modifying the height above a WindowScroller causes strange clipping

### ISSUE THREAD

**Issue by samouri** [bvaughn/react-virtualized#671]
When using WindowScroller, a varying height above the WindowScroller causes it to lose its place on the page.   This leads to some interesting clipping/whitespace.

Video: 
![windowscroller-bug](https://cloud.githubusercontent.com/assets/4656974/25672915/949d0c32-3003-11e7-9edf-33f82e0982a1.gif)

Plinker: https://plnkr.co/edit/T3G1OLeu7MRLwHPpvakP?p=preview

I'll take a stab at fixing this and #664 today/tomorrow.

**Comment by bvaughn** [comment]
Hey @samouri,

Thanks for the detailed report and Plnkr. 😄 

Fortunately this is not a bug. If the something on the page above `WindowScroller` changes in a way to impact its size, `WindowScroller` has no way to know about this and so you'll need to manually call the [`updatePosition` method](https://github.com/bvaughn/react-virtualized/blob/master/docs/WindowScroller.md#updateposition).

Here's an updated example with a fix: https://plnkr.co/edit/qt4Vjp?p=preview

**Comment by samouri** [comment]
> This method is automatically triggered when the component mounts as well as when the browser resizes. It should be manually called if the page header (eg any items in the DOM "above" the WindowScroller) resizes or changes.

And its even in the docs!!
Thank you, that looks perfect 👍
