### ISSUE TITLE
Setting scrollLeft on Collection = no change??

### ISSUE THREAD

**Issue by jkringen** [bvaughn/react-virtualized#679]
Hi there,

I'm attempting to use the Collection container to create an IPG (Interactive Programming Guide) similar to what you'd see on DirectTV, etc.

I have a vertical list of channels on the left, and use the scrollTop variable to control jumping to / scrolling between rows. This works very well.

Next was to add the program list. This is a bit more complex as each "channel" is a row, that itself is a Collection of programs that belong in that row. Each program in that row has a completely unique width depending on the length of that program, etc. So the channel list would only ever be vertically scrolled, while the program list needs to scroll both vertical & horizontal.

On the program list, I can set the scrollTop to be in-sync with the channel list's scrollTop variable, and the 2 Collections stay in-sync nicely when vertically scrolling. Excellent.

However, when I try and set scrollLeft on the program list Collection, absolutely nothing changes at all (vertical scrolling with scrollTop still works, but no horizontal scrolling at all). I've tried passing it positive and negative values, and it never "scrolls" the content of the Collection horizontally at all.

The contents of my program list Collection are much wider than the defined width I set on it, so there should be plenty to scroll through. 

Why would scrollTop work, but scrollLeft do nothing?? 

Actually, it sometimes does do something: Sometimes, when I set scrollLeft greater than 1200, suddenly all of the contents completely disappear. They contents stays hidden until I back the scrollLeft variable back down to under 1200. In this case, the contents never "Scroll" at all, they remain in place until scrollLeft exceeds 1200 and then they simply disappear and won't re-appear again until scrollLeft is back under 1200.

???

I can post some sample code if that is necessary, let me know. Thanks for any help on this, this has me completely stuck right now...

-Jason

**Comment by jkringen** [comment]
Just to be clear: the ProgramList component I am using renders a Collection, where the cells being rendered are another component call ProgramRow. Each ProgramRow renders a Collection, where the cells being rendered are divs with text in there. So my ProgramList is a Collection that has other Collections inside of it. I was assuming I would need to do this so that we could scroll vertically & horizontally and have the virtualized component systems on render what is visible, etc. Maybe I shouldn't be nesting them like this? I could have ProgramList render each row and item in each row as a cell, eliminating the need for ProgramRow components? 

FYI, I've also attached a screenshot of my layout for reference. The red highlight shows the ChannelList component, while the purple highlight shows the ProgramList component. 

![ipg-layout](https://cloud.githubusercontent.com/assets/11876681/26071958/8413d6e6-396f-11e7-8101-fa7ddfd598b7.jpg)

**Comment by jkringen** [comment]
Also, I found that if I set scrollLeft on EVERY ProgramRow that I have instead of setting it on the parent ProgramList, that does appear to work. However, it is much slower as it is scrolling every single row at a time vs. just scrolling the parent container, which would be more ideal.

**Comment by bvaughn** [comment]
I'm traveling to Europe today so I'm not really going to be very available to help debug things. You should probably reach out in the Slack channel where others might have ideas.

I do have a quick questions for you though. The above layout looks pretty checkerboard. Why not just use a `Grid` (or maybe multiple `Grid`s if you need to). Why use `Collection`?

**Comment by jkringen** [comment]
Hey there! ah I wasn't aware there was a Slack channel. What is the URL for that Slack team?

I had looked at Grid, but my understanding with that was that it was more like a traditional table with statically sized columns and rows. In this layout, the rows are always the same height, but the "columns" can be literally any width at all.

**Comment by jkringen** [comment]
Screenshot of what I was mentioning above about the "columns" not being consistently sized:
![ipg-layout2](https://cloud.githubusercontent.com/assets/11876681/26072972/fea9e2b2-3972-11e7-8cc4-b32f9e2c6a77.jpg)

**Comment by bvaughn** [comment]
Slack: https://react-virtualized.now.sh/

`Grid` supports varying width columns. The thing it _doesn't_ support is a given column being different widths in different rows. Put another way:
```
# This is supported
| 1A |   1B   |  1C  |
| 2A |   2B   |  2C  |

# This is note supported
|  1A  |   1B   | 1C |
|   2A   |  2B  | 2C |
```

**Comment by bvaughn** [comment]
Gotcha. Looks like that wouldn't work for a single `Grid` - unless the columns are few enough that you don't need to window in that direction?

**Comment by jkringen** [comment]
I'm thinking of re-designing this now to have the Program List render every single unique cell, instead of having it render each row, which then in turn renders its own cells. I'm wondering if having Collection instances inside of a parent Collection instance is causing this. That would mean that ProgramList would render a ton of cells, both vertically and horizontally, but that should be fine since it is virtualized. Hoping that will simplify this. I'll give it a shot here and see how that behaves. Did join the Slack team as well, thanks for letting me know about that! :)

**Comment by jkringen** [comment]
Ok, working much better now. It must have been something related to having nested Collection components. After having my main ProgramList component render all of the row/column cells individually, setting both scrollTop & scrollLeft work as expected. Seems like a possible issue though, that if you have nested Collections that scrolling left/right doesn't seem to work properly.

**Comment by bvaughn** [comment]
I don't see the benefit of nesting `Collection`s to be honest. A `Collection` supports an arbitrary layout so...anything you can accomplish with nested `Collection`s should be achievable with only 1- unless you want independent inner scrolling?

PS Just read your follow-up and it seems like you're having better luck with a single one.

**Comment by bvaughn** [comment]
I don't see the benefit of nesting `Collection`s to be honest. A `Collection` supports an arbitrary layout so...anything you can accomplish with nested `Collection`s should be achievable with only 1- unless you want independent inner scrolling?

PS Just read your follow-up and it seems like you're having better luck with a single one.
