### ISSUE TITLE
AutoSizer grows but doesn't shrink in certain conditions

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#68]
This can be seen on the demo page. :(

I'm not clear of how to fix this. I could use a relatively positioned placeholder (with a height of 0) and a nested, absolutely positioned div that grows to fill the height- but this might cause problems with flex layouts.

For inspiration check out...
* https://github.com/nkbt/react-height/blob/master/src/ReactHeight.js
* https://github.com/nkbt/react-collapse/blob/master/src/Collapse.js

**Comment by bvaughn** [comment]
Might also evaluate using something like this instead of our current resize detection code:
* https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js

**Comment by bvaughn** [comment]
Current element resize code also causes an occasional RTE to be logged in the console:
```
Uncaught TypeError: Cannot read property 'firstElementChild' of undefined
```

**Comment by ndragon75** [comment]
what was the conditon where it didn't shrink ?
