### ISSUE TITLE
Problem with scrollToIndex

### ISSUE THREAD

**Issue by ethankong113** [bvaughn/react-virtualized#683]
I have a problem with scrollToIndex for AutoSizer/List. When you have a very long list, say 100 items, and your screen only shows about 30 of them. You set your scrollToIndex to 50. It seems like the DOM doesn't show the first 50 items. Upon inspecting the Elements page in debugger, the very first item happens to be the 50-th item with position top set to the exact offset. I'm guessing the scroll is not working somehow. And when you scroll the list, it will start from the top. Any idea how to fix it?

**Comment by bvaughn** [comment]
Hi @ethankong113,

Can you share a Plnkr that reproduces the unexpected behavior you're seeing?

**Comment by ethankong113** [comment]
Do you have a boilerplate with it setup? I'm trying to look for one but they are all with dated versions.

**Comment by ethankong113** [comment]
This problem occurs if you give scrollToIndex to the list before the whole list is rendered. I tried to use setTimeout to delay the scroll and it worked, but this is a hack though.

**Comment by bvaughn** [comment]
> Do you have a boilerplate with it setup? I'm trying to look for one but they are all with dated versions

There's a link to a Plnkr templates in the new issue box. You had to erase it when you filed this issue.

**Comment by bvaughn** [comment]
Taken from the contents of a new issue being filed:

---

### Are you reporting a bug or runtime error?
Please include either a failing unit test or a Plnkr demonstrating the bug you are reporting. You can start by forking this Plnk! https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1

You may also find the online Babel tool (https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

---

> When you have a very long list, say 100 items, and your screen only shows about 30 of them. You set your scrollToIndex to 50.

The RV [demo page for `List`](https://bvaughn.github.io/react-virtualized/#/components/List) shows a list with 1,000 items and scroll-to-index works fine.

> It seems like the DOM doesn't show the first 50 items. Upon inspecting the Elements page in debugger, the very first item happens to be the 50-th item with position top set to the exact offset.

Maybe I'm misunderstanding what you're saying? This sounds like the primary purpose of a lib like RV- only render the DOM elements a user can see at any given point in time. If you've scrolled to item 50, then RV only shows items 50 through whatever fills the list. (Check out [this slide](https://bvaughn.github.io/forward-js-2017/#/12/3) for a visual demo of how this works.)

> I'm guessing the scroll is not working somehow. And when you scroll the list, it will start from the top. Any idea how to fix it?

I don't understand what you're saying. Again though, the [demo page for `List`](https://bvaughn.github.io/react-virtualized/#/components/List) works fine for me.

> This problem occurs if you give scrollToIndex to the list before the whole list is rendered in the DOM. I tried to use setTimeout to delay the scroll and it worked, but this is a hack though.

I don't know what you mean by "_before the whole list is rendered in the DOM_" but RV should never render the whole list, only a part of it.

I'm going to closet his issue for now as it isn't very actionable. If after reading the above- there's an actual issue and not a misunderstanding, please clone the Plnkr template I linked to with a repro case. 😄

**Comment by babsonmatt** [comment]
I'm experience a similar issue - if I pass a scrollToIndex to a List containing dynamic height rows with images loading things get a lil screwy trying to scroll up.  I think this might be what @ethankong113 might be referring to - passing scrollToIndex before the images have loaded for example.

**Comment by scf4** [comment]
@babsonmatt I'm sure you have a solution by now, but my own solution is to simply pass a function which calls `scrollToRow` to my images' `onLoad` props, as well as ensuring images have set height and widths wherever possible.
