### ISSUE TITLE
Feature request: Externalize ArrowKeyStepper state

### ISSUE THREAD

**Issue by mking-clari** [bvaughn/react-virtualized#687]
I would like to manage the scrollToColumn/scrollToRow state in Redux. I see that I can set the ArrowKeyStepper's scrollToColumn/scrollToRow via its props. In addition, I would like an onChange function to capture scrollToColumn/scrollToRow changes.

I think [ReactMeasure](https://github.com/souporserious/react-measure) is a good example of a component that provides both options (function child vs onMeasure).

**Comment by bvaughn** [comment]
`ArrowKeyStepper` works with a child function, so you already have access to the scrolled-to row and column.

```jsx
  <ArrowKeyStepper
    columnCount={columnCount}
    rowCount={rowCount}
  >
    {({ onSectionRendered, scrollToColumn, scrollToRow }) => {
      // Do whatever you want with scrollToColumn and scrollToRow here
      return (
        <Grid
          scrollToColumn={scrollToColumn}
          scrollToRow={scrollToRow}
          onSectionRendered={onSectionRendered}
          {...otherGridProps}
        />
      );
    }}
  </ArrowKeyStepper>
```

**Comment by mking-clari** [comment]
If I call a Redux action there, that causes a setState function to be called within render, which results in a React warning. I'll create an example repo to show it

**Comment by mking-clari** [comment]
Here is the issue (let me know if you know a better way to transfer the child args to Redux).

<img width="978" alt="screen shot 2017-05-28 at 10 07 10 am" src="https://cloud.githubusercontent.com/assets/15120143/26530655/dbd4a2a2-438d-11e7-9f16-9198415a9b59.png">

Repo: https://github.com/mking-clari/stepper-warning

**Comment by bvaughn** [comment]
> If I call a Redux action there, that causes a setState function to be called within render, which results in a React warning. I'll create an example repo to show it

You could dispatch your action on the next tick to avoid this.

**Comment by bvaughn** [comment]
Anyway, I'm pretty swamped at the moment so I haven't been taking on feature requests for this lib. Happy to review a PR if you'd like to submit one though. 😄

**Comment by mking-clari** [comment]
I'll close this for now. If I have time I'll open a PR. Thanks for taking the time to review!

**Comment by bvaughn** [comment]
Sounds reasonable. Thanks for understanding!
