### ISSUE TITLE
Solution: Compability with react-custom-scrollbars

### ISSUE THREAD

**Issue by 5angel** [bvaughn/react-virtualized#692]
After a long discussion in #143 I also took a shot at this problem and arrived to the following solution:

```javascript
import React, { Component } from 'react';
import { Scrollbars } from 'react-custom-scrollbars';
import { List } from 'react-virtualized';

const SCROLL_DIRECTION_BACKWARD = -1;
const SCROLL_DIRECTION_FORWARD = 1;
const SCROLL_POSITION_CHANGE_REASON_OBSERVED = 'observed';

const listStyle = {
  overflowX: false,
  overflowY: false,
};

export default class SmartList extends Component {
  _getScrollDirection(scrollTop) {
    const {
      scrollTop: oldScrollTop,
      scrollDirectionVertical,
    } = this.List.Grid.state;

    if (scrollTop !== oldScrollTop) {
      return scrollTop > oldScrollTop ?
        SCROLL_DIRECTION_FORWARD :
        SCROLL_DIRECTION_BACKWARD;
    }

    return scrollDirectionVertical;
  }

  handleScroll = ({ target }) => {
    const {
      scrollTop,
      scrollLeft,
    } = target;

    const { Grid: grid } = this.List;

    grid._debounceScrollEnded();

    const scrollDirectionVertical = this._getScrollDirection(scrollTop);
    const totalColumnsWidth = grid._columnSizeAndPositionManager.getTotalSize();
    const totalRowsHeight = grid._rowSizeAndPositionManager.getTotalSize();

    grid.setState({
      isScrolling: true,
      scrollDirectionVertical,
      scrollTop,
      scrollPositionChangeReason: SCROLL_POSITION_CHANGE_REASON_OBSERVED,
    });

    grid._invokeOnScrollMemoizer({ scrollLeft, scrollTop, totalColumnsWidth, totalRowsHeight });
  };

  List = null;

  render() {
    const { width, height } = this.props;

    return (
      <Scrollbars
        autoHide
        style={{ width, height }}
        onScroll={this.handleScroll}
      >
        <List
          {...this.props}
          ref={instance => (this.List = instance)}
          style={listStyle}
        />
      </Scrollbars>
    );
  }
}
```

You can see that I've pretty much rewritten the `_onScroll` method in https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L1110

The simplest way to make this work will be to add a way to bypass the container node check in `_onScroll`.

@bvaughn what do you think?

**Comment by bvaughn** [comment]
I don't understand this comment on #143:

> @bvaughn can you maybe add a second parameter to _onScroll that let you pass event from another container?

`_onScroll` (and `_invokeOnScrollMemoizer`) are private- not intended to be called by external code.

I guess `Grid` could be refactored to add a new `handleScroll({ scrollLeft, scrollTop })` method that `_onScroll` calls internally but could also be called externally. This would avoid the node-check.

**Comment by bvaughn** [comment]
If you'd like to submit a PR I'll review it.

**Comment by 5angel** [comment]
@bvaughn ah, yes, you're right about that one. brb 👍

**Comment by 5angel** [comment]
@bvaughn I'm a bit concerned that test don't pass even without my changes 🤔

**Comment by bvaughn** [comment]
![screen shot 2017-06-02 at 1 45 36 pm](https://cloud.githubusercontent.com/assets/29597/26744200/c855492e-4799-11e7-8c7e-64564f5f7df3.png)

https://circleci.com/gh/bvaughn/react-virtualized

**Comment by bvaughn** [comment]
Did you `yarn install` or `npm install` ?

**Comment by 5angel** [comment]
This is a fresh system, so I installed latest node an run `npm install`. And it failed too, yeah. Should I try yarn?

**Comment by bvaughn** [comment]
Use `yarn install`

**Comment by 5angel** [comment]
@bvaughn 👌 Yup, it works now, thanks.

**Comment by bvaughn** [comment]
😅  Glad to hear

**Comment by SereznoKot** [comment]
For anyone who struggles to understand `handleScrollEvent` and how it is related to the code snippet above, here how it all looks with the new method. @5angel tons of :+1: to you

```
import React, { Component } from 'react';
import { Scrollbars } from 'react-custom-scrollbars';
import { List } from 'react-virtualized';

const listStyle = {
  overflowX: false,
  overflowY: false,
};

export default class SmartList extends Component {
  handleScroll = ({ target }) => {
    const { scrollTop, scrollLeft } = target;

    const { Grid: grid } = this.List;

    grid.handleScrollEvent({ scrollTop, scrollLeft });
  }

  List = null;

  render() {
    const { width, height } = this.props;

    return (
      <Scrollbars
        autoHide
        style={{ width, height }}
        onScroll={this.handleScroll}
      >
        <List
          {...this.props}
          ref={instance => (this.List = instance)}
          style={listStyle}
        />
      </Scrollbars>
    );
  }
}
```

**Comment by evercool** [comment]
Hi, may I ask for help with solution from @alexpyzhianov? The method handleScrollEvent when fires and updates Grid component causes lags on scrolling. The method handleScrollEvent was bombed by scrolling events so I tried to reduce them by calling it only for scrolls of certain height. It wasnt so laggy, but still each call cause lag on scroll. Next step I tried was to call it in setTimeout to force run it in a new thread (I was desperated) - same result. Any ideas?

**Comment by borovik96** [comment]
@evercool have you found solution?

**Comment by Justin-ZS** [comment]
Maybe another solution, it works for me:
````js
import React from 'react';
import { Scrollbars } from 'react-custom-scrollbars';
import { List, AutoSizer } from 'react-virtualized';

export class DemoList extends React.Component {
  handleScroll = (e) => {
    this.list.Grid._onScroll(e);
  }
  componentDidMount = () => {
    this.list.Grid._scrollingContainer = this.scroll.view;
  }
  render() {
    return (
        <AutoSizer>
          {({ height, width }) => (
            <Scrollbars ref={node => this.scroll = node} onScroll={this.handleScroll} style={{ height, width }}>
              <List
                className="virtual-list"
                {...this.props}
                ref={node => this.list = node}
                height={height}
              />
            </Scrollbars>
          )}
        </AutoSizer>
    );
  }
}
````
don't forget to override the style:
````css
.virtual-list {
    overflow: visible !important;
}
````

**Comment by anstosa** [comment]
@evercool @borovik96 I'm having a similar problem. Trying to use `react-custom-scrollbars` instead of ScrollSync to avoid lag problem but the `onScroll` callback is called for API updates as well so on scroll, the natural event fires, which I use to call `scrollTop(y)` on the partner `Scrollbars` instance, but then it triggers `onScroll` on the other instance and fires it back, etc etc. react-custom-scrollbars does not differentiate API events from user events unfortunately... Any ideas?

**Comment by serle** [comment]
Can this technique be used with the table and would it let the headers be fixed and only scroll the data?

**Comment by bpGusar** [comment]
> Maybe another solution, it works for me:
> 
> ```js
> import React from 'react';
> import { Scrollbars } from 'react-custom-scrollbars';
> import { List, AutoSizer } from 'react-virtualized';
> 
> export class DemoList extends React.Component {
>   handleScroll = (e) => {
>     this.list.Grid._onScroll(e);
>   }
>   componentDidMount = () => {
>     this.list.Grid._scrollingContainer = this.scroll.view;
>   }
>   render() {
>     return (
>         <AutoSizer>
>           {({ height, width }) => (
>             <Scrollbars ref={node => this.scroll = node} onScroll={this.handleScroll} style={{ height, width }}>
>               <List
>                 {...this.props}
>                 style={{ overflowX: 'visible', overflowY: 'visible' }}
>                 ref={node => this.list = node}
>                 height={height}
>               />
>             </Scrollbars>
>           )}
>         </AutoSizer>
>     );
>   }
> }
> ```

where did you get the height and width values?
