### ISSUE TITLE
Wrong height of Masonry on first render

### ISSUE THREAD

**Issue by dev11235** [bvaughn/react-virtualized#695]
Hello!

My issue is related to Masonry layout. I'm trying to make a layout for images using react-virtualized, but get wrong height on first render. Then, when I refresh page everything is OK, but if i press Ctrl+F5 :) I get wrong height again.

Here is plunkr with example:
https://plnkr.co/edit/MqjeGd1cjZLxLNk2IaQL

You can try Stop & Run, F5 & Ctrl+F5 to catch the behaviour I described.

Thank you!

**Comment by bvaughn** [comment]
Hi @dev11235,

`Masonry` does not support async `CellMeasurer` (eg the `measure` param). I know this is probably an easy thing to miss or misunderstand but I tried to mention it in the [`Masonry` docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/Masonry.md#layout-constraints):
> * Cell measurements must be synchronous. Size impacts layout and async measurements would require frequent layout invalidation. Support for this may be added in the future but for now the use of the CellMeasurer render callback's async measure parameter is not supported.

Sorry for the confusion! I'm going to close this issue as working-as-expected for now though.

**Comment by dev11235** [comment]
Thank you very much for this explanation! Sorry for stupid question.

**Comment by bvaughn** [comment]
Not stupid at all. The docs probably don't point this out in a clear enough way. My apologies!
