### ISSUE TITLE
Multigrid falls out of sync with 50k+ items when scrollbars are on

### ISSUE THREAD

**Issue by ghost** [bvaughn/react-virtualized#696]
![image](https://cloud.githubusercontent.com/assets/12092271/26805782/d97a0514-4a0a-11e7-8a61-ded1be0107b5.png)

I'm using MultiGrid to keep a fixed column of row counts. The two grids become less aligned the farther I scroll.
I'm seeing this in chrome, firefox, and safari on OSX

Plunker: https://plnkr.co/edit/J8DcI4uva71mXMLVwPua?p=preview

**Comment by rakeljane** [comment]
@bvaughn I think this was caused by commit bcb3b3f1c354afc96f4f897b025d68f23e4260c5, that extra cell starts messing with the calculations in ScalingCellSizeAndPositionManager at getOffsetAdjustment once the grid gets past the max scroll size, removing the extra cell count fixed the issue for me.

I'd submit a PR but i'm not sure how best to address the issue without bringing back the issue you were fixing with that commit

**Comment by bvaughn** [comment]
Thanks for the update and for looking into the issue! I'd love a PR if you find a fix. 😄

**Comment by nathanpower** [comment]
@rakeljane probably worth checking to see if this has been fixed in 9.9.0 by https://github.com/bvaughn/react-virtualized/pull/727/commits/fe3a3cbf4a539222ac254fa0a32e87def5e7be5e

**Comment by rakeljane** [comment]
@nathanpower I'm still seeing it with the latest, worth a shot though! thanks.

**Comment by nathanpower** [comment]
@rakeljane I had a look at the Plunker, what I am seeing is that there is some loss of sync, but only _while_ scrolling (it corrects itself when scrolling stops) and only when using a track-pad / two-finger scroll. Using an actual mouse scroll-wheel or the scroll-bar seems to work fine. I'm on OSX, tested latest Chrome, Firefox, Safari. Is this what you are seeing, or does it remain out of sync when scrolling stops?

**Comment by rakeljane** [comment]
@nathanpower  it remains out of sync. It's worse the farther down the grid I scroll. Does the plunkr look right to you when you scroll to the bottom of the grid (just clicking and dragging the scrollbar)? I get this:
![image](https://user-images.githubusercontent.com/12092271/28034909-e4c367a0-656f-11e7-93e7-1661a1cebbda.png)

**Comment by nathanpower** [comment]
Weird... I can't seem to reproduce that, no matter how fast/slow I scroll. al

<img width="358" alt="screen shot 2017-07-10 at 20 05 40" src="https://user-images.githubusercontent.com/13329684/28035115-526e0504-65ab-11e7-8aa4-c89608b66139.png">

On the Plunker, does dev tools show the request for `react-virtualized` redirecting to `unpkg.com/react-virtualized@9.9.0/dist/umd`?

**Comment by rakeljane** [comment]
@nathanpower  It looks like the bug only happens if you have scrollbars always showing, changing my OS's setting to "when scrolling" prevents it from happening. 

![image](https://user-images.githubusercontent.com/12092271/28035483-00f01034-6572-11e7-87ce-2d7aa8c7dad1.png)

**Comment by nathanpower** [comment]
@rakeljane sorry, you are right. I should have thought to try that. I can see it now, definitely a different bug to https://github.com/bvaughn/react-virtualized/issues/725

**Comment by rakeljane** [comment]
@nathanpower  No problem, I'm glad we were able to narrow the bug down more. I hadn't thought of the scrollbars settings until now either, I'm going to edit the issue to make that more apparent

**Comment by nathanpower** [comment]
FWIW, I think you could achieve much the same effect with two `<Grid />`s, with both wrapped in a `<ScrollSync />`, and 'overflow: hidden` on the left-most, single-column, grid. I have something similar (but with lists) working well now for 60k+ rows. I guess you may need the MultiGrid for other things though.

**Comment by enriquecaballero** [comment]
Has anyone been able to come up with a fix for this?

**Comment by bvaughn** [comment]
Nope. At least no PRs have been opened about it.

**Comment by enriquecaballero** [comment]
:-(

**Comment by enriquecaballero** [comment]
After scrolling all the way down and begin scrolling upwards, the issue seems to go away. Any ideas?

**Comment by enriquecaballero** [comment]
OK, I was able to fix it by by removing the `additionalRowCount` on the bottom left grid _and_ adding this to the styling of the bottom left grid:
```
this._bottomLeftGridStyle = {
  left: 0,
  overflowX: "hidden",
  overflowY: enableFixedColumnScroll ? "auto" : "hidden",
  position: "absolute",
  ...styleBottomLeftGrid,
  paddingBottom: scrollbarSize()
};
```
`scrollbarSize()` coming from [`dom-helpers`](https://github.com/react-bootstrap/dom-helpers)

**Comment by bvaughn** [comment]
If someone else can confirm, a PR would be great.

**Comment by enriquecaballero** [comment]
As soon as someone confirms, I'll work on submitting the PR.

**Comment by tuchk4** [comment]
Still looking for the solution :(

**Comment by MIKL99999** [comment]
Hi, I think that I fix that bug, also I already create PR with the fix. I hope PR clear enough. So, can you take a look at it?
