### ISSUE TITLE
Upgrade to babel 6 and enable transform-runtime

### ISSUE THREAD

**Issue by cesarandreu** [bvaughn/react-virtualized#7]
See the following: [babel is injecting helpers into each file and bloating my code!](https://github.com/babel/babel-loader#babel-is-injecting-helpers-into-each-file-and-bloating-my-code)

You'll also need to pull in babel-runtime as a dependency.

**Comment by bvaughn** [comment]
Upgrading to babel 6 breaks eslint:
```path/to/file:0:0: Cannot read property 'tokTypes' of undefined```

Looks like this is known: babel/babel-eslint/issues/199, feross/standard/issues/348

**Comment by bvaughn** [comment]
I disabled eslint and went forward with the upgrade in a branch. I may have fat-fingered things somehow- I'm not a Webpack expert by any means- but after adding `transform-runtime` my dist increased from 68 KB to 91 KB.
