### ISSUE TITLE
InfinteLoader Memoization Not Cleared When List Reloaded

### ISSUE THREAD

**Issue by sedouard** [bvaughn/react-virtualized#701]
pInker Demonstration:

https://plnkr.co/edit/bBiaCABcIwxZCavPi727

Say you have a list of 15 items. You set `rowCount` on `InfiniteLoader` to 15 + 1. Upon initial render of the list the list calls `loadMoreRows` once to page in the next set of data where we fetch an additional 15 results.

Not scrolling the list, click the 'Fetch Data' button which will re-render the `InfinteLoader` with a new list of 15 loaded data results. (in our case, this is a filtered set of results, which we reset the user back to a fresh set of results. Meaning they are back at the top of the list). 

Now attempt to scroll to the bottom. Even though the last data result is not loaded, `loadMoreRows` is not called.

Re-do the above reproduction but before clicking 'Fetch Data' scroll just a small amount (enough to trigger an onScroll event but not enough to trigger `loadMoreRows` again. Now click the `Fetch Data` button. `loadMoreRows` is called.

I believe there's something funky going on with the Memoization. The [memoization documentation](https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md#memoization-and-rowcount-changes) says:

>  This can have an unexpected impact though if the underlying collection data changes. In that case it is possible that InfiniteLoader will not know to call loadMoreRows again because- from its point of view- it already made that call for a given row. (React Virtualized components do not know anything about the underlying data after all, only the number of items in the collection.)

> The easiest way to address this is for your application code to call `loadMoreRows` when it detects that the underlying collection may have changed.

This makes sense to be but because this pagination works if you scroll a tiny bit before you hit `Fetch Data` it doesn't make sense why I should call loadMoreRows. In addition, since the new set of data is potentially a *completely* different set of data, caching the last loaded rows and calling `loadMoreRows` to fetch data up to the last loaded row doesn't make sense because we're dealing with a different data set.

Am I correct in assuming that this is not expected behavior?

**Comment by sedouard** [comment]
I should also mention that the Plunker reproduction only works if you make your browser window about 400px tall

**Comment by bvaughn** [comment]
I don't really understand your description of the problem, but have you read the `InfiniteLoader` docs and seen [`resetLoadMoreRowsCache`](https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md#resetloadmorerowscache)?

> **resetLoadMoreRowsCache**
> Reset any cached data about already-loaded rows. This method should be called if any/all loaded data needs to be refetched (eg a filtered list where the search criteria changes).

If the underlying list data has changed then anything `InfiniteLoader` has cached is invalid.

**Comment by sedouard** [comment]
Woops. Clearly I missed that detail. Sorry for the noise!
