### ISSUE TITLE
Any idea how to implement Responsive List?

### ISSUE THREAD

**Issue by rmmjohann** [bvaughn/react-virtualized#702]
At first: Thanks @bvaughn for this awesome lib - even considered if I can use it for select implementing virtualization of select menues and saw that there is already an existing react-select integration. Perfect.

At the moment I'm stuck at implementing a responsive grid - actually a list with rows and four cells in each. Depending on the screen size the count of items should be either for or three.
Without this lib I'll throw the cells into a bootstrap row and assign proper css classes for different screen sizes to the items, but here I have to manually chunk the plain collection into a collection of rows with items.
If there is any way that I don't have to reimplement responsive breakpoint detection in JS to handle chunking into rows containing 3 or 4 items, it will be great.

Another alternative will be to use `Grid`, define a min width for each cell, based on that there will be the amount of items per row and then the actual cell width can be computed so the row gets filled completely.

Am I missing something, that leads to the desired result more elegant/with existing component settings?

**Comment by bvaughn** [comment]
Hey thanks for the kind words. I'm glad you're enjoying the library.

Have you seen this Plunk?
http://plnkr.co/edit/zjCwNeRZ7XtmFp1PDBsc?p=preview

I think an approach like this should work for you.

**Comment by bvaughn** [comment]
I believe this question has been answered so I'm going to close this issue. Feel free to leave a reply if I misunderstood.

**Comment by rmmjohann** [comment]
Thanks for the suggestion.

The goal should be to measure the items, which will be responsive via width.
Based on the width the count of of items per row will be determined.
I tried to use the cell measurer plus cache, but didn't get it work as I don't know the internals of the cell measurer.
Is it able to implement it this way?

**Comment by bvaughn** [comment]
> I tried to use the cell measurer plus cache, but didn't get it work as I don't know the internals of the cell measurer.

The source is in GitHub if you'd like to take a look. `CellMeasurer` isn't actually that big.

If the size of your cells varies (which I didn't know, based on your original description) then you'll have to do some experimentation. I haven't tackled that use-case before.

**Comment by rmmjohann** [comment]
I'll share the result if I have some time to fiddle out a proper solution
