### ISSUE TITLE
Bundle size evtl. too big

### ISSUE THREAD

**Issue by kof** [bvaughn/react-virtualized#714]
I was analyzing my bundle size and it seems to me that rv size is way bigger than it needs to be. 
It is 215 kb (uncompressed) and I am using only List, AutoSizer, CellMeasurer, InfiniteLoader. It is the ES build.

<img width="971" alt="screen shot 2017-06-30 at 4 58 45 pm" src="https://user-images.githubusercontent.com/52824/27741453-6dcc23ce-5db5-11e7-85c0-66242ac26afe.png">

**Comment by bvaughn** [comment]
I'm confused. Can I actually do anything about this from RV's perspective? Other than providing an ES build? Isn't this the responsibility of the bundles/DCE tooling your project uses?

**Comment by kof** [comment]
I am confused either, not sure why this is that way. The tool is webpack 2.6.

**Comment by bvaughn** [comment]
That's fair. 😄

I'm just saying that I think...providing an ES6 modules build is about all I can do from the library point of view. Beyond that it's up to the bundling tool you choose to get the dead code elimination right.

Out of curiosity, how are you requiring/importing react-virtualized components in your project?

**Comment by kof** [comment]
Sure, yeah just realized I am importing like this: `import {List, AutoSizer, CellMeasurer} from 'react-virtualized'` will change that to importing specific files and also chaging analyzer setup to production mode. Will update soon.

**Comment by kof** [comment]
Now minified it looks already much better (its the parsed size). I am still importing the entire library. Will change the imports now.

<img width="1079" alt="screen shot 2017-06-30 at 6 25 50 pm" src="https://user-images.githubusercontent.com/52824/27744871-9a7d468a-5dc1-11e7-9d0a-86b5db738f66.png">

**Comment by kof** [comment]
Much better now
<img width="982" alt="screen shot 2017-06-30 at 6 33 49 pm" src="https://user-images.githubusercontent.com/52824/27745209-c471b4fc-5dc2-11e7-95b6-dc296e018264.png">

Too bad we have rewrite

```js
import {List, AutoSizer, CellMeasurer} from 'react-virtualized'
```
to
```js
import List from 'react-virtualized/dist/es/List'
import AutoSizer from 'react-virtualized/dist/es/AutoSizer'
import CellMeasurer from 'react-virtualized/dist/es/CellMeasurer'
```

But thats def. not your steak.

**Comment by bvaughn** [comment]
Thanks for following up! That's sort of what I expected.

For what it's worth, he ["Getting Started" docs](https://github.com/bvaughn/react-virtualized/#getting-started) mention this:
```js
// But if you only use a few react-virtualized components,
// And you're concerned about increasing your application's bundle size,
// You can directly import only the components you need, like so:
import AutoSizer from 'react-virtualized/dist/commonjs/AutoSizer'
import List from 'react-virtualized/dist/commonjs/List'
```

But I realize that all of the examples show the root-level imports so it's easy to miss. Maybe I should change that.

**Comment by kof** [comment]
Yeah, they are very encouraging to import root-level or at least not to think about it or not to look for alternative imports in the docs.

**Comment by Guria** [comment]
You can try https://github.com/ant-design/babel-plugin-import/ to keep neat imports

**Comment by bvaughn** [comment]
Oh, that's neat.

**Comment by kof** [comment]
Cool!
