### ISSUE TITLE
List/Grid scroll sync fails when using wheel when total height exceeds DEFAULT_MAX_SCROLL_SIZE

### ISSUE THREAD

**Issue by nathanpower** [bvaughn/react-virtualized#725]
It seems that when syncing two or more scrollable lists whose total height exceeds DEFAULT_MAX_SCROLL_SIZE here: https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/utils/ScalingCellSizeAndPositionManager.js#L9, the cell offset calculation does not produce correct results.

Here is a fiddle demonstrating the problem: https://jsfiddle.net/nathanpower/823w11xr/1/
Note that using the scroll-bar is fine, but using a scroll wheel or two-finger trackpad scroll results in messed up rendering of the synced list.

I will try and look into this myself too, just wanted to bring it to your attention. If I get anywhere I will update.

**Comment by nathanpower** [comment]
whoops, incorrect link to the fiddle, fixed now

**Comment by bvaughn** [comment]
Looks like a bug. Would love a PR if you can find the time to look into it.

**Comment by nathanpower** [comment]
Do you think something like this would be appropriate, or would it sacrifice perf elsewhere?

<img width="998" alt="screen shot 2017-07-06 at 22 51 30" src="https://user-images.githubusercontent.com/13329684/27934453-c6966fa4-629d-11e7-9ae1-85e47bddf771.png">

**Comment by nathanpower** [comment]
Basically, if the list/grid which is following the scroll of another list/grid exceeds the height of the browser limit, _and_ it's style is cached, the problem occurs.

**Comment by nathanpower** [comment]
Actually maybe I am overthinking it, and the bug is just an `||` when an `&&` was intended. Will PR that first, as it is the simplest change which fixes this issue.

<img width="719" alt="screen shot 2017-07-07 at 09 42 28" src="https://user-images.githubusercontent.com/13329684/27950373-e631daa0-62f8-11e7-8d0f-09a8cc9b4709.png">

**Comment by bvaughn** [comment]
I think that's correct! Looks like my mistake there. 😄

**Comment by nathanpower** [comment]
Fixed in 9.9.0, many thanks for your efforts @bvaughn, sorry that I didn't get further with the tests there.

**Comment by bvaughn** [comment]
No problem. Thanks for following up about this!

On Jul 10, 2017 1:14 AM, "Nathan Power" <notifications@github.com> wrote:

Closed #725 <https://github.com/bvaughn/react-virtualized/issues/725>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bvaughn/react-virtualized/issues/725#event-1156327944>,
or mute the thread
