### ISSUE TITLE
React component or html inside table or grid cell

### ISSUE THREAD

**Issue by UnderNotic** [bvaughn/react-virtualized#732]
I'm trying to create column with buttons.  
Is this possible if not could there be an option to render react component into cell? If not rendering custom html would be also okay.

**Comment by UnderNotic** [comment]
Okay I sorted it out.  It is possible:
Cell renderer should be cellData => cellData  
And now in cellDataGetter you can return react element.  Is it expected behaviour,  shouldnt this be in docs?

**Comment by bvaughn** [comment]
This is in the docs (see [`cellRenderer` prop for `Column`](https://github.com/bvaughn/react-virtualized/blob/master/docs/Column.md#cellrenderer) and [`cellRenderer` prop for `Grid`](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#cellrenderer)). You can return whatever React element you want from the renderers.

**Comment by oilart** [comment]
Confirming - this doesn't work as you have it in the documentation.

All the columns will be empty div's (as default render with no data):
```
<Column
    key={column.prop}
    label={column.label}
    dataKey={column.prop}
    width={100}
    cellRenderer={() => (<div>custom?</div>)}
/>
```

However, if you use the same logic for `headerRenderer` you will see a custom template in the heading:

```
<Column
    key={column.prop}
    label={column.label}
    dataKey={column.prop}
    width={100}
    headerRenderer={() => (<div>custom indeed</div>)}
/>
```

Haven't look into code/details yet but please consider this as unresolved issue.

**Comment by oilart** [comment]
Figured that out - basically once you have a custom `rowRenderer` it should return a `column` from `data.columns`prop as it is (node).

**Comment by bvaughn** [comment]
Glad you figured it out 😄

**Comment by jdelafon** [comment]
I still don't understand it after reading through the docs and this post multiple times. Can somebody give an example of how one can render a React component in a cell? 
It should probably be more straightforward (i.e. not cost several hours trying); I'd be happy to improve the docs once I understand it.

**Comment by SocialHulkHogan** [comment]
Still a bit confused about this. I tried both UnderNotic and jdelafon's solutions and I can't seem to render a component (in my case a checkbox) inside the Table. Can I see an example of how this should be done? With correct syntax. In my humble opinion, examples of correct use (of things like cell renderer) are scarce within the documentation. I wouldn't really consider this resolved until the correct way to do this is clearer.

**Comment by maziey93** [comment]
Hi @bvaughn just said to mention, returning a react element in the column `cellRenderer` prop like in the docs [here](https://github.com/bvaughn/react-virtualized/blob/master/docs/Column.md#cellrenderer) and [here](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#cellrenderer), but it doesn't work I get this error

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Grid`.
```
