### ISSUE TITLE
Rendering issue in Firefox

### ISSUE THREAD

**Issue by sdanishevsky** [bvaughn/react-virtualized#733]
In Firefox when you decrease the number of columns in the Grid it doesn't render some of the columns that were off screen.

Steps to reproduce:
1. Open Grid example - https://bvaughn.github.io/react-virtualized/#/components/Grid
2. Change the number of columns to 25 and the number of rows to 5.
3. Scroll horizontally to the very end of the grid, where the first columns are now off screen.
![screen shot 2017-07-12 at 3 30 51 pm](https://user-images.githubusercontent.com/1136974/28140851-49a47724-6717-11e7-847f-357deb4472f1.png)
4. Change the number of columns to 20.

As a result, the Grid is autoscrolled and the columns that have been off screen have disappeared. 
![screen shot 2017-07-12 at 3 31 14 pm](https://user-images.githubusercontent.com/1136974/28140864-5906e68e-6717-11e7-99f5-4c086428a9aa.png)

If you manually scroll or change the number of columns again those missing columns get re-rendered correctly.

Log of the information passed to `onSectionRendered` callback also shows the difference between Chrome and Firefox. In Chrome `columnStartIndex` becomes 0, in Firefox it remains the same like it's not being recalculated.

Tried it with Firefox 54.0.1 (64-bit) on Mac and Firefox 54.0 (32-bit) on Windows 10.

**Comment by ericchernuka** [comment]
@adilbek Did you find a workaround for this?

**Comment by bvaughn** [comment]
I am not able to reproduce this with Firefox 56. Can you confirm if this still happens with react-virtualized 9.11.0 (aka on the live demo site)?
