### ISSUE TITLE
HoC defaultRowRenderer logs warning to console

### ISSUE THREAD

**Issue by arfarf89** [bvaughn/react-virtualized#746]
I am HoC decorating defaultRowRenderer to custom style special rows.

``` js
import { defaultTableRowRenderer } from 'react-virtualized';

const RowRenderer = RowHoC(defaultTableRowRenderer);

render() {
  ...
  <AutoSizer>
    {({ height, width }) =>
      <Table
        ...
        rowRenderer={RowRenderer}
        ...
      </Table>}
  </AutoSizer>
    ...
}
```
```js
function RowHoc(RowRenderer) {
  const getRowClass = (className, row) => {
    if (row.isSpecial) {
      return classnames(className, 'special');
    } else {
      return classnames(className, 'default');
    }
  };
  function TableRow(props) {
    return (
      <RowRenderer
        {...props}
        className={getRowClass(props.className, props.rowData)}
      />
    );
  }

  return TableRow;
}
```

It works as expected(highlighting special rows), except logging out a warning:

```
Warning: defaultRowRenderer: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
   __stack_frame_overlay_proxy_console__   proxyConsole.js:56
   printWarning                                  warning.js:36
   warning                                          warning.js:60
   warnAboutAccessingKey              ReactElement.js:60
   defaultRowRenderer                     defaultRowRenderer.js:13
   (anonymous)                                 ReactCompositeComponent.js:305
   measureLifeCyclePerf                  ReactCompositeComponent.js:75
   ...
```
The link in the warning redirects to [here](https://facebook.github.io/react/warnings/special-props.html) explaining that `key` and `ref` are not passed to components. The line in question is in defaultRowRenderer. 

``` js
export default function defaultRowRenderer(_ref) {
  var className = _ref.className,
    columns = _ref.columns,
    index = _ref.index,
    isScrolling = _ref.isScrolling,
    key = _ref.key, // <---------------------- defaultRowRenderer.js:13
    onRowClick = _ref.onRowClick,
    onRowDoubleClick = _ref.onRowDoubleClick,
```

Not referencing the key in props directly by replacing `_ref.key` with `_extends({}, _ref).key`  gets rid of the warning. There is nothing I can do on my end, since I can't pass key as a prop from my function wrapping the defaultRowRenderer for the same reason. Since this is the [recommended way to decorate the default implementation](https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md#rowrenderer), I think the warning should be handled in some other way.

**Comment by TrySound** [comment]
I guess, it's because all default components are not actually components. They are inlined into dom by just calling that functions. This let's to not increase count of wrapping elements, but makes it harder to use as components. @bvaughn fiber introduces arrays in components, so can this be solved (using as components) after React16 release?

**Comment by bvaughn** [comment]
@TrySound I don't think this is really related to Fiber's support for returning arrays. I think it's actually b'c @arfarf89 is treating the default render as a _component_ (with a HOC) rather than as a _function_ (with a HOF). Try this instead?
```js
function RowHof(rowRendererFn) {
  function tableRowFn(props) {
    return rowRendererFn({
      ...props,
      className: 'foobar'
    });
  }

  return tableRowFn;
}
const RowRenderer = RowHof(defaultRowRenderer);
```

That being said, I don't see a key warning from doing what @arfarf89 describes. Can you provide a Plnkr repro?

I'm going to close this for now because I don't think there's any action required from us. Let me know if I'm wrong, @arfarf89.

**Comment by arfarf89** [comment]
Thanks for the reply! You were right, I changed the default renderer to be consumed as a function and the warning went away. (I didn't understand @TrySound 's reply, but thanks anyway) Having above example in a documentation would be awesome for people like me. Or, they can just search the issues to get here I guess.
