### ISSUE TITLE
Padding-bottom percentage breaking CellMeasurer

### ISSUE THREAD

**Issue by atainter** [bvaughn/react-virtualized#755]
Hi, 
I'm trying to make a component which maintains aspect ratio in a grid by using padding-bottom as a percentage of height.

For example, I can produce a component with a 1:1 aspect ratio with the following css:

```
.1-1-ratio {
width: 100%;
padding-bottom: 100%;
}
```

It seems like CellMeasurer is not properly calculating the height for a component which uses padding as a percentage of width. I get the following result in a grid using the CellMeasurer:

<img width="807" alt="screen shot 2017-07-24 at 4 01 34 pm" src="https://user-images.githubusercontent.com/7866859/28548575-82f876f8-7089-11e7-8a86-ac9ef86e4629.png">

The numbered cells have a static height of 200px, but the white boxes use `padding-bottom: 100%` and should maintain a 1:1 aspect ratio.

**Comment by bvaughn** [comment]
Please provide a repro (Plnkr or similar).

**Comment by atainter** [comment]
@bvaughn you'll need to scroll down on the grid to see the issue.

https://plnkr.co/edit/adEWppc52dJCSuDVvAmt

**Comment by bvaughn** [comment]
Percentage-based calculations don't seem to work in this case. Adding a `console.log` call with the measurements shows that cells are being are reporting a width:2 and height:4.

I don't think this is really a use-case that I'm interested in trying to support with react-virtualized. Measurements need to be actual numbers. If you want to use a percentage-based thing, wrap it up as a HoC/HoF or something that takes in an actual width and does the calculations.
