### ISSUE TITLE
TS typings are incomplete

### ISSUE THREAD

**Issue by wasd171** [bvaughn/react-virtualized#756]
Hello.

The docs clearly state that

> Pass-thru props
>
> The shallowCompare method will detect changes to any props, even if they aren't declared as propTypes. This means you can also pass through additional properties that affect cell rendering to ensure changes are detected. For example, if you're using List to render a list of items that may be re-sorted after initial render- react-virtualized would not normally detect the sort operation because none of the properties it deals with change. However you can pass through the additional sort property to trigger a re-render. For example:
>
> ```
> <List
>   {...listProps}
>   sortBy={sortBy}
> />
> ```

Unfortunately provided TS types do not allow arbitrary props. I suggest the typings should include additional definition for props:
```
[key: string]: any
```

**Comment by bvaughn** [comment]
Hey @wasd171,

I don't have anything to do with the TS typings. You'll need to open an issue (or a pull request) over at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). The react-virtualized TypeScripted definitions are [there](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-virtualized).

**Comment by QuantumInformation** [comment]
So glad to hear there are types.
