### ISSUE TITLE
Event touchstart has (randomly) incorrect target during scroll on mobile

### ISSUE THREAD

**Issue by neooleg** [bvaughn/react-virtualized#766]
## STR
1. Use [List example](https://bvaughn.github.io/react-virtualized/#/components/List)
1. Toggle page to device emulation
1. Handle touchstart event and check e.target in JS Console
1. Scroll the list using left click (i.e. do not use scroll wheel) to simulate touchstart event

## AR
**Randomly** (the regularity is not revealed) target _contains list instead of item_!

## ER
Item should be always a target for touchstart, otherwise, it leads to issue build on top of react-virtualized, e.g. drag & drop, auto scroll, etc.

## Issue Demonstration

[GIF file (26 Mb)](https://gifyu.com/image/zsZ5)

## Investigation Notes
- Issue reproduces only if vertical scroll happens
- If you _wait a couple of seconds__ before scrolling again -- _the list element will never be in e.target_, i.e. issue will not reproduce

**Comment by bvaughn** [comment]
I don't understand how this is an issue for react-virtualized in any way. This library doesn't dispatch any events. It just generates a DOM structure more efficiently.

Is there any chance you're confusing `target` and `currentTarget`?

Unless you can help me understand the actionable item here, I'm going to have to close this.

**Comment by neooleg** [comment]
It's need to be investigated on react-virtualized level because a [simple scrollable divs on Plunker](https://run.plnkr.co/1sCz8bU7dTzkaV8a/) doesn't have this issue:

<img width="354" alt="screen shot 2017-07-28 at 1 39 18 pm" src="https://user-images.githubusercontent.com/1647049/28714252-4c7f7382-739b-11e7-8933-b72e3378a8ef.png">

There are _possible_ reasons:
- Buffering somehow affects scroll
- DOM elements in react-virtualized rendered in some special way

BTW, it reproduces on any found browser (Safari, Android Browser, Samsung Internet, Chrome, etc.), so it seems it's not a browsers bugs it looks like an expected behavior for particular solution.

**Comment by bvaughn** [comment]
@neooleg By default, RV disabled `pointer-events` while scrolling (see #724, #697, #564). All windowing libs (at least all I know of) do this. You can _prevent_ this behavior by passing in your own `containerStyle` that sets `pointer-events: "auto"` (and overrides RV's default). I believe this is why the `target` is different from some of the touch events.

I'm going to close this issue because I don't think there's anything RV can/should do differently here.

**Comment by neooleg** [comment]
Thx, it helped with Safari on iOS, but has another issue on Chrome (Android).
