### ISSUE TITLE
Scrolling in a Grid makes cells disappear

### ISSUE THREAD

**Issue by P-Henoch** [bvaughn/react-virtualized#767]
Hi! I've noticed a strange comportment when scrolling in a Grid.

Plnkr : https://plnkr.co/edit/um644ddN6CujTZR4DbYW?p=preview

First scroll down, then scroll up. When scrolling up, the lasts cells will disappear. When scrolling down, cells will disappear one by one.

**Comment by bvaughn** [comment]
You're not adding the `style` attribute 😄 
![screen shot 2017-07-28 at 8 03 19 am](https://user-images.githubusercontent.com/29597/28723315-3e10c43e-736b-11e7-94a8-6c521dced8b2.png)

In fact, you aren't using any of the params passed to the cell renderer. Read the docs 😁 

https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#cellrenderer

**Comment by mastrobardo** [comment]
actually i followed the link and i still have the same problem. Not sure if worth investigating, will add here my code just in case 
```
const Cell = ({ columnIndex, rowIndex, style }) => {
  const props = data[columnIndex];
  
  return (<div className='gameItem' style={style}>
            <span>{props.id}</span>
            <span>{props.name}</span>
            <span>{props.provider}</span>
            <span>{props.gameType}</span>
            {props.tags?.map((ele:string, idx:number) =>  <span key={idx}>{ele}</span>)}
        </div>)
  }
```
