### ISSUE TITLE
Wizard is completely broken (no errors)

### ISSUE THREAD

**Issue by 0xCMP** [bvaughn/react-virtualized#769]
When you visit the wizard I expected that checking the boxes would do something and I'd have an idea on which components to use for a full page, infinite scrolling, list of items with an unknown height.

This image shows that no matter what I do nothing changes. I checked the console and saw zero errors. I made sure all my content blockers were not affecting some possible `data.json` or similar that might have powered it and saw nothing was being blocked at all.
![2017-07-31-react-virtualize-wizard-broken](https://user-images.githubusercontent.com/505649/28794321-edacec84-7603-11e7-8ffb-81c78724fa02.gif)

# Are you asking a question?
No

# Are you reporting a bug or runtime error?
Yes. There were no errors

# Are you making a feature request?
No.

**Comment by iamrobinpham** [comment]
https://github.com/JedWatson/react-codemirror/issues/106

**Comment by bvaughn** [comment]
PRs welcome 😄
