### ISSUE TITLE
ArrowKeyStepper looses focus in list when item is virtualized

### ISSUE THREAD

**Issue by inssein** [bvaughn/react-virtualized#776]
All my list items have `<a>` tags that on click, select the list item.  When the item then gets virualized, the list looses focus, and the body takes over.

The simple fix was to change the `<a>` to `<div>`.

I have been dealing with this issue for a while, and finally figured it out. It's not technically a bug in the implementation, but perhaps something we can try and avoid, or at least inform users.

**Comment by bvaughn** [comment]
> All my list items have <a> tags that on click, select the list item. When the item then gets virualized, the list looses focus, and the body takes over.

I think what you're saying is that when an element is _removed_ from the page (b'c it's scrolled out of view) then the browser blurs it? If so, I don't see how the element type (`<a>`, `<div>`, etc) would change that behavior.

I'm not sure what RV can do about this to be honest. I'm happy to review PR submissions if you have suggestions for how to mention this in the docs.

**Comment by inssein** [comment]
Just to clarify a little more on the difference between an `<a>` and a `<div>`: When using a hyper link, when a list item is clicked, it becomes the active element on the page (focused element). This is not the same for `<div>` and presumably other block level elements.

As for what RV can do about this, I am not too sure either. Perhaps the ArrowKeyStopper could pass through the onclick somehow such that it returns focus back to the wrapping element of the HOC.

**Comment by bvaughn** [comment]
Understood. It's only an issue for elements that are focusable.

I don't think the `onClick` approach would be a good path to take; what about `<input>` elements?. I also think RV should be agnostic about its contents.

**Comment by bvaughn** [comment]
I don't think this is an issue I can take action on- (at least not without a proposal that I haven't thought of)- so I'm going to close it. We can keep talking here though and if something actionable comes up I will re-open.

**Comment by MarkBarbieri** [comment]
I had this same issue and fixed it nearly the same way.

I set focus on the grid in onSectionRendered() which minimized the frequency with which it was called.  

I wonder if this should be a 'default' action by arrowKeyStepper component?
