### ISSUE TITLE
Items all dissapear in list

### ISSUE THREAD

**Issue by ReinAkane** [bvaughn/react-virtualized#780]
# Bug or runtime error
I have verified that this is occurring on master. I'll see about adding a failing unit test tonight. Error is reproducible in `react-virtualized` list example.

1. Open list example in Firefox.
2. Scroll down (until originally visible items + overscan are not visible).
3. Reduce `Num rows` until you don't have a scroll.
4. Increase `Num rows` back to its previous value.
5. Notice that no items are visible.

Scrolling at all immediately brings them back into view.

Gif of reproduction in examples:
---
![virtualized_bug](https://user-images.githubusercontent.com/8212518/29366562-f5a188c4-825f-11e7-89da-95941b96aa53.gif)

edit: updated to specify the bug is only in Firefox.

**Comment by bvaughn** [comment]
I'm not able to reproduce this on the demo site, using Chrome or Safari. It seems to only happen for Firefox. Can you confirm if this is the browser you're using also?

**Comment by ReinAkane** [comment]
Let me try and reproduce in Chrome, as I have done so previously, but the examples reproduction was in Firefox. I'll try in all my browsers and let you know which I can and cannot reproduce in.

**Comment by ReinAkane** [comment]
Can only reproduce in Firefox. Tried in Chrome, IE11, and Firefox all on windows.

**Comment by bvaughn** [comment]
That's interesting.

**Comment by bvaughn** [comment]
I should add that my testing above was on Mac OS. So it seems like this issue affects Firefox on both platforms, but no other browsers.

**Comment by ReinAkane** [comment]
Working on a fix, hope to have a PR soon. The problem stems from the fact that when a container is shortened past the current scroll location Chrome fires a scroll event but Firefox does not. The fix we're going to try and make is to calculate our location when props change.

**Comment by bvaughn** [comment]
Great! Thanks for the update.

**Comment by ReinAkane** [comment]
So I've spent about two hours in a futile attempt to get tests to run at all. Something deciding not to babelify. I spent 30 minutes trying to get yarn to work, on a similarly futile attempt. Here's the commit that fixes this issue: https://github.com/ReinAkane/react-virtualized/commits/fix-items-all-disappear-in-list-780
If I remember to, I will try to test when I get home.

**Comment by bvaughn** [comment]
> So I've spent about two hours in a futile attempt to get tests to run at all.

```sh
yarn install
yarn test
```

**Comment by ReinAkane** [comment]
>  I spent 30 minutes trying to get yarn to work, on a similarly futile attempt.

Instead I attempted
```
npm install
npm test
```

**Comment by bvaughn** [comment]
Right. This is why I use Yarn, to prevent transient problems with upstream dependencies. Yarn uses a lock file to ensure it installs specific versions of direct and indirect dependencies.

**Comment by ReinAkane** [comment]
(that misclick)

**Comment by ReinAkane** [comment]
`yarn` works infinitely better on my personal computer than my corporate one. PR created.

**Comment by ReinAkane** [comment]
Fixed in #798
