### ISSUE TITLE
feature request: Huawei browser support

### ISSUE THREAD

**Issue by lqzerogg** [bvaughn/react-virtualized#781]
* What's your use case?
react virtualized seems not working properly in Huawei browser. In fact, it works in the first render, and fails afterwards. The list just become blank. But if I resize my browser(zoom in or zoom out), it will work again. Of cause it is Huawei browser's rendering bug, but do you guy have any plan to support it? You know, Huawei's cell phone, P7~P10, have many users.

**Comment by bvaughn** [comment]
No plans to support it really because I don't have any test devices or any
sense of how difficult it would be to support. You're free to contribute a
PR though!

**Comment by lqzerogg** [comment]
Alright, I should close it. And, after I understand all of your codes, I will do it.

**Comment by bvaughn** [comment]
I look forward to it!
