### ISSUE TITLE
ArrowKeyStepper disable property not in docs

### ISSUE THREAD

**Issue by thevtm** [bvaughn/react-virtualized#786]
I don't know if this is intended or not.

[Source](https://github.com/bvaughn/react-virtualized/blob/HEAD/source/ArrowKeyStepper/ArrowKeyStepper.js#L22)
[Docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/ArrowKeyStepper.md)

**Comment by bvaughn** [comment]
Not intentional. Want to submit a PR to add the prop?

**Comment by thevtm** [comment]
Sure.

**Comment by bvaughn** [comment]
Thanks!

**Comment by thevtm** [comment]
No problem!!
It's a great pkg.
That's the least I could contribute back!
:smile:
