### ISSUE TITLE
Feature request: add title attribute to Column

### ISSUE THREAD

**Issue by mccambridge** [bvaughn/react-virtualized#793]
I found myself providing icons to a very tight table column heading, passing the icon as a node to `label`:

```label={<i className='fa fa-image'></i>}```

It worked great. The only thing is, when I hover I get a tooltip from the generated title attribute that says:

```[object Object]```

It would be great if I could pass a `title` attribute to the `<Column />` component that would override the default behavior of passing the `label` to the `title` attr in the generated node.

I assume this would extend to `Grid`, etc.

Thanks!

**Comment by bvaughn** [comment]
You can accomplish this by creating your own `headerRenderer`. The default one is [here](https://github.com/bvaughn/react-virtualized/blob/master/source/Table/defaultHeaderRenderer.js). It's not very complicated. I'd suggest you just fork it and pass it to [`Column`](https://github.com/bvaughn/react-virtualized/blob/master/docs/Column.md#prop-types). 😄 The default one isn't meant to be super flexible.

**Comment by mccambridge** [comment]
Okay, thank you.
