### ISSUE TITLE
Problem with scroll position and dynamically sized rows using scrollToIndex

### ISSUE THREAD

**Issue by MattKunze** [bvaughn/react-virtualized#795]
Hopefully this isn't too convoluted an example, basically I have a list that has a concept of the active row that can be changed either by clicking to select or, or driven by an external selection. I was able to create an example that reproduces the issue and track down the cause to additional calls to measure the row after it has been updated. In this case the additional measurement isn't necessary because the content size isn't changing, but it does trigger the strange scroll behavior I'm seeing:

https://plnkr.co/edit/5sQ1Jg?p=preview

What is happening is when you are scrolled down a bit and select items above the current selection it unnecessarily repositions the scrolltop (ie: the newly active row is completely visible):

![](http://g.recordit.co/GBoVyqtt9B.gif)

Commenting out the second measure call in `componentDidUpdate` on line 86 avoids the issue, but causes other sizing issues in my use case

**Comment by bvaughn** [comment]
I'm not sure what's being reported here. A bug? A question?

**Comment by MattKunze** [comment]
It's a bug - I expect `scrollToIndex` to only change the scroll position when it is necessary to display the specified row, if the row is already visible I expect the scroll position to not change

**Comment by bvaughn** [comment]
This depends on `scrollToAlignment` but yeah, the default value ("auto") should behave the way you describe. There are unit tests checked into GitHub that verify this.

Making the `measure` callback async in `componentDidMount` and `componentDidUpdate` (eg `setTimeout(0, this.props.measure)`) seems to fix things, as does removing it entirely. (It's really not necessary for what you're doing, since there is no async-loading content.)

**Comment by MattKunze** [comment]
Thanks, `setTimeout` works around the issue for me as well (though I also had to add a guard to check that the component wasn't unmounted in my case or I get React warnings)

Another one to add to the growing list of things that are hacked around by `setTimeout`, oh well :)

**Comment by bvaughn** [comment]
I'd like to know more about why you need to synchronously call `measure` though?

If it's async, it should work. If measurement is sync, you shouldn't need to call it (and so it should also work).

**Comment by MattKunze** [comment]
In my case the content of each row is evaluated asynchronously, I left that out of the plunker to simplify the example. I had the measure call in `componentDidUpdate` as a catch-all to ensure that resize changes were detected, it looks like moving the measure call to where the async results are saved in state also behaves correctly and doesn't need the setTimeout workaround

**Comment by bvaughn** [comment]
Cool. Thanks for clarifying. 😄

**Comment by MattKunze** [comment]
np - thanks for the quick help on everything
