### ISSUE TITLE
defaultTableHeaderRenderer should include the container

### ISSUE THREAD

**Issue by silvenon** [bvaughn/react-virtualized#797]
I've been trying to reorder table columns with react-sortable-hoc. [This](https://github.com/clauderic/react-sortable-hoc/issues/218#issuecomment-326554677) is what I came up with, it almost works well, but I have to drag the headers pretty far in order for them to swap places.

It turns out that this happens because the `defaultTableHeaderRenderer` actually returns an array of children, without the container, so I have to add the container myself. However, this means that column header decorated with `sortableElement` won't be a _direct_ child of the header row decorated with `sortableContainer`, and that seems to be what causes the problem.

My proposition is to adjust `defaultTableHeaderRenderer` to also include the container, rather than only children. This may fix future issues with integrating with other library, not only react-sortable-hoc.

**Comment by bvaughn** [comment]
Thanks for the clear problem description. Here are my initial thoughts.

> However, this means that column header decorated with sortableElement won't be a _direct_ child of the header row decorated with `sortableContainer`, and that seems to be what causes the problem.

What problem? Having to drag the header columns farther than you think is necessary?

> My proposition is to adjust`defaultTableHeaderRenderer` to also include the container, rather than only children.

This would be a breaking change and would require a new major release. I'm not sure _this_ is enough to justify the effort that would cause. If/when I do a new major version, I have bigger ideas I'd want to tackle first.

> This may fix future issues with integrating with other library, not only react-sortable-hoc.

This claim seems a bit shaky (eg What other libraries? How do we know this would make things easier with them? etc.)

**Comment by silvenon** [comment]
You’re right. This sounds like a bug I should raise in react-sortable-hoc instead. My bad…

**Comment by silvenon** [comment]
For the record, perhaps it could be done in a non-breaking way, by exposing another renderer `defaultTableHeaderContainerRenderer`, but if the need for that hasn’t appeared before, no reason to add it now.

**Comment by bvaughn** [comment]
I appreciate your being so understanding about this. ❤️ Thank you.

**Comment by silvenon** [comment]
@bvaughn just so I know, would you accept a PR for that?

**Comment by bvaughn** [comment]
I'm willing to _review_ one but no promises that I'll accept it. Doesn't seem like a very intuitive prop name nor a common use-case. 😄

**Comment by silvenon** [comment]
Thanks for being willing to review it. In the meantime I realized that I'm not very smart 😆  and that the existing API provides enough flexibility. `headerRowRenderer` renderer allows me to make sortable header cells direct descendants of the their sortable container (the header row) via the `columns` param.

If anyone reading this would like to see an example, I'll post it soon to [react-sortable-hoc#218](https://github.com/clauderic/react-sortable-hoc/issues/218).

**Comment by bvaughn** [comment]
Great! 🎉  I'm glad you found a solution! Thanks for leaving an update here as well. 😄

**Comment by bvaughn** [comment]
You've probably already seen this but @clauderic added [a demo of this](http://clauderic.github.io/react-sortable-hoc/#/react-virtualized/sortable-table-columns) with [source code](https://github.com/clauderic/react-sortable-hoc/blob/master/examples/virtual-table-columns.js).

**Comment by silvenon** [comment]
Wohoo! 🌮
