### ISSUE TITLE
Table footer row like table header

### ISSUE THREAD

**Issue by sahaviev** [bvaughn/react-virtualized#805]
Hello! Thank you so much for such a wonderful and functional react component!

I need a little modification of this.
For my goals need table footer(tfood).
I have looked the source code and there are not support this.

Can i make a pull request, add optional table footer supporting and merge to repository?

**Comment by bvaughn** [comment]
Thank you!

You're welcome to submit a PR. I can't say whether I'll accept it yet but I'll be happy to review it. 😄

**Comment by bvaughn** [comment]
Please feel free to create a PR for this issue. I'll be happy to review it. Since I don't plan on acting on this issue though, I'm going to close it for now. 😄

**Comment by spjoshis** [comment]
@sahaviev Did you create PR for this issue? Or any update on this?

**Comment by guokangf** [comment]
What happened?
