### ISSUE TITLE
Inifinite AutoSizer has impact on other components animations

### ISSUE THREAD

**Issue by imosapatryk** [bvaughn/react-virtualized#806]
It seems that InfiniteLoader with AutoSizer or List has impact on other components css animations performance. There where I have these components used animations of other components falter.

**Comment by bvaughn** [comment]
This isn't enough into for me to do anything actionable on. If you'd like to provide a repro case (using CodeSandbox or similar) and more specific info, maybe I can help.

**Comment by imosapatryk** [comment]
Ok. I'll try to create a sample. But briefly speaking the problem is that i
have a sider which can be collapsed so the view is resizing and in auto
resizer onResize id called multipl times what causes big lags.

18.09.2017 6:19 AM "Brian Vaughn" <notifications@github.com> napisał(a):

**Comment by bvaughn** [comment]
Simplest approach on your side might be to debounce the callback. Have you
considered this?

**Comment by imosapatryk** [comment]
I've added something like with debounce from lodash :


  componentDidMount() {
    const { nonce } = this.props;
    if (this._autoSizer && this._autoSizer.parentNode instanceof
HTMLElement) {
      // Delay access of parentNode until mount.
      // This handles edge-cases where the component has already been
unmounted before its ref has been set,
      // As well as libraries like react-lite which have a slightly
different lifecycle.
      this._parentNode = this._autoSizer.parentNode;

      // Defer requiring resize handler in order to support server-side
rendering.
      // See issue #41
      this._detectElementResize = createDetectElementResize(nonce);

      this._detectElementResize.addResizeListener(
        this._parentNode,
        this._resizeHandler()
      );

      this._onResize();
    }
  }

  _resizeHandler = () => {
    const { debounce: propDebounce } = this.props;
    return propDebounce
      ? debounce(this._onResize, propDebounce, {
          leading: true,
          trailing: true
        })
      : this._onResize;
  };

But it's working strange. Firstly the parent width is changed then list
rudely stretches...

2017-09-19 16:28 GMT+02:00 Brian Vaughn <notifications@github.com>:

> Simplest approach on your side might be to debounce the callback. Have you
> considered this?
>

**Comment by bvaughn** [comment]
I dunno. That isolated code snippet seems reasonable at a glance.

**Comment by imosapatryk** [comment]
Yeah. Anyway thank  you very much for response ;)

19.09.2017 19:14 "Brian Vaughn" <notifications@github.com> napisał(a):
