### ISSUE TITLE
Rows rendered outside of view

### ISSUE THREAD

**Issue by nifgraup** [bvaughn/react-virtualized#807]
**Steps to reproduce**
- visit https://bvaughn.github.io/react-virtualized/#/components/List
- set "Num rows" to 100000
- scroll top bottom
- click "Use dynamic row heights?"

**What happens**
The list is just white. Everything is fine when "Num rows" is set to 10000. The DOM nodes are positioned outside of the list. It's possible to bypass this issue by making DEFAULT_MAX_SCROLL_SIZE very large.

**Comment by bvaughn** [comment]
At a glance, I think this maybe indicates a bug with cached styles and scaling. RV handles resized rows properly in non-scaling case (eg 1000 rows) but needs a nudge to properly reset itself when things change from non-scaling to scaling (or maybe when scaling changes from one scale to another, note sure).

FWIW when I say "scaling" I'm referring to [this](https://bvaughn.github.io/forward-js-2017/#/24/5) which is done by [this](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/utils/ScalingCellSizeAndPositionManager.js).

**Comment by avranju** [comment]
I am seeing a similar behavior with a table component inside an `AutoSizer`. A new row gets dynamically added about twice a second and after about 16000 rows I see the screen going blank with every update. If I scroll up or down a bit it comes back and then blanks out when the next row is added.

**Comment by nifgraup** [comment]
I can not reproduce anymore.

**Comment by nifgraup** [comment]
Still an issue, I didn't test properly when closing.

**Comment by nifgraup** [comment]
This used to work, but detection of Chromium based browsers broke when chrome.webstore was removed around v71. Submitted pull request: https://github.com/bvaughn/react-virtualized/pull/1355
