### ISSUE TITLE
Would you be interested in linking to npmcharts.com for the shields badge?

### ISSUE THREAD

**Issue by cheapsteak** [bvaughn/react-virtualized#810]
Currently clicking on these badges on the homepage will link to the badge image files

What do you think about having them link to my site npmcharts.com instead?

Link - https://npmcharts.com/compare/react-virtualized?minimal=true

Example badges: 

[![NPM total downloads](https://img.shields.io/npm/dt/react-virtualized.svg?style=flat)](https://npmcharts.com/compare/react-virtualized?minimal=true)
[![NPM monthly downloads](https://img.shields.io/npm/dm/react-virtualized.svg?style=flat)](https://npmcharts.com/compare/react-virtualized?minimal=true)

**Comment by bvaughn** [comment]
Sure 😄
