### ISSUE TITLE
Warning: Failed prop type: Invalid prop `containerStyle` of type `function` supplied to `Grid`, expected `object`

### ISSUE THREAD

**Issue by willemx** [bvaughn/react-virtualized#812]
I'm getting this warning after upgrading to RV 9.10.0
Looking through the code in `Grid.js` I see `containerStyle: Object` as a default prop.
I have never used default props in my code myself, but should this not be: `containerStyle: {}` ?

**Comment by TrySound** [comment]
Yep. You are right.

**Comment by bvaughn** [comment]
Thanks! I fixed this but my fix was in a branch ☹️  Realized on the ride to work this morning. Glad Bogdan posted a fix 😄
