### ISSUE TITLE
tabIndex error on MultiGrid component - version 9.10.1

### ISSUE THREAD

**Issue by kupkovski** [bvaughn/react-virtualized#815]
After upgrading to version 9.10.1, I started getting the following error on using `<MultiGrid>` component:
```
Warning: Failed prop type: The prop `tabIndex` is marked as required in `Grid`, but its value is `null`.
    in Grid (created by MultiGrid)
    in MultiGrid (at MyGrid.jsx:258)
    in div (created by AutoSizer)
    in AutoSizer (at MyGrid.jsx:256)
```

The problem is `<MultiGrid>` creates all their `<Grid>`s setting the `tabIndex` prop as `null` on the following lines:
- https://github.com/bvaughn/react-virtualized/blob/9.10.1/source/MultiGrid/MultiGrid.js#L636
- https://github.com/bvaughn/react-virtualized/blob/9.10.1/source/MultiGrid/MultiGrid.js#L690
- https://github.com/bvaughn/react-virtualized/blob/9.10.1/source/MultiGrid/MultiGrid.js#L728

But `<Grid>` component allows only numbers:
- https://github.com/bvaughn/react-virtualized/blob/9.10.1/source/Grid/Grid.js#L211

Creating a `<MultiGrid>` passing the `tabIndex` prop as a number does not help, because the component itself always creates the Grids using `null`.

**Comment by bvaughn** [comment]
A PR would be welcome if you have the time
