### ISSUE TITLE
ArrowKeyStepper Example continues to jump to currentIndex

### ISSUE THREAD

**Issue by austin94** [bvaughn/react-virtualized#816]
# Bug
I am attempting to include a `ArrowKeyStepper` with my Table component and am trying to get an example that allows scrolling and click selection as well as key-based navigation.

From the live example I would expect scrolling to work, but it appears that for both controlled and uncontrolled modes that as you scroll the grid jumps back in a loop.

![2017-09-19 16_49_04](https://user-images.githubusercontent.com/4030377/30620551-e307efda-9d5a-11e7-9ce9-6a8208048d20.gif)

Could you confirm that this is the expected behavior? Otherwise I will move to Slack/StackOverflow.

**Comment by bvaughn** [comment]
Doesn't seem expected, no. Probably a regression.

**Comment by bvaughn** [comment]
My guess is that this was introduced with PR #798 (cc @ReinAkane)

**Comment by bvaughn** [comment]
This issue has been fixed in the 9.11 release that will be going out momentarily.
