### ISSUE TITLE
Tag independent rendering for Table

### ISSUE THREAD

**Issue by Dangoo** [bvaughn/react-virtualized#817]
## Motivation
For some complex data structures, nested headers are a good way to give your data structure hierarchy. Typically two levels are used but arbitrary levels are possible use cases as well.

In my use case we intent to implement a nested header structure using `<table>`markup like this:
```
+-------------------------------------------------------------------+
|          Names         |            |          |                  |
+------------------------+ Birthday   | City     | Mail             |
| First name | Last name |            |          |                  |
+------------+-----------+------------------------------------------+
| Roy        | Stokes    | 1989-01-01 | New York | roy@grid.com     |
| Kelly      | Rose      | 1988-02-02 | London   | kelly@grid.com   |
+-------------------------------------------------------------------+
```

And the resulting markup should look like that:
```html
<table>
    <thead>
        <tr>
            <th colspan="2">Names</th>
            <th rowspan="2">Birthday</th>
            <th rowspan="2">City</th>
            <th rowspan="2">Mail</th>
        </tr>
        <tr>
            <th>First name</th>
            <th>Last name</th>
        </th>
    </thead>
</table>
```

## Problem
React virtualized does a great job offering multiple "renderers" (e.g. `headerRenderer`, `rowRenderer`etc.) to make the main component extensible.
These functions even allow to render a `<table>` instead of the header row `<div>` and to customize the cell content.

But in the class `Table` the return value of `_createColumn` and `_createHeader` prevent the ability to use complete custom markup for the Table by enforcing `<div>` as tag for header columns (and for regular columns as well, incase one intends to use `<table>`markup in the `<Grid>`).

## Solution
Providing another "renderer" function for `_createColumn` and `_createHeader` and moving the current return values of both of them to a `default<Name>Renderer` similar to `headerRenderer` would enable users of the table to use their own markup for the table (-header) and on the other hand keep the API change low for existing projects.

Table.js
```jsx
_createHeader({ column, index }) {
    ...

    // Returns cell content wrapper, customizable
    const renderedHeader = headerRenderer(...);

    ...

    return tableHeaderRenderer({
        a11yProps,
        index,
        className: classNames,
        style,
        renderedHeader
      }
    );
}
```

defaultTableHeaderRenderer.js
```jsx
export default function defaultTableHeaderRenderer({
  a11yProps,
  index,
  className,
  style,
  renderedHeader
}) {
  return (
    <div
        {...a11yProps}
        key={`Header-Col${index}`}
        className={className}
        style={style}
      >
        {renderedHeader}
      </div>
  );
}
```

Looking forward to your feedback and I'd be glad to work on a PR for that, if desired  😃

**Comment by bvaughn** [comment]
I'd be happy to review a PR, although I can't promise I'll get to it quickly. It would be important to me that any changes made to `Table` were backwards compatible (and didn't require a 10.0 release).

**Comment by bvaughn** [comment]
I read through this quickly the first time and I missed this statement:

> These functions even allow to render a &lgtable&gt; instead of the header row <div> and to customize the cell content.

This isn't actually the case due to the [DOM structure required for windowing](https://bvaughn.github.io/forward-js-2017/#/12/3) and the more limited nested structure supported by [`HTMLTableElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement) (at least assuming you care about valid HTML markup).

**Comment by Dangoo** [comment]
> This isn't actually the case due to the DOM structure required for windowing and the more limited nested structure supported by HTMLTableElement (at least assuming you care about valid HTML markup).

Except for issue of using two tables (one for the header and one for the content), I'm not sure if I'm getting your point since scrolling happens only in the gridContainer?

Managed to get the above behavior working like this (aria-label not finetuned yet…):
![table](https://user-images.githubusercontent.com/1252204/30817593-8982e532-a219-11e7-941e-a83ed2e69beb.png)
 
Using `<table>` like this is the easiest way to achieve span of cells across both axis. Doing that with divs is feels ugly when it comes e.g. to absolute positioning everything and calculating x,y, width and height of each cell…

**Comment by bvaughn** [comment]
> Except for the issue of using two tables (one for the header and one for the content), I'm not sure if I'm getting your point since scrolling happens only in the gridContainer?

I didn't interpret your proposal as using multiple `<table>` tags. If it did, then yes- that could work around the issue I mentioned, although I wonder what the impact of all of those extra wrapper elements (eg `tbody`, `tr`) would be on performance.

**Comment by Dangoo** [comment]
> I didn't interpret your proposal as using multiple `<table>` tags.

Sorry, could have made that more clear.

Do you have any performance experience for the case of doing the following replacements?

1. any `<div  role="row" class="ReactVirtualized__Table__row">` by `<tr …>`
2. any `<div role="gridcell" class="ReactVirtualized__Table__rowColumn">` by `<td …>
3. wrapping them into `<table><tbody></tbody></table>` inside `<div class="ReactVirtualized__Grid__innerScrollContainer" role="rowgroup">`

This would mean just two additional wrappers (`table` and `tbody`), whereas maybe the `ReactVirtualized__Grid__innerScrollContainer` could be the `<table>` itself…

**Comment by bvaughn** [comment]
Been a while without any input on this issue, so I'm going to close it.

It's a bit hacky, but I believe you can accomplish the layout (or a similar one) to what you're describing using the existing `headerRowRenderer` prop roughly like so:

```js
function headerRowRenderer({
  className,
  columns,
  style,
}) {
  // This should be the sum of <Column> widths
  // Plus 10px right margin per <Column> (assuming default styles)
  // For each of the "grouped" column (in this case, 2 of them)
  const groupWidth = ...;

  return (
    <div className={className} role="row" style={style}>
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          flex: `0 1 ${groupWidth}px`,
          height: '100%',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            flex: '0 0 30px',
          }}
        >
          Names
        </div>
        <div
          style={{
            display: 'flex',
            flex: '0 0 30px',
            marginLeft: -10,
          }}
        >
          {columns.slice(0,2)}
        </div>
      </div>
      {columns.slice(2)}
    </div>
  );
}


<Table
  headerHeight={60}
  headerRowRenderer={headerRowRenderer}
  rowHeight={30}
  {...otherTableProps}
/>
```
