### ISSUE TITLE
grid default mouse scroll

### ISSUE THREAD

**Issue by HenShalom** [bvaughn/react-virtualized#823]
I'm using the scroll sync component with 2 grids and i wanted to know if there a possibility to add(or if it already exist  ) a way to set the grid to use invert mouse scroll (normal mouse scroll will scroll horizontal ).

**Comment by bvaughn** [comment]
There may be a way to do this with JavaScript, but I'm not familiar with that technique and it wouldn't be react-virtualized specific. 😄
