### ISSUE TITLE
Grid tabIndex prop is marked as required, but docs say otherwise

### ISSUE THREAD

**Issue by rygine** [bvaughn/react-virtualized#826]
# Are you asking a question?
No

# Are you reporting a bug or runtime error?
Yes

I think this may be the offending line: https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L211

This looks like the commit where this cropped up: https://github.com/bvaughn/react-virtualized/commit/d6704d685dce133449516516b4ff12cd52b75953

And this PR: https://github.com/bvaughn/react-virtualized/pull/818

react: `15.6.1`
react-virtualized: `9.10.1`

This could be an issue with `babel-plugin-flow-react-proptypes` since maybe number should accept `null` or `undefined`. Weird.

This looks related: https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/131#issuecomment-329698667

# Are you making a feature request?
No

**Comment by kalley** [comment]
The propType warning fix hasn't been released. The "offending line" actually removes that warning and was necessary since `null` is being explicitly passed in from `MultiGrid`.

**Comment by bvaughn** [comment]
Thanks for the added context @kalley

Closing via #818

**Comment by bvaughn** [comment]
(This fix will be released via 9.11 in a few moments)
