### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by csvan** [bvaughn/react-virtualized#827]
React 16 has been officially released:

https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html

Would be awesome to see RV default to it - the current package.json points to the Beta.

**Comment by elrumordelaluz** [comment]
Updating to `react@16.0.0` I am having this logs blocking the render. Any idea?
<img width="537" alt="screen shot 2017-09-27 at 15 19 06" src="https://user-images.githubusercontent.com/784056/30915755-0706005a-a398-11e7-823e-d599f8cd7d3b.png">

I am using `react-virtualized@9.10.1` and with `react@15.6.2` works perfect.

**Comment by bvaughn** [comment]
> Would be awesome to see RV default to it - the current package.json points to the Beta.

This is just the version of React that react-virtualized is running on the demo site. It doesn't have any impact on which version of React you run on your own website. RV supports anything 15.3.0+ for that.

> Updating to react@16.0.0 I am having this logs blocking the render. Any idea?

No. Please provide a repro as a separate issue if you're still seeing this.  I don't see this issue on the RV demo site (which I've updated to 16.0.0 locally) for either `AutoSizer` nor `WindowScroller`.
