### ISSUE TITLE
When using 2 Multigrids within a flex container, Autosize does not correctly set the width in firefox

### ISSUE THREAD

**Issue by Typhon66** [bvaughn/react-virtualized#831]
When using 2 Multigrids in a flex container, autosizer will incorrectly size the tables, this only happens in firefox. If i have a table with 2 columns, and another next to it with 6 columns, the one with 2 columns is significantly smaller than the one with 6 columns.

**Comment by bvaughn** [comment]
Not enough info provided to reproduce this so I'm closing it.

Happy to look into it though if you'll provide either a repro case (using Code Sandbox or something similar) or a failing unit test. Cheers!
