### ISSUE TITLE
CellMeasurer has no maxWidth, only minWidth?

### ISSUE THREAD

**Issue by wtfdaemon** [bvaughn/react-virtualized#834]
Any particular reason blocking this?  I'm willing to dive a little deeper and submit a PR this week if possible.

In addition to this, would be really nice if I could give CellMeasurer content that I want to be sized and used to update the CellMeasurerCache for dynamic sizing, and a different content value that gets rendered.

This is an issue for me because I'm wrapping cell content with an overlay trigger/popover for content with multiple items.

**Comment by bvaughn** [comment]
> CellMeasurer has no maxWidth, only minWidth

You should be able to accomplish this via CSS 😄 

```jsx
  function cellRenderer({ columnIndex, key, parent, rowIndex, style }) {
    return (
      <CellMeasurer
        cache={cellMeasurerCache}
        columnIndex={columnIndex}
        key={key}
        parent={parent}
        rowIndex={rowIndex}
      >
        <div
          style={{
            ...style,
            maxHeight: 150,
            overflow: 'auto'
          }}
        >
          {content}
        </div>
      </CellMeasurer>
    );
  }
```

> In addition to this, would be really nice if I could give CellMeasurer content that I want to be sized and used to update the CellMeasurerCache for dynamic sizing, and a different content value that gets rendered.

This sounds like something I probably won't support in `CellMeasurer` but you might be able to support by forking it?
