### ISSUE TITLE
IE 11: Invalid calling object

### ISSUE THREAD

**Issue by Krekotun** [bvaughn/react-virtualized#837]
I guess this bug has appear, after you'd introduced requestAnimationFrame.

Screenshot: http://d.pr/i/uzQcQ5

Any ideas how to fix?

**Comment by bvaughn** [comment]
No ideas.

Just tried RV (the demo site) on IE11 in a VM and it works fine for me, no error.

Unless you can provide more info and a repro, there's not much I can do here. Sorry! ☹️
