### ISSUE TITLE
AutoSizer is not triggering onResize when it gets the dimensions on the first run

### ISSUE THREAD

**Issue by kumarharsh** [bvaughn/react-virtualized#838]
It seems like `<AutoSizer>` is not triggering it's `onResize` even when it gets the actual dimensions for the first time. The onResize is on subsequent renders.

In the demo here:
https://codepen.io/khs/pen/yzjzYg

When you load the page, the `width` and `height` are set as `0` but the canvas is always properly sized. When you resize the view pane, the width and height change with the canvas' dimensions.

**Comment by TrySound** [comment]
There is double render in AutoSizer. First computes width and height and pass to callback before the second. Your draw method should look like this.
```js
_draw = ({ width, height }) => {
  this.setState({
    width,
    height
  });
};
```

**Comment by kumarharsh** [comment]
Thanks for the clarification. But why doesn't taking the width & height from the canvas work? I guess the callback gets called before the children are rendered?

**Comment by TrySound** [comment]
@kumarharsh Yep. Callback may force render too, so render would be called twice. It's unnecessary since size information is provided in the first pass.

**Comment by Mr-Wallet** [comment]
This seems like a valid issue to me, unless I'm misunderstanding something. I just ran into the same problem and it was very unintuitive.

I expect the AutoSizer to call onResize every time the size changes. It's all right for it to be called twice when mounting; the most critical thing is that if it "settles" on a size then the most recent size should have been the most recent call to onResize. The fact that it behaves this way only after it "finishes mounting" but not at first is pretty confusing.
