### ISSUE TITLE
Feature Request - Multigrid overall className

### ISSUE THREAD

**Issue by simple-nguyen** [bvaughn/react-virtualized#845]
Hi Team,

Was wondering if you could make it so if I pass in a className from the Multigrid component that this className is used for the overall Multigrid div?

eg.
```
<MultiGrid
  className={'multi-grid'}
  ......          
/>
```

in Multigrid.js - render():
```
return (
      <div style={this._containerOuterStyle} className={this.props.className}>
        ......
      </div>
    );
```

**Comment by kylechartio** [comment]
<Grid> component has this option. Would be nice if MultiGrid had it too
