### ISSUE TITLE
Height zero by AutoSizer after a lot of the parent components are re-rendered

### ISSUE THREAD

**Issue by fc** [bvaughn/react-virtualized#848]
We have a toggle in our app to turn a particular feature on / off.  This causes a re-render of everything in this component and then a list a component wrapped by AutoSizer returns zero for the height so does not correctly redraw the list.  If you manually resize the browser with your cursor, the height by AutoSizer is detected and it draws the list.  We are also using flex box.

The fix / workaround we are using for now is this:
```
<div style={{flex: 1, transform: 'scale(1)'}}>
... 
</div>
 ```
Reference to the answer on StackOverflow:
https://stackoverflow.com/a/9513843/747678

I really wish I could produce a test case for this since this issue is so peculiar.  Hopefully this will help someone else out though if they run into the issue.

Let me know if you would like me to dig any deeper.  It looks like the AutoSizer derives the height from the parentNode so could probe around there as needed.

**Comment by bvaughn** [comment]
Hi Clayton.

I'm not sure I understand this issue. It doesn't seem actionable with the amount of detail you've provided. If you're just posting it as an "FYI" for someone to discover in the future- that's cool (and thanks!) and we can just close it.

If you're looking for some action from me though, it isn't clear.

**Comment by fc** [comment]
Yep, it's an FYI, we can just close it.

The issue is basically that when a number of the parent components are unmounted/remounted  then re-rendered the parentNode height is zero even though it is inside of a flex container.

**Comment by bvaughn** [comment]
Cool 👍  Thanks for clarifying! and for the issue.
