### ISSUE TITLE
Show more than 1000 items in the examples

### ISSUE THREAD

**Issue by phpnode** [bvaughn/react-virtualized#85]
Hi, thanks for this great library. In the examples it would be really useful to see how it performs when there are many more than 1000 rows, e.g. 1,000,000.

**Comment by bvaughn** [comment]
Fair enough. I mainly avoided this because I didn't want to spend a lot of time generating fake data and give the impression that the slowness that results was due to react-virtualized. Maybe I'll just remove the upper bounds on the number of rows/cols and just loop through my sample list.

**Comment by bvaughn** [comment]
Check out the updated demo. Defaults to 1000 still but you can crank it up as high as you want (until you run into max-browser-size dimensions as mentioned on #73)
