### ISSUE TITLE
how to freeze the right columns?

### ISSUE THREAD

**Issue by rendongsc** [bvaughn/react-virtualized#859]
just like fixed-data-table:
[fixed-right-columns](http://schrodinger.github.io/fixed-data-table-2/fixed-right-columns.html)
thanks!

**Comment by bvaughn** [comment]
It isn't supported by the `MultiGrid` component, but you could achieve this using `ScrollSync` + `Grid`. I realize it requires a bit of boilerplate to do this, but the use-case isn't common enough that the base library supports it. (Each new supported features is more maintenance work and it's hard to keep up as it is.) Thanks for understanding!
