### ISSUE TITLE
onChildScroll undefined of WindowScroller

### ISSUE THREAD

**Issue by Zulfia73** [bvaughn/react-virtualized#862]
in WindowScroller, function onChildScroll  all time undefined

**Comment by bvaughn** [comment]
Hi @Zulfia73. I'm not sure what you're reporting here, sorry.

If you're reporting a bug though, please follow the instructions in the new issue template:

# Reporting a Bug?

Please include either a failing unit test or a simple repro. You can start by forking one of these:
* Code Sandbox: https://codesandbox.io/s/03qpzq1p9p?module=%2FExample.js
* Plnkr: https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1
