### ISSUE TITLE
[Bug] List with CellMeasurer does not render correctly

### ISSUE THREAD

**Issue by steinso** [bvaughn/react-virtualized#866]
Reproducible case: https://plnkr.co/edit/5I4FzHs8juZ4L6m5NKwV?p=preview

When rendering a List with a CellMeasurer (and deferredMeasurementCache) all rows are rendered on top of each other, only when you start to scroll the items are rendered. Also notice how it does not invalidate the dimensions of the initially rendered rows, and they all get the default height. Any rows not initially rendered are measured and rendered correctly.

My initial findings are that the Grid on List is not initialized at the point where cells are measured, therefore the invalidateCellSizeAfterRender is not called. 

This was working prior to version 9.10.0.

**Comment by krsnaa** [comment]
+1. an easy workaround for the cell sizing appears to be to pass in the function form ({ measure }) => <element />) instead of the actual element to the CellMeasurer and call measure from inside.

**Comment by reganperkins** [comment]
+1

**Comment by smerat** [comment]
+1

**Comment by Cordazar** [comment]
+1

**Comment by bvaughn** [comment]
If any of you leaving +1 comments would be interested in contributing a fix for this issue, I'd welcome the help. 😄

**Comment by OriR** [comment]
@bvaughn I'd be happy to try and fix this!
As I'm not that familiar with the code, I would appreciate it If you could point me in the right direction 😄

**Comment by bvaughn** [comment]
I'd welcome a fix, @OriR!

I don't really have anything to point you at though, other than [`Grid`](https://github.com/bvaughn/react-virtualized/tree/master/source/Grid) (which `List` uses internally) and [`CellMeasurer`](https://github.com/bvaughn/react-virtualized/tree/master/source/CellMeasurer).

**Comment by OriR** [comment]
Ok then, I'll start digging around and see what I can find :)
I'll post here any updates 👍

**Comment by OriR** [comment]
@bvaughn I opened a PR fixing this issue :)

**Comment by Miindaugas** [comment]
```
    componentDidMount() {
       this.cache.clearAll();
       this.list.Grid.forceUpdate();
    }
```

Yeh same problem, waiting for fix. 

Right now i use workaround.

**Comment by bvaughn** [comment]
I plan to release an update this morning with this fix.

**Comment by ngwing** [comment]
Have this bug fixed?

**Comment by ngwing** [comment]
Has this bug fixed?

**Comment by JunlinZhu-Tommy** [comment]
still suffering on this issue.
