### ISSUE TITLE
I need help with contextTypes.

### ISSUE THREAD

**Issue by Zulfia73** [bvaughn/react-virtualized#873]
I want add dynamic height for items of List. And I add in contextTypes : 
` list: PropTypes.instanceOf(Immutable.List).isRequired`
As in example. But `this.context.list: undefined` all time. I can't understant what do. Thanks!

**Comment by TrySound** [comment]
https://github.com/bvaughn/react-virtualized/blob/master/source/demo/Application.js#L48-L53
https://github.com/bvaughn/react-virtualized/blob/master/source/demo/Application.js#L68-L76

**Comment by bvaughn** [comment]
Hi @Zulfia73,

For `contextTypes` to work in your component, it will need a parent component that declares a matching `childContextTypes`.

You can read all about context in the official React docs here: https://reactjs.org/docs/context.html#how-to-use-context
