### ISSUE TITLE
Jumping scroll bar on 2 lists in one window using WindowScroller

### ISSUE THREAD

**Issue by ZoharLiran** [bvaughn/react-virtualized#878]
Hi,
AMAZING work on this package.

One issue I am seeing while implementing multiple lists that are using `WindowScroller` is that the scroll bar jumps as the browser reaches the bottom of the first list.
Here is an example:
https://codesandbox.io/s/jnpwvq5623

**Comment by bvaughn** [comment]
Thank you, Zohar. 😄 

Unless I'm misunderstanding the scrollbar thing you mention, that's just the way the browser works. When momentum scrolling is active and one scrollable thing reaches its end (eg your `List`), the event bubbles up to the next scrollable thing (eg the `body`).

I don't think I can/should change that behavior in react-virtualized. You can fix it in your example app though by adding the following style to the outer container:
```css
overflow-y: hidden;
```
