### ISSUE TITLE
support column resize

### ISSUE THREAD

**Issue by zllc** [bvaughn/react-virtualized#883]
can Multigrid support column resize？

**Comment by bvaughn** [comment]
Not as part of the built-in library. You can add this yourself using a library like `react-draggable`.

You can see a row-resize demo [here](https://bvaughn.github.io/forward-js-2017/#/28/1) and source for it [here](https://github.com/bvaughn/forward-js-2017/blob/master/src/Components/ResizableRowsList.js).

**Comment by bvaughn** [comment]
Update: I've also created a basic example of resizable `Table` columns here https://codesandbox.io/s/j30k46l7xw

**Comment by CZL95** [comment]
@bvaughn hi! I copy your code and when I use the  headerRenderer={this.headerRenderer} in Colunm, It got an error:

### Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Table`.

When I commented it out, it worked, Can you tell me the reason, thank you!

**Comment by pavankumar-n** [comment]
Checkout below link for Column resizer in MultiGrid:
[column-resizer-multigird](https://codesandbox.io/s/multigrid-column-resizer-ccnxn)
