### ISSUE TITLE
support onMouseEnter and onMouseLeave

### ISSUE THREAD

**Issue by klysak** [bvaughn/react-virtualized#885]
Hello!

I want to suggest adding support for handlers `onMouseEnter` and `onMouseLeave`. There are problems with a case when a cell contains not a plain text, but an element with its own logic. Events `mouseenter` and `mouseleave` don't count transitions within an element. Sometimes it is very necessary. In the [defaultRowRenderer.js](https://github.com/bvaughn/react-virtualized/blob/master/source/Table/defaultRowRenderer.js) you should add a check of methods `onRowMouseEnter` and `onRowMouseLeave`

```javascript 
    if (onRowMouseEnter) {
      a11yProps.onMouseEnter = function (event) {
        return onRowMouseEnter({ event: event, index: index, rowData: rowData });
      };
    }
    if (onRowMouseLeave) {
      a11yProps.onMouseLeave = function (event) {
        return onRowMouseLeave({ event: event, index: index, rowData: rowData });
      };
    }
```

**Comment by bvaughn** [comment]
I don't like continuing to add `onRow*` properties to `Table`. I wish I had designed that part of the API differently, but it is what it is now.

I prefer you define your own row renderer if you want to add additional event handlers to it. It requires very little code. You can just fork `defaultRowRenderer`.
