### ISSUE TITLE
MultiGrid example shows scrollbar in header?

### ISSUE THREAD

**Issue by Tetheta** [bvaughn/react-virtualized#888]
For me in all browsers https://bvaughn.github.io/react-virtualized/#/components/MultiGrid is showing a scrollbar for the fixed header. Is that intentional? It doesn't look that great and I have a similar issue with my own scroll synced grid, wondering if they're related.

**Comment by bvaughn** [comment]
This behavior can be toggled via `enableFixedColumnScroll` and/or `enableFixedRowScroll`; (see [the docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/MultiGrid.md#prop-types)). The demo page [explicitly enables it](https://github.com/bvaughn/react-virtualized/blob/b446761b13cbf142e71de106cf799c0962bc0397/source/MultiGrid/MultiGrid.example.js#L93-L94) but it's [disabled by default](https://github.com/bvaughn/react-virtualized/blob/b446761b13cbf142e71de106cf799c0962bc0397/source/MultiGrid/MultiGrid.js#L38-L39.

**Comment by Tetheta** [comment]
Ah not related to my issue then, should've just asked in the slack sorry.

**Comment by bvaughn** [comment]
No worries.
