### ISSUE TITLE
server rendering with WindowScroller

### ISSUE THREAD

**Issue by landvibe** [bvaughn/react-virtualized#891]
I'm using next.js for server rendering.
Below code has a console warning
`Warning: Expected server HTML to contain a matching <div> in <div>.`
I think client rendering is failed with this warning, so the List has no row.
If I change WindowScroller to AutoSizer, then there is no console warning.
I don't know what causes this warning.

![image](https://user-images.githubusercontent.com/3401416/33539601-979a4930-d90a-11e7-859e-07f1a41b409e.png)

If I skip server rendering like below, it also has the warning but the rows are rendered correctly on client side.
```
render() {
    if (!IS_CLIENT) {
      return null;
    }
    ...
```

**Comment by bvaughn** [comment]
`WindowScroller` depends on a `window` object, else it [falls back to a width and height of 0](https://github.com/bvaughn/react-virtualized/blob/43b84762ccb242c2048703463df570ff884ff167/source/WindowScroller/WindowScroller.js#L56-L58). I guess we could add `serverWidth`/`serverHeight` props, but it's possible that the server and client markup would still different based on the actual size of the client window.

**Edit** Looks like you already opened a PR for this. (Thanks!) I don't mind making this addition, although I'm going to tweak it slightly.

**Comment by bvaughn** [comment]
Going out as 9.14.0
