### ISSUE TITLE
Add style prop to wizard Grid.cellRenderer

### ISSUE THREAD

**Issue by albinekb** [bvaughn/react-virtualized#894]
When using the wizard to create the `<Grid />` (https://bvaughn.github.io/react-virtualized/#/wizard)
That code is not enough, you need to pass `style` also. I think the wizard should show this since it's easy to miss and it's required to make the table work

From wizard (not working): https://codesandbox.io/s/ywv2zzvx6v
With added `style` prop on `cellRenderer` child (works): https://codesandbox.io/s/8npvl4yloj

This is the code that you get when you want to have a grid:
```js
<AutoSizer>
  {({ height, width }) => (
    <Grid
      cellRenderer={({ columnIndex, isScrolling, rowIndex }) => <div/>}
      columnCount={numColumns}
      columnWidth={100}
      height={height}
      rowCount={numRows}
      rowHeight={50}
      width={width}
    />
  )}
</AutoSizer>
```

I think it should be:
```js
<AutoSizer>
  {({ height, width }) => (
    <Grid
      cellRenderer={({ columnIndex, isScrolling, rowIndex, style }) => <div style={style} />}
      columnCount={numColumns}
      columnWidth={100}
      height={height}
      rowCount={numRows}
      rowHeight={50}
      width={width}
    />
  )}
</AutoSizer>
```

I think it would be good to mention the docs in the wizard, I missed them completely.

Thanks for making this awesome lib! 🎉 

[Slack convo](https://user-images.githubusercontent.com/5027156/33670119-97d986cc-daa4-11e7-87f0-c4f7b9de0b8a.png)

**Comment by bvaughn** [comment]
Added in 43b8476
