### ISSUE TITLE
Creating a custom Column using composition instead of inheritance?

### ISSUE THREAD

**Issue by genomics-geek** [bvaughn/react-virtualized#898]
Are there any plans to support using composition of `Column` in `Table`?  Seems like `Table` is very strict about children types seen [here](https://github.com/bvaughn/react-virtualized/blob/master/source/Table/Table.js#L29-L38).  

I ask because it seems like composition is preferred over inheritance in React... I want to create custom column components and right now I find myself having to extend `Column` instead of `React.Component`.

**Comment by genomics-geek** [comment]
One possible solution is changing [here](https://github.com/bvaughn/react-virtualized/blob/master/source/Table/Table.js#L29-L38) to `PropTypes.node`.  Is there a reason that we must enforce `Column` here?

**Comment by bvaughn** [comment]
I think we talked about this out of band (maybe over Slack?) I can't recall. Anyway, I don't think this is necessary.

You can extend `Column`, use a `cellRenderer`, or a shared factory method that creates pre-configured `Column` instances for you. 👍

**Comment by genomics-geek** [comment]
Yup - I agree with you.

**Comment by jeron-diovis** [comment]
> You can extend Column

Did I understand correctly, that this is supposed way to create custom columns?

```js
const defineCustomColumn = props => class MyColumn extends Column {
   static defaultProps = {
     ...Column.defaultProps,
     ...props,
   }
}

const MyColumn = defineCustomColumn({ cellRenderer: ... })
```

It looks strange, isn't it?

> shared factory method that creates pre-configured Column instances for you

That is:

```js
const createCustomColumn = props => (
  <Column 
    {...props}
    cellRenderer={somePredefinedCellRenderer}
  />
)

...

<Table>
   {createCustomColumn(...)}
</Table>
```

?

**Comment by rmehlinger** [comment]
Personally I think table should be changed to allow custom column components. React specifically discourages the use of inheritance, and anyway you can't use it with functional components, which is the direction things are heading. One option might be to search descendants of children components and ensure that all leaves are `Columns`?

**Comment by Calamitizer** [comment]
Agreed -- yes, you could extend `<Column />`, but there's a [whole first-party docs page](https://reactjs.org/docs/composition-vs-inheritance.html) about why you probably shouldn't. Classes as a whole are seriously falling out of fashion too. Even though the React team is adamant about not dropping support altogether, it seems like class components are on the way out in a large segment of userland.

For anyone butting their head against this trying to use a functional component, there's a way to work around these "opinions" (limitations). You can call the component directly as a function, instead of using it as a JSX element. Here's an example (in TypeScript):

```tsx
interface Props extends ColumnProps {
  dataKey: AccountField; // this is a string enum
}

const AccountColumn: React.FC<Props> = ({ dataKey, ...rest }) => (
  <Column
    {...rest}
    {...{ dataKey }}
    cellDataGetter={getAccountFieldAccessor(dataKey)}
    label={getAccountFieldLabel(dataKey)}
  />
);
```

Then you can use it like so:

```tsx
<Table {...myTableProps}>
  {/* instead of this */}
  <AccountColumn dataKey={AccountField.SEGMENT} {...{ width }} />
  {/* do this */}
  {AccountColumn({ dataKey: AccountField.SEGMENT, width })}
</Table>
```
