### ISSUE TITLE
Autosizer MaxHeight instead of Height

### ISSUE THREAD

**Issue by borisd9** [bvaughn/react-virtualized#902]
I'm currently using the AutoSizer + InfiniteLoader + Table in the following setup:

```
<AutoSizer>
  {({ height, width }) => (
    <InfiniteLoader {...}>
      {({onRowsRendered, registerChild}) => (
        <Table {...} />
      )}
    </InfiniteLoader>
  )}
</AutoSizer>
```

My Table is searchable, and the items will change according to the search term. 
Meaning, the Table's height is dynamic.

My issue is with the AutoSizer. By default it acts to greedily expand to all available space in the parent. Even if it only has 2 items, it will expand to the full height, and leave an empty space below the items.

This can be fixed if i could control the height type on the AutoSizer. 
Changing the CSS Height property to MaxHeight, would resolve this issue, and allow the Table to expand to its potential height rather, than having a fixed height.

IMO, the AutoSizer should act dynamically on height. Meaning, that it should expand onto the available space only if there are enough items inside the Table/List/Grid.

**Comment by bvaughn** [comment]
> IMO, the AutoSizer should act dynamically on height. Meaning, that it should expand onto the available space only if there are enough items inside the Table/List/Grid.

This is not the way `AutoSizer` was written to work. Hopefully [the docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/usingAutoSizer.md) make that clear.

The way to approach this would be to put the `max-height` constraint (in CSS) on the container element you're putting the `AutoSizer` within. 😄

**Comment by borisd9** [comment]
Sorry, but that will not solve my problem, since it will only limit the container element which will still expand to fill the parent regardless of no. of items. 

For anyone else that stumbled upon this, another way to solve this would be to manage the height by watching the number of items and setting height dynamically.

**Comment by bvaughn** [comment]
`AutoSizer` will expand to fill its container/parent. This is by design. The way to limit it (via a `maxHeight`) is to put that constraint on the style of its container/parent. That's all I'm saying. If you have enough info to know that max-height constraint, then that would work.

**Comment by cbranch101** [comment]
Do you happen to have an example for how to do this?  I've tried every conceivable pairing of containers and flexboxes that I can think of, and no matter what I do, if I apply a `height`, it works, but if I apply a `max-height` it always collapses to zero
