### ISSUE TITLE
Jumping scroll in a List on options change and scrollToIndex defined

### ISSUE THREAD

**Issue by istarkov** [bvaughn/react-virtualized#907]
The easiest way to reproduce is to use `react-virtualized-select` as locally I use a List control inside InfiniteLoader based on source of react-virtualized-select. 
I had no such issue on a version 9.9 

Picture:
![rv_bug](https://user-images.githubusercontent.com/5077042/34161625-41651e9e-e4e2-11e7-838e-0617a7be97e9.gif)

Example:
https://istarkov.github.io/rv-bug/index.html

Example source:
https://github.com/istarkov/rv-bug/blob/6437eb8f68aff3bccbaeb82cc2bd1dd07c40d5a4/src/App.js#L13-L27

Currently I avoid this issue locally setting `scrollToIndex` property of List control to undefined whenever scrolling occurs.
But its somehow tricky because key up down also a source of scroll events, also works poorly in firefox

**Comment by istarkov** [comment]
Naive solution to avoid this is to prevent calling of this [this._rowSizeAndPositionManager.getUpdatedOffsetForIndex](https://github.com/bvaughn/react-virtualized/blob/6364d5dd50e25da28090f86ba2be79e092acc79b/source/Grid/Grid.js#L1312-L1317) if `targetIndex` is equal to `targetIndex` from previous call [here](https://github.com/bvaughn/react-virtualized/blob/6364d5dd50e25da28090f86ba2be79e092acc79b/source/Grid/Grid.js#L1307) has not changed.

**Comment by istarkov** [comment]
The bug exists and not fixed why issue is closed?

**Comment by TrySound** [comment]
I believe it's select issue. However okay, will open it.

**Comment by KathrynN** [comment]
I'm also having this problem with List (not inside a select) when scrolling too quickly.

**Comment by mkawczynski07** [comment]
It should be mentioned in docs that rowRenderer must return div or any html element rather than component. I had the same problem as @KathrynN and spend more than one day...

**Comment by thibaultvdb-incerta** [comment]
I'm having the same issue with the grid. This only happens with the horizontal scrollbar, not the vertical.
I'm using windowscroller, autosizer, columnsizer with the grid and I'm on version 9.20.0. Is there any concrete solution for this?
