### ISSUE TITLE
Infinite Loading Table issue

### ISSUE THREAD

**Issue by telaoumatenyanis** [bvaughn/react-virtualized#913]
As I need to pull my data from my GraphCool simple api (not the relay one), I am using skip and first to load more rows, and concatenate them to my rows array. Therefore I am not really using the startIndex and stopIndex as the example use them.
E.g. : 
`query{allEntities(first: 50 skip: 50)
{
id name
}
}`

The defaultCellDataGetter is creating an error, while trying to use .get on null data (as it is still not loaded).

**Bug Replication :** 
You can find the way I am concatenating the data here : [Code Sandbox](https://codesandbox.io/s/q98vxllly6)

**Workaround :**
Add a cellDataGetter to the column in order to prevent the null value to bug the whole thing.
[Code Sandbox](https://codesandbox.io/s/91o5povlxr)

Maybe I am not using it the right way, but as I stumbled across this bug, I guess other did so adding a null check to the defaultCellDataGetter shouldn't be overkill ?

**Comment by bvaughn** [comment]
The "trick" with sparsely-loaded `Table` data is to just return an empty object for unloaded rows. Your `Column` cell renderers can either render nothing (the default) or you can use `rowRenderer` to detect this case and render a flat placeholder div to avoid the unnecessary work of even calling the cell renderers.

I don't think this issue really requires any action on my part. There are a couple of options for making sparsely loaded `Table` data work. 😄 If you'd like to contribute an example of doing this to the docs though, I would be happy to receive a PR!

**Comment by StoneCypher** [comment]
it would be nice if you would update the docs to show a code example of this common need, as this comment in passing is difficult to find and difficult to interpret

**Comment by StoneCypher** [comment]
it's difficult to understand how this is meant to work
