### ISSUE TITLE
Masonry - react@16.x Warning: `Infinity` is an invalid value for the `height` css style property.

### ISSUE THREAD

**Issue by borm** [bvaughn/react-virtualized#914]
Subj

**Comment by borm** [comment]
https://github.com/bvaughn/react-virtualized/blob/master/source/Masonry/Masonry.js
Think can be fixed by checkin isFinite in _getEstimatedTotalHeight

**Comment by bvaughn** [comment]
"Subj" is not a reasonable set of steps to reproduce the error you're reporting. Next time, please provide the info the new issue template asks for 😄 

> # Reporting a Bug?
> Please include either a failing unit test or a simple repro. You can start by forking one of these:
> * Code Sandbox: https://codesandbox.io/s/03qpzq1p9p?module=%2FExample.js
> * Plnkr: https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1

Btw this should have been fixed by #961
