### ISSUE TITLE
Making it virtualized completely ignores the shadow.

### ISSUE THREAD

**Issue by robgev** [bvaughn/react-virtualized#916]
I want to have a box shadow on the elements but only the bottom part of the shadow is visible by default.
Here is the demo:
https://codesandbox.io/s/9j522y1z5y
Box Shadow is hidden because of the immediate element wrapper with styles position: absolute, left: 0, top: 0. 
I could not fine any workaround for this, so at least if anyone knows any workaround for now, share it here.

**Comment by TrySound** [comment]
@robgev It doesn't ignore. It's overflow: scroll.
https://codesandbox.io/s/wjkq6y69l

**Comment by robgev** [comment]
Hello there again, I cannot seem to open the codesandbox and the message is not really clear to me. The issue still persists tho.

**Comment by TrySound** [comment]
@robgev 
1. you didn't not applied style to you row element
2. elements overlap each other, remove or reduce height of p, add top/bottom paddings to row
3. add left/right paddings to row to make overflow shadow visible
