### ISSUE TITLE
[bug] - Blink on first resize

### ISSUE THREAD

**Issue by borm** [bvaughn/react-virtualized#917]
So, i have a question on [stackoverflow](https://stackoverflow.com/questions/47981695/react-virtualized-masonry-dynamic-column-width-correct-way-clear-cache) about dynamic column width for massonry component, but i think it`s a bug, because  on your [example](https://github.com/bvaughn/react-virtualized/blob/master/playground/chat.html) it exist also

Step to reproduce
open this [example](https://rawgit.com/bvaughn/react-virtualized/master/playground/chat.html) on your browser
Scroll down to end of page
Try resize window

AR
We have see blink on first time resizing, after first resize all worked fine
I think we need other optimized way to clear cache

**Comment by borm** [comment]
I think it`s happen because scroll change position

**Comment by borm** [comment]
What about run `this._measure();` on https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.js#L38 ?

**Comment by bvaughn** [comment]
> Step to reproduce
open this example on your browser
Scroll down to end of page
Try resize window

I don't see a blink when scrolling to the bottom of the page you linked to. I think you'll need to provide more information (eg your browser, OS, etc)

> What you think about run `this._measure();` instead of `this._maybeMeasureCell();` on CellMeasurer componentDidUpdate?

That would cause a lot of unnecessary measurements, for cases where the cache hasn't actually been invalidated, which would harm performance.

**Comment by borm** [comment]
You see scroll jumps on each times when we have scroll on end of page?
And please see this [plunker](https://embed.plnkr.co/knQLm5NCog2Pvf1wWoMF/), wait 2 sec, then scroll to end of page and try resize

**Comment by borm** [comment]
up
