### ISSUE TITLE
Table cellDataGetter inputs changed?

### ISSUE THREAD

**Issue by davelaker** [bvaughn/react-virtualized#925]
Has something changed wit the table functionality?

I just upgraded to latest version and my table stopped working This was my code:

<Column
  label="Email"
  dataKey="email"
  width={100}
  flexGrow={1}
/>
<Column
  label="Orders"
  dataKey="orders"
  width={100}
  cellDataGetter={({rowData}) => rowData.orders.size}
/>

I decided to take a look at what was in rowData and the response is now an array:
![image](https://user-images.githubusercontent.com/285474/34426669-0149660e-ebee-11e7-8096-6b69ca4eecd2.png)

If I was to access rowData[1] then all is good, but what about my email column?

**Comment by davelaker** [comment]
So I have updated my rowGetter to be 

  `const rowGetter = ({index}) => this.state.customers.toArray()[index][1];`

this all works, was this an expected change?

**Comment by bvaughn** [comment]
Hi @davelaker! Can you let me know which versions you upgrade _from_ and _to_? I was not aware of any breaking changes made to `Table`, certainly not within version 9.

**Comment by davelaker** [comment]
Interesting I wonder if it has anything to do with updating to the latest RC version of immutable JS (which I did as the same time) this.state.customers is an Immutable.Map<string, CustomerRecord> where the string is the email. Then I call toArray() on it in the rowGetter function

**Comment by davelaker** [comment]
Yup! It looks like immutable changed!

https://github.com/facebook/immutable-js/commit/5d9fd215721f77246bac88e6d96f177f5e597325

**Comment by bvaughn** [comment]
Ah. Good find, David. Glad you got it sorted out. 😄
