### ISSUE TITLE
Problematic use of babel-plugin-flow-react-proptypes in ESM build

### ISSUE THREAD

**Issue by billyjanitsch** [bvaughn/react-virtualized#926]
The use of [babel-plugin-flow-react-proptypes](https://github.com/brigand/babel-plugin-flow-react-proptypes) in the [`es` Babel env](https://github.com/bvaughn/react-virtualized/blob/master/.babelrc#L56) causes many CJS `require` calls to end up in what should be an ESM build. You can observe this in the [published build](https://unpkg.com/react-virtualized@9.14.1/dist/es/); for example, [List contains `require('../Grid')`](https://unpkg.com/react-virtualized@9.14.1/dist/es/List/List).

This largely defeats the purpose of an ESM build, since it means that most modules in the build cannot be tree-shaken under any circumstances.

The problem was introduced in #731 and there's some discussion about the need for the plugin in #730.

---

P.S. thanks for your amazing work on this library ❤️

**Comment by billyjanitsch** [comment]
Unfortunately it looks like the Babel plugin cannot currently output ESM, but there is talk of potentially supporting it in brigand/babel-plugin-flow-react-proptypes#159.

I've seen other libraries solve this problem by using Flow types internally and _also_ adding explicit propTypes to user-facing components (rather than using a Babel plugin which transpiles the former into the latter). The duplication sucks, but it more explicitly captures the fact that Flow types can't always map precisely onto PropTypes (e.g. functions), and tests can generically prevent the two from getting out of sync.

**Comment by TrySound** [comment]
@billyjanitsch I have the same decision. Gonna write explicit prop types maybe in next minor release.

**Comment by bvaughn** [comment]
FYI it looks like the `babel-plugin-flow-react-proptypes` functionality was implemented via brigand/babel-plugin-flow-react-proptypes/pull/162 and published as 14.0.0.

**Comment by TrySound** [comment]
Awesome! Accidentally unwatched that repo.

**Comment by TrySound** [comment]
Fixed in 9.18.1
