### ISSUE TITLE
v10 roadmap

### ISSUE THREAD

**Issue by TrySound** [bvaughn/react-virtualized#929]
Want to formulate my ideas

- prefer [resize-observer-polyfill](https://github.com/que-etc/resize-observer-polyfill) to use chrome 64 feature and remove `nonce` prop
- find a way to not use findDOMNode maybe via ref callbacks in render props
- make WindowScroller universal for any component
- use WindowScroller in MultiGrid implementation and ScrollSync example
- find different examples of using ScrollSync. Freezing colums is bad case because of lagging and wheel blocking.
- remove scrollToRow, scrollToColumn, scrollToIndex in favor of ref public methods, since representing events/commands as state changing introduces a lot of bugs and inconsistences.
- Finish flow types
- removing proptypes babel plugin which generates untreeshakable commonjs

**Comment by bvaughn** [comment]
Hey 😄 Want to combine this with #658? We can close either one. Just doesn't seem great to have both open.

**Comment by TrySound** [comment]
Sure
