### ISSUE TITLE
virtualscroll on row click

### ISSUE THREAD

**Issue by x4080** [bvaughn/react-virtualized#93]
Is it not available? Im doing workaround by using tag inside the row to get the index row position, is this the intended thing?

thanks

**Comment by bvaughn** [comment]
The `VirtualScroll` row is only what your `rowRenderer` function returns. So if you want to add a click listener for the row, just declare it as part of whatever your `rowRenderer` function returns. :)

As for getting the 'index' in your on-click handler, that should be as simple as taking advantage of the scope.

```js
function rowRender (index) {
  return (
    <div onClick={yourListener(index)}>
      {`I am row ${index}`}
    </div>
  )
}
```

**Comment by x4080** [comment]
ahh, i forgot abou that after es6 bind thing. thanks for the tip

**Comment by bvaughn** [comment]
No problem :)
