### ISSUE TITLE
Large lists are scrolled too fast

### ISSUE THREAD

**Issue by d07RiV** [bvaughn/react-virtualized#932]
If I make a very large list (a million lines), it becomes extremely sensitive to scrolling. Mouse wheel scrolls for ~60 lines per tick, and page up/down key goes through 500+ lines.

Here's a simple demo: https://codesandbox.io/s/zl3yomvlqm

**Comment by TrySound** [comment]
@d07RiV It's artificial scroll virtualization. Browsers has constraints for element size. So virtualized is trying to scale scroll and fit it to 1_500_000 pixels.

**Comment by bvaughn** [comment]
FWIW, I mentioned this particular feature of RV [in a set of presentation slides](https://bvaughn.github.io/forward-js-2017/#/24/5). (Maybe the visualization will be useful.)

Currently, RV compresses for IE (the lowest common denominator) which has a limit of 1.5 million pixels. I've thought in the past about trying to maintain a built-in map of browser-to-max-size though, so we don't have to scale so early for eg Firefox and Chrome. Unfortunately I don't think there's a way to query the browser for this sort of info, so it would have to be hard-coded. I'd be happy to review a PR that adds this, provided it doesn't add a ton of complexity or runtime cost.

**Comment by d07RiV** [comment]
Yes, I noticed that it is due to scroll area being limited to 1.5M pixels, but isn't it possible to artificially slow down scrolling? It makes no sense when PageDown scrolls 10 pages at a time.

Also, browsers don't seem to have an issue displaying gigantic plain files (other than doing it very slowly), but I guess the limitation doesn't apply there?

**Comment by TrySound** [comment]
@d07RiV From slides
> Chrome 33.5M px, IE 1.5M px
Are you sure they are so big?

**Comment by TrySound** [comment]
@bvaughn Is there a video with that talk?

**Comment by bvaughn** [comment]
> Yes, I noticed that it is due to scroll area being limited to 1.5M pixels, but isn't it possible to artificially slow down scrolling? It makes no sense when PageDown scrolls 10 pages at a time.

Nope. Not with the way RV is implemented, and not without breaking momentum scrolling.

If I ever find the time to finish PR #515 this would become a non-issue.

> Also, browsers don't seem to have an issue displaying gigantic plain files (other than doing it very slowly), but I guess the limitation doesn't apply there?

Show me a "gigantic plain file" with a DOM element that's > 1,500,000 pixels wide or tall. 😄 Even so, it would work okay it Chrome and Firefox, but not in Internet Explorer.

>> Chrome 33.5M px, IE 1.5M px

> Are you sure they are so big?

Yes 😄 

> Is there a video with that talk?

Yup https://www.youtube.com/watch?v=t4tuhg7b50I

**Comment by d07RiV** [comment]
> Show me a "gigantic plain file" with a DOM element that's > 1,500,000 pixels wide or tall. 😄 Even so, it would work okay it Chrome and Firefox, but not in Internet Explorer.

Chrome renders plain files into a gigantic PRE. Not quite enough to break the supposed 33.5M px, though, maybe I should try with an even bigger file.

![image](https://user-images.githubusercontent.com/3448203/34458347-fe5d109c-edde-11e7-9c12-1401db2b8855.png)

Edge stops rendering at around 5.5M pixels, though, so guess plain files are also an issue :|

Anyway, thanks, I'll have to deal with unnatural scrolling I guess.

**Comment by bvaughn** [comment]
>Anyway, thanks, I'll have to deal with unnatural scrolling I guess.

Or you could submit a PR like I mentioned above. :wink:

**Comment by bvaughn** [comment]
Fixed by #936. Releasing shortly as 9.17

**Comment by artur0117** [comment]
Hello, I am displaying large lists over 20, 000 items in react-virtualized. Scrolling is moving too fast on Firefox. But it works well on Chrome. Is there any solution to fix this issue on Firefox?
