### ISSUE TITLE
Investigate replacing `transform` with `transform3d` for supported browsers 

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#94]
Things to investigate:
* Does it cause too much GPU strain?
* Does it introduce any rendering artifacts for Safari (or other browsers)
* Should it be opt-in or on by default?

Reference: [detecting `transform3d` support](https://gist.github.com/lorenzopolidori/3794226).

# Original Description

Refer to [this comment](https://github.com/bvaughn/react-virtualized/issues/87#issuecomment-183481441) by James:
> I think I found one potential problem: each row is placed by setting the top CSS property, which apparently makes Chrome redraw the whole viewport. I changed it to transform: translateY(...) and it seems a bit smoother.

Quick test _does_ seem smoother but it could be confirmation bias. Need to test more and confirm that (1) performance really does improve and (2) not at an unacceptable GPU cost.

Will leave this issue open for now and see if more people have opinion or information.

**Comment by jlongster** [comment]
Does Chrome have any way to measure GPU usage? The only potential downside is forcing each row to be handled as a GPU texture (or something like that). I'm not sure what the right pattern here is, but using transforms is probably the way to go, especially since we're only showing a constant number at one time anyway.

I've heard concerns from various browser devs about using too much GPU memory by overusing CSS properties that trigger GPU offloading, but I'm not really sure. What's the "scientific" way we can measure this?

I can see if there's anything in Firefox I can profile. I can't tell any difference in Firefox 46 with the APZ feature making things happen async.

**Comment by bvaughn** [comment]
> Does Chrome have any way to measure GPU usage?

I _think_ the white bar inside of Chrome's Timeline view is GPU but I'm _very_ inexperienced with that type of profiling. :)

**Comment by jlongster** [comment]
I found it: it's in the FPS overlay (???). devtools menu > more tools > rendering settings > show FPS meter. That meter shows the amount of GPU memory.

Observed results while scrolling down through the entire page:

**Using `top`**:

Without any overscan rows: 8-16 MB 
With an overscan of 100: 8->25 MB

**Using `transform`**:

Without any overscan rows: 15->22MB
With an overscan of 100: 30->55MB

The question is if this is acceptable or not. I'm not really sure. But it seems like it could potentially use about twice as much memory on average (although this is all anecdotal, just watching the meter while scrolling).

I'm surprised the `top` works this well, honestly. I thought transforms would be clearly smoother, but maybe we should hold off on this until there's a clear reason to do it. Or wait until this lib gets used in more situations and other people complain about performance.

**Comment by jlongster** [comment]
I'm actually not sure if we have GPU memory in our devtools yet, but I'll check Firefox if we do.

**Comment by bvaughn** [comment]
Bah. I've used that overlay before and forgotten that there was a GPU meter in there too. Nice! :)

Yeah. I'm okay to sit on this for a bit then and see if others have input. If the performance is at least improved from before (now that on-wheel is gone) then the need isn't as pressing.

I really appreciate all of the info and suggestions :)

**Comment by jlongster** [comment]
Thanks for all the work on this project!

There's a well-known post by Paul Irish about this: http://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/ I think if you are animating complex objects, `transform` is better. But I think for the use case here, `top` is probably better, because there are many objects and they will likely be simpler.

Eventually, it would be easy to even make this configurable so users could choose whatever they want.

**Comment by bvaughn** [comment]
I ended up making this change in [version 5](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#500) because, anecdotally, it seemed like an improvement. I may revert the change (or more likely, as you say, make it configurable) if I get any reports of negative performance impact.

**Comment by bvaughn** [comment]
Actually I'll re-open this and repurpose for considering `transform` -> `transform3d`

**Comment by flosstik** [comment]
Performance is really bad. It would be cool if we will have ability to configure it.

**Comment by bvaughn** [comment]
> Performance is really bad.

Huh? Mind giving a little more context? My testing (in various browsers and devices) seems to suggest performance is quite good.

**Comment by bvaughn** [comment]
Pinging @flosstik

**Comment by flosstik** [comment]
Sorry, but i don't have enough time for research. When i was update from version 4.0.9 to 5.1.0(and another libs), i saw jerky scrolling. When i was reinstall all dependencies and update lib to 5.2.0, i saw smooth scrolling, but when i scrolled fast, i was saw white screen and after 3 or 5 second content was loaded.

i will try use   overscanColumnsCount and overscanRowsCount, and i think it can help me.

I'm write postgresql viewer with electron. I'm have 1000 rows in one page, and can be infinity columns(in test 30).

I was switched from FixedDataTable (https://github.com/facebook/fixed-data-table). They also use transform for positioning, and they have problems (https://github.com/facebook/fixed-data-table/issues/49)

I think this information isn't helpful. When i will have time i will test it again, and will can give facts.

**Comment by bvaughn** [comment]
Research is not necessary. More context than "Performance is really bad." is absolutely necessary if I'm going to do anything about what you're reporting.

For what it's worth, I think the discussion on #124 actually may actually be related to what @flosstik is reporting.

**Comment by bvaughn** [comment]
Put another way: I don't think it's actually the `transform` change that's causing the problem you reported,  but rather, the `key` change. However I'm not currently sure of a way to resolve this and there is ongoing discussion on #124 about it.

**Comment by bvaughn** [comment]
@flosstik: You'll be happy to learn that version 5.2.3 replaces transform with left/top as you suggest. I'm going to go ahead and close this issue for now as that positioning seems to work the best in my testing when compared against translate and translate3d
