### ISSUE TITLE
list-prop gets rendered into the markup (in the demos)

### ISSUE THREAD

**Issue by petetnt** [bvaughn/react-virtualized#95]
When passed down and then spread with `{...props}` the `list`-prop gets rendered into the markup (to the `<ContentBox>`-div) as it's an valid HTML attribute for `<input>`-element

https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes

> Identifies a list of pre-defined options to suggest to the user. The value must be the id of a <datalist> element in the same document. The browser displays only options that are valid values for this input element. This attribute is ignored when the type attribute's value is hidden, checkbox, radio, file, or a button type.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

![image](https://cloud.githubusercontent.com/assets/7641760/13029575/ac331e96-d298-11e5-9d3d-876f122c2ef0.png)

It doesn't happen to `InfiniteLoader` example due to [this line](https://github.com/bvaughn/react-virtualized/blob/master/source/InfiniteLoader/InfiniteLoader.example.js#L46) I think. 

Unless I am missing something and it's wanted behavior.

**Comment by bvaughn** [comment]
Ah, good point @petetnt. It was not intended. :)

**Comment by petetnt** [comment]
:+1:
