### ISSUE TITLE
Please provide masonry demo with responsive layout, full width

### ISSUE THREAD

**Issue by borm** [bvaughn/react-virtualized#958]
something like this [plunker](https://embed.plnkr.co/knQLm5NCog2Pvf1wWoMF/)
in my example, I was required to clean the all cache on every resize event

i have used other func for calculate columns
```js
_calculateColumnCount() {
    const brakePoints = [640, 768, 920, 1200, 1400];
    this._columnCount = brakePoints.reduceRight( (p, c, i) => {
      return c < this._width ? p : i;
    }, brakePoints.length) + 1;

    this._columnWidth = Math.floor(
      (this._width - this._columnCount * this._gutterSize) / this._columnCount
    );
  }
```

Maybe you can combine _(as i look in source code it not possible)_ `ColumnSizer` with `Masonry`?)

**Comment by bvaughn** [comment]
[There is already a demo like this](https://bvaughn.github.io/react-virtualized/#/components/Masonry). It uses the full width of the page and is responsive on resize. The source code for it is [right here, in GitHub](https://github.com/bvaughn/react-virtualized/blob/master/source/Masonry/Masonry.example.js).

**Comment by borm** [comment]
You do not understood me, i told about something  ColumnSizer for each masonry item, columns should have flexible not fixed width

**Comment by bvaughn** [comment]
The demo I linked to shows how you can change column width as well. Not using `ColumnSizer` but the logic for that component [is extremely small](https://github.com/bvaughn/react-virtualized/blob/04de423e9fe9db5f896add1aadc722c82bbc94ce/source/ColumnSizer/ColumnSizer.js#L70-L73) so you can just do it in your own application code.

**Comment by borm** [comment]
I did it on my plunker demo, (plunker don't worked, i have create copy of demo on [jsbin](https://jsbin.com/qarogugecu/edit?output))
but it seems to me i have lags, 
so i'll try create new example later
