### ISSUE TITLE
List component does not support deferredMeasurementCache in the latest release how to create dynamic height rows with List component now.

### ISSUE THREAD

**Issue by anshuPurohit** [bvaughn/react-virtualized#963]
To support dynamic row height in the List component I am using CellMeasurer, CellMeasurerCache HOC. But List component now doesn't support deferredMeasurementCache.

Now what are the options available for dynamic row height in the List component.

**Comment by bvaughn** [comment]
> But List component now doesn't support deferredMeasurementCache.

Yes it does. You can see an example of this [on the demo page](https://bvaughn.github.io/react-virtualized/#/components/CellMeasurer) under "**List:** dynamic height image".

If I'm wrong, and this is not just a misunderstanding on your part, please provide additional information on how to reproduce this issue, as the new-issue template says. 😄 

> # Reporting a Bug?
> Please include either a failing unit test or a simple repro. You can start by forking one of these:
> * Code Sandbox: https://codesandbox.io/s/03qpzq1p9p?module=%2FExample.js
> * Plnkr: https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1
