### ISSUE TITLE
Network request not finishing until scroll stops in chrome

### ISSUE THREAD

**Issue by inssein** [bvaughn/react-virtualized#964]
I have been working on a bug all day today that is related to a network call being stalled due to the browser (chrome only) thinking that it is still scrolling.

Relevant stackoverflow with more detail:
https://stackoverflow.com/questions/35024301/xhr-settimeout-promise-not-finishing-until-scrolling-stops-in-chrome

Besides making calls inside web workers, is there something the library can do? Somehow tell the browser that scrolling has stopped?

**Comment by bvaughn** [comment]
This library just listens to scroll events. It doesn't initiate scrolling (except for the specific case of `scrollToCell` but that's an immediate scroll, not an animation).

So no, I don't think there's anything RV can do to help out with this issue. Sorry!
