### ISSUE TITLE
Can you calculate real estimateTotalHeight?

### ISSUE THREAD

**Issue by borm** [bvaughn/react-virtualized#972]
So, in long lists the height updated on scroll event and scroll jumping every time, 
can you calculate real height on initial render?

i have commented `defaultHeight` and `defaultWidth` because after initial render on first scroll scrolling too slow on the first couple of seconds 
```
this._cache = new CellMeasurerCache({
      // defaultHeight: 250,
      // defaultWidth: 200,
      fixedWidth: true,
      fixedHeight: false,
});
```

i have a small [video](https://youtu.be/EA_yQSyX_eo)
on second 28 i have used fast scroll to bottom and how you can see, we have lag, see position of scroll on 34 second

[codesandbox](https://codesandbox.io/s/7y01rnz8r6)

**Comment by bvaughn** [comment]
> can you calculate real height on initial render?

No. Not without measuring every single item in the list, which would defeat the purpose of windowing.

> i have commented `defaultHeight` and `defaultWidth` because after initial render on first scroll scrolling too slow on the first couple of seconds

This suggests to me that your estimated height was just wildly inaccurate. By commenting out that parameter, all you've done is [chosen to use the built-in default of 30 pixels instead](https://github.com/bvaughn/react-virtualized/blob/3bf98a432529850b226cbff0c9dd88a84b4ca9a5/source/CellMeasurer/CellMeasurerCache.js#L65).

RV starts with estimated values and then [gradually adjusts them as real data streams in](https://github.com/bvaughn/react-virtualized/blob/3bf98a432529850b226cbff0c9dd88a84b4ca9a5/source/Masonry/PositionCache.js#L19-L29).

I don't think there's anything actionable to do here. Seems like a misunderstanding how the library works.
