### ISSUE TITLE
[Improvement] Remove "Row" from InfiniteLoader

### ISSUE THREAD

**Issue by thomassuckow** [bvaughn/react-virtualized#973]
InfiniteLoader doesn't specifically care about rows, it generically tracks loading of items in an array/list and triggers loading more of said items when displaying outside of the bounds. It is possible to make an infinite horizontal scrolling component just as easily as it is a vertical one, but instead of giving row indexes, it needs to be given column indexes.

For this reason I believe it is a misnomer that the props and methods exposed by InfiniteLoader have the word "Row" in them.

**Comment by bvaughn** [comment]
I understand your point of view, but I don't think this semantic nit is worth a backwards breaking change.

I will, however, add this as a note to the version 10 umbrella for consideration in the next major release.

**Comment by thomassuckow** [comment]
Thanks and I wouldn't consider it before 10 either.
