### ISSUE TITLE
Safari re-renders all rows every scroll after click

### ISSUE THREAD

**Issue by piotrblasiak** [bvaughn/react-virtualized#983]
In safari, once you have simply clicked inside the List, even for super simple rows with no click handler - the List goes bananas and starts to re-render all rows on every scroll.

```
import React from "react";
import { List } from "react-virtualized";

export default function Playground() {
  return (
    <div style={{ height: 1000 }}>
      <List
        width={1000}
        height={1000}
        rowCount={10000}
        rowHeight={30}
        rowRenderer={({ index, key, style }) => (
          <div key={key} style={{ ...style, height: 30 }}>
            Row {index}
          </div>
        )}
      />
    </div>
  );
}
```

https://codesandbox.io/s/l5m9q4v7z

Tested with Safari 11.0.3

**Comment by piotrblasiak** [comment]
Apparently this happens even without AutoSizer - edited and removed the AutoSizer from sample code.

**Comment by TrySound** [comment]
@piotrblasiak `List` is `PureComponent`. It's possible `Playground` render  is forced, so rowRenderer is created every time and List reacts on its change and rerenders everything.

**Comment by piotrblasiak** [comment]
@TrySound I´m afraid that´s not what happens - the Playground is never rerendered. It looks like something breaks the List once something in it is clicked. On my computer - nothing outside of the List is changed or rerendered, and my CPU goes up to 100% when scrolling.

**Comment by TrySound** [comment]
@piotrblasiak Can you provider [codesandbox example](https://codesandbox.io)?

**Comment by piotrblasiak** [comment]
@TrySound here you go: https://codesandbox.io/s/l5m9q4v7z

**Comment by piotrblasiak** [comment]
Ok, I found a workaround. For some reason once the list is clicked it gets focused and the outline causes it all to go banana in safari. So by adding "outline: none" to the css of the List, it works nicely again.

**Comment by bvaughn** [comment]
Yeah, this has come up in the past (rendering performance for focused components). See threads like this one: https://gist.github.com/paulirish/5d52fb081b3570c81e3a#gistcomment-1805373

I'm not sure that react-virtualized can do anything about this. Focus is important for accessibility. You can disable the default browser outline (as you've pointed out) but then it's important for you to implement some other kind of focus style in its place.

I'm pretty tempted to close this issue since I don't see what action I can take. Thoughts?

**Comment by piotrblasiak** [comment]
I see - I think it could save a lot of grief if you mentioned this somewhere in the docs. Other than that, you are probably right that this should be closed. Thanks for the attention.

**Comment by TrySound** [comment]
@piotrblasiak Would you like to send a PR?

**Comment by bvaughn** [comment]
Keeping documentation up-to-date with the ever-changing browser quirks related to rendering/scrolling/perf is a large job. As it is, I struggle to find enough time to maintain this project.

If you have suggestions for docs, PRs are open.

**Comment by vjeranc** [comment]
I'm seeing a similar issue in Firefox and Chrome.

Scrolling just 1 px rerenders all the cells. Even if `outline` is added.
