### ISSUE TITLE
update 9.18.0 > 9.18.2: Error: Invalid prop `noRowsRenderer` of type `function` supplied to `List`, expected `object`

### ISSUE THREAD

**Issue by barbalex** [bvaughn/react-virtualized#990]
Works fine with v9.18.0.

This is the file `noRowsRenderer` is built in: https://github.com/barbalex/ae2/blob/9c5cd06202f8c3a24e0b5448a0b949236a80849f/src/components/Tree/index.js

Also happens in a different project of mine.

Update: also happens when updating from 9.18.0 to 9.18.1

**Comment by vieron** [comment]
Same happening here, it looks like the latest changes in the flow to propTypes conversion is not working as expected. Look at the output of `List/List.js` for example:

```js
import { bpfrpt_proptype_NoContentRenderer } from '../Grid';
import { bpfrpt_proptype_Alignment } from '../Grid';
import { bpfrpt_proptype_CellSize } from '../Grid';
import { bpfrpt_proptype_CellPosition } from '../Grid';
import { bpfrpt_proptype_OverscanIndicesGetter } from '../Grid';
import { bpfrpt_proptype_RenderedSection } from '../Grid';
import { bpfrpt_proptype_CellRendererParams } from '../Grid';
import { bpfrpt_proptype_Scroll } from '../Grid';
import { bpfrpt_proptype_RowRenderer } from './types';
import { bpfrpt_proptype_RenderedRows } from './types';
import { bpfrpt_proptype_Scroll } from './types';
```

flow types are converted to regular ES6 imports.

**Comment by TrySound** [comment]
Temporary reverted last change in 9.18.3

**Comment by dmr** [comment]
Thank you for the quick reaction!
