### ISSUE TITLE
'../Grid' does not contain an export named 'bpfrpt_proptype_NoContentRenderer'

### ISSUE THREAD

**Issue by dawnmist** [bvaughn/react-virtualized#991]
# Reporting a Bug?
```
Failed to compile.

./node_modules/react-virtualized/dist/es/List/List.js
281:117-150 '../Grid' does not contain an export named 'bpfrpt_proptype_NoContentRenderer'.
```

react-virtualized versions: 9.18.1 & 9.18.2
`dist/es/List/List.js`, lines 352-363: this tries to import prototype types from the Grid directory, but those types are only defined in the `../Grid/types.js` file. They are not exported from the `../Grid/index.js` file and are thus not able to be imported from `../Grid` directly.

There are also name-clashes between imports from local types and from what is being tried to be imported from the Grid types - see lines 359 & 362 of `dist/es/List/List.js` which both try to import "bpfrpt_proptype_Scroll".

This breaks the ability to use the dist/es files.

**Comment by TrySound** [comment]
Temporary reverted last change in 9.18.3
