### ISSUE TITLE
List Padding

### ISSUE THREAD

**Issue by jacobp100** [bvaughn/react-virtualized#992]
Is it possible to add internal vertical padding on the list, so the first row appears say 10px down, but in a way that shorten the scrollbar.

So in the example above, when at the top of the list, the first row would be 10px below the top of the scrollbar?

**Comment by bvaughn** [comment]
No, this isn't supported. My answer to this sort of question has usually been to put this padding in a `<div>` (or similar) that wraps `List`. Spacing "between" rows could be accomplished by making the rows a little bit taller and then padding within the `rowRenderer`. This keeps the positioning logic within RV simpler (and it's already complex enough). 😄

**Comment by jacobp100** [comment]
I didn't explain this very well, it's easier with an [example](https://jsfiddle.net/zqrd4w4p/).

Notice that the background is only visible at the start and end of the list. Using a container with padding would always show the background!

**Comment by bvaughn** [comment]
Here's an example of how you could do that with react-virtualized

https://codesandbox.io/s/j2px9kpl9y

**Comment by jacobp100** [comment]
That's one way to do it!

Is this a feature you'd be open for a PR for—maybe via `inset{Top,Right,Bottom,Left}` props? It's really common in iOS at least to have a insets.

**Comment by bvaughn** [comment]
You can always submit a PR 😄 I'll be happy to take a look (although it might take me a while).

**Comment by smeijer** [comment]
@jacobp100, I would be highly interested in this functionality. 

I use a top-padding to create "white space" above the list, so a search bar can be positioned absolutely in this whitespace. After scroll, the list-items "disappear" behind the search bar.

Currently fixed with the 'PaddingRow' solution, but an inset prop would be really nice.

**Comment by TrySound** [comment]
@smeijer @jacobp100 There is `WindowScroller` component which allows to pass own scrollable html element and register child around Table/List/Grid.

See "Use custom element for scrolling" checkbox in [WindowScroller example](https://bvaughn.github.io/react-virtualized/#/components/WindowScroller)

**Comment by jacobp100** [comment]
Thanks! Did a demo on stackblitz: https://stackblitz.com/edit/react-kwjixn?file=index.js

If anybody has any feedback on how to do things better, I'd love to know!

**Comment by stop2stare** [comment]
Here's what I did to hack:
``` css
&:after {
  content: '';
  position: absolute;
  bottom: 0px;
  left: 0;
  width: 100%;
  height: 10px;
  background-color: #f4f4f4;
}
```
It works well!

**Comment by martis-git** [comment]
Still actual!!!
