### ISSUE TITLE
onScroll fires when RV components first load

### ISSUE THREAD

**Issue by josephong** [bvaughn/react-virtualized#996]
RV components automatically fire their onScroll handlers when they load. Is this by design or a bug? Reasonable either way – just checking!

Plunkr: https://plnkr.co/edit/kpeUZrk7KZdv6q0VQVAY

**Comment by bvaughn** [comment]
It's by design 😄 and tested: https://github.com/bvaughn/react-virtualized/blob/e775173881faca608f65af98d97f0fc114097575/source/Grid/Grid.jest.js#L1069-L1089

I think it makes the components easier to reason about.
