### ISSUE TITLE
Grid new prop - maxHeight

### ISSUE THREAD

**Issue by gut4** [bvaughn/react-virtualized#997]
In some cases [like this](https://stackoverflow.com/questions/48336244/react-virtualized-list-how-to-remove-empty-space-when-the-list-is-too-short) it will be useful to set ```maxHeight``` instead of ```height```.

It can look like this:
``` source/Grid/Grid.js ```
```
const {autoHeight, autoWidth, height, width, maxHeight} = this.props;
const totalRowsHeight = this._rowSizeAndPositionManager.getTotalSize();
if (totalRowsHeight < maxHeight){
  height = totalRowsHeight
} else if(totalRowsHeight >= maxHeight){
  height = maxHeight
}
```

**Comment by bvaughn** [comment]
My initial reaction is that it's fine for this to be done in application code.

But if you'd like to put together a PR - with docs and tests - I'll be happy to take a look and consider it.
